<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 symbolic evaluation engine.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SymbExpr.fs" />
    <Compile Include="ISymbMemory.fs" />
    <Compile Include="SymbMemory.fs" />
    <Compile Include="BinSectionSymbMemory.fs" />
    <Compile Include="SymbState.fs" />
    <Compile Include="SymbStateAccessor.fs" />
    <Compile Include="SymbExprTranslator.fs" />
    <Compile Include="SymbEvaluator.fs" />
    <Compile Include="SMTLibSerializer.fs" />
    <Compile Include="ISolver.fs" />
    <Compile Include="SymbModel.fs" />
    <Compile Include="SolverOutputParser.fs" />
    <Compile Include="SymbCallHook.fs" />
    <Compile Include="SymbExecutor.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BinIR\B2R2.BinIR.fsproj" />
    <ProjectReference Include="..\..\FrontEnd\API\B2R2.FrontEnd.API.fsproj" />
    <ProjectReference Include="..\Executor\B2R2.MiddleEnd.Executor.fsproj" />
  </ItemGroup>

</Project>
