<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageIcon>b2r2-240x240.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>B2R2 Python assembly library.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Spec.fs" />
    <Compile Include="Encoder.fs" />
    <Compile Include="Tables.fs" />
    <Compile Include="Assembler.fs" />
    <None Include="..\..\..\LICENSE.md" Pack="true" PackagePath="" />
    <None Include="..\..\..\assets\b2r2-240x240.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrontEnd\Python\B2R2.FrontEnd.Python.fsproj" />
    <ProjectReference Include="..\BinLowerer\B2R2.Assembly.BinLowerer.fsproj" />
  </ItemGroup>

</Project>
