<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 symbolic evaluation engine.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="String.fs" />
    <Compile Include="Enum.fs" />
    <Compile Include="PrintingUtils.fs" />
    <Compile Include="IVerboseOption.fs" />
    <Compile Include="CmdOpts.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="B2R2.FsOptParse" Version="0.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\B2R2.Core.fsproj" />
  </ItemGroup>

</Project>
