<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2-to-LLVM translation library.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LLVMContext.fs" />
    <Compile Include="LLVMIRHelper.fs" />
    <Compile Include="LLVMAST.fs" />
    <Compile Include="LLVMIRBuilder.fs" />
    <Compile Include="LLVMTranslator.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\B2R2.Core.fsproj" />
    <ProjectReference Include="..\..\FrontEnd\API\B2R2.FrontEnd.API.fsproj" />
  </ItemGroup>

</Project>
