<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageIcon>b2r2-240x240.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>B2R2 Python frontend.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Register.fs" />
    <Compile Include="RegisterFactory.fs" />
    <Compile Include="Opcode.fs" />
    <Compile Include="Tables.fs" />
    <Compile Include="Operands.fs" />
    <Compile Include="Instruction.fs" />
    <Compile Include="Disasm.fs" />
    <Compile Include="LifterHelpers.fs" />
    <Compile Include="Semantics.fs" />
    <Compile Include="Python300\Lifter.fs" />
    <Compile Include="Python301\Lifter.fs" />
    <Compile Include="Python302\Lifter.fs" />
    <Compile Include="Python303\Lifter.fs" />
    <Compile Include="Python304\Lifter.fs" />
    <Compile Include="Python305\Lifter.fs" />
    <Compile Include="Python306\Lifter.fs" />
    <Compile Include="Python307\Lifter.fs" />
    <Compile Include="Python308\Lifter.fs" />
    <Compile Include="Python309\Lifter.fs" />
    <Compile Include="Python310\Lifter.fs" />
    <Compile Include="Python311\Lifter.fs" />
    <Compile Include="Python312\Lifter.fs" />
    <Compile Include="Python313\Lifter.fs" />
    <Compile Include="Python314\Lifter.fs" />
    <Compile Include="Python315\Lifter.fs" />
    <Compile Include="Parsing.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="RawParser.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\B2R2.Core.fsproj" />
    <ProjectReference Include="..\..\BinIR\B2R2.BinIR.fsproj" />
    <ProjectReference Include="..\BinFile\B2R2.FrontEnd.BinFile.fsproj" />
    <ProjectReference Include="..\BinLifter\B2R2.FrontEnd.BinLifter.fsproj" />
  </ItemGroup>
</Project>
