(*
  B2R2 - the Next-Generation Reversing Platform

  Copyright (c) SoftSec Lab. @ KAIST, since 2016

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*)


namespace B2R2.FrontEnd.Python

/// <summary>
/// Represents a Python opcode, named as CPython names it. The numbering is
/// B2R2's own and means nothing to CPython, which renumbers freely between
/// versions: a byte becomes one of these only through the table of the
/// version it was read from -- see <see cref='T:B2R2.FrontEnd.Python.Tables'/>.
/// </summary>
type Opcode =
  /// No instruction of this version has that number.
  | InvalidOp = 0
  | ANNOTATIONS_PLACEHOLDER = 1
  | ASYNC_GEN_WRAP = 2
  | BEFORE_ASYNC_WITH = 3
  | BEFORE_WITH = 4
  | BEGIN_FINALLY = 5
  | BINARY_ADD = 6
  | BINARY_AND = 7
  | BINARY_FLOOR_DIVIDE = 8
  | BINARY_LSHIFT = 9
  | BINARY_MATRIX_MULTIPLY = 10
  | BINARY_MODULO = 11
  | BINARY_MULTIPLY = 12
  | BINARY_OP = 13
  | BINARY_OR = 14
  | BINARY_POWER = 15
  | BINARY_RSHIFT = 16
  | BINARY_SLICE = 17
  | BINARY_SUBSCR = 18
  | BINARY_SUBTRACT = 19
  | BINARY_TRUE_DIVIDE = 20
  | BINARY_XOR = 21
  | BREAK_LOOP = 22
  | BUILD_CONST_KEY_MAP = 23
  | BUILD_INTERPOLATION = 24
  | BUILD_LIST = 25
  | BUILD_LIST_UNPACK = 26
  | BUILD_MAP = 27
  | BUILD_MAP_UNPACK = 28
  | BUILD_MAP_UNPACK_WITH_CALL = 29
  | BUILD_SET = 30
  | BUILD_SET_UNPACK = 31
  | BUILD_SLICE = 32
  | BUILD_STRING = 33
  | BUILD_TEMPLATE = 34
  | BUILD_TUPLE = 35
  | BUILD_TUPLE_UNPACK = 36
  | BUILD_TUPLE_UNPACK_WITH_CALL = 37
  | CACHE = 38
  | CALL = 39
  | CALL_FINALLY = 40
  | CALL_FUNCTION = 41
  | CALL_FUNCTION_EX = 42
  | CALL_FUNCTION_KW = 43
  | CALL_FUNCTION_VAR = 44
  | CALL_FUNCTION_VAR_KW = 45
  | CALL_INTRINSIC_1 = 46
  | CALL_INTRINSIC_2 = 47
  | CALL_KW = 48
  | CALL_METHOD = 49
  | CHECK_EG_MATCH = 50
  | CHECK_EXC_MATCH = 51
  | CLEANUP_THROW = 52
  | COMPARE_OP = 53
  | CONTAINS_OP = 54
  | CONTINUE_LOOP = 55
  | CONVERT_VALUE = 56
  | COPY = 57
  | COPY_DICT_WITHOUT_KEYS = 58
  | COPY_FREE_VARS = 59
  | DELETE_ATTR = 60
  | DELETE_DEREF = 61
  | DELETE_FAST = 62
  | DELETE_GLOBAL = 63
  | DELETE_NAME = 64
  | DELETE_SUBSCR = 65
  | DICT_MERGE = 66
  | DICT_UPDATE = 67
  | DUP_TOP = 68
  | DUP_TOPX = 69
  | DUP_TOP_TWO = 70
  | END_ASYNC_FOR = 71
  | END_FINALLY = 72
  | END_FOR = 73
  | END_SEND = 74
  | ENTER_EXECUTOR = 75
  | EXIT_INIT_CHECK = 76
  | EXTENDED_ARG = 77
  | FORMAT_SIMPLE = 78
  | FORMAT_VALUE = 79
  | FORMAT_WITH_SPEC = 80
  | FOR_ITER = 81
  | GEN_START = 82
  | GET_AITER = 83
  | GET_ANEXT = 84
  | GET_AWAITABLE = 85
  | GET_ITER = 86
  | GET_LEN = 87
  | GET_YIELD_FROM_ITER = 88
  | IMPORT_FROM = 89
  | IMPORT_NAME = 90
  | IMPORT_STAR = 91
  | INPLACE_ADD = 92
  | INPLACE_AND = 93
  | INPLACE_FLOOR_DIVIDE = 94
  | INPLACE_LSHIFT = 95
  | INPLACE_MATRIX_MULTIPLY = 96
  | INPLACE_MODULO = 97
  | INPLACE_MULTIPLY = 98
  | INPLACE_OR = 99
  | INPLACE_POWER = 100
  | INPLACE_RSHIFT = 101
  | INPLACE_SUBTRACT = 102
  | INPLACE_TRUE_DIVIDE = 103
  | INPLACE_XOR = 104
  | INSTRUMENTED_CALL = 105
  | INSTRUMENTED_CALL_FUNCTION_EX = 106
  | INSTRUMENTED_CALL_KW = 107
  | INSTRUMENTED_END_ASYNC_FOR = 108
  | INSTRUMENTED_END_FOR = 109
  | INSTRUMENTED_END_SEND = 110
  | INSTRUMENTED_FOR_ITER = 111
  | INSTRUMENTED_INSTRUCTION = 112
  | INSTRUMENTED_JUMP_BACKWARD = 113
  | INSTRUMENTED_JUMP_FORWARD = 114
  | INSTRUMENTED_LINE = 115
  | INSTRUMENTED_LOAD_SUPER_ATTR = 116
  | INSTRUMENTED_NOT_TAKEN = 117
  | INSTRUMENTED_POP_ITER = 118
  | INSTRUMENTED_POP_JUMP_IF_FALSE = 119
  | INSTRUMENTED_POP_JUMP_IF_NONE = 120
  | INSTRUMENTED_POP_JUMP_IF_NOT_NONE = 121
  | INSTRUMENTED_POP_JUMP_IF_TRUE = 122
  | INSTRUMENTED_RESUME = 123
  | INSTRUMENTED_RETURN_CONST = 124
  | INSTRUMENTED_RETURN_VALUE = 125
  | INSTRUMENTED_YIELD_VALUE = 126
  | INTERPRETER_EXIT = 127
  | IS_OP = 128
  | JUMP = 129
  | JUMP_ABSOLUTE = 130
  | JUMP_BACKWARD = 131
  | JUMP_BACKWARD_NO_INTERRUPT = 132
  | JUMP_FORWARD = 133
  | JUMP_IF_FALSE = 134
  | JUMP_IF_FALSE_OR_POP = 135
  | JUMP_IF_NOT_EXC_MATCH = 136
  | JUMP_IF_TRUE = 137
  | JUMP_IF_TRUE_OR_POP = 138
  | JUMP_NO_INTERRUPT = 139
  | KW_NAMES = 140
  | LIST_APPEND = 141
  | LIST_EXTEND = 142
  | LIST_TO_TUPLE = 143
  | LOAD_ASSERTION_ERROR = 144
  | LOAD_ATTR = 145
  | LOAD_BUILD_CLASS = 146
  | LOAD_CLASSDEREF = 147
  | LOAD_CLOSURE = 148
  | LOAD_COMMON_CONSTANT = 149
  | LOAD_CONST = 150
  | LOAD_DEREF = 151
  | LOAD_FAST = 152
  | LOAD_FAST_AND_CLEAR = 153
  | LOAD_FAST_BORROW = 154
  | LOAD_FAST_BORROW_LOAD_FAST_BORROW = 155
  | LOAD_FAST_CHECK = 156
  | LOAD_FAST_LOAD_FAST = 157
  | LOAD_FROM_DICT_OR_DEREF = 158
  | LOAD_FROM_DICT_OR_GLOBALS = 159
  | LOAD_GLOBAL = 160
  | LOAD_LOCALS = 161
  | LOAD_METHOD = 162
  | LOAD_NAME = 163
  | LOAD_SMALL_INT = 164
  | LOAD_SPECIAL = 165
  | LOAD_SUPER_ATTR = 166
  | LOAD_SUPER_METHOD = 167
  | LOAD_ZERO_SUPER_ATTR = 168
  | LOAD_ZERO_SUPER_METHOD = 169
  | MAKE_CELL = 170
  | MAKE_CLOSURE = 171
  | MAKE_FUNCTION = 172
  | MAP_ADD = 173
  | MATCH_CLASS = 174
  | MATCH_KEYS = 175
  | MATCH_MAPPING = 176
  | MATCH_SEQUENCE = 177
  | NOP = 178
  | NOT_TAKEN = 179
  | POP_BLOCK = 180
  | POP_EXCEPT = 181
  | POP_FINALLY = 182
  | POP_ITER = 183
  | POP_JUMP_BACKWARD_IF_FALSE = 184
  | POP_JUMP_BACKWARD_IF_NONE = 185
  | POP_JUMP_BACKWARD_IF_NOT_NONE = 186
  | POP_JUMP_BACKWARD_IF_TRUE = 187
  | POP_JUMP_FORWARD_IF_FALSE = 188
  | POP_JUMP_FORWARD_IF_NONE = 189
  | POP_JUMP_FORWARD_IF_NOT_NONE = 190
  | POP_JUMP_FORWARD_IF_TRUE = 191
  | POP_JUMP_IF_FALSE = 192
  | POP_JUMP_IF_NONE = 193
  | POP_JUMP_IF_NOT_NONE = 194
  | POP_JUMP_IF_TRUE = 195
  | POP_TOP = 196
  | PRECALL = 197
  | PREP_RERAISE_STAR = 198
  | PRINT_EXPR = 199
  | PUSH_EXC_INFO = 200
  | PUSH_NULL = 201
  | RAISE_VARARGS = 202
  | RERAISE = 203
  | RESERVED = 204
  | RESUME = 205
  | RETURN_CONST = 206
  | RETURN_GENERATOR = 207
  | RETURN_VALUE = 208
  | ROT_FOUR = 209
  | ROT_N = 210
  | ROT_THREE = 211
  | ROT_TWO = 212
  | SEND = 213
  | SETUP_ANNOTATIONS = 214
  | SETUP_ASYNC_WITH = 215
  | SETUP_CLEANUP = 216
  | SETUP_EXCEPT = 217
  | SETUP_FINALLY = 218
  | SETUP_LOOP = 219
  | SETUP_WITH = 220
  | SET_ADD = 221
  | SET_FUNCTION_ATTRIBUTE = 222
  | SET_UPDATE = 223
  | STOP_CODE = 224
  | STORE_ANNOTATION = 225
  | STORE_ATTR = 226
  | STORE_DEREF = 227
  | STORE_FAST = 228
  | STORE_FAST_LOAD_FAST = 229
  | STORE_FAST_MAYBE_NULL = 230
  | STORE_FAST_STORE_FAST = 231
  | STORE_GLOBAL = 232
  | STORE_LOCALS = 233
  | STORE_MAP = 234
  | STORE_NAME = 235
  | STORE_SLICE = 236
  | STORE_SUBSCR = 237
  | SWAP = 238
  | TO_BOOL = 239
  | TRACE_RECORD = 240
  | UNARY_INVERT = 241
  | UNARY_NEGATIVE = 242
  | UNARY_NOT = 243
  | UNARY_POSITIVE = 244
  | UNPACK_EX = 245
  | UNPACK_SEQUENCE = 246
  | WITH_CLEANUP = 247
  | WITH_CLEANUP_FINISH = 248
  | WITH_CLEANUP_START = 249
  | WITH_EXCEPT_START = 250
  | YIELD_FROM = 251
  | YIELD_VALUE = 252

// vim: set tw=80 sts=2 sw=2:
