(*
  B2R2 - the Next-Generation Reversing Platform

  Copyright (c) SoftSec Lab. @ KAIST, since 2016

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*)

namespace B2R2.FrontEnd.Python

/// <summary>
/// Represents a Python opcode(Python 3.12).
/// </summary>
type Opcode =
  | CACHE = 0x0
  | POP_TOP = 0x1
  | PUSH_NULL = 0x2
  | INTERPRETER_EXIT = 0x3
  | END_FOR = 0x4
  | END_SEND = 0x5
  | NOP = 0x9
  | UNARY_NEGATIVE = 0xB
  | UNARY_NOT = 0xC
  | UNARY_INVERT = 0xF
  | RESERVED = 0x11
  | BINARY_SUBSCR = 0x19
  | BINARY_SLICE = 0x1A
  | STORE_SLICE = 0x1B
  | GET_LEN = 0x1E
  | MATCH_MAPPING = 0x1F
  | MATCH_SEQUENCE = 0x20
  | MATCH_KEYS = 0x21
  | PUSH_EXC_INFO = 0x23
  | CHECK_EXC_MATCH = 0x24
  | CHECK_EG_MATCH = 0x25
  | WITH_EXCEPT_START = 0x31
  | GET_AITER = 0x32
  | GET_ANEXT = 0x33
  | BEFORE_ASYNC_WITH = 0x34
  | BEFORE_WITH = 0x35
  | END_ASYNC_FOR = 0x36
  | CLEANUP_THROW = 0x37
  | STORE_SUBSCR = 0x3C
  | DELETE_SUBSCR = 0x3D
  | GET_ITER = 0x44
  | GET_YIELD_FROM_ITER = 0x45
  | LOAD_BUILD_CLASS = 0x47
  | LOAD_ASSERTION_ERROR = 0x4A
  | RETURN_GENERATOR = 0x4B
  | RETURN_VALUE = 0x53
  | IMPORT_STAR = 0x54
  | SETUP_ANNOTATIONS = 0x55
  | LOAD_LOCALS = 0x57
  | POP_EXCEPT = 0x59
  | STORE_NAME = 0x5A
  | DELETE_NAME = 0x5B
  | UNPACK_SEQUENCE = 0x5C
  | FOR_ITER = 0x5D
  | UNPACK_EX = 0x5E
  | STORE_ATTR = 0x5F
  | DELETE_ATTR = 0x60
  | STORE_GLOBAL = 0x61
  | DELETE_GLOBAL = 0x62
  | SWAP = 0x63
  | LOAD_CONST = 0x64
  | LOAD_NAME = 0x65
  | BUILD_TUPLE = 0x66
  | BUILD_LIST = 0x67
  | BUILD_SET = 0x68
  | BUILD_MAP = 0x69
  | LOAD_ATTR = 0x6A
  | COMPARE_OP = 0x6B
  | IMPORT_NAME = 0x6C
  | IMPORT_FROM = 0x6D
  | JUMP_FORWARD = 0x6E
  | JUMP_IF_FALSE_OR_POP = 0x6F (* Removed in 3.12 *)
  | JUMP_IF_TRUE_OR_POP = 0x70 (* Removed in 3.12 *)
  | JUMP_ABSOLUTE = 0x71 (* Removed in 3.12 *)
  | POP_JUMP_IF_FALSE = 0x72
  | POP_JUMP_IF_TRUE = 0x73
  | LOAD_GLOBAL = 0x74
  | IS_OP = 0x75
  | CONTAINS_OP = 0x76
  | RERAISE = 0x77
  | COPY = 0x78
  | RETURN_CONST = 0x79
  | BINARY_OP = 0x7A
  | SEND = 0x7B
  | LOAD_FAST = 0x7C
  | STORE_FAST = 0x7D
  | DELETE_FAST = 0x7E
  | LOAD_FAST_CHECK = 0x7F
  | POP_JUMP_IF_NOT_NONE = 0x80
  | POP_JUMP_IF_NONE = 0x81
  | RAISE_VARARGS = 0x82
  | GET_AWAITABLE = 0x83
  | MAKE_FUNCTION = 0x84
  | BUILD_SLICE = 0x85
  | JUMP_BACKWARD_NO_INTERRUPT = 0x86
  | MAKE_CELL = 0x87
  | LOAD_CLOSURE = 0x88
  | LOAD_DEREF = 0x89
  | STORE_DEREF = 0x8A
  | DELETE_DEREF = 0x8B
  | JUMP_BACKWARD = 0x8C
  | LOAD_SUPER_ATTR = 0x8D
  | CALL_FUNCTION_EX = 0x8E
  | LOAD_FAST_AND_CLEAR = 0x8F
  | EXTENDED_ARG = 0x90
  | LIST_APPEND = 0x91
  | SET_ADD = 0x92
  | MAP_ADD = 0x93
  | COPY_FREE_VARS = 0x95
  | YIELD_VALUE = 0x96
  | RESUME = 0x97
  | MATCH_CLASS = 0x98
  | FORMAT_VALUE = 0x9B
  | BUILD_CONST_KEY_MAP = 0x9C
  | BUILD_STRING = 0x9D
  | LIST_EXTEND = 0xA2
  | SET_UPDATE = 0xA3
  | DICT_MERGE = 0xA4
  | DICT_UPDATE = 0xA5
  | CALL = 0xAB
  | KW_NAMES = 0xAC
  | CALL_INTRINSIC_1 = 0xAD
  | CALL_INTRINSIC_2 = 0xAE
  | LOAD_FROM_DICT_OR_GLOBALS = 0xAF
  | LOAD_FROM_DICT_OR_DEREF = 0xB0
  | INSTRUMENTED_LOAD_SUPER_ATTR = 0xED
  | INSTRUMENTED_POP_JUMP_IF_NONE = 0xEE
  | INSTRUMENTED_POP_JUMP_IF_NOT_NONE = 0xEF
  | INSTRUMENTED_RESUME = 0xF0
  | INSTRUMENTED_CALL = 0xF1
  | INSTRUMENTED_RETURN_VALUE = 0xF2
  | INSTRUMENTED_YIELD_VALUE = 0xF3
  | INSTRUMENTED_CALL_FUNCTION_EX = 0xF4
  | INSTRUMENTED_JUMP_FORWARD = 0xF5
  | INSTRUMENTED_JUMP_BACKWARD = 0xF6
  | INSTRUMENTED_RETURN_CONST = 0xF7
  | INSTRUMENTED_FOR_ITER = 0xF8
  | INSTRUMENTED_POP_JUMP_IF_FALSE = 0xF9
  | INSTRUMENTED_POP_JUMP_IF_TRUE = 0xFA
  | INSTRUMENTED_END_FOR = 0xFB
  | INSTRUMENTED_END_SEND = 0xFC
  | INSTRUMENTED_INSTRUCTION = 0xFD
  | INSTRUMENTED_LINE = 0xFE
  | SETUP_FINALLY = 0x100
  | SETUP_CLEANUP = 0x101
  | SETUP_WITH = 0x102
  | POP_BLOCK = 0x103
  | JUMP = 0x104
  | JUMP_NO_INTERRUPT = 0x105
  | LOAD_METHOD = 0x106
  | LOAD_SUPER_METHOD = 0x107
  | LOAD_ZERO_SUPER_METHOD = 0x108
  | LOAD_ZERO_SUPER_ATTR = 0x109
  | STORE_FAST_MAYBE_NULL = 0x10A
  (* Python 3.11-specific: FORWARD/BACKWARD variants of
     POP_JUMP_IF_NONE/NOT_NONE. We note that two opcodes overlap with Python
     3.12's different opcodes, so we assign them to pseudo-opcodes here. *)
  | POP_JUMP_FORWARD_IF_NONE = 0x10B
  | POP_JUMP_FORWARD_IF_NOT_NONE = 0x10C
  | POP_JUMP_BACKWARD_IF_FALSE = 0x10D
  | POP_JUMP_BACKWARD_IF_TRUE = 0x10E
  | POP_JUMP_BACKWARD_IF_NONE = 0x10F
  | POP_JUMP_BACKWARD_IF_NOT_NONE = 0x110
  (* Python 3.10-and-earlier-specific opcodes with no 3.12 equivalent, or
     whose byte value collides with an unrelated 3.12 opcode -- assigned
     pseudo-values here the same way the 3.11 POP_JUMP_* variants above
     are, since Parsing310.fs matches raw byte values against these enum
     cases directly rather than relying on the enum's underlying int. *)
  | ROT_TWO = 0x111
  | ROT_THREE = 0x112
  | ROT_FOUR = 0x113
  | DUP_TOP = 0x114
  | DUP_TOP_TWO = 0x115
  | UNARY_POSITIVE = 0x116
  | BINARY_MATRIX_MULTIPLY = 0x117
  | INPLACE_MATRIX_MULTIPLY = 0x118
  | BINARY_POWER = 0x119
  | BINARY_MULTIPLY = 0x11A
  | BINARY_MODULO = 0x11B
  | BINARY_ADD = 0x11C
  | BINARY_SUBTRACT = 0x11D
  | BINARY_FLOOR_DIVIDE = 0x11E
  | BINARY_TRUE_DIVIDE = 0x11F
  | INPLACE_FLOOR_DIVIDE = 0x120
  | INPLACE_TRUE_DIVIDE = 0x121
  | COPY_DICT_WITHOUT_KEYS = 0x122
  | INPLACE_ADD = 0x123
  | INPLACE_SUBTRACT = 0x124
  | INPLACE_MULTIPLY = 0x125
  | INPLACE_MODULO = 0x126
  | BINARY_LSHIFT = 0x127
  | BINARY_RSHIFT = 0x128
  | BINARY_AND = 0x129
  | BINARY_XOR = 0x12A
  | BINARY_OR = 0x12B
  | INPLACE_POWER = 0x12C
  | PRINT_EXPR = 0x12D
  | YIELD_FROM = 0x12E
  | INPLACE_LSHIFT = 0x12F
  | INPLACE_RSHIFT = 0x130
  | INPLACE_AND = 0x131
  | INPLACE_XOR = 0x132
  | INPLACE_OR = 0x133
  | LIST_TO_TUPLE = 0x134
  | ROT_N = 0x135
  | JUMP_IF_NOT_EXC_MATCH = 0x136
  | GEN_START = 0x137
  | CALL_FUNCTION = 0x138
  | CALL_FUNCTION_KW = 0x139
  | LOAD_CLASSDEREF = 0x13A
  | SETUP_ASYNC_WITH = 0x13B
  | CALL_METHOD = 0x13C

type internal Op = Opcode
