<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 CIL frontend.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Register.fs" />
    <Compile Include="RegisterFactory.fs" />
    <Compile Include="Instruction.fs" />
    <Compile Include="Parser.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\B2R2.Core.fsproj" />
    <ProjectReference Include="..\..\BinIR\B2R2.BinIR.fsproj" />
    <ProjectReference Include="..\BinLifter\B2R2.FrontEnd.BinLifter.fsproj" />
  </ItemGroup>

</Project>
