<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BinHandleTests.fs" />
    <Compile Include="LiftingUnitTests.fs" />
    <Compile Include="ParserContractTests.fs" />
    <Compile Include="InstructionCollectionTests.fs" />
    <Compile Include="ExceptionInfoTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\B2R2.Core.fsproj" />
    <ProjectReference Include="..\BinFile\B2R2.FrontEnd.BinFile.fsproj" />
    <ProjectReference Include="..\API\B2R2.FrontEnd.API.fsproj" />
  </ItemGroup>

</Project>
