<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageIcon>b2r2-240x240.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>B2R2 assembly main interface.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Assembler.fs" />
    <None Include="..\..\..\LICENSE.md" Pack="true" PackagePath="" />
    <None Include="..\..\..\assets\b2r2-240x240.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BinLowerer\B2R2.Assembly.BinLowerer.fsproj" />
    <ProjectReference Include="..\Intel\B2R2.Assembly.Intel.fsproj" />
    <ProjectReference Include="..\ARM32\B2R2.Assembly.ARM32.fsproj" />
    <ProjectReference Include="..\ARM64\B2R2.Assembly.ARM64.fsproj" />
    <ProjectReference Include="..\AVR\B2R2.Assembly.AVR.fsproj" />
    <ProjectReference Include="..\EVM\B2R2.Assembly.EVM.fsproj" />
    <ProjectReference Include="..\M68K\B2R2.Assembly.M68K.fsproj" />
    <ProjectReference Include="..\MIPS\B2R2.Assembly.MIPS.fsproj" />
    <ProjectReference
      Include="..\PARISC\B2R2.Assembly.PARISC.fsproj" />
    <ProjectReference Include="..\PPC\B2R2.Assembly.PPC.fsproj" />
    <ProjectReference Include="..\Python\B2R2.Assembly.Python.fsproj" />
    <ProjectReference
      Include="..\RISCV64\B2R2.Assembly.RISCV64.fsproj" />
    <ProjectReference Include="..\S390\B2R2.Assembly.S390.fsproj" />
    <ProjectReference Include="..\SPARC\B2R2.Assembly.SPARC.fsproj" />
    <ProjectReference Include="..\SH4\B2R2.Assembly.SH4.fsproj" />
  </ItemGroup>

</Project>
