version: '1.0.{build}'
image: Previous Visual Studio 2022
branches:
  only:
  - master
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build
clone_depth: 1
test_script:
  - cmd: dotnet test
deploy: off
