<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 frontend basic types.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Exceptions.fs" />
    <Compile Include="BinReader.fs" />
    <Compile Include="ConditionCodeOp.fs" />
    <Compile Include="IRegisterFactory.fs" />
    <Compile Include="INameResolvable.fs" />
    <Compile Include="LowUIRStream.fs" />
    <Compile Include="ILowUIRBuilder.fs" />
    <Compile Include="AsmWord.fs" />
    <Compile Include="DisasmSyntax.fs" />
    <Compile Include="IDisasmBuilder.fs" />
    <Compile Include="StringDisasmBuilder.fs" />
    <Compile Include="AsmWordDisasmBuilder.fs" />
    <Compile Include="IInstruction.fs" />
    <Compile Include="IInstructionParsable.fs" />
    <Compile Include="IIRBlockOptimizable.fs" />
    <Compile Include="ParsingUtils.fs" />
    <Compile Include="LiftingUtils.fs" />
    <Compile Include="ConstantFolding.fs" />
    <Compile Include="DeadCodeElimination.fs" />
    <Compile Include="LocalOptimizer.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\B2R2.Core.fsproj" />
    <ProjectReference Include="..\..\BinIR\B2R2.BinIR.fsproj" />
  </ItemGroup>

</Project>
