<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 middle-end SSA namespace.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ISSALiftable.fs" />
    <Compile Include="ISSAStackPointerObserver.fs" />
    <Compile Include="SSALifterFactory.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrontEnd\API\B2R2.FrontEnd.API.fsproj" />
    <ProjectReference Include="..\BinGraph\B2R2.MiddleEnd.BinGraph.fsproj" />
    <ProjectReference Include="..\ControlFlowGraph\B2R2.MiddleEnd.ControlFlowGraph.fsproj" />
    <ProjectReference Include="..\DataFlow\B2R2.MiddleEnd.DataFlow.fsproj" />
  </ItemGroup>

</Project>
