<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 assembly core library.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ILowerable.fs" />
    <Compile Include="Exceptions.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrontEnd\API\B2R2.FrontEnd.API.fsproj" />
  </ItemGroup>

</Project>
