<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 data-flow engine.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Constants.fs" />
    <Compile Include="VarPoint.fs" />
    <Compile Include="ConstantDomain.fs" />
    <Compile Include="StackPointerDomain.fs" />
    <Compile Include="UntouchedValueDomain.fs" />
    <Compile Include="VarDefDomain.fs" />
    <Compile Include="IDataFlowComputable.fs" />
    <Compile Include="Stmts.fs" />
    <Compile Include="WorklistDataFlow.fs" />
    <Compile Include="ReachingDefinition.fs" />
    <Compile Include="DataFlowChain.fs" />
    <Compile Include="LowUIRSparseDataFlow.fs" />
    <Compile Include="ConstantPropagation.fs" />
    <Compile Include="StackPointerPropagation.fs" />
    <Compile Include="UntouchedValueAnalysis.fs" />
    <Compile Include="LowUIRSensitiveDataFlow.fs" />
    <Compile Include="LowUIRSensitiveConstantPropagation.fs" />
    <Compile Include="SSAEdges.fs" />
    <Compile Include="SSASparseDataFlow.fs" />
    <Compile Include="SSAConstantPropagation.fs" />
    <Compile Include="SSAStackPointerPropagation.fs" />
    <Compile Include="SSAUntouchedValueAnalysis.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BinGraph\B2R2.MiddleEnd.BinGraph.fsproj" />
    <ProjectReference Include="..\ControlFlowGraph\B2R2.MiddleEnd.ControlFlowGraph.fsproj" />
  </ItemGroup>

</Project>
