(*
  B2R2 - the Next-Generation Reversing Platform

  Copyright (c) SoftSec Lab. @ KAIST, since 2016

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*)

module internal B2R2.FrontEnd.S390.Disasm

open B2R2
open B2R2.FrontEnd.BinLifter

let opCodeToString = function
  | Op.A -> "a"
  | Op.AD -> "ad"
  | Op.ADB -> "adb"
  | Op.ADBR -> "adbr"
  | Op.ADR -> "adr"
  | Op.ADTR -> "adtr"
  | Op.ADTRA -> "adtra"
  | Op.AE -> "ae"
  | Op.AEB -> "aeb"
  | Op.AEBR -> "aebr"
  | Op.AER -> "aer"
  | Op.AFI -> "afi"
  | Op.AG -> "ag"
  | Op.AGF -> "agf"
  | Op.AGFI -> "agfi"
  | Op.AGFR -> "agfr"
  | Op.AGH -> "agh"
  | Op.AGHI -> "aghi"
  | Op.AGHIK -> "aghik"
  | Op.AGR -> "agr"
  | Op.AGRK -> "agrk"
  | Op.AGSI -> "agsi"
  | Op.AH -> "ah"
  | Op.AHHHR -> "ahhhr"
  | Op.AHHLR -> "ahhlr"
  | Op.AHI -> "ahi"
  | Op.AHIK -> "ahik"
  | Op.AHY -> "ahy"
  | Op.AIH -> "aih"
  | Op.AL -> "al"
  | Op.ALC -> "alc"
  | Op.ALCG -> "alcg"
  | Op.ALCGR -> "alcgr"
  | Op.ALCR -> "alcr"
  | Op.ALFI -> "alfi"
  | Op.ALG -> "alg"
  | Op.ALGF -> "algf"
  | Op.ALGFI -> "algfi"
  | Op.ALGFR -> "algfr"
  | Op.ALGHSIK -> "alghsik"
  | Op.ALGR -> "algr"
  | Op.ALGRK -> "algrk"
  | Op.ALGSI -> "algsi"
  | Op.ALHHHR -> "alhhhr"
  | Op.ALHHLR -> "alhhlr"
  | Op.ALHSIK -> "alhsik"
  | Op.ALR -> "alr"
  | Op.ALRK -> "alrk"
  | Op.ALSI -> "alsi"
  | Op.ALSIH -> "alsih"
  | Op.ALSIHN -> "alsihn"
  | Op.ALY -> "aly"
  | Op.AP -> "ap"
  | Op.AR -> "ar"
  | Op.ARK -> "ark"
  | Op.ASI -> "asi"
  | Op.AU -> "au"
  | Op.AUR -> "aur"
  | Op.AW -> "aw"
  | Op.AWR -> "awr"
  | Op.AXBR -> "axbr"
  | Op.AXR -> "axr"
  | Op.AXTR -> "axtr"
  | Op.AXTRA -> "axtra"
  | Op.AY -> "ay"
  | Op.BAKR -> "bakr"
  | Op.BAL -> "bal"
  | Op.BALR -> "balr"
  | Op.BAS -> "bas"
  | Op.BASR -> "basr"
  | Op.BASSM -> "bassm"
  | Op.BC -> "bc"
  | Op.BCR -> "bcr"
  | Op.BCT -> "bct"
  | Op.BCTG -> "bctg"
  | Op.BCTGR -> "bctgr"
  | Op.BCTR -> "bctr"
  | Op.BIC -> "bic"
  | Op.BPP -> "bpp"
  | Op.BPRP -> "bprp"
  | Op.BRAS -> "bras"
  | Op.BRASL -> "brasl"
  | Op.BRC -> "brc"
  | Op.BRCL -> "brcl"
  | Op.BRCT -> "brct"
  | Op.BRCTG -> "brctg"
  | Op.BRCTH -> "brcth"
  | Op.BRXH -> "brxh"
  | Op.BRXHG -> "brxhg"
  | Op.BRXLE -> "brxle"
  | Op.BRXLG -> "brxlg"
  | Op.BSA -> "bsa"
  | Op.BSG -> "bsg"
  | Op.BSM -> "bsm"
  | Op.BXH -> "bxh"
  | Op.BXHG -> "bxhg"
  | Op.BXLE -> "bxle"
  | Op.BXLEG -> "bxleg"
  | Op.C -> "c"
  | Op.CD -> "cd"
  | Op.CDB -> "cdb"
  | Op.CDBR -> "cdbr"
  | Op.CDFBR -> "cdfbr"
  | Op.CDFBRA -> "cdfbra"
  | Op.CDFR -> "cdfr"
  | Op.CDFTR -> "cdftr"
  | Op.CDGBR -> "cdgbr"
  | Op.CDGBRA -> "cdgbra"
  | Op.CDGR -> "cdgr"
  | Op.CDGTR -> "cdgtr"
  | Op.CDGTRA -> "cdgtra"
  | Op.CDLFBR -> "cdlfbr"
  | Op.CDLFTR -> "cdlftr"
  | Op.CDLGBR -> "cdlgbr"
  | Op.CDLGTR -> "cdlgtr"
  | Op.CDPT -> "cdpt"
  | Op.CDR -> "cdr"
  | Op.CDS -> "cds"
  | Op.CDSG -> "cdsg"
  | Op.CDSTR -> "cdstr"
  | Op.CDSY -> "cdsy"
  | Op.CDTR -> "cdtr"
  | Op.CDUTR -> "cdutr"
  | Op.CDZT -> "cdzt"
  | Op.CE -> "ce"
  | Op.CEB -> "ceb"
  | Op.CEBR -> "cebr"
  | Op.CEDTR -> "cedtr"
  | Op.CEFBR -> "cefbr"
  | Op.CEFBRA -> "cefbra"
  | Op.CEFR -> "cefr"
  | Op.CEGBR -> "cegbr"
  | Op.CEGBRA -> "cegbra"
  | Op.CEGR -> "cegr"
  | Op.CELFBR -> "celfbr"
  | Op.CELGBR -> "celgbr"
  | Op.CER -> "cer"
  | Op.CEXTR -> "cextr"
  | Op.CFC -> "cfc"
  | Op.CFDBR -> "cfdbr"
  | Op.CFDBRA -> "cfdbra"
  | Op.CFDR -> "cfdr"
  | Op.CFDTR -> "cfdtr"
  | Op.CFEBR -> "cfebr"
  | Op.CFEBRA -> "cfebra"
  | Op.CFER -> "cfer"
  | Op.CFI -> "cfi"
  | Op.CFXBR -> "cfxbr"
  | Op.CFXBRA -> "cfxbra"
  | Op.CFXR -> "cfxr"
  | Op.CFXTR -> "cfxtr"
  | Op.CG -> "cg"
  | Op.CGDBR -> "cgdbr"
  | Op.CGDBRA -> "cgdbra"
  | Op.CGDR -> "cgdr"
  | Op.CGDTR -> "cgdtr"
  | Op.CGDTRA -> "cgdtra"
  | Op.CGEBR -> "cgebr"
  | Op.CGEBRA -> "cgebra"
  | Op.CGER -> "cger"
  | Op.CGF -> "cgf"
  | Op.CGFI -> "cgfi"
  | Op.CGFR -> "cgfr"
  | Op.CGFRL -> "cgfrl"
  | Op.CGH -> "cgh"
  | Op.CGHI -> "cghi"
  | Op.CGHRL -> "cghrl"
  | Op.CGHSI -> "cghsi"
  | Op.CGIB -> "cgib"
  | Op.CGIJ -> "cgij"
  | Op.CGIT -> "cgit"
  | Op.CGR -> "cgr"
  | Op.CGRB -> "cgrb"
  | Op.CGRJ -> "cgrj"
  | Op.CGRL -> "cgrl"
  | Op.CGRT -> "cgrt"
  | Op.CGXBR -> "cgxbr"
  | Op.CGXBRA -> "cgxbra"
  | Op.CGXR -> "cgxr"
  | Op.CGXTR -> "cgxtr"
  | Op.CGXTRA -> "cgxtra"
  | Op.CH -> "ch"
  | Op.CHF -> "chf"
  | Op.CHHR -> "chhr"
  | Op.CHHSI -> "chhsi"
  | Op.CHI -> "chi"
  | Op.CHLR -> "chlr"
  | Op.CHRL -> "chrl"
  | Op.CHSI -> "chsi"
  | Op.CHY -> "chy"
  | Op.CIB -> "cib"
  | Op.CIH -> "cih"
  | Op.CIJ -> "cij"
  | Op.CIT -> "cit"
  | Op.CKSM -> "cksm"
  | Op.CL -> "cl"
  | Op.CLC -> "clc"
  | Op.CLCL -> "clcl"
  | Op.CLCLE -> "clcle"
  | Op.CLCLU -> "clclu"
  | Op.CLFDBR -> "clfdbr"
  | Op.CLFDTR -> "clfdtr"
  | Op.CLFEBR -> "clfebr"
  | Op.CLFHSI -> "clfhsi"
  | Op.CLFI -> "clfi"
  | Op.CLFIT -> "clfit"
  | Op.CLFXBR -> "clfxbr"
  | Op.CLFXTR -> "clfxtr"
  | Op.CLG -> "clg"
  | Op.CLGDBR -> "clgdbr"
  | Op.CLGDTR -> "clgdtr"
  | Op.CLGEBR -> "clgebr"
  | Op.CLGF -> "clgf"
  | Op.CLGFI -> "clgfi"
  | Op.CLGFR -> "clgfr"
  | Op.CLGFRL -> "clgfrl"
  | Op.CLGHRL -> "clghrl"
  | Op.CLGHSI -> "clghsi"
  | Op.CLGIB -> "clgib"
  | Op.CLGIJ -> "clgij"
  | Op.CLGIT -> "clgit"
  | Op.CLGR -> "clgr"
  | Op.CLGRB -> "clgrb"
  | Op.CLGRJ -> "clgrj"
  | Op.CLGRL -> "clgrl"
  | Op.CLGRT -> "clgrt"
  | Op.CLGT -> "clgt"
  | Op.CLGXBR -> "clgxbr"
  | Op.CLGXTR -> "clgxtr"
  | Op.CLHF -> "clhf"
  | Op.CLHHR -> "clhhr"
  | Op.CLHHSI -> "clhhsi"
  | Op.CLHLR -> "clhlr"
  | Op.CLHRL -> "clhrl"
  | Op.CLI -> "cli"
  | Op.CLIB -> "clib"
  | Op.CLIH -> "clih"
  | Op.CLIJ -> "clij"
  | Op.CLIY -> "cliy"
  | Op.CLM -> "clm"
  | Op.CLMH -> "clmh"
  | Op.CLMY -> "clmy"
  | Op.CLR -> "clr"
  | Op.CLRB -> "clrb"
  | Op.CLRJ -> "clrj"
  | Op.CLRL -> "clrl"
  | Op.CLRT -> "clrt"
  | Op.CLST -> "clst"
  | Op.CLT -> "clt"
  | Op.CLY -> "cly"
  | Op.CMPSC -> "cmpsc"
  | Op.CP -> "cp"
  | Op.CPDT -> "cpdt"
  | Op.CPSDR -> "cpsdr"
  | Op.CPXT -> "cpxt"
  | Op.CPYA -> "cpya"
  | Op.CR -> "cr"
  | Op.CRB -> "crb"
  | Op.CRDTE -> "crdte"
  | Op.CRJ -> "crj"
  | Op.CRL -> "crl"
  | Op.CRT -> "crt"
  | Op.CS -> "cs"
  | Op.CSCH -> "csch"
  | Op.CSDTR -> "csdtr"
  | Op.CSG -> "csg"
  | Op.CSP -> "csp"
  | Op.CSPG -> "cspg"
  | Op.CSST -> "csst"
  | Op.CSXTR -> "csxtr"
  | Op.CSY -> "csy"
  | Op.CU12 -> "cu12"
  | Op.CU14 -> "cu14"
  | Op.CU21 -> "cu21"
  | Op.CU24 -> "cu24"
  | Op.CU41 -> "cu41"
  | Op.CU42 -> "cu42"
  | Op.CUDTR -> "cudtr"
  | Op.CUSE -> "cuse"
  | Op.CUTFU -> "cutfu"
  | Op.CUUTF -> "cuutf"
  | Op.CUXTR -> "cuxtr"
  | Op.CVB -> "cvb"
  | Op.CVBG -> "cvbg"
  | Op.CVBY -> "cvby"
  | Op.CVD -> "cvd"
  | Op.CVDG -> "cvdg"
  | Op.CVDY -> "cvdy"
  | Op.CXBR -> "cxbr"
  | Op.CXFBR -> "cxfbr"
  | Op.CXFBRA -> "cxfbra"
  | Op.CXFR -> "cxfr"
  | Op.CXFTR -> "cxftr"
  | Op.CXGBR -> "cxgbr"
  | Op.CXGBRA -> "cxgbra"
  | Op.CXGR -> "cxgr"
  | Op.CXGTR -> "cxgtr"
  | Op.CXGTRA -> "cxgtra"
  | Op.CXLFBR -> "cxlfbr"
  | Op.CXLFTR -> "cxlftr"
  | Op.CXLGBR -> "cxlgbr"
  | Op.CXLGTR -> "cxlgtr"
  | Op.CXPT -> "cxpt"
  | Op.CXR -> "cxr"
  | Op.CXSTR -> "cxstr"
  | Op.CXTR -> "cxtr"
  | Op.CXUTR -> "cxutr"
  | Op.CXZT -> "cxzt"
  | Op.CY -> "cy"
  | Op.CZDT -> "czdt"
  | Op.CZXT -> "czxt"
  | Op.D -> "d"
  | Op.DD -> "dd"
  | Op.DDB -> "ddb"
  | Op.DDBR -> "ddbr"
  | Op.DDR -> "ddr"
  | Op.DDTR -> "ddtr"
  | Op.DDTRA -> "ddtra"
  | Op.DE -> "de"
  | Op.DEB -> "deb"
  | Op.DEBR -> "debr"
  | Op.DER -> "der"
  | Op.DFLTCC -> "dfltcc"
  | Op.Diagnose -> "diagnose"
  | Op.DIDBR -> "didbr"
  | Op.DIEBR -> "diebr"
  | Op.DL -> "dl"
  | Op.DLG -> "dlg"
  | Op.DLGR -> "dlgr"
  | Op.DLR -> "dlr"
  | Op.DP -> "dp"
  | Op.DR -> "dr"
  | Op.DSG -> "dsg"
  | Op.DSGF -> "dsgf"
  | Op.DSGFR -> "dsgfr"
  | Op.DSGR -> "dsgr"
  | Op.DXBR -> "dxbr"
  | Op.DXR -> "dxr"
  | Op.DXTR -> "dxtr"
  | Op.DXTRA -> "dxtra"
  | Op.EAR -> "ear"
  | Op.ECAG -> "ecag"
  | Op.ECTG -> "ectg"
  | Op.ED -> "ed"
  | Op.EDMK -> "edmk"
  | Op.EEDTR -> "eedtr"
  | Op.EEXTR -> "eextr"
  | Op.EFPC -> "efpc"
  | Op.EPAIR -> "epair"
  | Op.EPAR -> "epar"
  | Op.EPSW -> "epsw"
  | Op.EREG -> "ereg"
  | Op.EREGG -> "eregg"
  | Op.ESAIR -> "esair"
  | Op.ESAR -> "esar"
  | Op.ESDTR -> "esdtr"
  | Op.ESEA -> "esea"
  | Op.ESTA -> "esta"
  | Op.ESXTR -> "esxtr"
  | Op.ETND -> "etnd"
  | Op.EX -> "ex"
  | Op.EXRL -> "exrl"
  | Op.FIDBR -> "fidbr"
  | Op.FIDBRA -> "fidbra"
  | Op.FIDR -> "fidr"
  | Op.FIDTR -> "fidtr"
  | Op.FIEBR -> "fiebr"
  | Op.FIEBRA -> "fiebra"
  | Op.FIER -> "fier"
  | Op.FIXBR -> "fixbr"
  | Op.FIXBRA -> "fixbra"
  | Op.FIXR -> "fixr"
  | Op.FIXTR -> "fixtr"
  | Op.FLOGR -> "flogr"
  | Op.HDR -> "hdr"
  | Op.HER -> "her"
  | Op.HSCH -> "hsch"
  | Op.IAC -> "iac"
  | Op.IC -> "ic"
  | Op.ICM -> "icm"
  | Op.ICMH -> "icmh"
  | Op.ICMY -> "icmy"
  | Op.ICY -> "icy"
  | Op.IDTE -> "idte"
  | Op.IEDTR -> "iedtr"
  | Op.IEXTR -> "iextr"
  | Op.IIHF -> "iihf"
  | Op.IIHH -> "iihh"
  | Op.IIHL -> "iihl"
  | Op.IILF -> "iilf"
  | Op.IILH -> "iilh"
  | Op.IILL -> "iill"
  | Op.IPK -> "ipk"
  | Op.IPM -> "ipm"
  | Op.IPTE -> "ipte"
  | Op.IRBM -> "irbm"
  | Op.ISKE -> "iske"
  | Op.IVSK -> "ivsk"
  | Op.KDB -> "kdb"
  | Op.KDBR -> "kdbr"
  | Op.KDSA -> "kdsa"
  | Op.KDTR -> "kdtr"
  | Op.KEB -> "keb"
  | Op.KEBR -> "kebr"
  | Op.KIMD -> "kimd"
  | Op.KLMD -> "klmd"
  | Op.KM -> "km"
  | Op.KMA -> "kma"
  | Op.KMAC -> "kmac"
  | Op.KMC -> "kmc"
  | Op.KMCTR -> "kmctr"
  | Op.KMF -> "kmf"
  | Op.KMO -> "kmo"
  | Op.KXBR -> "kxbr"
  | Op.KXTR -> "kxtr"
  | Op.L -> "l"
  | Op.LA -> "la"
  | Op.LAA -> "laa"
  | Op.LAAG -> "laag"
  | Op.LAAL -> "laal"
  | Op.LAALG -> "laalg"
  | Op.LAE -> "lae"
  | Op.LAEY -> "laey"
  | Op.LAM -> "lam"
  | Op.LAMY -> "lamy"
  | Op.LAN -> "lan"
  | Op.LANG -> "lang"
  | Op.LAO -> "lao"
  | Op.LAOG -> "laog"
  | Op.LARL -> "larl"
  | Op.LASP -> "lasp"
  | Op.LAT -> "lat"
  | Op.LAX -> "lax"
  | Op.LAXG -> "laxg"
  | Op.LAY -> "lay"
  | Op.LB -> "lb"
  | Op.LBEAR -> "lbear"
  | Op.LBH -> "lbh"
  | Op.LBR -> "lbr"
  | Op.LCBB -> "lcbb"
  | Op.LCDBR -> "lcdbr"
  | Op.LCDFR -> "lcdfr"
  | Op.LCDR -> "lcdr"
  | Op.LCEBR -> "lcebr"
  | Op.LCER -> "lcer"
  | Op.LCGFR -> "lcgfr"
  | Op.LCGR -> "lcgr"
  | Op.LCR -> "lcr"
  | Op.LCTL -> "lctl"
  | Op.LCTLG -> "lctlg"
  | Op.LCXBR -> "lcxbr"
  | Op.LCXR -> "lcxr"
  | Op.LD -> "ld"
  | Op.LDE -> "lde"
  | Op.LDEB -> "ldeb"
  | Op.LDEBR -> "ldebr"
  | Op.LDER -> "lder"
  | Op.LDETR -> "ldetr"
  | Op.LDGR -> "ldgr"
  | Op.LDR -> "ldr"
  | Op.LDXBR -> "ldxbr"
  | Op.LDXBRA -> "ldxbra"
  | Op.LDXR -> "ldxr"
  | Op.LDXTR -> "ldxtr"
  | Op.LDY -> "ldy"
  | Op.LE -> "le"
  | Op.LEDBR -> "ledbr"
  | Op.LEDBRA -> "ledbra"
  | Op.LEDR -> "ledr"
  | Op.LEDTR -> "ledtr"
  | Op.LER -> "ler"
  | Op.LEXBR -> "lexbr"
  | Op.LEXBRA -> "lexbra"
  | Op.LEXR -> "lexr"
  | Op.LEY -> "ley"
  | Op.LFAS -> "lfas"
  | Op.LFH -> "lfh"
  | Op.LFHAT -> "lfhat"
  | Op.LFPC -> "lfpc"
  | Op.LG -> "lg"
  | Op.LGAT -> "lgat"
  | Op.LGB -> "lgb"
  | Op.LGBR -> "lgbr"
  | Op.LGDR -> "lgdr"
  | Op.LGF -> "lgf"
  | Op.LGFI -> "lgfi"
  | Op.LGFR -> "lgfr"
  | Op.LGFRL -> "lgfrl"
  | Op.LGG -> "lgg"
  | Op.LGH -> "lgh"
  | Op.LGHI -> "lghi"
  | Op.LGHR -> "lghr"
  | Op.LGHRL -> "lghrl"
  | Op.LGR -> "lgr"
  | Op.LGRL -> "lgrl"
  | Op.LGSC -> "lgsc"
  | Op.LH -> "lh"
  | Op.LHH -> "lhh"
  | Op.LHI -> "lhi"
  | Op.LHR -> "lhr"
  | Op.LHRL -> "lhrl"
  | Op.LHY -> "lhy"
  | Op.LLC -> "llc"
  | Op.LLCH -> "llch"
  | Op.LLCR -> "llcr"
  | Op.LLGC -> "llgc"
  | Op.LLGCR -> "llgcr"
  | Op.LLGF -> "llgf"
  | Op.LLGFAT -> "llgfat"
  | Op.LLGFR -> "llgfr"
  | Op.LLGFRL -> "llgfrl"
  | Op.LLGFSG -> "llgfsg"
  | Op.LLGH -> "llgh"
  | Op.LLGHR -> "llghr"
  | Op.LLGHRL -> "llghrl"
  | Op.LLGT -> "llgt"
  | Op.LLGTAT -> "llgtat"
  | Op.LLGTR -> "llgtr"
  | Op.LLH -> "llh"
  | Op.LLHH -> "llhh"
  | Op.LLHR -> "llhr"
  | Op.LLHRL -> "llhrl"
  | Op.LLIHF -> "llihf"
  | Op.LLIHH -> "llihh"
  | Op.LLIHL -> "llihl"
  | Op.LLILF -> "llilf"
  | Op.LLILH -> "llilh"
  | Op.LLILL -> "llill"
  | Op.LLZRGF -> "llzrgf"
  | Op.LM -> "lm"
  | Op.LMD -> "lmd"
  | Op.LMG -> "lmg"
  | Op.LMH -> "lmh"
  | Op.LMY -> "lmy"
  | Op.LNDBR -> "lndbr"
  | Op.LNDFR -> "lndfr"
  | Op.LNDR -> "lndr"
  | Op.LNEBR -> "lnebr"
  | Op.LNER -> "lner"
  | Op.LNGFR -> "lngfr"
  | Op.LNGR -> "lngr"
  | Op.LNR -> "lnr"
  | Op.LNXBR -> "lnxbr"
  | Op.LNXR -> "lnxr"
  | Op.LOC -> "loc"
  | Op.LOCFH -> "locfh"
  | Op.LOCFHR -> "locfhr"
  | Op.LOCG -> "locg"
  | Op.LOCGHI -> "locghi"
  | Op.LOCGR -> "locgr"
  | Op.LOCHHI -> "lochhi"
  | Op.LOCHI -> "lochi"
  | Op.LOCR -> "locr"
  | Op.LPD -> "lpd"
  | Op.LPDBR -> "lpdbr"
  | Op.LPDFR -> "lpdfr"
  | Op.LPDG -> "lpdg"
  | Op.LPDR -> "lpdr"
  | Op.LPEBR -> "lpebr"
  | Op.LPER -> "lper"
  | Op.LPGFR -> "lpgfr"
  | Op.LPGR -> "lpgr"
  | Op.LPQ -> "lpq"
  | Op.LPR -> "lpr"
  | Op.LPSW -> "lpsw"
  | Op.LPSWE -> "lpswe"
  | Op.LPSWEY -> "lpswey"
  | Op.LPTEA -> "lptea"
  | Op.LPXBR -> "lpxbr"
  | Op.LPXR -> "lpxr"
  | Op.LR -> "lr"
  | Op.LRA -> "lra"
  | Op.LRAG -> "lrag"
  | Op.LRAY -> "lray"
  | Op.LRL -> "lrl"
  | Op.LRV -> "lrv"
  | Op.LRVG -> "lrvg"
  | Op.LRVGR -> "lrvgr"
  | Op.LRVH -> "lrvh"
  | Op.LRVR -> "lrvr"
  | Op.LT -> "lt"
  | Op.LTDBR -> "ltdbr"
  | Op.LTDR -> "ltdr"
  | Op.LTDTR -> "ltdtr"
  | Op.LTEBR -> "ltebr"
  | Op.LTER -> "lter"
  | Op.LTG -> "ltg"
  | Op.LTGF -> "ltgf"
  | Op.LTGFR -> "ltgfr"
  | Op.LTGR -> "ltgr"
  | Op.LTR -> "ltr"
  | Op.LTXBR -> "ltxbr"
  | Op.LTXR -> "ltxr"
  | Op.LTXTR -> "ltxtr"
  | Op.LURA -> "lura"
  | Op.LURAG -> "lurag"
  | Op.LXD -> "lxd"
  | Op.LXDB -> "lxdb"
  | Op.LXDBR -> "lxdbr"
  | Op.LXDR -> "lxdr"
  | Op.LXDTR -> "lxdtr"
  | Op.LXE -> "lxe"
  | Op.LXEB -> "lxeb"
  | Op.LXEBR -> "lxebr"
  | Op.LXER -> "lxer"
  | Op.LXR -> "lxr"
  | Op.LY -> "ly"
  | Op.LZDR -> "lzdr"
  | Op.LZER -> "lzer"
  | Op.LZRF -> "lzrf"
  | Op.LZRG -> "lzrg"
  | Op.LZXR -> "lzxr"
  | Op.M -> "m"
  | Op.MAD -> "mad"
  | Op.MADB -> "madb"
  | Op.MADBR -> "madbr"
  | Op.MADR -> "madr"
  | Op.MAE -> "mae"
  | Op.MAEB -> "maeb"
  | Op.MAEBR -> "maebr"
  | Op.MAER -> "maer"
  | Op.MAY -> "may"
  | Op.MAYH -> "mayh"
  | Op.MAYHR -> "mayhr"
  | Op.MAYL -> "mayl"
  | Op.MAYLR -> "maylr"
  | Op.MAYR -> "mayr"
  | Op.MC -> "mc"
  | Op.MD -> "md"
  | Op.MDB -> "mdb"
  | Op.MDBR -> "mdbr"
  | Op.MDE -> "mde"
  | Op.MDEB -> "mdeb"
  | Op.MDEBR -> "mdebr"
  | Op.MDER -> "mder"
  | Op.MDR -> "mdr"
  | Op.MDTR -> "mdtr"
  | Op.MDTRA -> "mdtra"
  | Op.MEE -> "mee"
  | Op.MEEB -> "meeb"
  | Op.MEEBR -> "meebr"
  | Op.MEER -> "meer"
  | Op.MFY -> "mfy"
  | Op.MG -> "mg"
  | Op.MGH -> "mgh"
  | Op.MGHI -> "mghi"
  | Op.MGRK -> "mgrk"
  | Op.MH -> "mh"
  | Op.MHI -> "mhi"
  | Op.MHY -> "mhy"
  | Op.ML -> "ml"
  | Op.MLG -> "mlg"
  | Op.MLGR -> "mlgr"
  | Op.MLR -> "mlr"
  | Op.MP -> "mp"
  | Op.MR -> "mr"
  | Op.MS -> "ms"
  | Op.MSC -> "msc"
  | Op.MSCH -> "msch"
  | Op.MSD -> "msd"
  | Op.MSDB -> "msdb"
  | Op.MSDBR -> "msdbr"
  | Op.MSDR -> "msdr"
  | Op.MSE -> "mse"
  | Op.MSEB -> "mseb"
  | Op.MSEBR -> "msebr"
  | Op.MSER -> "mser"
  | Op.MSFI -> "msfi"
  | Op.MSG -> "msg"
  | Op.MSGC -> "msgc"
  | Op.MSGF -> "msgf"
  | Op.MSGFI -> "msgfi"
  | Op.MSGFR -> "msgfr"
  | Op.MSGR -> "msgr"
  | Op.MSGRKC -> "msgrkc"
  | Op.MSR -> "msr"
  | Op.MSRKC -> "msrkc"
  | Op.MSTA -> "msta"
  | Op.MSY -> "msy"
  | Op.MVC -> "mvc"
  | Op.MVCDK -> "mvcdk"
  | Op.MVCIN -> "mvcin"
  | Op.MVCK -> "mvck"
  | Op.MVCL -> "mvcl"
  | Op.MVCLE -> "mvcle"
  | Op.MVCLU -> "mvclu"
  | Op.MVCOS -> "mvcos"
  | Op.MVCP -> "mvcp"
  | Op.MVCRL -> "mvcrl"
  | Op.MVCS -> "mvcs"
  | Op.MVCSK -> "mvcsk"
  | Op.MVGHI -> "mvghi"
  | Op.MVHHI -> "mvhhi"
  | Op.MVHI -> "mvhi"
  | Op.MVI -> "mvi"
  | Op.MVIY -> "mviy"
  | Op.MVN -> "mvn"
  | Op.MVO -> "mvo"
  | Op.MVPG -> "mvpg"
  | Op.MVST -> "mvst"
  | Op.MVZ -> "mvz"
  | Op.MXBR -> "mxbr"
  | Op.MXD -> "mxd"
  | Op.MXDB -> "mxdb"
  | Op.MXDBR -> "mxdbr"
  | Op.MXDR -> "mxdr"
  | Op.MXR -> "mxr"
  | Op.MXTR -> "mxtr"
  | Op.MXTRA -> "mxtra"
  | Op.MY -> "my"
  | Op.MYH -> "myh"
  | Op.MYHR -> "myhr"
  | Op.MYL -> "myl"
  | Op.MYLR -> "mylr"
  | Op.MYR -> "myr"
  | Op.N -> "n"
  | Op.NC -> "nc"
  | Op.NG -> "ng"
  | Op.NGR -> "ngr"
  | Op.NGRK -> "ngrk"
  | Op.NI -> "ni"
  | Op.NIAI -> "niai"
  | Op.NIHF -> "nihf"
  | Op.NIHH -> "nihh"
  | Op.NIHL -> "nihl"
  | Op.NILF -> "nilf"
  | Op.NILH -> "nilh"
  | Op.NILL -> "nill"
  | Op.NIY -> "niy"
  | Op.NNPA -> "nnpa"
  | Op.NR -> "nr"
  | Op.NRK -> "nrk"
  | Op.NTSTG -> "ntstg"
  | Op.NY -> "ny"
  | Op.O -> "o"
  | Op.OC -> "oc"
  | Op.OG -> "og"
  | Op.OGR -> "ogr"
  | Op.OGRK -> "ogrk"
  | Op.OI -> "oi"
  | Op.OIHF -> "oihf"
  | Op.OIHH -> "oihh"
  | Op.OIHL -> "oihl"
  | Op.OILF -> "oilf"
  | Op.OILH -> "oilh"
  | Op.OILL -> "oill"
  | Op.OIY -> "oiy"
  | Op.OR -> "or"
  | Op.ORK -> "ork"
  | Op.OY -> "oy"
  | Op.PACK -> "pack"
  | Op.PALB -> "palb"
  | Op.PC -> "pc"
  | Op.PCC -> "pcc"
  | Op.PCKMO -> "pckmo"
  | Op.PFD -> "pfd"
  | Op.PFDRL -> "pfdrl"
  | Op.PFMF -> "pfmf"
  | Op.PFPO -> "pfpo"
  | Op.PGIN -> "pgin"
  | Op.PGOUT -> "pgout"
  | Op.PKA -> "pka"
  | Op.PKU -> "pku"
  | Op.PLO -> "plo"
  | Op.POPCNT -> "popcnt"
  | Op.PPA -> "ppa"
  | Op.PR -> "pr"
  | Op.PRNO -> "prno"
  | Op.PT -> "pt"
  | Op.PTF -> "ptf"
  | Op.PTFF -> "ptff"
  | Op.PTI -> "pti"
  | Op.PTLB -> "ptlb"
  | Op.QADTR -> "qadtr"
  | Op.QAXTR -> "qaxtr"
  | Op.QPACI -> "qpaci"
  | Op.RCHP -> "rchp"
  | Op.RISBG -> "risbg"
  | Op.RISBGN -> "risbgn"
  | Op.RISBHG -> "risbhg"
  | Op.RISBLG -> "risblg"
  | Op.RLL -> "rll"
  | Op.RLLG -> "rllg"
  | Op.RNSBG -> "rnsbg"
  | Op.ROSBG -> "rosbg"
  | Op.RP -> "rp"
  | Op.RRBE -> "rrbe"
  | Op.RRBM -> "rrbm"
  | Op.RRDTR -> "rrdtr"
  | Op.RRXTR -> "rrxtr"
  | Op.RSCH -> "rsch"
  | Op.RXSBG -> "rxsbg"
  | Op.S -> "s"
  | Op.SAC -> "sac"
  | Op.SACF -> "sacf"
  | Op.SAL -> "sal"
  | Op.SAM24 -> "sam24"
  | Op.SAM31 -> "sam31"
  | Op.SAM64 -> "sam64"
  | Op.SAR -> "sar"
  | Op.SCHM -> "schm"
  | Op.SCK -> "sck"
  | Op.SCKC -> "sckc"
  | Op.SCKPF -> "sckpf"
  | Op.SD -> "sd"
  | Op.SDB -> "sdb"
  | Op.SDBR -> "sdbr"
  | Op.SDR -> "sdr"
  | Op.SDTR -> "sdtr"
  | Op.SDTRA -> "sdtra"
  | Op.SE -> "se"
  | Op.SEB -> "seb"
  | Op.SEBR -> "sebr"
  | Op.SER -> "ser"
  | Op.SFASR -> "sfasr"
  | Op.SFPC -> "sfpc"
  | Op.SG -> "sg"
  | Op.SGF -> "sgf"
  | Op.SGFR -> "sgfr"
  | Op.SGH -> "sgh"
  | Op.SGR -> "sgr"
  | Op.SGRK -> "sgrk"
  | Op.SH -> "sh"
  | Op.SHHHR -> "shhhr"
  | Op.SHHLR -> "shhlr"
  | Op.SHY -> "shy"
  | Op.SIGP -> "sigp"
  | Op.SL -> "sl"
  | Op.SLA -> "sla"
  | Op.SLAG -> "slag"
  | Op.SLAK -> "slak"
  | Op.SLB -> "slb"
  | Op.SLBG -> "slbg"
  | Op.SLBGR -> "slbgr"
  | Op.SLBR -> "slbr"
  | Op.SLDA -> "slda"
  | Op.SLDL -> "sldl"
  | Op.SLDT -> "sldt"
  | Op.SLFI -> "slfi"
  | Op.SLG -> "slg"
  | Op.SLGF -> "slgf"
  | Op.SLGFI -> "slgfi"
  | Op.SLGFR -> "slgfr"
  | Op.SLGR -> "slgr"
  | Op.SLGRK -> "slgrk"
  | Op.SLHHHR -> "slhhhr"
  | Op.SLHHLR -> "slhhlr"
  | Op.SLL -> "sll"
  | Op.SLLG -> "sllg"
  | Op.SLLK -> "sllk"
  | Op.SLR -> "slr"
  | Op.SLRK -> "slrk"
  | Op.SLXT -> "slxt"
  | Op.SLY -> "sly"
  | Op.SORTL -> "sortl"
  | Op.SP -> "sp"
  | Op.SPKA -> "spka"
  | Op.SPM -> "spm"
  | Op.SPT -> "spt"
  | Op.SPX -> "spx"
  | Op.SQD -> "sqd"
  | Op.SQDB -> "sqdb"
  | Op.SQDBR -> "sqdbr"
  | Op.SQDR -> "sqdr"
  | Op.SQE -> "sqe"
  | Op.SQEB -> "sqeb"
  | Op.SQEBR -> "sqebr"
  | Op.SQER -> "sqer"
  | Op.SQXBR -> "sqxbr"
  | Op.SQXR -> "sqxr"
  | Op.SR -> "sr"
  | Op.SRA -> "sra"
  | Op.SRAG -> "srag"
  | Op.SRAK -> "srak"
  | Op.SRDA -> "srda"
  | Op.SRDL -> "srdl"
  | Op.SRDT -> "srdt"
  | Op.SRK -> "srk"
  | Op.SRL -> "srl"
  | Op.SRLG -> "srlg"
  | Op.SRLK -> "srlk"
  | Op.SRNM -> "srnm"
  | Op.SRNMB -> "srnmb"
  | Op.SRNMT -> "srnmt"
  | Op.SRP -> "srp"
  | Op.SRST -> "srst"
  | Op.SRSTU -> "srstu"
  | Op.SRXT -> "srxt"
  | Op.SSAIR -> "ssair"
  | Op.SSAR -> "ssar"
  | Op.SSCH -> "ssch"
  | Op.SSKE -> "sske"
  | Op.SSM -> "ssm"
  | Op.ST -> "st"
  | Op.STAM -> "stam"
  | Op.STAMY -> "stamy"
  | Op.STAP -> "stap"
  | Op.STBEAR -> "stbear"
  | Op.STC -> "stc"
  | Op.STCH -> "stch"
  | Op.STCK -> "stck"
  | Op.STCKC -> "stckc"
  | Op.STCKE -> "stcke"
  | Op.STCKF -> "stckf"
  | Op.STCM -> "stcm"
  | Op.STCMH -> "stcmh"
  | Op.STCMY -> "stcmy"
  | Op.STCPS -> "stcps"
  | Op.STCRW -> "stcrw"
  | Op.STCTG -> "stctg"
  | Op.STCTL -> "stctl"
  | Op.STCY -> "stcy"
  | Op.STD -> "std"
  | Op.STDY -> "stdy"
  | Op.STE -> "ste"
  | Op.STEY -> "stey"
  | Op.STFH -> "stfh"
  | Op.STFL -> "stfl"
  | Op.STFLE -> "stfle"
  | Op.STFPC -> "stfpc"
  | Op.STG -> "stg"
  | Op.STGRL -> "stgrl"
  | Op.STGSC -> "stgsc"
  | Op.STH -> "sth"
  | Op.STHH -> "sthh"
  | Op.STHRL -> "sthrl"
  | Op.STHY -> "sthy"
  | Op.STIDP -> "stidp"
  | Op.STM -> "stm"
  | Op.STMG -> "stmg"
  | Op.STMH -> "stmh"
  | Op.STMY -> "stmy"
  | Op.STNSM -> "stnsm"
  | Op.STOC -> "stoc"
  | Op.STOCFH -> "stocfh"
  | Op.STOCG -> "stocg"
  | Op.STOSM -> "stosm"
  | Op.STPQ -> "stpq"
  | Op.STPT -> "stpt"
  | Op.STPX -> "stpx"
  | Op.STRAG -> "strag"
  | Op.STRL -> "strl"
  | Op.STRV -> "strv"
  | Op.STRVG -> "strvg"
  | Op.STRVH -> "strvh"
  | Op.STSCH -> "stsch"
  | Op.STSI -> "stsi"
  | Op.STURA -> "stura"
  | Op.STURG -> "sturg"
  | Op.STY -> "sty"
  | Op.SU -> "su"
  | Op.SUR -> "sur"
  | Op.SVC -> "svc"
  | Op.SW -> "sw"
  | Op.SWR -> "swr"
  | Op.SXBR -> "sxbr"
  | Op.SXR -> "sxr"
  | Op.SXTR -> "sxtr"
  | Op.SXTRA -> "sxtra"
  | Op.SY -> "sy"
  | Op.TABORT -> "tabort"
  | Op.TAM -> "tam"
  | Op.TAR -> "tar"
  | Op.TB -> "tb"
  | Op.TBDR -> "tbdr"
  | Op.TBEDR -> "tbedr"
  | Op.TBEGIN -> "tbegin"
  | Op.TBEGINC -> "tbeginc"
  | Op.TCDB -> "tcdb"
  | Op.TCEB -> "tceb"
  | Op.TCXB -> "tcxb"
  | Op.TDCDT -> "tdcdt"
  | Op.TDCET -> "tdcet"
  | Op.TDCXT -> "tdcxt"
  | Op.TDGDT -> "tdgdt"
  | Op.TDGET -> "tdget"
  | Op.TDGXT -> "tdgxt"
  | Op.TEND -> "tend"
  | Op.THDER -> "thder"
  | Op.THDR -> "thdr"
  | Op.TM -> "tm"
  | Op.TMHH -> "tmhh"
  | Op.TMHL -> "tmhl"
  | Op.TMLH -> "tmlh"
  | Op.TMLL -> "tmll"
  | Op.TMY -> "tmy"
  | Op.TP -> "tp"
  | Op.TPEI -> "tpei"
  | Op.TPI -> "tpi"
  | Op.TPROT -> "tprot"
  | Op.TR -> "tr"
  | Op.TRACE -> "trace"
  | Op.TRACG -> "tracg"
  | Op.TRAP2 -> "trap2"
  | Op.TRAP4 -> "trap4"
  | Op.TRE -> "tre"
  | Op.TROO -> "troo"
  | Op.TROT -> "trot"
  | Op.TRT -> "trt"
  | Op.TRTE -> "trte"
  | Op.TRTO -> "trto"
  | Op.TRTR -> "trtr"
  | Op.TRTRE -> "trtre"
  | Op.TRTT -> "trtt"
  | Op.TS -> "ts"
  | Op.TSCH -> "tsch"
  | Op.UNPK -> "unpk"
  | Op.UNPKA -> "unpka"
  | Op.UNPKU -> "unpku"
  | Op.UPT -> "upt"
  | Op.VA -> "va"
  | Op.VAC -> "vac"
  | Op.VACC -> "vacc"
  | Op.VACCC -> "vaccc"
  | Op.VAP -> "vap"
  | Op.VAVG -> "vavg"
  | Op.VAVGL -> "vavgl"
  | Op.VBPERM -> "vbperm"
  | Op.VCEQ -> "vceq"
  | Op.VCFN -> "vcfn"
  | Op.VCFPL -> "vcfpl"
  | Op.VCFPS -> "vcfps"
  | Op.VCH -> "vch"
  | Op.VCHL -> "vchl"
  | Op.VCKSM -> "vcksm"
  | Op.VCLFNH -> "vclfnh"
  | Op.VCLFNL -> "vclfnl"
  | Op.VCLFP -> "vclfp"
  | Op.VCLZ -> "vclz"
  | Op.VCLZDP -> "vclzdp"
  | Op.VCNF -> "vcnf"
  | Op.VCP -> "vcp"
  | Op.VCRNF -> "vcrnf"
  | Op.VCSFP -> "vcsfp"
  | Op.VCSPH -> "vcsph"
  | Op.VCTZ -> "vctz"
  | Op.VCVB -> "vcvb"
  | Op.VCVBG -> "vcvbg"
  | Op.VCVD -> "vcvd"
  | Op.VCVDG -> "vcvdg"
  | Op.VDP -> "vdp"
  | Op.VEC -> "vec"
  | Op.VECL -> "vecl"
  | Op.VERIM -> "verim"
  | Op.VERLL -> "verll"
  | Op.VERLLV -> "verllv"
  | Op.VESL -> "vesl"
  | Op.VESLV -> "veslv"
  | Op.VESRA -> "vesra"
  | Op.VESRAV -> "vesrav"
  | Op.VESRL -> "vesrl"
  | Op.VESRLV -> "vesrlv"
  | Op.VFA -> "vfa"
  | Op.VFAE -> "vfae"
  | Op.VFCE -> "vfce"
  | Op.VFCH -> "vfch"
  | Op.VFCHE -> "vfche"
  | Op.VFD -> "vfd"
  | Op.VFEE -> "vfee"
  | Op.VFENE -> "vfene"
  | Op.VFI -> "vfi"
  | Op.VFLL -> "vfll"
  | Op.VFLR -> "vflr"
  | Op.VFM -> "vfm"
  | Op.VFMA -> "vfma"
  | Op.VFMAX -> "vfmax"
  | Op.VFMIN -> "vfmin"
  | Op.VFMS -> "vfms"
  | Op.VFNMA -> "vfnma"
  | Op.VFNMS -> "vfnms"
  | Op.VFPSO -> "vfpso"
  | Op.VFS -> "vfs"
  | Op.VFSQ -> "vfsq"
  | Op.VFTCI -> "vftci"
  | Op.VGBM -> "vgbm"
  | Op.VGEF -> "vgef"
  | Op.VGEG -> "vgeg"
  | Op.VGFM -> "vgfm"
  | Op.VGFMA -> "vgfma"
  | Op.VGM -> "vgm"
  | Op.VISTR -> "vistr"
  | Op.VL -> "vl"
  | Op.VLBB -> "vlbb"
  | Op.VLBR -> "vlbr"
  | Op.VLBRREP -> "vlbrrep"
  | Op.VLC -> "vlc"
  | Op.VLEB -> "vleb"
  | Op.VLEBRF -> "vlebrf"
  | Op.VLEBRG -> "vlebrg"
  | Op.VLEBRH -> "vlebrh"
  | Op.VLEF -> "vlef"
  | Op.VLEG -> "vleg"
  | Op.VLEH -> "vleh"
  | Op.VLEIB -> "vleib"
  | Op.VLEIF -> "vleif"
  | Op.VLEIG -> "vleig"
  | Op.VLEIH -> "vleih"
  | Op.VLER -> "vler"
  | Op.VLGV -> "vlgv"
  | Op.VLIP -> "vlip"
  | Op.VLL -> "vll"
  | Op.VLLEBRZ -> "vllebrz"
  | Op.VLLEZ -> "vllez"
  | Op.VLM -> "vlm"
  | Op.VLP -> "vlp"
  | Op.VLR -> "vlr"
  | Op.VLREP -> "vlrep"
  | Op.VLRL -> "vlrl"
  | Op.VLRLR -> "vlrlr"
  | Op.VLVG -> "vlvg"
  | Op.VLVGP -> "vlvgp"
  | Op.VMAE -> "vmae"
  | Op.VMAH -> "vmah"
  | Op.VMAL -> "vmal"
  | Op.VMALE -> "vmale"
  | Op.VMALH -> "vmalh"
  | Op.VMALO -> "vmalo"
  | Op.VMAO -> "vmao"
  | Op.VME -> "vme"
  | Op.VMH -> "vmh"
  | Op.VML -> "vml"
  | Op.VMLE -> "vmle"
  | Op.VMLH -> "vmlh"
  | Op.VMLO -> "vmlo"
  | Op.VMN -> "vmn"
  | Op.VMNL -> "vmnl"
  | Op.VMO -> "vmo"
  | Op.VMP -> "vmp"
  | Op.VMRH -> "vmrh"
  | Op.VMRL -> "vmrl"
  | Op.VMSL -> "vmsl"
  | Op.VMSP -> "vmsp"
  | Op.VMX -> "vmx"
  | Op.VMXL -> "vmxl"
  | Op.VN -> "vn"
  | Op.VNC -> "vnc"
  | Op.VNN -> "vnn"
  | Op.VNO -> "vno"
  | Op.VNX -> "vnx"
  | Op.VO -> "vo"
  | Op.VOC -> "voc"
  | Op.VPDI -> "vpdi"
  | Op.VPERM -> "vperm"
  | Op.VPK -> "vpk"
  | Op.VPKLS -> "vpkls"
  | Op.VPKS -> "vpks"
  | Op.VPKZ -> "vpkz"
  | Op.VPKZR -> "vpkzr"
  | Op.VPOPCT -> "vpopct"
  | Op.VPSOP -> "vpsop"
  | Op.VREP -> "vrep"
  | Op.VREPI -> "vrepi"
  | Op.VRP -> "vrp"
  | Op.VS -> "vs"
  | Op.VSBCBI -> "vsbcbi"
  | Op.VSBI -> "vsbi"
  | Op.VSCBI -> "vscbi"
  | Op.VSCEF -> "vscef"
  | Op.VSCEG -> "vsceg"
  | Op.VSCHP -> "vschp"
  | Op.VSCSHP -> "vscshp"
  | Op.VSDP -> "vsdp"
  | Op.VSEG -> "vseg"
  | Op.VSEL -> "vsel"
  | Op.VSL -> "vsl"
  | Op.VSLB -> "vslb"
  | Op.VSLD -> "vsld"
  | Op.VSLDB -> "vsldb"
  | Op.VSP -> "vsp"
  | Op.VSRA -> "vsra"
  | Op.VSRAB -> "vsrab"
  | Op.VSRD -> "vsrd"
  | Op.VSRL -> "vsrl"
  | Op.VSRLB -> "vsrlb"
  | Op.VSRP -> "vsrp"
  | Op.VSRPR -> "vsrpr"
  | Op.VST -> "vst"
  | Op.VSTBR -> "vstbr"
  | Op.VSTEB -> "vsteb"
  | Op.VSTEBRF -> "vstebrf"
  | Op.VSTEBRG -> "vstebrg"
  | Op.VSTEBRH -> "vstebrh"
  | Op.VSTEF -> "vstef"
  | Op.VSTEG -> "vsteg"
  | Op.VSTEH -> "vsteh"
  | Op.VSTER -> "vster"
  | Op.VSTL -> "vstl"
  | Op.VSTM -> "vstm"
  | Op.VSTRC -> "vstrc"
  | Op.VSTRL -> "vstrl"
  | Op.VSTRLR -> "vstrlr"
  | Op.VSTRS -> "vstrs"
  | Op.VSUM -> "vsum"
  | Op.VSUMG -> "vsumg"
  | Op.VSUMQ -> "vsumq"
  | Op.VTM -> "vtm"
  | Op.VTP -> "vtp"
  | Op.VUPH -> "vuph"
  | Op.VUPKZ -> "vupkz"
  | Op.VUPKZH -> "vupkzh"
  | Op.VUPKZL -> "vupkzl"
  | Op.VUPL -> "vupl"
  | Op.VUPLH -> "vuplh"
  | Op.VUPLL -> "vupll"
  | Op.VX -> "vx"
  | Op.WFC -> "wfc"
  | Op.WFK -> "wfk"
  | Op.X -> "x"
  | Op.XC -> "xc"
  | Op.XG -> "xg"
  | Op.XGR -> "xgr"
  | Op.XGRK -> "xgrk"
  | Op.XI -> "xi"
  | Op.XIHF -> "xihf"
  | Op.XILF -> "xilf"
  | Op.XIY -> "xiy"
  | Op.XR -> "xr"
  | Op.XRK -> "xrk"
  | Op.XSCH -> "xsch"
  | Op.XY -> "xy"
  | Op.ZAP -> "zap"
  | Op.InvalOp -> "(illegal)"
  | _ -> Terminator.impossible ()

let extendMnemonic (ins: Instruction) (builder: IDisasmBuilder) =
  Terminator.futureFeature ()

let binaryMaskString (mask: Mask) =
  "B'" + System.Convert.ToString(int mask, 2).PadLeft(4, '0') + "'"

let hexDispString (disp: Displacement) =
  match disp with
  | DispS imm -> HexString.ofInt32 imm
  | DispU imm -> HexString.ofUInt32 imm
  | DispS20 bitvec -> bitvec.ToString()
  | DispU12 bitvec -> bitvec.ToString()

let inline buildOpcode (ins: Instruction) (builder: IDisasmBuilder) =
  let opcode = ins.Opcode
  builder.Accumulate(AsmWordKind.Mnemonic, opCodeToString opcode)

let prefix = { AsmWordKind = AsmWordKind.String; AsmWordValue = " ; <" }

let suffix = { AsmWordKind = AsmWordKind.String; AsmWordValue = ">" }

let private mapNoSymbol addr =
  [| { AsmWordKind = AsmWordKind.String; AsmWordValue = " ; " }
     { AsmWordKind = AsmWordKind.Value
       AsmWordValue = HexString.ofUInt64 addr } |]

let private buildComment targetAddr (builder: IDisasmBuilder) =
  builder.AccumulateSymbol(targetAddr, prefix, suffix, mapNoSymbol)

let oprToString (ins: Instruction) opr delim (builder: IDisasmBuilder) =
  match opr with
  | OpReg reg ->
    builder.Accumulate(AsmWordKind.String, delim)
    builder.Accumulate(AsmWordKind.Variable, Register.toString reg)
  | OpImm imm ->
    builder.Accumulate(AsmWordKind.String, delim)
    match imm with
    | ImmU4 value ->
      builder.Accumulate(AsmWordKind.Value,
        HexString.ofUInt32 (BitVector.ToUInt32 value))
    | ImmU8 value ->
      builder.Accumulate(AsmWordKind.Value, HexString.ofUInt16 (uint16 value))
    | ImmS8 value ->
      builder.Accumulate(AsmWordKind.Value, HexString.ofInt16 (int16 value))
    | ImmU12 value ->
      builder.Accumulate(AsmWordKind.Value,
        HexString.ofUInt32 (BitVector.ToUInt32 value))
    | ImmS12 value ->
      builder.Accumulate(AsmWordKind.Value,
        HexString.ofInt32 (BitVector.ToInt32 value))
    | ImmU16 value ->
      builder.Accumulate(AsmWordKind.Value, HexString.ofUInt16 value)
    | ImmS16 value ->
      builder.Accumulate(AsmWordKind.Value, HexString.ofInt16 value)
    | ImmS24 value ->
      builder.Accumulate(AsmWordKind.Value,
        HexString.ofInt32 (BitVector.ToInt32 value))
    | ImmU32 value ->
      builder.Accumulate(AsmWordKind.Value, HexString.ofUInt32 value)
    | ImmS32 value ->
      builder.Accumulate(AsmWordKind.Value, HexString.ofInt32 value)
  | OpRImm immTyp ->
    match immTyp with
    | ImmS16 value ->
      builder.Accumulate(AsmWordKind.String, delim)
      let offset = 2L * int64 value
      if offset < 0 then
        builder.Accumulate(AsmWordKind.String, "-")
        builder.Accumulate(AsmWordKind.Value, HexString.ofInt64 -offset)
      else
        builder.Accumulate(AsmWordKind.String, "+")
        builder.Accumulate(AsmWordKind.Value, HexString.ofInt64 offset)
      let targetAddr = int64 ins.Address + offset |> uint64
      buildComment targetAddr builder
    | ImmS32 value ->
      builder.Accumulate(AsmWordKind.String, delim)
      let offset = 2L * int64 value
      if offset < 0 then
        builder.Accumulate(AsmWordKind.String, "-")
        builder.Accumulate(AsmWordKind.Value, HexString.ofInt64 -offset)
      else
        builder.Accumulate(AsmWordKind.String, "+")
        builder.Accumulate(AsmWordKind.Value, HexString.ofInt64 offset)
      let targetAddr = int64 ins.Address + offset |> uint64
      buildComment targetAddr builder
    | _ -> printfn "%A" immTyp; failwith "Invalid immType"
  | OpMask mask ->
    builder.Accumulate(AsmWordKind.String, delim)
    builder.Accumulate(AsmWordKind.Value, binaryMaskString mask)
  | OpStore(idxReg, baseReg, disp) ->
    builder.Accumulate(AsmWordKind.String, delim)
    builder.Accumulate(AsmWordKind.Value, hexDispString disp)
    builder.Accumulate(AsmWordKind.String, "(")
    match idxReg with
    | Some reg ->
      builder.Accumulate(AsmWordKind.Variable, Register.toString reg)
      builder.Accumulate(AsmWordKind.String, ", ")
    | None -> ()
    builder.Accumulate(AsmWordKind.Variable, Register.toString baseReg)
    builder.Accumulate(AsmWordKind.String, ")")
  | OpStoreLen(len, baseReg, disp) ->
    builder.Accumulate(AsmWordKind.String, delim)
    builder.Accumulate(AsmWordKind.Value, hexDispString disp)
    builder.Accumulate(AsmWordKind.String, "(")
    builder.Accumulate(AsmWordKind.Value, len.ToString())
    builder.Accumulate(AsmWordKind.String, ", ")
    builder.Accumulate(AsmWordKind.Variable, Register.toString baseReg)
    builder.Accumulate(AsmWordKind.String, ")")

let inline buildOprs (ins: Instruction) (builder: IDisasmBuilder) =
  match ins.Operands with
  | NoOperand -> ()
  | OneOperand op1 ->
    oprToString ins op1 " " builder
  | TwoOperands(op1, op2) ->
    oprToString ins op1 " " builder
    oprToString ins op2 ", " builder
  | ThreeOperands(op1, op2, op3) ->
    oprToString ins op1 " " builder
    if ins.Fmt <> Fmt.RS then
      oprToString ins op2 ", " builder
      oprToString ins op3 ", " builder
    else
      oprToString ins op3 ", " builder
      oprToString ins op2 ", " builder
  | FourOperands(op1, op2, op3, op4) ->
    oprToString ins op1 " " builder
    oprToString ins op2 ", " builder
    oprToString ins op3 ", " builder
    oprToString ins op4 ", " builder
  | FiveOperands(op1, op2, op3, op4, op5) ->
    oprToString ins op1 " " builder
    oprToString ins op2 ", " builder
    oprToString ins op3 ", " builder
    oprToString ins op4 ", " builder
    oprToString ins op5 ", " builder
  | SixOperands(op1, op2, op3, op4, op5, op6) ->
    oprToString ins op1 " " builder
    oprToString ins op2 ", " builder
    oprToString ins op3 ", " builder
    oprToString ins op4 ", " builder
    oprToString ins op5 ", " builder
    oprToString ins op6 ", " builder

let disasm (ins: Instruction) (builder: IDisasmBuilder) =
  builder.AccumulateAddrMarker ins.Address
  buildOpcode ins builder
  buildOprs ins builder