<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 symbolic evaluation engine.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Expr.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="IFunctionApplicable.fs" />
    <Compile Include="Intrinsics.fs" />
    <Compile Include="Evaluator.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FParsec" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\B2R2.Core.fsproj" />
  </ItemGroup>

</Project>
