<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 Intel assembly library.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Encoded.fs" />
    <Compile Include="ParserHelper.fs" />
    <Compile Include="AsmPrefix.fs" />
    <Compile Include="AsmOperands.fs" />
    <Compile Include="AsmOpcode.fs" />
    <Compile Include="AsmMain.fs" />
    <Compile Include="Assembler.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrontEnd\API\B2R2.FrontEnd.API.fsproj" />
    <ProjectReference Include="..\BinLowerer\B2R2.Assembly.BinLowerer.fsproj" />
  </ItemGroup>

</Project>
