<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>B2R2 middle-end main interface.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BinaryBrew.fs" />
    <Compile Include="CallGraph.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrontEnd\API\B2R2.FrontEnd.API.fsproj" />
    <ProjectReference Include="..\ConcEval\B2R2.MiddleEnd.ConcEval.fsproj" />
    <ProjectReference Include="..\BinGraph\B2R2.MiddleEnd.BinGraph.fsproj" />
    <ProjectReference Include="..\ControlFlowGraph\B2R2.MiddleEnd.ControlFlowGraph.fsproj" />
    <ProjectReference Include="..\DataFlow\B2R2.MiddleEnd.DataFlow.fsproj" />
    <ProjectReference Include="..\ControlFlowAnalysis\B2R2.MiddleEnd.ControlFlowAnalysis.fsproj" />
  </ItemGroup>

</Project>
