(*
  B2R2 - the Next-Generation Reversing Platform

  Copyright (c) SoftSec Lab. @ KAIST, since 2016

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*)
namespace B2R2.FrontEnd.Intel

/// <summary>
/// Represents an Intel opcode. This type should be generated using
/// <c>scripts/genOpcode.fsx</c> from the `IntelSupportedOpcodes.txt` file.
/// </summary>
type Opcode =
  | AAA = 0
  | AAD = 1
  | AAM = 2
  | AAS = 3
  | ADC = 4
  | ADCX = 5
  | ADD = 6
  | ADDPD = 7
  | ADDPS = 8
  | ADDSD = 9
  | ADDSS = 10
  | ADDSUBPD = 11
  | ADDSUBPS = 12
  | ADOX = 13
  | AESDEC = 14
  | AESDEC128KL = 15
  | AESDEC256KL = 16
  | AESDECLAST = 17
  | AESDECWIDE128KL = 18
  | AESDECWIDE256KL = 19
  | AESENC = 20
  | AESENC128KL = 21
  | AESENC256KL = 22
  | AESENCLAST = 23
  | AESENCWIDE128KL = 24
  | AESENCWIDE256KL = 25
  | AESIMC = 26
  | AESKEYGENASSIST = 27
  | AND = 28
  | ANDN = 29
  | ANDNPD = 30
  | ANDNPS = 31
  | ANDPD = 32
  | ANDPS = 33
  | ARPL = 34
  | BEXTR = 35
  | BLENDPD = 36
  | BLENDPS = 37
  | BLENDVPD = 38
  | BLENDVPS = 39
  | BLSI = 40
  | BLSMSK = 41
  | BLSR = 42
  | BNDCL = 43
  | BNDCN = 44
  | BNDCU = 45
  | BNDLDX = 46
  | BNDMK = 47
  | BNDMOV = 48
  | BNDSTX = 49
  | BOUND = 50
  | BSF = 51
  | BSR = 52
  | BSWAP = 53
  | BT = 54
  | BTC = 55
  | BTR = 56
  | BTS = 57
  | BZHI = 58
  | CALL = 59
  | CBW = 60
  | CDQ = 61
  | CDQE = 62
  | CLAC = 63
  | CLC = 64
  | CLD = 65
  | CLDEMOTE = 66
  | CLFLUSH = 67
  | CLFLUSHOPT = 68
  | CLI = 69
  | CLRSSBSY = 70
  | CLTS = 71
  | CLUI = 72
  | CLWB = 73
  | CMC = 74
  | CMOVA = 75
  | CMOVAE = 76
  | CMOVB = 77
  | CMOVBE = 78
  | CMOVC = 79
  | CMOVE = 80
  | CMOVG = 81
  | CMOVGE = 82
  | CMOVL = 83
  | CMOVLE = 84
  | CMOVNA = 85
  | CMOVNAE = 86
  | CMOVNB = 87
  | CMOVNBE = 88
  | CMOVNC = 89
  | CMOVNE = 90
  | CMOVNG = 91
  | CMOVNGE = 92
  | CMOVNL = 93
  | CMOVNLE = 94
  | CMOVNO = 95
  | CMOVNP = 96
  | CMOVNS = 97
  | CMOVNZ = 98
  | CMOVO = 99
  | CMOVP = 100
  | CMOVPE = 101
  | CMOVPO = 102
  | CMOVS = 103
  | CMOVZ = 104
  | CMP = 105
  | CMPBEXADD = 106
  | CMPBXADD = 107
  | CMPLEXADD = 108
  | CMPLXADD = 109
  | CMPNBEXADD = 110
  | CMPNBXADD = 111
  | CMPNLEXADD = 112
  | CMPNLXADD = 113
  | CMPNOXADD = 114
  | CMPNPXADD = 115
  | CMPNSXADD = 116
  | CMPNZXADD = 117
  | CMPOXADD = 118
  | CMPPD = 119
  | CMPPS = 120
  | CMPPXADD = 121
  | CMPS = 122
  | CMPSB = 123
  | CMPSD = 124
  | CMPSQ = 125
  | CMPSS = 126
  | CMPSW = 127
  | CMPSXADD = 128
  | CMPXCHG = 129
  | CMPXCHG16B = 130
  | CMPXCHG8B = 131
  | CMPZXADD = 132
  | COMISD = 133
  | COMISS = 134
  | CPUID = 135
  | CQO = 136
  | CRC32 = 137
  | CVTDQ2PD = 138
  | CVTDQ2PS = 139
  | CVTPD2DQ = 140
  | CVTPD2PI = 141
  | CVTPD2PS = 142
  | CVTPI2PD = 143
  | CVTPI2PS = 144
  | CVTPS2DQ = 145
  | CVTPS2PD = 146
  | CVTPS2PI = 147
  | CVTSD2SI = 148
  | CVTSD2SS = 149
  | CVTSI2SD = 150
  | CVTSI2SS = 151
  | CVTSS2SD = 152
  | CVTSS2SI = 153
  | CVTTPD2DQ = 154
  | CVTTPD2PI = 155
  | CVTTPS2DQ = 156
  | CVTTPS2PI = 157
  | CVTTSD2SI = 158
  | CVTTSS2SI = 159
  | CWD = 160
  | CWDE = 161
  | DAA = 162
  | DAS = 163
  | DEC = 164
  | DIV = 165
  | DIVPD = 166
  | DIVPS = 167
  | DIVSD = 168
  | DIVSS = 169
  | DPPD = 170
  | DPPS = 171
  | EMMS = 172
  | ENCODEKEY128 = 173
  | ENCODEKEY256 = 174
  | ENDBR32 = 175
  | ENDBR64 = 176
  | ENQCMD = 177
  | ENQCMDS = 178
  | ENTER = 179
  | EXTRACTPS = 180
  | F2XM1 = 181
  | FABS = 182
  | FADD = 183
  | FADDP = 184
  | FBLD = 185
  | FBSTP = 186
  | FCHS = 187
  | FCLEX = 188
  | FCMOVB = 189
  | FCMOVBE = 190
  | FCMOVE = 191
  | FCMOVNB = 192
  | FCMOVNBE = 193
  | FCMOVNE = 194
  | FCMOVNU = 195
  | FCMOVU = 196
  | FCOM = 197
  | FCOMI = 198
  | FCOMIP = 199
  | FCOMP = 200
  | FCOMPP = 201
  | FCOS = 202
  | FDECSTP = 203
  | FDIV = 204
  | FDIVP = 205
  | FDIVR = 206
  | FDIVRP = 207
  | FFREE = 208
  | FIADD = 209
  | FICOM = 210
  | FICOMP = 211
  | FIDIV = 212
  | FIDIVR = 213
  | FILD = 214
  | FIMUL = 215
  | FINCSTP = 216
  | FINIT = 217
  | FIST = 218
  | FISTP = 219
  | FISTTP = 220
  | FISUB = 221
  | FISUBR = 222
  | FLD = 223
  | FLD1 = 224
  | FLDCW = 225
  | FLDENV = 226
  | FLDL2E = 227
  | FLDL2T = 228
  | FLDLG2 = 229
  | FLDLN2 = 230
  | FLDPI = 231
  | FLDZ = 232
  | FMUL = 233
  | FMULP = 234
  | FNCLEX = 235
  | FNINIT = 236
  | FNOP = 237
  | FNSAVE = 238
  | FNSTCW = 239
  | FNSTENV = 240
  | FNSTSW = 241
  | FPATAN = 242
  | FPREM = 243
  | FPREM1 = 244
  | FPTAN = 245
  | FRNDINT = 246
  | FRSTOR = 247
  | FSAVE = 248
  | FSCALE = 249
  | FSIN = 250
  | FSINCOS = 251
  | FSQRT = 252
  | FST = 253
  | FSTCW = 254
  | FSTENV = 255
  | FSTP = 256
  | FSTSW = 257
  | FSUB = 258
  | FSUBP = 259
  | FSUBR = 260
  | FSUBRP = 261
  | FTST = 262
  | FUCOM = 263
  | FUCOMI = 264
  | FUCOMIP = 265
  | FUCOMP = 266
  | FUCOMPP = 267
  | FWAIT = 268
  | FXAM = 269
  | FXCH = 270
  | FXRSTOR = 271
  | FXRSTOR64 = 272
  | FXSAVE = 273
  | FXSAVE64 = 274
  | FXTRACT = 275
  | FYL2X = 276
  | FYL2XP1 = 277
  | GETSEC = 278
  | GF2P8AFFINEINVQB = 279
  | GF2P8AFFINEQB = 280
  | GF2P8MULB = 281
  | HADDPD = 282
  | HADDPS = 283
  | HLT = 284
  | HRESET = 285
  | HSUBPD = 286
  | HSUBPS = 287
  | IDIV = 288
  | IMUL = 289
  | IN = 290
  | INC = 291
  | INCSSPD = 292
  | INCSSPQ = 293
  | INS = 294
  | INSB = 295
  | INSD = 296
  | INSERTPS = 297
  | INSW = 298
  | INT = 299
  | INT1 = 300
  | INT3 = 301
  | INTO = 302
  | INVD = 303
  | INVLPG = 304
  | INVPCID = 305
  | IRET = 306
  | IRETD = 307
  | IRETQ = 308
  | JA = 309
  | JAE = 310
  | JB = 311
  | JBE = 312
  | JC = 313
  | JCXZ = 314
  | JE = 315
  | JECXZ = 316
  | JG = 317
  | JGE = 318
  | JL = 319
  | JLE = 320
  | JMP = 321
  | JNA = 322
  | JNAE = 323
  | JNB = 324
  | JNBE = 325
  | JNC = 326
  | JNE = 327
  | JNG = 328
  | JNGE = 329
  | JNL = 330
  | JNLE = 331
  | JNO = 332
  | JNP = 333
  | JNS = 334
  | JNZ = 335
  | JO = 336
  | JP = 337
  | JPE = 338
  | JPO = 339
  | JRCXZ = 340
  | JS = 341
  | JZ = 342
  | KADDB = 343
  | KADDD = 344
  | KADDQ = 345
  | KADDW = 346
  | KANDB = 347
  | KANDD = 348
  | KANDNB = 349
  | KANDND = 350
  | KANDNQ = 351
  | KANDNW = 352
  | KANDQ = 353
  | KANDW = 354
  | KMOVB = 355
  | KMOVD = 356
  | KMOVQ = 357
  | KMOVW = 358
  | KNOTB = 359
  | KNOTD = 360
  | KNOTQ = 361
  | KNOTW = 362
  | KORB = 363
  | KORD = 364
  | KORQ = 365
  | KORTESTB = 366
  | KORTESTD = 367
  | KORTESTQ = 368
  | KORTESTW = 369
  | KORW = 370
  | KSHIFTLB = 371
  | KSHIFTLD = 372
  | KSHIFTLQ = 373
  | KSHIFTLW = 374
  | KSHIFTRB = 375
  | KSHIFTRD = 376
  | KSHIFTRQ = 377
  | KSHIFTRW = 378
  | KTESTB = 379
  | KTESTD = 380
  | KTESTQ = 381
  | KTESTW = 382
  | KUNPCKBW = 383
  | KUNPCKDQ = 384
  | KUNPCKWD = 385
  | KXNORB = 386
  | KXNORD = 387
  | KXNORQ = 388
  | KXNORW = 389
  | KXORB = 390
  | KXORD = 391
  | KXORQ = 392
  | KXORW = 393
  | LAHF = 394
  | LAR = 395
  | LDDQU = 396
  | LDMXCSR = 397
  | LDS = 398
  | LDTILECFG = 399
  | LEA = 400
  | LEAVE = 401
  | LES = 402
  | LFENCE = 403
  | LFS = 404
  | LGDT = 405
  | LGS = 406
  | LIDT = 407
  | LLDT = 408
  | LMSW = 409
  | LOADIWKEY = 410
  | LOCK = 411
  | LODS = 412
  | LODSB = 413
  | LODSD = 414
  | LODSQ = 415
  | LODSW = 416
  | LOOP = 417
  | LOOPE = 418
  | LOOPNE = 419
  | LSL = 420
  | LSS = 421
  | LTR = 422
  | LZCNT = 423
  | MASKMOVDQU = 424
  | MASKMOVQ = 425
  | MAXPD = 426
  | MAXPS = 427
  | MAXSD = 428
  | MAXSS = 429
  | MFENCE = 430
  | MINPD = 431
  | MINPS = 432
  | MINSD = 433
  | MINSS = 434
  | MONITOR = 435
  | MOV = 436
  | MOVAPD = 437
  | MOVAPS = 438
  | MOVBE = 439
  | MOVD = 440
  | MOVDDUP = 441
  | MOVDIR64B = 442
  | MOVDIRI = 443
  | MOVDQ2Q = 444
  | MOVDQA = 445
  | MOVDQU = 446
  | MOVHLPS = 447
  | MOVHPD = 448
  | MOVHPS = 449
  | MOVLHPS = 450
  | MOVLPD = 451
  | MOVLPS = 452
  | MOVMSKPD = 453
  | MOVMSKPS = 454
  | MOVNTDQ = 455
  | MOVNTDQA = 456
  | MOVNTI = 457
  | MOVNTPD = 458
  | MOVNTPS = 459
  | MOVNTQ = 460
  | MOVQ = 461
  | MOVQ2DQ = 462
  | MOVS = 463
  | MOVSB = 464
  | MOVSD = 465
  | MOVSHDUP = 466
  | MOVSLDUP = 467
  | MOVSQ = 468
  | MOVSS = 469
  | MOVSW = 470
  | MOVSX = 471
  | MOVSXD = 472
  | MOVUPD = 473
  | MOVUPS = 474
  | MOVZX = 475
  | MPSADBW = 476
  | MUL = 477
  | MULPD = 478
  | MULPS = 479
  | MULSD = 480
  | MULSS = 481
  | MULX = 482
  | MWAIT = 483
  | NEG = 484
  | NOP = 485
  | NOT = 486
  | OR = 487
  | ORPD = 488
  | ORPS = 489
  | OUT = 490
  | OUTS = 491
  | OUTSB = 492
  | OUTSD = 493
  | OUTSW = 494
  | PABSB = 495
  | PABSD = 496
  | PABSW = 497
  | PACKSSDW = 498
  | PACKSSWB = 499
  | PACKUSDW = 500
  | PACKUSWB = 501
  | PADDB = 502
  | PADDD = 503
  | PADDQ = 504
  | PADDSB = 505
  | PADDSW = 506
  | PADDUSB = 507
  | PADDUSW = 508
  | PADDW = 509
  | PALIGNR = 510
  | PAND = 511
  | PANDN = 512
  | PAUSE = 513
  | PAVGB = 514
  | PAVGW = 515
  | PBLENDVB = 516
  | PBLENDW = 517
  | PCLMULQDQ = 518
  | PCMPEQB = 519
  | PCMPEQD = 520
  | PCMPEQQ = 521
  | PCMPEQW = 522
  | PCMPESTRI = 523
  | PCMPESTRM = 524
  | PCMPGTB = 525
  | PCMPGTD = 526
  | PCMPGTQ = 527
  | PCMPGTW = 528
  | PCMPISTRI = 529
  | PCMPISTRM = 530
  | PCONFIG = 531
  | PDEP = 532
  | PEXT = 533
  | PEXTRB = 534
  | PEXTRD = 535
  | PEXTRQ = 536
  | PEXTRW = 537
  | PHADDD = 538
  | PHADDSW = 539
  | PHADDW = 540
  | PHMINPOSUW = 541
  | PHSUBD = 542
  | PHSUBSW = 543
  | PHSUBW = 544
  | PINSRB = 545
  | PINSRD = 546
  | PINSRQ = 547
  | PINSRW = 548
  | PMADDUBSW = 549
  | PMADDWD = 550
  | PMAXSB = 551
  | PMAXSD = 552
  | PMAXSW = 553
  | PMAXUB = 554
  | PMAXUD = 555
  | PMAXUW = 556
  | PMINSB = 557
  | PMINSD = 558
  | PMINSW = 559
  | PMINUB = 560
  | PMINUD = 561
  | PMINUW = 562
  | PMOVMSKB = 563
  | PMOVSXBD = 564
  | PMOVSXBQ = 565
  | PMOVSXBW = 566
  | PMOVSXDQ = 567
  | PMOVSXWD = 568
  | PMOVSXWQ = 569
  | PMOVZXBD = 570
  | PMOVZXBQ = 571
  | PMOVZXBW = 572
  | PMOVZXDQ = 573
  | PMOVZXWD = 574
  | PMOVZXWQ = 575
  | PMULDQ = 576
  | PMULHRSW = 577
  | PMULHUW = 578
  | PMULHW = 579
  | PMULLD = 580
  | PMULLW = 581
  | PMULUDQ = 582
  | POP = 583
  | POPA = 584
  | POPAD = 585
  | POPCNT = 586
  | POPF = 587
  | POPFD = 588
  | POPFQ = 589
  | POR = 590
  | PREFETCHIT0 = 591
  | PREFETCHIT1 = 592
  | PREFETCHNTA = 593
  | PREFETCHT0 = 594
  | PREFETCHT1 = 595
  | PREFETCHT2 = 596
  | PREFETCHW = 597
  | PREFETCHWT1 = 598
  | PSADBW = 599
  | PSHUFB = 600
  | PSHUFD = 601
  | PSHUFHW = 602
  | PSHUFLW = 603
  | PSHUFW = 604
  | PSIGNB = 605
  | PSIGND = 606
  | PSIGNW = 607
  | PSLLD = 608
  | PSLLDQ = 609
  | PSLLQ = 610
  | PSLLW = 611
  | PSRAD = 612
  | PSRAW = 613
  | PSRLD = 614
  | PSRLDQ = 615
  | PSRLQ = 616
  | PSRLW = 617
  | PSUBB = 618
  | PSUBD = 619
  | PSUBQ = 620
  | PSUBSB = 621
  | PSUBSW = 622
  | PSUBUSB = 623
  | PSUBUSW = 624
  | PSUBW = 625
  | PTEST = 626
  | PTWRITE = 627
  | PUNPCKHBW = 628
  | PUNPCKHDQ = 629
  | PUNPCKHQDQ = 630
  | PUNPCKHWD = 631
  | PUNPCKLBW = 632
  | PUNPCKLDQ = 633
  | PUNPCKLQDQ = 634
  | PUNPCKLWD = 635
  | PUSH = 636
  | PUSHA = 637
  | PUSHAD = 638
  | PUSHF = 639
  | PUSHFD = 640
  | PUSHFQ = 641
  | PXOR = 642
  | RCL = 643
  | RCPPS = 644
  | RCPSS = 645
  | RCR = 646
  | RDFSBASE = 647
  | RDGSBASE = 648
  | RDMSR = 649
  | RDMSRLIST = 650
  | RDPID = 651
  | RDPKRU = 652
  | RDPMC = 653
  | RDRAND = 654
  | RDSEED = 655
  | RDSSPD = 656
  | RDSSPQ = 657
  | RDTSC = 658
  | RDTSCP = 659
  | RET = 660
  | ROL = 661
  | ROR = 662
  | RORX = 663
  | ROUNDPD = 664
  | ROUNDPS = 665
  | ROUNDSD = 666
  | ROUNDSS = 667
  | RSM = 668
  | RSQRTPS = 669
  | RSQRTSS = 670
  | RSTORSSP = 671
  | SAHF = 672
  | SAL = 673
  | SAR = 674
  | SARX = 675
  | SAVEPREVSSP = 676
  | SBB = 677
  | SCAS = 678
  | SCASB = 679
  | SCASD = 680
  | SCASQ = 681
  | SCASW = 682
  | SENDUIPI = 683
  | SERIALIZE = 684
  | SETA = 685
  | SETAE = 686
  | SETB = 687
  | SETBE = 688
  | SETC = 689
  | SETE = 690
  | SETG = 691
  | SETGE = 692
  | SETL = 693
  | SETLE = 694
  | SETNA = 695
  | SETNAE = 696
  | SETNB = 697
  | SETNBE = 698
  | SETNC = 699
  | SETNE = 700
  | SETNG = 701
  | SETNGE = 702
  | SETNL = 703
  | SETNLE = 704
  | SETNO = 705
  | SETNP = 706
  | SETNS = 707
  | SETNZ = 708
  | SETO = 709
  | SETP = 710
  | SETPE = 711
  | SETPO = 712
  | SETS = 713
  | SETSSBSY = 714
  | SETZ = 715
  | SFENCE = 716
  | SGDT = 717
  | SHA1MSG1 = 718
  | SHA1MSG2 = 719
  | SHA1NEXTE = 720
  | SHA1RNDS4 = 721
  | SHA256MSG1 = 722
  | SHA256MSG2 = 723
  | SHA256RNDS2 = 724
  | SHL = 725
  | SHLD = 726
  | SHLX = 727
  | SHR = 728
  | SHRD = 729
  | SHRX = 730
  | SHUFPD = 731
  | SHUFPS = 732
  | SIDT = 733
  | SLDT = 734
  | SMSW = 735
  | SQRTPD = 736
  | SQRTPS = 737
  | SQRTSD = 738
  | SQRTSS = 739
  | STAC = 740
  | STC = 741
  | STD = 742
  | STI = 743
  | STMXCSR = 744
  | STOS = 745
  | STOSB = 746
  | STOSD = 747
  | STOSQ = 748
  | STOSW = 749
  | STR = 750
  | STTILECFG = 751
  | STUI = 752
  | SUB = 753
  | SUBPD = 754
  | SUBPS = 755
  | SUBSD = 756
  | SUBSS = 757
  | SWAPGS = 758
  | SYSCALL = 759
  | SYSENTER = 760
  | SYSEXIT = 761
  | SYSRET = 762
  | TDPBF16PS = 763
  | TDPBSSD = 764
  | TDPBSUD = 765
  | TDPBUSD = 766
  | TDPBUUD = 767
  | TDPFP16PS = 768
  | TEST = 769
  | TESTUI = 770
  | TILELOADD = 771
  | TILELOADDT1 = 772
  | TILERELEASE = 773
  | TILESTORED = 774
  | TILEZERO = 775
  | TPAUSE = 776
  | TZCNT = 777
  | UCOMISD = 778
  | UCOMISS = 779
  | UD0 = 780
  | UD1 = 781
  | UD2 = 782
  | UDB = 783
  | UIRET = 784
  | UMONITOR = 785
  | UMWAIT = 786
  | UNPCKHPD = 787
  | UNPCKHPS = 788
  | UNPCKLPD = 789
  | UNPCKLPS = 790
  | V4FMADDPS = 791
  | V4FMADDSS = 792
  | V4FNMADDPS = 793
  | V4FNMADDSS = 794
  | VADDPD = 795
  | VADDPH = 796
  | VADDPS = 797
  | VADDSD = 798
  | VADDSH = 799
  | VADDSS = 800
  | VADDSUBPD = 801
  | VADDSUBPS = 802
  | VAESDEC = 803
  | VAESDECLAST = 804
  | VAESENC = 805
  | VAESENCLAST = 806
  | VAESIMC = 807
  | VAESKEYGENASSIST = 808
  | VALIGND = 809
  | VALIGNQ = 810
  | VANDNPD = 811
  | VANDNPS = 812
  | VANDPD = 813
  | VANDPS = 814
  | VBCSTNEBF162PS = 815
  | VBCSTNESH2PS = 816
  | VBLENDMPD = 817
  | VBLENDMPS = 818
  | VBLENDPD = 819
  | VBLENDPS = 820
  | VBLENDVPD = 821
  | VBLENDVPS = 822
  | VBROADCASTF128 = 823
  | VBROADCASTF32X2 = 824
  | VBROADCASTF32X4 = 825
  | VBROADCASTF32X8 = 826
  | VBROADCASTF64X2 = 827
  | VBROADCASTF64X4 = 828
  | VBROADCASTI128 = 829
  | VBROADCASTI32X2 = 830
  | VBROADCASTI32X4 = 831
  | VBROADCASTI32X8 = 832
  | VBROADCASTI64X2 = 833
  | VBROADCASTI64X4 = 834
  | VBROADCASTSD = 835
  | VBROADCASTSS = 836
  | VCMPPD = 837
  | VCMPPH = 838
  | VCMPPS = 839
  | VCMPSD = 840
  | VCMPSH = 841
  | VCMPSS = 842
  | VCOMISD = 843
  | VCOMISH = 844
  | VCOMISS = 845
  | VCOMPRESSPD = 846
  | VCOMPRESSPS = 847
  | VCVTDQ2PD = 848
  | VCVTDQ2PH = 849
  | VCVTDQ2PS = 850
  | VCVTNE2PS2BF16 = 851
  | VCVTNEEBF162PS = 852
  | VCVTNEEPH2PS = 853
  | VCVTNEOBF162PS = 854
  | VCVTNEOPH2PS = 855
  | VCVTNEPS2BF16 = 856
  | VCVTPD2DQ = 857
  | VCVTPD2PH = 858
  | VCVTPD2PS = 859
  | VCVTPD2QQ = 860
  | VCVTPD2UDQ = 861
  | VCVTPD2UQQ = 862
  | VCVTPH2DQ = 863
  | VCVTPH2PD = 864
  | VCVTPH2PS = 865
  | VCVTPH2PSX = 866
  | VCVTPH2QQ = 867
  | VCVTPH2UDQ = 868
  | VCVTPH2UQQ = 869
  | VCVTPH2UW = 870
  | VCVTPH2W = 871
  | VCVTPS2DQ = 872
  | VCVTPS2PD = 873
  | VCVTPS2PH = 874
  | VCVTPS2PHX = 875
  | VCVTPS2QQ = 876
  | VCVTPS2UDQ = 877
  | VCVTPS2UQQ = 878
  | VCVTQQ2PD = 879
  | VCVTQQ2PH = 880
  | VCVTQQ2PS = 881
  | VCVTSD2SH = 882
  | VCVTSD2SI = 883
  | VCVTSD2SS = 884
  | VCVTSD2USI = 885
  | VCVTSH2SD = 886
  | VCVTSH2SI = 887
  | VCVTSH2SS = 888
  | VCVTSH2USI = 889
  | VCVTSI2SD = 890
  | VCVTSI2SH = 891
  | VCVTSI2SS = 892
  | VCVTSS2SD = 893
  | VCVTSS2SH = 894
  | VCVTSS2SI = 895
  | VCVTSS2USI = 896
  | VCVTTPD2DQ = 897
  | VCVTTPD2QQ = 898
  | VCVTTPD2UDQ = 899
  | VCVTTPD2UQQ = 900
  | VCVTTPH2DQ = 901
  | VCVTTPH2QQ = 902
  | VCVTTPH2UDQ = 903
  | VCVTTPH2UQQ = 904
  | VCVTTPH2UW = 905
  | VCVTTPH2W = 906
  | VCVTTPS2DQ = 907
  | VCVTTPS2QQ = 908
  | VCVTTPS2UDQ = 909
  | VCVTTPS2UQQ = 910
  | VCVTTSD2SI = 911
  | VCVTTSD2USI = 912
  | VCVTTSH2SI = 913
  | VCVTTSH2USI = 914
  | VCVTTSS2SI = 915
  | VCVTTSS2USI = 916
  | VCVTUDQ2PD = 917
  | VCVTUDQ2PH = 918
  | VCVTUDQ2PS = 919
  | VCVTUQQ2PD = 920
  | VCVTUQQ2PH = 921
  | VCVTUQQ2PS = 922
  | VCVTUSI2SD = 923
  | VCVTUSI2SH = 924
  | VCVTUSI2SS = 925
  | VCVTUW2PH = 926
  | VCVTW2PH = 927
  | VDBPSADBW = 928
  | VDIVPD = 929
  | VDIVPH = 930
  | VDIVPS = 931
  | VDIVSD = 932
  | VDIVSH = 933
  | VDIVSS = 934
  | VDPBF16PS = 935
  | VDPPD = 936
  | VDPPS = 937
  | VERR = 938
  | VERW = 939
  | VEXP2PD = 940
  | VEXP2PS = 941
  | VEXPANDPD = 942
  | VEXPANDPS = 943
  | VEXTRACTF128 = 944
  | VEXTRACTF32X4 = 945
  | VEXTRACTF32X8 = 946
  | VEXTRACTF64X2 = 947
  | VEXTRACTF64X4 = 948
  | VEXTRACTI128 = 949
  | VEXTRACTI32X4 = 950
  | VEXTRACTI32X8 = 951
  | VEXTRACTI64X2 = 952
  | VEXTRACTI64X4 = 953
  | VEXTRACTPS = 954
  | VFCMADDCPH = 955
  | VFCMADDCSH = 956
  | VFCMULCPH = 957
  | VFCMULCSH = 958
  | VFIXUPIMMPD = 959
  | VFIXUPIMMPS = 960
  | VFIXUPIMMSD = 961
  | VFIXUPIMMSS = 962
  | VFMADD132PD = 963
  | VFMADD132PH = 964
  | VFMADD132PS = 965
  | VFMADD132SD = 966
  | VFMADD132SH = 967
  | VFMADD132SS = 968
  | VFMADD213PD = 969
  | VFMADD213PH = 970
  | VFMADD213PS = 971
  | VFMADD213SD = 972
  | VFMADD213SH = 973
  | VFMADD213SS = 974
  | VFMADD231PD = 975
  | VFMADD231PH = 976
  | VFMADD231PS = 977
  | VFMADD231SD = 978
  | VFMADD231SH = 979
  | VFMADD231SS = 980
  | VFMADDCPH = 981
  | VFMADDCSH = 982
  | VFMADDSUB132PD = 983
  | VFMADDSUB132PH = 984
  | VFMADDSUB132PS = 985
  | VFMADDSUB213PD = 986
  | VFMADDSUB213PH = 987
  | VFMADDSUB213PS = 988
  | VFMADDSUB231PD = 989
  | VFMADDSUB231PH = 990
  | VFMADDSUB231PS = 991
  | VFMSUB132PD = 992
  | VFMSUB132PH = 993
  | VFMSUB132PS = 994
  | VFMSUB132SD = 995
  | VFMSUB132SH = 996
  | VFMSUB132SS = 997
  | VFMSUB213PD = 998
  | VFMSUB213PH = 999
  | VFMSUB213PS = 1000
  | VFMSUB213SD = 1001
  | VFMSUB213SH = 1002
  | VFMSUB213SS = 1003
  | VFMSUB231PD = 1004
  | VFMSUB231PH = 1005
  | VFMSUB231PS = 1006
  | VFMSUB231SD = 1007
  | VFMSUB231SH = 1008
  | VFMSUB231SS = 1009
  | VFMSUBADD132PD = 1010
  | VFMSUBADD132PH = 1011
  | VFMSUBADD132PS = 1012
  | VFMSUBADD213PD = 1013
  | VFMSUBADD213PH = 1014
  | VFMSUBADD213PS = 1015
  | VFMSUBADD231PD = 1016
  | VFMSUBADD231PH = 1017
  | VFMSUBADD231PS = 1018
  | VFMULCPH = 1019
  | VFMULCSH = 1020
  | VFNMADD132PD = 1021
  | VFNMADD132PH = 1022
  | VFNMADD132PS = 1023
  | VFNMADD132SD = 1024
  | VFNMADD132SH = 1025
  | VFNMADD132SS = 1026
  | VFNMADD213PD = 1027
  | VFNMADD213PH = 1028
  | VFNMADD213PS = 1029
  | VFNMADD213SD = 1030
  | VFNMADD213SH = 1031
  | VFNMADD213SS = 1032
  | VFNMADD231PD = 1033
  | VFNMADD231PH = 1034
  | VFNMADD231PS = 1035
  | VFNMADD231SD = 1036
  | VFNMADD231SH = 1037
  | VFNMADD231SS = 1038
  | VFNMSUB132PD = 1039
  | VFNMSUB132PH = 1040
  | VFNMSUB132PS = 1041
  | VFNMSUB132SD = 1042
  | VFNMSUB132SH = 1043
  | VFNMSUB132SS = 1044
  | VFNMSUB213PD = 1045
  | VFNMSUB213PH = 1046
  | VFNMSUB213PS = 1047
  | VFNMSUB213SD = 1048
  | VFNMSUB213SH = 1049
  | VFNMSUB213SS = 1050
  | VFNMSUB231PD = 1051
  | VFNMSUB231PH = 1052
  | VFNMSUB231PS = 1053
  | VFNMSUB231SD = 1054
  | VFNMSUB231SH = 1055
  | VFNMSUB231SS = 1056
  | VFPCLASSPD = 1057
  | VFPCLASSPH = 1058
  | VFPCLASSPS = 1059
  | VFPCLASSSD = 1060
  | VFPCLASSSH = 1061
  | VFPCLASSSS = 1062
  | VGATHERDPD = 1063
  | VGATHERDPS = 1064
  | VGATHERPF0DPD = 1065
  | VGATHERPF0DPS = 1066
  | VGATHERPF0QPD = 1067
  | VGATHERPF0QPS = 1068
  | VGATHERPF1DPD = 1069
  | VGATHERPF1DPS = 1070
  | VGATHERPF1QPD = 1071
  | VGATHERPF1QPS = 1072
  | VGATHERQPD = 1073
  | VGATHERQPS = 1074
  | VGETEXPPD = 1075
  | VGETEXPPH = 1076
  | VGETEXPPS = 1077
  | VGETEXPSD = 1078
  | VGETEXPSH = 1079
  | VGETEXPSS = 1080
  | VGETMANTPD = 1081
  | VGETMANTPH = 1082
  | VGETMANTPS = 1083
  | VGETMANTSD = 1084
  | VGETMANTSH = 1085
  | VGETMANTSS = 1086
  | VGF2P8AFFINEINVQB = 1087
  | VGF2P8AFFINEQB = 1088
  | VGF2P8MULB = 1089
  | VHADDPD = 1090
  | VHADDPS = 1091
  | VHSUBPD = 1092
  | VHSUBPS = 1093
  | VINSERTF128 = 1094
  | VINSERTF32X4 = 1095
  | VINSERTF32X8 = 1096
  | VINSERTF64X2 = 1097
  | VINSERTF64X4 = 1098
  | VINSERTI128 = 1099
  | VINSERTI32X4 = 1100
  | VINSERTI32X8 = 1101
  | VINSERTI64X2 = 1102
  | VINSERTI64X4 = 1103
  | VINSERTPS = 1104
  | VLDDQU = 1105
  | VLDMXCSR = 1106
  | VMASKMOVDQU = 1107
  | VMASKMOVPD = 1108
  | VMASKMOVPS = 1109
  | VMAXPD = 1110
  | VMAXPH = 1111
  | VMAXPS = 1112
  | VMAXSD = 1113
  | VMAXSH = 1114
  | VMAXSS = 1115
  | VMINPD = 1116
  | VMINPH = 1117
  | VMINPS = 1118
  | VMINSD = 1119
  | VMINSH = 1120
  | VMINSS = 1121
  | VMOVAPD = 1122
  | VMOVAPS = 1123
  | VMOVD = 1124
  | VMOVDDUP = 1125
  | VMOVDQA = 1126
  | VMOVDQA32 = 1127
  | VMOVDQA64 = 1128
  | VMOVDQU = 1129
  | VMOVDQU16 = 1130
  | VMOVDQU32 = 1131
  | VMOVDQU64 = 1132
  | VMOVDQU8 = 1133
  | VMOVHLPS = 1134
  | VMOVHPD = 1135
  | VMOVHPS = 1136
  | VMOVLHPS = 1137
  | VMOVLPD = 1138
  | VMOVLPS = 1139
  | VMOVMSKPD = 1140
  | VMOVMSKPS = 1141
  | VMOVNTDQ = 1142
  | VMOVNTDQA = 1143
  | VMOVNTPD = 1144
  | VMOVNTPS = 1145
  | VMOVQ = 1146
  | VMOVSD = 1147
  | VMOVSH = 1148
  | VMOVSHDUP = 1149
  | VMOVSLDUP = 1150
  | VMOVSS = 1151
  | VMOVUPD = 1152
  | VMOVUPS = 1153
  | VMOVW = 1154
  | VMPSADBW = 1155
  | VMULPD = 1156
  | VMULPH = 1157
  | VMULPS = 1158
  | VMULSD = 1159
  | VMULSH = 1160
  | VMULSS = 1161
  | VORPD = 1162
  | VORPS = 1163
  | VP2INTERSECTD = 1164
  | VP2INTERSECTQ = 1165
  | VP4DPWSSD = 1166
  | VP4DPWSSDS = 1167
  | VPABSB = 1168
  | VPABSD = 1169
  | VPABSQ = 1170
  | VPABSW = 1171
  | VPACKSSDW = 1172
  | VPACKSSWB = 1173
  | VPACKUSDW = 1174
  | VPACKUSWB = 1175
  | VPADDB = 1176
  | VPADDD = 1177
  | VPADDQ = 1178
  | VPADDSB = 1179
  | VPADDSW = 1180
  | VPADDUSB = 1181
  | VPADDUSW = 1182
  | VPADDW = 1183
  | VPALIGNR = 1184
  | VPAND = 1185
  | VPANDD = 1186
  | VPANDN = 1187
  | VPANDND = 1188
  | VPANDNQ = 1189
  | VPANDQ = 1190
  | VPAVGB = 1191
  | VPAVGW = 1192
  | VPBLENDD = 1193
  | VPBLENDMB = 1194
  | VPBLENDMD = 1195
  | VPBLENDMQ = 1196
  | VPBLENDMW = 1197
  | VPBLENDVB = 1198
  | VPBLENDW = 1199
  | VPBROADCASTB = 1200
  | VPBROADCASTD = 1201
  | VPBROADCASTMB2Q = 1202
  | VPBROADCASTMW2D = 1203
  | VPBROADCASTQ = 1204
  | VPBROADCASTW = 1205
  | VPCLMULQDQ = 1206
  | VPCMPB = 1207
  | VPCMPD = 1208
  | VPCMPEQB = 1209
  | VPCMPEQD = 1210
  | VPCMPEQQ = 1211
  | VPCMPEQW = 1212
  | VPCMPESTRI = 1213
  | VPCMPESTRM = 1214
  | VPCMPGTB = 1215
  | VPCMPGTD = 1216
  | VPCMPGTQ = 1217
  | VPCMPGTW = 1218
  | VPCMPISTRI = 1219
  | VPCMPISTRM = 1220
  | VPCMPQ = 1221
  | VPCMPUB = 1222
  | VPCMPUD = 1223
  | VPCMPUQ = 1224
  | VPCMPUW = 1225
  | VPCMPW = 1226
  | VPCOMPRESSB = 1227
  | VPCOMPRESSD = 1228
  | VPCOMPRESSQ = 1229
  | VPCOMPRESSW = 1230
  | VPCONFLICTD = 1231
  | VPCONFLICTQ = 1232
  | VPDPBSSD = 1233
  | VPDPBSSDS = 1234
  | VPDPBSUD = 1235
  | VPDPBSUDS = 1236
  | VPDPBUSD = 1237
  | VPDPBUSDS = 1238
  | VPDPBUUD = 1239
  | VPDPBUUDS = 1240
  | VPDPWSSD = 1241
  | VPDPWSSDS = 1242
  | VPDPWSUD = 1243
  | VPDPWSUDS = 1244
  | VPDPWUSD = 1245
  | VPDPWUSDS = 1246
  | VPDPWUUD = 1247
  | VPDPWUUDS = 1248
  | VPERM2F128 = 1249
  | VPERM2I128 = 1250
  | VPERMB = 1251
  | VPERMD = 1252
  | VPERMI2B = 1253
  | VPERMI2D = 1254
  | VPERMI2PD = 1255
  | VPERMI2PS = 1256
  | VPERMI2Q = 1257
  | VPERMI2W = 1258
  | VPERMILPD = 1259
  | VPERMILPS = 1260
  | VPERMPD = 1261
  | VPERMPS = 1262
  | VPERMQ = 1263
  | VPERMT2B = 1264
  | VPERMT2D = 1265
  | VPERMT2PD = 1266
  | VPERMT2PS = 1267
  | VPERMT2Q = 1268
  | VPERMT2W = 1269
  | VPERMW = 1270
  | VPEXPANDB = 1271
  | VPEXPANDD = 1272
  | VPEXPANDQ = 1273
  | VPEXPANDW = 1274
  | VPEXTRB = 1275
  | VPEXTRD = 1276
  | VPEXTRQ = 1277
  | VPEXTRW = 1278
  | VPGATHERDD = 1279
  | VPGATHERDQ = 1280
  | VPGATHERQD = 1281
  | VPGATHERQQ = 1282
  | VPHADDD = 1283
  | VPHADDSW = 1284
  | VPHADDW = 1285
  | VPHMINPOSUW = 1286
  | VPHSUBD = 1287
  | VPHSUBSW = 1288
  | VPHSUBW = 1289
  | VPINSRB = 1290
  | VPINSRD = 1291
  | VPINSRQ = 1292
  | VPINSRW = 1293
  | VPLZCNTD = 1294
  | VPLZCNTQ = 1295
  | VPMADD52HUQ = 1296
  | VPMADD52LUQ = 1297
  | VPMADDUBSW = 1298
  | VPMADDWD = 1299
  | VPMASKMOVD = 1300
  | VPMASKMOVQ = 1301
  | VPMAXSB = 1302
  | VPMAXSD = 1303
  | VPMAXSQ = 1304
  | VPMAXSW = 1305
  | VPMAXUB = 1306
  | VPMAXUD = 1307
  | VPMAXUQ = 1308
  | VPMAXUW = 1309
  | VPMINSB = 1310
  | VPMINSD = 1311
  | VPMINSQ = 1312
  | VPMINSW = 1313
  | VPMINUB = 1314
  | VPMINUD = 1315
  | VPMINUQ = 1316
  | VPMINUW = 1317
  | VPMOVB2M = 1318
  | VPMOVD2M = 1319
  | VPMOVDB = 1320
  | VPMOVDW = 1321
  | VPMOVM2B = 1322
  | VPMOVM2D = 1323
  | VPMOVM2Q = 1324
  | VPMOVM2W = 1325
  | VPMOVMSKB = 1326
  | VPMOVQ2M = 1327
  | VPMOVQB = 1328
  | VPMOVQD = 1329
  | VPMOVQW = 1330
  | VPMOVSDB = 1331
  | VPMOVSDW = 1332
  | VPMOVSQB = 1333
  | VPMOVSQD = 1334
  | VPMOVSQW = 1335
  | VPMOVSWB = 1336
  | VPMOVSXBD = 1337
  | VPMOVSXBQ = 1338
  | VPMOVSXBW = 1339
  | VPMOVSXDQ = 1340
  | VPMOVSXWD = 1341
  | VPMOVSXWQ = 1342
  | VPMOVUSDB = 1343
  | VPMOVUSDW = 1344
  | VPMOVUSQB = 1345
  | VPMOVUSQD = 1346
  | VPMOVUSQW = 1347
  | VPMOVUSWB = 1348
  | VPMOVW2M = 1349
  | VPMOVWB = 1350
  | VPMOVZXBD = 1351
  | VPMOVZXBQ = 1352
  | VPMOVZXBW = 1353
  | VPMOVZXDQ = 1354
  | VPMOVZXWD = 1355
  | VPMOVZXWQ = 1356
  | VPMULDQ = 1357
  | VPMULHRSW = 1358
  | VPMULHUW = 1359
  | VPMULHW = 1360
  | VPMULLD = 1361
  | VPMULLQ = 1362
  | VPMULLW = 1363
  | VPMULTISHIFTQB = 1364
  | VPMULUDQ = 1365
  | VPOPCNTB = 1366
  | VPOPCNTD = 1367
  | VPOPCNTQ = 1368
  | VPOPCNTW = 1369
  | VPOR = 1370
  | VPORD = 1371
  | VPORQ = 1372
  | VPROLD = 1373
  | VPROLQ = 1374
  | VPROLVD = 1375
  | VPROLVQ = 1376
  | VPRORD = 1377
  | VPRORQ = 1378
  | VPRORVD = 1379
  | VPRORVQ = 1380
  | VPSADBW = 1381
  | VPSCATTERDD = 1382
  | VPSCATTERDQ = 1383
  | VPSCATTERQD = 1384
  | VPSCATTERQQ = 1385
  | VPSHLDD = 1386
  | VPSHLDQ = 1387
  | VPSHLDVD = 1388
  | VPSHLDVQ = 1389
  | VPSHLDVW = 1390
  | VPSHLDW = 1391
  | VPSHRDD = 1392
  | VPSHRDQ = 1393
  | VPSHRDVD = 1394
  | VPSHRDVQ = 1395
  | VPSHRDVW = 1396
  | VPSHRDW = 1397
  | VPSHUFB = 1398
  | VPSHUFBITQMB = 1399
  | VPSHUFD = 1400
  | VPSHUFHW = 1401
  | VPSHUFLW = 1402
  | VPSIGNB = 1403
  | VPSIGND = 1404
  | VPSIGNW = 1405
  | VPSLLD = 1406
  | VPSLLDQ = 1407
  | VPSLLQ = 1408
  | VPSLLVD = 1409
  | VPSLLVQ = 1410
  | VPSLLVW = 1411
  | VPSLLW = 1412
  | VPSRAD = 1413
  | VPSRAQ = 1414
  | VPSRAVD = 1415
  | VPSRAVQ = 1416
  | VPSRAVW = 1417
  | VPSRAW = 1418
  | VPSRLD = 1419
  | VPSRLDQ = 1420
  | VPSRLQ = 1421
  | VPSRLVD = 1422
  | VPSRLVQ = 1423
  | VPSRLVW = 1424
  | VPSRLW = 1425
  | VPSUBB = 1426
  | VPSUBD = 1427
  | VPSUBQ = 1428
  | VPSUBSB = 1429
  | VPSUBSW = 1430
  | VPSUBUSB = 1431
  | VPSUBUSW = 1432
  | VPSUBW = 1433
  | VPTERNLOGD = 1434
  | VPTERNLOGQ = 1435
  | VPTEST = 1436
  | VPTESTMB = 1437
  | VPTESTMD = 1438
  | VPTESTMQ = 1439
  | VPTESTMW = 1440
  | VPTESTNMB = 1441
  | VPTESTNMD = 1442
  | VPTESTNMQ = 1443
  | VPTESTNMW = 1444
  | VPUNPCKHBW = 1445
  | VPUNPCKHDQ = 1446
  | VPUNPCKHQDQ = 1447
  | VPUNPCKHWD = 1448
  | VPUNPCKLBW = 1449
  | VPUNPCKLDQ = 1450
  | VPUNPCKLQDQ = 1451
  | VPUNPCKLWD = 1452
  | VPXOR = 1453
  | VPXORD = 1454
  | VPXORQ = 1455
  | VRANGEPD = 1456
  | VRANGEPS = 1457
  | VRANGESD = 1458
  | VRANGESS = 1459
  | VRCP14PD = 1460
  | VRCP14PS = 1461
  | VRCP14SD = 1462
  | VRCP14SS = 1463
  | VRCP28PD = 1464
  | VRCP28PS = 1465
  | VRCP28SD = 1466
  | VRCP28SS = 1467
  | VRCPPH = 1468
  | VRCPPS = 1469
  | VRCPSH = 1470
  | VRCPSS = 1471
  | VREDUCEPD = 1472
  | VREDUCEPH = 1473
  | VREDUCEPS = 1474
  | VREDUCESD = 1475
  | VREDUCESH = 1476
  | VREDUCESS = 1477
  | VRNDSCALEPD = 1478
  | VRNDSCALEPH = 1479
  | VRNDSCALEPS = 1480
  | VRNDSCALESD = 1481
  | VRNDSCALESH = 1482
  | VRNDSCALESS = 1483
  | VROUNDPD = 1484
  | VROUNDPS = 1485
  | VROUNDSD = 1486
  | VROUNDSS = 1487
  | VRSQRT14PD = 1488
  | VRSQRT14PS = 1489
  | VRSQRT14SD = 1490
  | VRSQRT14SS = 1491
  | VRSQRT28PD = 1492
  | VRSQRT28PS = 1493
  | VRSQRT28SD = 1494
  | VRSQRT28SS = 1495
  | VRSQRTPH = 1496
  | VRSQRTPS = 1497
  | VRSQRTSH = 1498
  | VRSQRTSS = 1499
  | VSCALEFPD = 1500
  | VSCALEFPH = 1501
  | VSCALEFPS = 1502
  | VSCALEFSD = 1503
  | VSCALEFSH = 1504
  | VSCALEFSS = 1505
  | VSCATTERDPD = 1506
  | VSCATTERDPS = 1507
  | VSCATTERPF0DPD = 1508
  | VSCATTERPF0DPS = 1509
  | VSCATTERPF0QPD = 1510
  | VSCATTERPF0QPS = 1511
  | VSCATTERPF1DPD = 1512
  | VSCATTERPF1DPS = 1513
  | VSCATTERPF1QPD = 1514
  | VSCATTERPF1QPS = 1515
  | VSCATTERQPD = 1516
  | VSCATTERQPS = 1517
  | VSHA512MSG1 = 1518
  | VSHA512MSG2 = 1519
  | VSHA512RNDS2 = 1520
  | VSHUFF32X4 = 1521
  | VSHUFF64X2 = 1522
  | VSHUFI32X4 = 1523
  | VSHUFI64X2 = 1524
  | VSHUFPD = 1525
  | VSHUFPS = 1526
  | VSM3MSG1 = 1527
  | VSM3MSG2 = 1528
  | VSM3RNDS2 = 1529
  | VSM4KEY4 = 1530
  | VSM4RNDS4 = 1531
  | VSQRTPD = 1532
  | VSQRTPH = 1533
  | VSQRTPS = 1534
  | VSQRTSD = 1535
  | VSQRTSH = 1536
  | VSQRTSS = 1537
  | VSTMXCSR = 1538
  | VSUBPD = 1539
  | VSUBPH = 1540
  | VSUBPS = 1541
  | VSUBSD = 1542
  | VSUBSH = 1543
  | VSUBSS = 1544
  | VTESTPD = 1545
  | VTESTPS = 1546
  | VUCOMISD = 1547
  | VUCOMISH = 1548
  | VUCOMISS = 1549
  | VUNPCKHPD = 1550
  | VUNPCKHPS = 1551
  | VUNPCKLPD = 1552
  | VUNPCKLPS = 1553
  | VXORPD = 1554
  | VXORPS = 1555
  | VZEROALL = 1556
  | VZEROUPPER = 1557
  | WAIT = 1558
  | WBINVD = 1559
  | WBNOINVD = 1560
  | WRFSBASE = 1561
  | WRGSBASE = 1562
  | WRMSR = 1563
  | WRMSRLIST = 1564
  | WRMSRNS = 1565
  | WRPKRU = 1566
  | WRSSD = 1567
  | WRSSQ = 1568
  | WRUSSD = 1569
  | WRUSSQ = 1570
  | XABORT = 1571
  | XACQUIRE = 1572
  | XADD = 1573
  | XBEGIN = 1574
  | XCHG = 1575
  | XEND = 1576
  | XGETBV = 1577
  | XLAT = 1578
  | XLATB = 1579
  | XOR = 1580
  | XORPD = 1581
  | XORPS = 1582
  | XRELEASE = 1583
  | XRESLDTRK = 1584
  | XRSTOR = 1585
  | XRSTOR64 = 1586
  | XRSTORS = 1587
  | XRSTORS64 = 1588
  | XSAVE = 1589
  | XSAVE64 = 1590
  | XSAVEC = 1591
  | XSAVEC64 = 1592
  | XSAVEOPT = 1593
  | XSAVEOPT64 = 1594
  | XSAVES = 1595
  | XSAVES64 = 1596
  | XSETBV = 1597
  | XSUSLDTRK = 1598
  | XTEST = 1599
  | FFREEP = 1600
  | VMREAD = 1601
  | EXTRQ = 1602
  | INSERTQ = 1603
  | VFMADDPS = 1604
  | VFMADDPD = 1605
  | VFMADDSS = 1606
  | VFMADDSD = 1607
  | VMCALL = 1608
  | VMLAUNCH = 1609
  | VMRESUME = 1610
  | VMXOFF = 1611
  | VMFUNC = 1612
  | VMPTRLD = 1613
  | VMPTRST = 1614
  | VMCLEAR = 1615
  | VMXON = 1616
  | JMPFar = 1617
  | JMPNear = 1618
  | CALLFar = 1619
  | CALLNear = 1620
  | RETFar = 1621
  | RETFarImm = 1622
  | RETNear = 1623
  | RETNearImm = 1624
  | InvalOP = 1625

/// Provides functions to check properties of opcodes.
[<RequireQualifiedAccess>]
module internal Opcode =
  let isBranch = function
    | Opcode.CALLFar | Opcode.CALLNear
    | Opcode.JMPFar | Opcode.JMPNear
    | Opcode.RETFar | Opcode.RETFarImm | Opcode.RETNear | Opcode.RETNearImm
    | Opcode.JA | Opcode.JB | Opcode.JBE | Opcode.JCXZ | Opcode.JECXZ
    | Opcode.JG | Opcode.JL | Opcode.JLE | Opcode.JNB | Opcode.JNL | Opcode.JNO
    | Opcode.JNP | Opcode.JNS | Opcode.JNZ | Opcode.JO | Opcode.JP
    | Opcode.JRCXZ | Opcode.JS | Opcode.JZ | Opcode.LOOP | Opcode.LOOPE
    | Opcode.LOOPNE -> true
    | _ -> false

  let isCETInstr = function
    | Opcode.INCSSPD | Opcode.INCSSPQ | Opcode.RDSSPD | Opcode.RDSSPQ
    | Opcode.SAVEPREVSSP | Opcode.RSTORSSP | Opcode.WRSSD | Opcode.WRSSQ
    | Opcode.WRUSSD | Opcode.WRUSSQ | Opcode.SETSSBSY | Opcode.CLRSSBSY -> true
    | _ -> false

  let opcodeToString = function
    | Opcode.AAA -> "aaa"
    | Opcode.AAD -> "aad"
    | Opcode.AAM -> "aam"
    | Opcode.AAS -> "aas"
    | Opcode.ADC -> "adc"
    | Opcode.ADCX -> "adcx"
    | Opcode.ADD -> "add"
    | Opcode.ADDPD -> "addpd"
    | Opcode.ADDPS -> "addps"
    | Opcode.ADDSD -> "addsd"
    | Opcode.ADDSS -> "addss"
    | Opcode.ADDSUBPD -> "addsubpd"
    | Opcode.ADDSUBPS -> "addsubps"
    | Opcode.ADOX -> "adox"
    | Opcode.AESDEC -> "aesdec"
    | Opcode.AESDEC128KL -> "aesdec128kl"
    | Opcode.AESDEC256KL -> "aesdec256kl"
    | Opcode.AESDECLAST -> "aesdeclast"
    | Opcode.AESDECWIDE128KL -> "aesdecwide128kl"
    | Opcode.AESDECWIDE256KL -> "aesdecwide256kl"
    | Opcode.AESENC -> "aesenc"
    | Opcode.AESENC128KL -> "aesenc128kl"
    | Opcode.AESENC256KL -> "aesenc256kl"
    | Opcode.AESENCLAST -> "aesenclast"
    | Opcode.AESENCWIDE128KL -> "aesencwide128kl"
    | Opcode.AESENCWIDE256KL -> "aesencwide256kl"
    | Opcode.AESIMC -> "aesimc"
    | Opcode.AESKEYGENASSIST -> "aeskeygenassist"
    | Opcode.AND -> "and"
    | Opcode.ANDN -> "andn"
    | Opcode.ANDNPD -> "andnpd"
    | Opcode.ANDNPS -> "andnps"
    | Opcode.ANDPD -> "andpd"
    | Opcode.ANDPS -> "andps"
    | Opcode.ARPL -> "arpl"
    | Opcode.BEXTR -> "bextr"
    | Opcode.BLENDPD -> "blendpd"
    | Opcode.BLENDPS -> "blendps"
    | Opcode.BLENDVPD -> "blendvpd"
    | Opcode.BLENDVPS -> "blendvps"
    | Opcode.BLSI -> "blsi"
    | Opcode.BLSMSK -> "blsmsk"
    | Opcode.BLSR -> "blsr"
    | Opcode.BNDCL -> "bndcl"
    | Opcode.BNDCN -> "bndcn"
    | Opcode.BNDCU -> "bndcu"
    | Opcode.BNDLDX -> "bndldx"
    | Opcode.BNDMK -> "bndmk"
    | Opcode.BNDMOV -> "bndmov"
    | Opcode.BNDSTX -> "bndstx"
    | Opcode.BOUND -> "bound"
    | Opcode.BSF -> "bsf"
    | Opcode.BSR -> "bsr"
    | Opcode.BSWAP -> "bswap"
    | Opcode.BT -> "bt"
    | Opcode.BTC -> "btc"
    | Opcode.BTR -> "btr"
    | Opcode.BTS -> "bts"
    | Opcode.BZHI -> "bzhi"
    | Opcode.CALL -> "call"
    | Opcode.CBW -> "cbw"
    | Opcode.CDQ -> "cdq"
    | Opcode.CDQE -> "cdqe"
    | Opcode.CLAC -> "clac"
    | Opcode.CLC -> "clc"
    | Opcode.CLD -> "cld"
    | Opcode.CLDEMOTE -> "cldemote"
    | Opcode.CLFLUSH -> "clflush"
    | Opcode.CLFLUSHOPT -> "clflushopt"
    | Opcode.CLI -> "cli"
    | Opcode.CLRSSBSY -> "clrssbsy"
    | Opcode.CLTS -> "clts"
    | Opcode.CLUI -> "clui"
    | Opcode.CLWB -> "clwb"
    | Opcode.CMC -> "cmc"
    | Opcode.CMOVA -> "cmova"
    | Opcode.CMOVAE -> "cmovae"
    | Opcode.CMOVB -> "cmovb"
    | Opcode.CMOVBE -> "cmovbe"
    | Opcode.CMOVC -> "cmovc"
    | Opcode.CMOVE -> "cmove"
    | Opcode.CMOVG -> "cmovg"
    | Opcode.CMOVGE -> "cmovge"
    | Opcode.CMOVL -> "cmovl"
    | Opcode.CMOVLE -> "cmovle"
    | Opcode.CMOVNA -> "cmovna"
    | Opcode.CMOVNAE -> "cmovnae"
    | Opcode.CMOVNB -> "cmovnb"
    | Opcode.CMOVNBE -> "cmovnbe"
    | Opcode.CMOVNC -> "cmovnc"
    | Opcode.CMOVNE -> "cmovne"
    | Opcode.CMOVNG -> "cmovng"
    | Opcode.CMOVNGE -> "cmovnge"
    | Opcode.CMOVNL -> "cmovnl"
    | Opcode.CMOVNLE -> "cmovnle"
    | Opcode.CMOVNO -> "cmovno"
    | Opcode.CMOVNP -> "cmovnp"
    | Opcode.CMOVNS -> "cmovns"
    | Opcode.CMOVNZ -> "cmovnz"
    | Opcode.CMOVO -> "cmovo"
    | Opcode.CMOVP -> "cmovp"
    | Opcode.CMOVPE -> "cmovpe"
    | Opcode.CMOVPO -> "cmovpo"
    | Opcode.CMOVS -> "cmovs"
    | Opcode.CMOVZ -> "cmovz"
    | Opcode.CMP -> "cmp"
    | Opcode.CMPBEXADD -> "cmpbexadd"
    | Opcode.CMPBXADD -> "cmpbxadd"
    | Opcode.CMPLEXADD -> "cmplexadd"
    | Opcode.CMPLXADD -> "cmplxadd"
    | Opcode.CMPNBEXADD -> "cmpnbexadd"
    | Opcode.CMPNBXADD -> "cmpnbxadd"
    | Opcode.CMPNLEXADD -> "cmpnlexadd"
    | Opcode.CMPNLXADD -> "cmpnlxadd"
    | Opcode.CMPNOXADD -> "cmpnoxadd"
    | Opcode.CMPNPXADD -> "cmpnpxadd"
    | Opcode.CMPNSXADD -> "cmpnsxadd"
    | Opcode.CMPNZXADD -> "cmpnzxadd"
    | Opcode.CMPOXADD -> "cmpoxadd"
    | Opcode.CMPPD -> "cmppd"
    | Opcode.CMPPS -> "cmpps"
    | Opcode.CMPPXADD -> "cmppxadd"
    | Opcode.CMPS -> "cmps"
    | Opcode.CMPSB -> "cmpsb"
    | Opcode.CMPSD -> "cmpsd"
    | Opcode.CMPSQ -> "cmpsq"
    | Opcode.CMPSS -> "cmpss"
    | Opcode.CMPSW -> "cmpsw"
    | Opcode.CMPSXADD -> "cmpsxadd"
    | Opcode.CMPXCHG -> "cmpxchg"
    | Opcode.CMPXCHG16B -> "cmpxchg16b"
    | Opcode.CMPXCHG8B -> "cmpxchg8b"
    | Opcode.CMPZXADD -> "cmpzxadd"
    | Opcode.COMISD -> "comisd"
    | Opcode.COMISS -> "comiss"
    | Opcode.CPUID -> "cpuid"
    | Opcode.CQO -> "cqo"
    | Opcode.CRC32 -> "crc32"
    | Opcode.CVTDQ2PD -> "cvtdq2pd"
    | Opcode.CVTDQ2PS -> "cvtdq2ps"
    | Opcode.CVTPD2DQ -> "cvtpd2dq"
    | Opcode.CVTPD2PI -> "cvtpd2pi"
    | Opcode.CVTPD2PS -> "cvtpd2ps"
    | Opcode.CVTPI2PD -> "cvtpi2pd"
    | Opcode.CVTPI2PS -> "cvtpi2ps"
    | Opcode.CVTPS2DQ -> "cvtps2dq"
    | Opcode.CVTPS2PD -> "cvtps2pd"
    | Opcode.CVTPS2PI -> "cvtps2pi"
    | Opcode.CVTSD2SI -> "cvtsd2si"
    | Opcode.CVTSD2SS -> "cvtsd2ss"
    | Opcode.CVTSI2SD -> "cvtsi2sd"
    | Opcode.CVTSI2SS -> "cvtsi2ss"
    | Opcode.CVTSS2SD -> "cvtss2sd"
    | Opcode.CVTSS2SI -> "cvtss2si"
    | Opcode.CVTTPD2DQ -> "cvttpd2dq"
    | Opcode.CVTTPD2PI -> "cvttpd2pi"
    | Opcode.CVTTPS2DQ -> "cvttps2dq"
    | Opcode.CVTTPS2PI -> "cvttps2pi"
    | Opcode.CVTTSD2SI -> "cvttsd2si"
    | Opcode.CVTTSS2SI -> "cvttss2si"
    | Opcode.CWD -> "cwd"
    | Opcode.CWDE -> "cwde"
    | Opcode.DAA -> "daa"
    | Opcode.DAS -> "das"
    | Opcode.DEC -> "dec"
    | Opcode.DIV -> "div"
    | Opcode.DIVPD -> "divpd"
    | Opcode.DIVPS -> "divps"
    | Opcode.DIVSD -> "divsd"
    | Opcode.DIVSS -> "divss"
    | Opcode.DPPD -> "dppd"
    | Opcode.DPPS -> "dpps"
    | Opcode.EMMS -> "emms"
    | Opcode.ENCODEKEY128 -> "encodekey128"
    | Opcode.ENCODEKEY256 -> "encodekey256"
    | Opcode.ENDBR32 -> "endbr32"
    | Opcode.ENDBR64 -> "endbr64"
    | Opcode.ENQCMD -> "enqcmd"
    | Opcode.ENQCMDS -> "enqcmds"
    | Opcode.ENTER -> "enter"
    | Opcode.EXTRACTPS -> "extractps"
    | Opcode.F2XM1 -> "f2xm1"
    | Opcode.FABS -> "fabs"
    | Opcode.FADD -> "fadd"
    | Opcode.FADDP -> "faddp"
    | Opcode.FBLD -> "fbld"
    | Opcode.FBSTP -> "fbstp"
    | Opcode.FCHS -> "fchs"
    | Opcode.FCLEX -> "fclex"
    | Opcode.FCMOVB -> "fcmovb"
    | Opcode.FCMOVBE -> "fcmovbe"
    | Opcode.FCMOVE -> "fcmove"
    | Opcode.FCMOVNB -> "fcmovnb"
    | Opcode.FCMOVNBE -> "fcmovnbe"
    | Opcode.FCMOVNE -> "fcmovne"
    | Opcode.FCMOVNU -> "fcmovnu"
    | Opcode.FCMOVU -> "fcmovu"
    | Opcode.FCOM -> "fcom"
    | Opcode.FCOMI -> "fcomi"
    | Opcode.FCOMIP -> "fcomip"
    | Opcode.FCOMP -> "fcomp"
    | Opcode.FCOMPP -> "fcompp"
    | Opcode.FCOS -> "fcos"
    | Opcode.FDECSTP -> "fdecstp"
    | Opcode.FDIV -> "fdiv"
    | Opcode.FDIVP -> "fdivp"
    | Opcode.FDIVR -> "fdivr"
    | Opcode.FDIVRP -> "fdivrp"
    | Opcode.FFREE -> "ffree"
    | Opcode.FIADD -> "fiadd"
    | Opcode.FICOM -> "ficom"
    | Opcode.FICOMP -> "ficomp"
    | Opcode.FIDIV -> "fidiv"
    | Opcode.FIDIVR -> "fidivr"
    | Opcode.FILD -> "fild"
    | Opcode.FIMUL -> "fimul"
    | Opcode.FINCSTP -> "fincstp"
    | Opcode.FINIT -> "finit"
    | Opcode.FIST -> "fist"
    | Opcode.FISTP -> "fistp"
    | Opcode.FISTTP -> "fisttp"
    | Opcode.FISUB -> "fisub"
    | Opcode.FISUBR -> "fisubr"
    | Opcode.FLD -> "fld"
    | Opcode.FLD1 -> "fld1"
    | Opcode.FLDCW -> "fldcw"
    | Opcode.FLDENV -> "fldenv"
    | Opcode.FLDL2E -> "fldl2e"
    | Opcode.FLDL2T -> "fldl2t"
    | Opcode.FLDLG2 -> "fldlg2"
    | Opcode.FLDLN2 -> "fldln2"
    | Opcode.FLDPI -> "fldpi"
    | Opcode.FLDZ -> "fldz"
    | Opcode.FMUL -> "fmul"
    | Opcode.FMULP -> "fmulp"
    | Opcode.FNCLEX -> "fnclex"
    | Opcode.FNINIT -> "fninit"
    | Opcode.FNOP -> "fnop"
    | Opcode.FNSAVE -> "fnsave"
    | Opcode.FNSTCW -> "fnstcw"
    | Opcode.FNSTENV -> "fnstenv"
    | Opcode.FNSTSW -> "fnstsw"
    | Opcode.FPATAN -> "fpatan"
    | Opcode.FPREM -> "fprem"
    | Opcode.FPREM1 -> "fprem1"
    | Opcode.FPTAN -> "fptan"
    | Opcode.FRNDINT -> "frndint"
    | Opcode.FRSTOR -> "frstor"
    | Opcode.FSAVE -> "fsave"
    | Opcode.FSCALE -> "fscale"
    | Opcode.FSIN -> "fsin"
    | Opcode.FSINCOS -> "fsincos"
    | Opcode.FSQRT -> "fsqrt"
    | Opcode.FST -> "fst"
    | Opcode.FSTCW -> "fstcw"
    | Opcode.FSTENV -> "fstenv"
    | Opcode.FSTP -> "fstp"
    | Opcode.FSTSW -> "fstsw"
    | Opcode.FSUB -> "fsub"
    | Opcode.FSUBP -> "fsubp"
    | Opcode.FSUBR -> "fsubr"
    | Opcode.FSUBRP -> "fsubrp"
    | Opcode.FTST -> "ftst"
    | Opcode.FUCOM -> "fucom"
    | Opcode.FUCOMI -> "fucomi"
    | Opcode.FUCOMIP -> "fucomip"
    | Opcode.FUCOMP -> "fucomp"
    | Opcode.FUCOMPP -> "fucompp"
    | Opcode.FWAIT -> "fwait"
    | Opcode.FXAM -> "fxam"
    | Opcode.FXCH -> "fxch"
    | Opcode.FXRSTOR -> "fxrstor"
    | Opcode.FXRSTOR64 -> "fxrstor64"
    | Opcode.FXSAVE -> "fxsave"
    | Opcode.FXSAVE64 -> "fxsave64"
    | Opcode.FXTRACT -> "fxtract"
    | Opcode.FYL2X -> "fyl2x"
    | Opcode.FYL2XP1 -> "fyl2xp1"
    | Opcode.GETSEC -> "getsec"
    | Opcode.GF2P8AFFINEINVQB -> "gf2p8affineinvqb"
    | Opcode.GF2P8AFFINEQB -> "gf2p8affineqb"
    | Opcode.GF2P8MULB -> "gf2p8mulb"
    | Opcode.HADDPD -> "haddpd"
    | Opcode.HADDPS -> "haddps"
    | Opcode.HLT -> "hlt"
    | Opcode.HRESET -> "hreset"
    | Opcode.HSUBPD -> "hsubpd"
    | Opcode.HSUBPS -> "hsubps"
    | Opcode.IDIV -> "idiv"
    | Opcode.IMUL -> "imul"
    | Opcode.IN -> "in"
    | Opcode.INC -> "inc"
    | Opcode.INCSSPD -> "incsspd"
    | Opcode.INCSSPQ -> "incsspq"
    | Opcode.INS -> "ins"
    | Opcode.INSB -> "insb"
    | Opcode.INSD -> "insd"
    | Opcode.INSERTPS -> "insertps"
    | Opcode.INSW -> "insw"
    | Opcode.INT -> "int"
    | Opcode.INT1 -> "int1"
    | Opcode.INT3 -> "int3"
    | Opcode.INTO -> "into"
    | Opcode.INVD -> "invd"
    | Opcode.INVLPG -> "invlpg"
    | Opcode.INVPCID -> "invpcid"
    | Opcode.IRET -> "iret"
    | Opcode.IRETD -> "iretd"
    | Opcode.IRETQ -> "iretq"
    | Opcode.JA -> "ja"
    | Opcode.JAE -> "jae"
    | Opcode.JB -> "jb"
    | Opcode.JBE -> "jbe"
    | Opcode.JC -> "jc"
    | Opcode.JCXZ -> "jcxz"
    | Opcode.JE -> "je"
    | Opcode.JECXZ -> "jecxz"
    | Opcode.JG -> "jg"
    | Opcode.JGE -> "jge"
    | Opcode.JL -> "jl"
    | Opcode.JLE -> "jle"
    | Opcode.JMP -> "jmp"
    | Opcode.JNA -> "jna"
    | Opcode.JNAE -> "jnae"
    | Opcode.JNB -> "jnb"
    | Opcode.JNBE -> "jnbe"
    | Opcode.JNC -> "jnc"
    | Opcode.JNE -> "jne"
    | Opcode.JNG -> "jng"
    | Opcode.JNGE -> "jnge"
    | Opcode.JNL -> "jnl"
    | Opcode.JNLE -> "jnle"
    | Opcode.JNO -> "jno"
    | Opcode.JNP -> "jnp"
    | Opcode.JNS -> "jns"
    | Opcode.JNZ -> "jnz"
    | Opcode.JO -> "jo"
    | Opcode.JP -> "jp"
    | Opcode.JPE -> "jpe"
    | Opcode.JPO -> "jpo"
    | Opcode.JRCXZ -> "jrcxz"
    | Opcode.JS -> "js"
    | Opcode.JZ -> "jz"
    | Opcode.KADDB -> "kaddb"
    | Opcode.KADDD -> "kaddd"
    | Opcode.KADDQ -> "kaddq"
    | Opcode.KADDW -> "kaddw"
    | Opcode.KANDB -> "kandb"
    | Opcode.KANDD -> "kandd"
    | Opcode.KANDNB -> "kandnb"
    | Opcode.KANDND -> "kandnd"
    | Opcode.KANDNQ -> "kandnq"
    | Opcode.KANDNW -> "kandnw"
    | Opcode.KANDQ -> "kandq"
    | Opcode.KANDW -> "kandw"
    | Opcode.KMOVB -> "kmovb"
    | Opcode.KMOVD -> "kmovd"
    | Opcode.KMOVQ -> "kmovq"
    | Opcode.KMOVW -> "kmovw"
    | Opcode.KNOTB -> "knotb"
    | Opcode.KNOTD -> "knotd"
    | Opcode.KNOTQ -> "knotq"
    | Opcode.KNOTW -> "knotw"
    | Opcode.KORB -> "korb"
    | Opcode.KORD -> "kord"
    | Opcode.KORQ -> "korq"
    | Opcode.KORTESTB -> "kortestb"
    | Opcode.KORTESTD -> "kortestd"
    | Opcode.KORTESTQ -> "kortestq"
    | Opcode.KORTESTW -> "kortestw"
    | Opcode.KORW -> "korw"
    | Opcode.KSHIFTLB -> "kshiftlb"
    | Opcode.KSHIFTLD -> "kshiftld"
    | Opcode.KSHIFTLQ -> "kshiftlq"
    | Opcode.KSHIFTLW -> "kshiftlw"
    | Opcode.KSHIFTRB -> "kshiftrb"
    | Opcode.KSHIFTRD -> "kshiftrd"
    | Opcode.KSHIFTRQ -> "kshiftrq"
    | Opcode.KSHIFTRW -> "kshiftrw"
    | Opcode.KTESTB -> "ktestb"
    | Opcode.KTESTD -> "ktestd"
    | Opcode.KTESTQ -> "ktestq"
    | Opcode.KTESTW -> "ktestw"
    | Opcode.KUNPCKBW -> "kunpckbw"
    | Opcode.KUNPCKDQ -> "kunpckdq"
    | Opcode.KUNPCKWD -> "kunpckwd"
    | Opcode.KXNORB -> "kxnorb"
    | Opcode.KXNORD -> "kxnord"
    | Opcode.KXNORQ -> "kxnorq"
    | Opcode.KXNORW -> "kxnorw"
    | Opcode.KXORB -> "kxorb"
    | Opcode.KXORD -> "kxord"
    | Opcode.KXORQ -> "kxorq"
    | Opcode.KXORW -> "kxorw"
    | Opcode.LAHF -> "lahf"
    | Opcode.LAR -> "lar"
    | Opcode.LDDQU -> "lddqu"
    | Opcode.LDMXCSR -> "ldmxcsr"
    | Opcode.LDS -> "lds"
    | Opcode.LDTILECFG -> "ldtilecfg"
    | Opcode.LEA -> "lea"
    | Opcode.LEAVE -> "leave"
    | Opcode.LES -> "les"
    | Opcode.LFENCE -> "lfence"
    | Opcode.LFS -> "lfs"
    | Opcode.LGDT -> "lgdt"
    | Opcode.LGS -> "lgs"
    | Opcode.LIDT -> "lidt"
    | Opcode.LLDT -> "lldt"
    | Opcode.LMSW -> "lmsw"
    | Opcode.LOADIWKEY -> "loadiwkey"
    | Opcode.LOCK -> "lock"
    | Opcode.LODS -> "lods"
    | Opcode.LODSB -> "lodsb"
    | Opcode.LODSD -> "lodsd"
    | Opcode.LODSQ -> "lodsq"
    | Opcode.LODSW -> "lodsw"
    | Opcode.LOOP -> "loop"
    | Opcode.LOOPE -> "loope"
    | Opcode.LOOPNE -> "loopne"
    | Opcode.LSL -> "lsl"
    | Opcode.LSS -> "lss"
    | Opcode.LTR -> "ltr"
    | Opcode.LZCNT -> "lzcnt"
    | Opcode.MASKMOVDQU -> "maskmovdqu"
    | Opcode.MASKMOVQ -> "maskmovq"
    | Opcode.MAXPD -> "maxpd"
    | Opcode.MAXPS -> "maxps"
    | Opcode.MAXSD -> "maxsd"
    | Opcode.MAXSS -> "maxss"
    | Opcode.MFENCE -> "mfence"
    | Opcode.MINPD -> "minpd"
    | Opcode.MINPS -> "minps"
    | Opcode.MINSD -> "minsd"
    | Opcode.MINSS -> "minss"
    | Opcode.MONITOR -> "monitor"
    | Opcode.MOV -> "mov"
    | Opcode.MOVAPD -> "movapd"
    | Opcode.MOVAPS -> "movaps"
    | Opcode.MOVBE -> "movbe"
    | Opcode.MOVD -> "movd"
    | Opcode.MOVDDUP -> "movddup"
    | Opcode.MOVDIR64B -> "movdir64b"
    | Opcode.MOVDIRI -> "movdiri"
    | Opcode.MOVDQ2Q -> "movdq2q"
    | Opcode.MOVDQA -> "movdqa"
    | Opcode.MOVDQU -> "movdqu"
    | Opcode.MOVHLPS -> "movhlps"
    | Opcode.MOVHPD -> "movhpd"
    | Opcode.MOVHPS -> "movhps"
    | Opcode.MOVLHPS -> "movlhps"
    | Opcode.MOVLPD -> "movlpd"
    | Opcode.MOVLPS -> "movlps"
    | Opcode.MOVMSKPD -> "movmskpd"
    | Opcode.MOVMSKPS -> "movmskps"
    | Opcode.MOVNTDQ -> "movntdq"
    | Opcode.MOVNTDQA -> "movntdqa"
    | Opcode.MOVNTI -> "movnti"
    | Opcode.MOVNTPD -> "movntpd"
    | Opcode.MOVNTPS -> "movntps"
    | Opcode.MOVNTQ -> "movntq"
    | Opcode.MOVQ -> "movq"
    | Opcode.MOVQ2DQ -> "movq2dq"
    | Opcode.MOVS -> "movs"
    | Opcode.MOVSB -> "movsb"
    | Opcode.MOVSD -> "movsd"
    | Opcode.MOVSHDUP -> "movshdup"
    | Opcode.MOVSLDUP -> "movsldup"
    | Opcode.MOVSQ -> "movsq"
    | Opcode.MOVSS -> "movss"
    | Opcode.MOVSW -> "movsw"
    | Opcode.MOVSX -> "movsx"
    | Opcode.MOVSXD -> "movsxd"
    | Opcode.MOVUPD -> "movupd"
    | Opcode.MOVUPS -> "movups"
    | Opcode.MOVZX -> "movzx"
    | Opcode.MPSADBW -> "mpsadbw"
    | Opcode.MUL -> "mul"
    | Opcode.MULPD -> "mulpd"
    | Opcode.MULPS -> "mulps"
    | Opcode.MULSD -> "mulsd"
    | Opcode.MULSS -> "mulss"
    | Opcode.MULX -> "mulx"
    | Opcode.MWAIT -> "mwait"
    | Opcode.NEG -> "neg"
    | Opcode.NOP -> "nop"
    | Opcode.NOT -> "not"
    | Opcode.OR -> "or"
    | Opcode.ORPD -> "orpd"
    | Opcode.ORPS -> "orps"
    | Opcode.OUT -> "out"
    | Opcode.OUTS -> "outs"
    | Opcode.OUTSB -> "outsb"
    | Opcode.OUTSD -> "outsd"
    | Opcode.OUTSW -> "outsw"
    | Opcode.PABSB -> "pabsb"
    | Opcode.PABSD -> "pabsd"
    | Opcode.PABSW -> "pabsw"
    | Opcode.PACKSSDW -> "packssdw"
    | Opcode.PACKSSWB -> "packsswb"
    | Opcode.PACKUSDW -> "packusdw"
    | Opcode.PACKUSWB -> "packuswb"
    | Opcode.PADDB -> "paddb"
    | Opcode.PADDD -> "paddd"
    | Opcode.PADDQ -> "paddq"
    | Opcode.PADDSB -> "paddsb"
    | Opcode.PADDSW -> "paddsw"
    | Opcode.PADDUSB -> "paddusb"
    | Opcode.PADDUSW -> "paddusw"
    | Opcode.PADDW -> "paddw"
    | Opcode.PALIGNR -> "palignr"
    | Opcode.PAND -> "pand"
    | Opcode.PANDN -> "pandn"
    | Opcode.PAUSE -> "pause"
    | Opcode.PAVGB -> "pavgb"
    | Opcode.PAVGW -> "pavgw"
    | Opcode.PBLENDVB -> "pblendvb"
    | Opcode.PBLENDW -> "pblendw"
    | Opcode.PCLMULQDQ -> "pclmulqdq"
    | Opcode.PCMPEQB -> "pcmpeqb"
    | Opcode.PCMPEQD -> "pcmpeqd"
    | Opcode.PCMPEQQ -> "pcmpeqq"
    | Opcode.PCMPEQW -> "pcmpeqw"
    | Opcode.PCMPESTRI -> "pcmpestri"
    | Opcode.PCMPESTRM -> "pcmpestrm"
    | Opcode.PCMPGTB -> "pcmpgtb"
    | Opcode.PCMPGTD -> "pcmpgtd"
    | Opcode.PCMPGTQ -> "pcmpgtq"
    | Opcode.PCMPGTW -> "pcmpgtw"
    | Opcode.PCMPISTRI -> "pcmpistri"
    | Opcode.PCMPISTRM -> "pcmpistrm"
    | Opcode.PCONFIG -> "pconfig"
    | Opcode.PDEP -> "pdep"
    | Opcode.PEXT -> "pext"
    | Opcode.PEXTRB -> "pextrb"
    | Opcode.PEXTRD -> "pextrd"
    | Opcode.PEXTRQ -> "pextrq"
    | Opcode.PEXTRW -> "pextrw"
    | Opcode.PHADDD -> "phaddd"
    | Opcode.PHADDSW -> "phaddsw"
    | Opcode.PHADDW -> "phaddw"
    | Opcode.PHMINPOSUW -> "phminposuw"
    | Opcode.PHSUBD -> "phsubd"
    | Opcode.PHSUBSW -> "phsubsw"
    | Opcode.PHSUBW -> "phsubw"
    | Opcode.PINSRB -> "pinsrb"
    | Opcode.PINSRD -> "pinsrd"
    | Opcode.PINSRQ -> "pinsrq"
    | Opcode.PINSRW -> "pinsrw"
    | Opcode.PMADDUBSW -> "pmaddubsw"
    | Opcode.PMADDWD -> "pmaddwd"
    | Opcode.PMAXSB -> "pmaxsb"
    | Opcode.PMAXSD -> "pmaxsd"
    | Opcode.PMAXSW -> "pmaxsw"
    | Opcode.PMAXUB -> "pmaxub"
    | Opcode.PMAXUD -> "pmaxud"
    | Opcode.PMAXUW -> "pmaxuw"
    | Opcode.PMINSB -> "pminsb"
    | Opcode.PMINSD -> "pminsd"
    | Opcode.PMINSW -> "pminsw"
    | Opcode.PMINUB -> "pminub"
    | Opcode.PMINUD -> "pminud"
    | Opcode.PMINUW -> "pminuw"
    | Opcode.PMOVMSKB -> "pmovmskb"
    | Opcode.PMOVSXBD -> "pmovsxbd"
    | Opcode.PMOVSXBQ -> "pmovsxbq"
    | Opcode.PMOVSXBW -> "pmovsxbw"
    | Opcode.PMOVSXDQ -> "pmovsxdq"
    | Opcode.PMOVSXWD -> "pmovsxwd"
    | Opcode.PMOVSXWQ -> "pmovsxwq"
    | Opcode.PMOVZXBD -> "pmovzxbd"
    | Opcode.PMOVZXBQ -> "pmovzxbq"
    | Opcode.PMOVZXBW -> "pmovzxbw"
    | Opcode.PMOVZXDQ -> "pmovzxdq"
    | Opcode.PMOVZXWD -> "pmovzxwd"
    | Opcode.PMOVZXWQ -> "pmovzxwq"
    | Opcode.PMULDQ -> "pmuldq"
    | Opcode.PMULHRSW -> "pmulhrsw"
    | Opcode.PMULHUW -> "pmulhuw"
    | Opcode.PMULHW -> "pmulhw"
    | Opcode.PMULLD -> "pmulld"
    | Opcode.PMULLW -> "pmullw"
    | Opcode.PMULUDQ -> "pmuludq"
    | Opcode.POP -> "pop"
    | Opcode.POPA -> "popa"
    | Opcode.POPAD -> "popad"
    | Opcode.POPCNT -> "popcnt"
    | Opcode.POPF -> "popf"
    | Opcode.POPFD -> "popfd"
    | Opcode.POPFQ -> "popfq"
    | Opcode.POR -> "por"
    | Opcode.PREFETCHIT0 -> "prefetchit0"
    | Opcode.PREFETCHIT1 -> "prefetchit1"
    | Opcode.PREFETCHNTA -> "prefetchnta"
    | Opcode.PREFETCHT0 -> "prefetcht0"
    | Opcode.PREFETCHT1 -> "prefetcht1"
    | Opcode.PREFETCHT2 -> "prefetcht2"
    | Opcode.PREFETCHW -> "prefetchw"
    | Opcode.PREFETCHWT1 -> "prefetchwt1"
    | Opcode.PSADBW -> "psadbw"
    | Opcode.PSHUFB -> "pshufb"
    | Opcode.PSHUFD -> "pshufd"
    | Opcode.PSHUFHW -> "pshufhw"
    | Opcode.PSHUFLW -> "pshuflw"
    | Opcode.PSHUFW -> "pshufw"
    | Opcode.PSIGNB -> "psignb"
    | Opcode.PSIGND -> "psignd"
    | Opcode.PSIGNW -> "psignw"
    | Opcode.PSLLD -> "pslld"
    | Opcode.PSLLDQ -> "pslldq"
    | Opcode.PSLLQ -> "psllq"
    | Opcode.PSLLW -> "psllw"
    | Opcode.PSRAD -> "psrad"
    | Opcode.PSRAW -> "psraw"
    | Opcode.PSRLD -> "psrld"
    | Opcode.PSRLDQ -> "psrldq"
    | Opcode.PSRLQ -> "psrlq"
    | Opcode.PSRLW -> "psrlw"
    | Opcode.PSUBB -> "psubb"
    | Opcode.PSUBD -> "psubd"
    | Opcode.PSUBQ -> "psubq"
    | Opcode.PSUBSB -> "psubsb"
    | Opcode.PSUBSW -> "psubsw"
    | Opcode.PSUBUSB -> "psubusb"
    | Opcode.PSUBUSW -> "psubusw"
    | Opcode.PSUBW -> "psubw"
    | Opcode.PTEST -> "ptest"
    | Opcode.PTWRITE -> "ptwrite"
    | Opcode.PUNPCKHBW -> "punpckhbw"
    | Opcode.PUNPCKHDQ -> "punpckhdq"
    | Opcode.PUNPCKHQDQ -> "punpckhqdq"
    | Opcode.PUNPCKHWD -> "punpckhwd"
    | Opcode.PUNPCKLBW -> "punpcklbw"
    | Opcode.PUNPCKLDQ -> "punpckldq"
    | Opcode.PUNPCKLQDQ -> "punpcklqdq"
    | Opcode.PUNPCKLWD -> "punpcklwd"
    | Opcode.PUSH -> "push"
    | Opcode.PUSHA -> "pusha"
    | Opcode.PUSHAD -> "pushad"
    | Opcode.PUSHF -> "pushf"
    | Opcode.PUSHFD -> "pushfd"
    | Opcode.PUSHFQ -> "pushfq"
    | Opcode.PXOR -> "pxor"
    | Opcode.RCL -> "rcl"
    | Opcode.RCPPS -> "rcpps"
    | Opcode.RCPSS -> "rcpss"
    | Opcode.RCR -> "rcr"
    | Opcode.RDFSBASE -> "rdfsbase"
    | Opcode.RDGSBASE -> "rdgsbase"
    | Opcode.RDMSR -> "rdmsr"
    | Opcode.RDMSRLIST -> "rdmsrlist"
    | Opcode.RDPID -> "rdpid"
    | Opcode.RDPKRU -> "rdpkru"
    | Opcode.RDPMC -> "rdpmc"
    | Opcode.RDRAND -> "rdrand"
    | Opcode.RDSEED -> "rdseed"
    | Opcode.RDSSPD -> "rdsspd"
    | Opcode.RDSSPQ -> "rdsspq"
    | Opcode.RDTSC -> "rdtsc"
    | Opcode.RDTSCP -> "rdtscp"
    | Opcode.RET -> "ret"
    | Opcode.ROL -> "rol"
    | Opcode.ROR -> "ror"
    | Opcode.RORX -> "rorx"
    | Opcode.ROUNDPD -> "roundpd"
    | Opcode.ROUNDPS -> "roundps"
    | Opcode.ROUNDSD -> "roundsd"
    | Opcode.ROUNDSS -> "roundss"
    | Opcode.RSM -> "rsm"
    | Opcode.RSQRTPS -> "rsqrtps"
    | Opcode.RSQRTSS -> "rsqrtss"
    | Opcode.RSTORSSP -> "rstorssp"
    | Opcode.SAHF -> "sahf"
    | Opcode.SAL -> "sal"
    | Opcode.SAR -> "sar"
    | Opcode.SARX -> "sarx"
    | Opcode.SAVEPREVSSP -> "saveprevssp"
    | Opcode.SBB -> "sbb"
    | Opcode.SCAS -> "scas"
    | Opcode.SCASB -> "scasb"
    | Opcode.SCASD -> "scasd"
    | Opcode.SCASQ -> "scasq"
    | Opcode.SCASW -> "scasw"
    | Opcode.SENDUIPI -> "senduipi"
    | Opcode.SERIALIZE -> "serialize"
    | Opcode.SETA -> "seta"
    | Opcode.SETAE -> "setae"
    | Opcode.SETB -> "setb"
    | Opcode.SETBE -> "setbe"
    | Opcode.SETC -> "setc"
    | Opcode.SETE -> "sete"
    | Opcode.SETG -> "setg"
    | Opcode.SETGE -> "setge"
    | Opcode.SETL -> "setl"
    | Opcode.SETLE -> "setle"
    | Opcode.SETNA -> "setna"
    | Opcode.SETNAE -> "setnae"
    | Opcode.SETNB -> "setnb"
    | Opcode.SETNBE -> "setnbe"
    | Opcode.SETNC -> "setnc"
    | Opcode.SETNE -> "setne"
    | Opcode.SETNG -> "setng"
    | Opcode.SETNGE -> "setnge"
    | Opcode.SETNL -> "setnl"
    | Opcode.SETNLE -> "setnle"
    | Opcode.SETNO -> "setno"
    | Opcode.SETNP -> "setnp"
    | Opcode.SETNS -> "setns"
    | Opcode.SETNZ -> "setnz"
    | Opcode.SETO -> "seto"
    | Opcode.SETP -> "setp"
    | Opcode.SETPE -> "setpe"
    | Opcode.SETPO -> "setpo"
    | Opcode.SETS -> "sets"
    | Opcode.SETSSBSY -> "setssbsy"
    | Opcode.SETZ -> "setz"
    | Opcode.SFENCE -> "sfence"
    | Opcode.SGDT -> "sgdt"
    | Opcode.SHA1MSG1 -> "sha1msg1"
    | Opcode.SHA1MSG2 -> "sha1msg2"
    | Opcode.SHA1NEXTE -> "sha1nexte"
    | Opcode.SHA1RNDS4 -> "sha1rnds4"
    | Opcode.SHA256MSG1 -> "sha256msg1"
    | Opcode.SHA256MSG2 -> "sha256msg2"
    | Opcode.SHA256RNDS2 -> "sha256rnds2"
    | Opcode.SHL -> "shl"
    | Opcode.SHLD -> "shld"
    | Opcode.SHLX -> "shlx"
    | Opcode.SHR -> "shr"
    | Opcode.SHRD -> "shrd"
    | Opcode.SHRX -> "shrx"
    | Opcode.SHUFPD -> "shufpd"
    | Opcode.SHUFPS -> "shufps"
    | Opcode.SIDT -> "sidt"
    | Opcode.SLDT -> "sldt"
    | Opcode.SMSW -> "smsw"
    | Opcode.SQRTPD -> "sqrtpd"
    | Opcode.SQRTPS -> "sqrtps"
    | Opcode.SQRTSD -> "sqrtsd"
    | Opcode.SQRTSS -> "sqrtss"
    | Opcode.STAC -> "stac"
    | Opcode.STC -> "stc"
    | Opcode.STD -> "std"
    | Opcode.STI -> "sti"
    | Opcode.STMXCSR -> "stmxcsr"
    | Opcode.STOS -> "stos"
    | Opcode.STOSB -> "stosb"
    | Opcode.STOSD -> "stosd"
    | Opcode.STOSQ -> "stosq"
    | Opcode.STOSW -> "stosw"
    | Opcode.STR -> "str"
    | Opcode.STTILECFG -> "sttilecfg"
    | Opcode.STUI -> "stui"
    | Opcode.SUB -> "sub"
    | Opcode.SUBPD -> "subpd"
    | Opcode.SUBPS -> "subps"
    | Opcode.SUBSD -> "subsd"
    | Opcode.SUBSS -> "subss"
    | Opcode.SWAPGS -> "swapgs"
    | Opcode.SYSCALL -> "syscall"
    | Opcode.SYSENTER -> "sysenter"
    | Opcode.SYSEXIT -> "sysexit"
    | Opcode.SYSRET -> "sysret"
    | Opcode.TDPBF16PS -> "tdpbf16ps"
    | Opcode.TDPBSSD -> "tdpbssd"
    | Opcode.TDPBSUD -> "tdpbsud"
    | Opcode.TDPBUSD -> "tdpbusd"
    | Opcode.TDPBUUD -> "tdpbuud"
    | Opcode.TDPFP16PS -> "tdpfp16ps"
    | Opcode.TEST -> "test"
    | Opcode.TESTUI -> "testui"
    | Opcode.TILELOADD -> "tileloadd"
    | Opcode.TILELOADDT1 -> "tileloaddt1"
    | Opcode.TILERELEASE -> "tilerelease"
    | Opcode.TILESTORED -> "tilestored"
    | Opcode.TILEZERO -> "tilezero"
    | Opcode.TPAUSE -> "tpause"
    | Opcode.TZCNT -> "tzcnt"
    | Opcode.UCOMISD -> "ucomisd"
    | Opcode.UCOMISS -> "ucomiss"
    | Opcode.UD0 -> "ud0"
    | Opcode.UD1 -> "ud1"
    | Opcode.UD2 -> "ud2"
    | Opcode.UDB -> "udb"
    | Opcode.UIRET -> "uiret"
    | Opcode.UMONITOR -> "umonitor"
    | Opcode.UMWAIT -> "umwait"
    | Opcode.UNPCKHPD -> "unpckhpd"
    | Opcode.UNPCKHPS -> "unpckhps"
    | Opcode.UNPCKLPD -> "unpcklpd"
    | Opcode.UNPCKLPS -> "unpcklps"
    | Opcode.V4FMADDPS -> "v4fmaddps"
    | Opcode.V4FMADDSS -> "v4fmaddss"
    | Opcode.V4FNMADDPS -> "v4fnmaddps"
    | Opcode.V4FNMADDSS -> "v4fnmaddss"
    | Opcode.VADDPD -> "vaddpd"
    | Opcode.VADDPH -> "vaddph"
    | Opcode.VADDPS -> "vaddps"
    | Opcode.VADDSD -> "vaddsd"
    | Opcode.VADDSH -> "vaddsh"
    | Opcode.VADDSS -> "vaddss"
    | Opcode.VADDSUBPD -> "vaddsubpd"
    | Opcode.VADDSUBPS -> "vaddsubps"
    | Opcode.VAESDEC -> "vaesdec"
    | Opcode.VAESDECLAST -> "vaesdeclast"
    | Opcode.VAESENC -> "vaesenc"
    | Opcode.VAESENCLAST -> "vaesenclast"
    | Opcode.VAESIMC -> "vaesimc"
    | Opcode.VAESKEYGENASSIST -> "vaeskeygenassist"
    | Opcode.VALIGND -> "valignd"
    | Opcode.VALIGNQ -> "valignq"
    | Opcode.VANDNPD -> "vandnpd"
    | Opcode.VANDNPS -> "vandnps"
    | Opcode.VANDPD -> "vandpd"
    | Opcode.VANDPS -> "vandps"
    | Opcode.VBCSTNEBF162PS -> "vbcstnebf162ps"
    | Opcode.VBCSTNESH2PS -> "vbcstnesh2ps"
    | Opcode.VBLENDMPD -> "vblendmpd"
    | Opcode.VBLENDMPS -> "vblendmps"
    | Opcode.VBLENDPD -> "vblendpd"
    | Opcode.VBLENDPS -> "vblendps"
    | Opcode.VBLENDVPD -> "vblendvpd"
    | Opcode.VBLENDVPS -> "vblendvps"
    | Opcode.VBROADCASTF128 -> "vbroadcastf128"
    | Opcode.VBROADCASTF32X2 -> "vbroadcastf32x2"
    | Opcode.VBROADCASTF32X4 -> "vbroadcastf32x4"
    | Opcode.VBROADCASTF32X8 -> "vbroadcastf32x8"
    | Opcode.VBROADCASTF64X2 -> "vbroadcastf64x2"
    | Opcode.VBROADCASTF64X4 -> "vbroadcastf64x4"
    | Opcode.VBROADCASTI128 -> "vbroadcasti128"
    | Opcode.VBROADCASTI32X2 -> "vbroadcasti32x2"
    | Opcode.VBROADCASTI32X4 -> "vbroadcasti32x4"
    | Opcode.VBROADCASTI32X8 -> "vbroadcasti32x8"
    | Opcode.VBROADCASTI64X2 -> "vbroadcasti64x2"
    | Opcode.VBROADCASTI64X4 -> "vbroadcasti64x4"
    | Opcode.VBROADCASTSD -> "vbroadcastsd"
    | Opcode.VBROADCASTSS -> "vbroadcastss"
    | Opcode.VCMPPD -> "vcmppd"
    | Opcode.VCMPPH -> "vcmpph"
    | Opcode.VCMPPS -> "vcmpps"
    | Opcode.VCMPSD -> "vcmpsd"
    | Opcode.VCMPSH -> "vcmpsh"
    | Opcode.VCMPSS -> "vcmpss"
    | Opcode.VCOMISD -> "vcomisd"
    | Opcode.VCOMISH -> "vcomish"
    | Opcode.VCOMISS -> "vcomiss"
    | Opcode.VCOMPRESSPD -> "vcompresspd"
    | Opcode.VCOMPRESSPS -> "vcompressps"
    | Opcode.VCVTDQ2PD -> "vcvtdq2pd"
    | Opcode.VCVTDQ2PH -> "vcvtdq2ph"
    | Opcode.VCVTDQ2PS -> "vcvtdq2ps"
    | Opcode.VCVTNE2PS2BF16 -> "vcvtne2ps2bf16"
    | Opcode.VCVTNEEBF162PS -> "vcvtneebf162ps"
    | Opcode.VCVTNEEPH2PS -> "vcvtneeph2ps"
    | Opcode.VCVTNEOBF162PS -> "vcvtneobf162ps"
    | Opcode.VCVTNEOPH2PS -> "vcvtneoph2ps"
    | Opcode.VCVTNEPS2BF16 -> "vcvtneps2bf16"
    | Opcode.VCVTPD2DQ -> "vcvtpd2dq"
    | Opcode.VCVTPD2PH -> "vcvtpd2ph"
    | Opcode.VCVTPD2PS -> "vcvtpd2ps"
    | Opcode.VCVTPD2QQ -> "vcvtpd2qq"
    | Opcode.VCVTPD2UDQ -> "vcvtpd2udq"
    | Opcode.VCVTPD2UQQ -> "vcvtpd2uqq"
    | Opcode.VCVTPH2DQ -> "vcvtph2dq"
    | Opcode.VCVTPH2PD -> "vcvtph2pd"
    | Opcode.VCVTPH2PS -> "vcvtph2ps"
    | Opcode.VCVTPH2PSX -> "vcvtph2psx"
    | Opcode.VCVTPH2QQ -> "vcvtph2qq"
    | Opcode.VCVTPH2UDQ -> "vcvtph2udq"
    | Opcode.VCVTPH2UQQ -> "vcvtph2uqq"
    | Opcode.VCVTPH2UW -> "vcvtph2uw"
    | Opcode.VCVTPH2W -> "vcvtph2w"
    | Opcode.VCVTPS2DQ -> "vcvtps2dq"
    | Opcode.VCVTPS2PD -> "vcvtps2pd"
    | Opcode.VCVTPS2PH -> "vcvtps2ph"
    | Opcode.VCVTPS2PHX -> "vcvtps2phx"
    | Opcode.VCVTPS2QQ -> "vcvtps2qq"
    | Opcode.VCVTPS2UDQ -> "vcvtps2udq"
    | Opcode.VCVTPS2UQQ -> "vcvtps2uqq"
    | Opcode.VCVTQQ2PD -> "vcvtqq2pd"
    | Opcode.VCVTQQ2PH -> "vcvtqq2ph"
    | Opcode.VCVTQQ2PS -> "vcvtqq2ps"
    | Opcode.VCVTSD2SH -> "vcvtsd2sh"
    | Opcode.VCVTSD2SI -> "vcvtsd2si"
    | Opcode.VCVTSD2SS -> "vcvtsd2ss"
    | Opcode.VCVTSD2USI -> "vcvtsd2usi"
    | Opcode.VCVTSH2SD -> "vcvtsh2sd"
    | Opcode.VCVTSH2SI -> "vcvtsh2si"
    | Opcode.VCVTSH2SS -> "vcvtsh2ss"
    | Opcode.VCVTSH2USI -> "vcvtsh2usi"
    | Opcode.VCVTSI2SD -> "vcvtsi2sd"
    | Opcode.VCVTSI2SH -> "vcvtsi2sh"
    | Opcode.VCVTSI2SS -> "vcvtsi2ss"
    | Opcode.VCVTSS2SD -> "vcvtss2sd"
    | Opcode.VCVTSS2SH -> "vcvtss2sh"
    | Opcode.VCVTSS2SI -> "vcvtss2si"
    | Opcode.VCVTSS2USI -> "vcvtss2usi"
    | Opcode.VCVTTPD2DQ -> "vcvttpd2dq"
    | Opcode.VCVTTPD2QQ -> "vcvttpd2qq"
    | Opcode.VCVTTPD2UDQ -> "vcvttpd2udq"
    | Opcode.VCVTTPD2UQQ -> "vcvttpd2uqq"
    | Opcode.VCVTTPH2DQ -> "vcvttph2dq"
    | Opcode.VCVTTPH2QQ -> "vcvttph2qq"
    | Opcode.VCVTTPH2UDQ -> "vcvttph2udq"
    | Opcode.VCVTTPH2UQQ -> "vcvttph2uqq"
    | Opcode.VCVTTPH2UW -> "vcvttph2uw"
    | Opcode.VCVTTPH2W -> "vcvttph2w"
    | Opcode.VCVTTPS2DQ -> "vcvttps2dq"
    | Opcode.VCVTTPS2QQ -> "vcvttps2qq"
    | Opcode.VCVTTPS2UDQ -> "vcvttps2udq"
    | Opcode.VCVTTPS2UQQ -> "vcvttps2uqq"
    | Opcode.VCVTTSD2SI -> "vcvttsd2si"
    | Opcode.VCVTTSD2USI -> "vcvttsd2usi"
    | Opcode.VCVTTSH2SI -> "vcvttsh2si"
    | Opcode.VCVTTSH2USI -> "vcvttsh2usi"
    | Opcode.VCVTTSS2SI -> "vcvttss2si"
    | Opcode.VCVTTSS2USI -> "vcvttss2usi"
    | Opcode.VCVTUDQ2PD -> "vcvtudq2pd"
    | Opcode.VCVTUDQ2PH -> "vcvtudq2ph"
    | Opcode.VCVTUDQ2PS -> "vcvtudq2ps"
    | Opcode.VCVTUQQ2PD -> "vcvtuqq2pd"
    | Opcode.VCVTUQQ2PH -> "vcvtuqq2ph"
    | Opcode.VCVTUQQ2PS -> "vcvtuqq2ps"
    | Opcode.VCVTUSI2SD -> "vcvtusi2sd"
    | Opcode.VCVTUSI2SH -> "vcvtusi2sh"
    | Opcode.VCVTUSI2SS -> "vcvtusi2ss"
    | Opcode.VCVTUW2PH -> "vcvtuw2ph"
    | Opcode.VCVTW2PH -> "vcvtw2ph"
    | Opcode.VDBPSADBW -> "vdbpsadbw"
    | Opcode.VDIVPD -> "vdivpd"
    | Opcode.VDIVPH -> "vdivph"
    | Opcode.VDIVPS -> "vdivps"
    | Opcode.VDIVSD -> "vdivsd"
    | Opcode.VDIVSH -> "vdivsh"
    | Opcode.VDIVSS -> "vdivss"
    | Opcode.VDPBF16PS -> "vdpbf16ps"
    | Opcode.VDPPD -> "vdppd"
    | Opcode.VDPPS -> "vdpps"
    | Opcode.VERR -> "verr"
    | Opcode.VERW -> "verw"
    | Opcode.VEXP2PD -> "vexp2pd"
    | Opcode.VEXP2PS -> "vexp2ps"
    | Opcode.VEXPANDPD -> "vexpandpd"
    | Opcode.VEXPANDPS -> "vexpandps"
    | Opcode.VEXTRACTF128 -> "vextractf128"
    | Opcode.VEXTRACTF32X4 -> "vextractf32x4"
    | Opcode.VEXTRACTF32X8 -> "vextractf32x8"
    | Opcode.VEXTRACTF64X2 -> "vextractf64x2"
    | Opcode.VEXTRACTF64X4 -> "vextractf64x4"
    | Opcode.VEXTRACTI128 -> "vextracti128"
    | Opcode.VEXTRACTI32X4 -> "vextracti32x4"
    | Opcode.VEXTRACTI32X8 -> "vextracti32x8"
    | Opcode.VEXTRACTI64X2 -> "vextracti64x2"
    | Opcode.VEXTRACTI64X4 -> "vextracti64x4"
    | Opcode.VEXTRACTPS -> "vextractps"
    | Opcode.VFCMADDCPH -> "vfcmaddcph"
    | Opcode.VFCMADDCSH -> "vfcmaddcsh"
    | Opcode.VFCMULCPH -> "vfcmulcph"
    | Opcode.VFCMULCSH -> "vfcmulcsh"
    | Opcode.VFIXUPIMMPD -> "vfixupimmpd"
    | Opcode.VFIXUPIMMPS -> "vfixupimmps"
    | Opcode.VFIXUPIMMSD -> "vfixupimmsd"
    | Opcode.VFIXUPIMMSS -> "vfixupimmss"
    | Opcode.VFMADD132PD -> "vfmadd132pd"
    | Opcode.VFMADD132PH -> "vfmadd132ph"
    | Opcode.VFMADD132PS -> "vfmadd132ps"
    | Opcode.VFMADD132SD -> "vfmadd132sd"
    | Opcode.VFMADD132SH -> "vfmadd132sh"
    | Opcode.VFMADD132SS -> "vfmadd132ss"
    | Opcode.VFMADD213PD -> "vfmadd213pd"
    | Opcode.VFMADD213PH -> "vfmadd213ph"
    | Opcode.VFMADD213PS -> "vfmadd213ps"
    | Opcode.VFMADD213SD -> "vfmadd213sd"
    | Opcode.VFMADD213SH -> "vfmadd213sh"
    | Opcode.VFMADD213SS -> "vfmadd213ss"
    | Opcode.VFMADD231PD -> "vfmadd231pd"
    | Opcode.VFMADD231PH -> "vfmadd231ph"
    | Opcode.VFMADD231PS -> "vfmadd231ps"
    | Opcode.VFMADD231SD -> "vfmadd231sd"
    | Opcode.VFMADD231SH -> "vfmadd231sh"
    | Opcode.VFMADD231SS -> "vfmadd231ss"
    | Opcode.VFMADDCPH -> "vfmaddcph"
    | Opcode.VFMADDCSH -> "vfmaddcsh"
    | Opcode.VFMADDSUB132PD -> "vfmaddsub132pd"
    | Opcode.VFMADDSUB132PH -> "vfmaddsub132ph"
    | Opcode.VFMADDSUB132PS -> "vfmaddsub132ps"
    | Opcode.VFMADDSUB213PD -> "vfmaddsub213pd"
    | Opcode.VFMADDSUB213PH -> "vfmaddsub213ph"
    | Opcode.VFMADDSUB213PS -> "vfmaddsub213ps"
    | Opcode.VFMADDSUB231PD -> "vfmaddsub231pd"
    | Opcode.VFMADDSUB231PH -> "vfmaddsub231ph"
    | Opcode.VFMADDSUB231PS -> "vfmaddsub231ps"
    | Opcode.VFMSUB132PD -> "vfmsub132pd"
    | Opcode.VFMSUB132PH -> "vfmsub132ph"
    | Opcode.VFMSUB132PS -> "vfmsub132ps"
    | Opcode.VFMSUB132SD -> "vfmsub132sd"
    | Opcode.VFMSUB132SH -> "vfmsub132sh"
    | Opcode.VFMSUB132SS -> "vfmsub132ss"
    | Opcode.VFMSUB213PD -> "vfmsub213pd"
    | Opcode.VFMSUB213PH -> "vfmsub213ph"
    | Opcode.VFMSUB213PS -> "vfmsub213ps"
    | Opcode.VFMSUB213SD -> "vfmsub213sd"
    | Opcode.VFMSUB213SH -> "vfmsub213sh"
    | Opcode.VFMSUB213SS -> "vfmsub213ss"
    | Opcode.VFMSUB231PD -> "vfmsub231pd"
    | Opcode.VFMSUB231PH -> "vfmsub231ph"
    | Opcode.VFMSUB231PS -> "vfmsub231ps"
    | Opcode.VFMSUB231SD -> "vfmsub231sd"
    | Opcode.VFMSUB231SH -> "vfmsub231sh"
    | Opcode.VFMSUB231SS -> "vfmsub231ss"
    | Opcode.VFMSUBADD132PD -> "vfmsubadd132pd"
    | Opcode.VFMSUBADD132PH -> "vfmsubadd132ph"
    | Opcode.VFMSUBADD132PS -> "vfmsubadd132ps"
    | Opcode.VFMSUBADD213PD -> "vfmsubadd213pd"
    | Opcode.VFMSUBADD213PH -> "vfmsubadd213ph"
    | Opcode.VFMSUBADD213PS -> "vfmsubadd213ps"
    | Opcode.VFMSUBADD231PD -> "vfmsubadd231pd"
    | Opcode.VFMSUBADD231PH -> "vfmsubadd231ph"
    | Opcode.VFMSUBADD231PS -> "vfmsubadd231ps"
    | Opcode.VFMULCPH -> "vfmulcph"
    | Opcode.VFMULCSH -> "vfmulcsh"
    | Opcode.VFNMADD132PD -> "vfnmadd132pd"
    | Opcode.VFNMADD132PH -> "vfnmadd132ph"
    | Opcode.VFNMADD132PS -> "vfnmadd132ps"
    | Opcode.VFNMADD132SD -> "vfnmadd132sd"
    | Opcode.VFNMADD132SH -> "vfnmadd132sh"
    | Opcode.VFNMADD132SS -> "vfnmadd132ss"
    | Opcode.VFNMADD213PD -> "vfnmadd213pd"
    | Opcode.VFNMADD213PH -> "vfnmadd213ph"
    | Opcode.VFNMADD213PS -> "vfnmadd213ps"
    | Opcode.VFNMADD213SD -> "vfnmadd213sd"
    | Opcode.VFNMADD213SH -> "vfnmadd213sh"
    | Opcode.VFNMADD213SS -> "vfnmadd213ss"
    | Opcode.VFNMADD231PD -> "vfnmadd231pd"
    | Opcode.VFNMADD231PH -> "vfnmadd231ph"
    | Opcode.VFNMADD231PS -> "vfnmadd231ps"
    | Opcode.VFNMADD231SD -> "vfnmadd231sd"
    | Opcode.VFNMADD231SH -> "vfnmadd231sh"
    | Opcode.VFNMADD231SS -> "vfnmadd231ss"
    | Opcode.VFNMSUB132PD -> "vfnmsub132pd"
    | Opcode.VFNMSUB132PH -> "vfnmsub132ph"
    | Opcode.VFNMSUB132PS -> "vfnmsub132ps"
    | Opcode.VFNMSUB132SD -> "vfnmsub132sd"
    | Opcode.VFNMSUB132SH -> "vfnmsub132sh"
    | Opcode.VFNMSUB132SS -> "vfnmsub132ss"
    | Opcode.VFNMSUB213PD -> "vfnmsub213pd"
    | Opcode.VFNMSUB213PH -> "vfnmsub213ph"
    | Opcode.VFNMSUB213PS -> "vfnmsub213ps"
    | Opcode.VFNMSUB213SD -> "vfnmsub213sd"
    | Opcode.VFNMSUB213SH -> "vfnmsub213sh"
    | Opcode.VFNMSUB213SS -> "vfnmsub213ss"
    | Opcode.VFNMSUB231PD -> "vfnmsub231pd"
    | Opcode.VFNMSUB231PH -> "vfnmsub231ph"
    | Opcode.VFNMSUB231PS -> "vfnmsub231ps"
    | Opcode.VFNMSUB231SD -> "vfnmsub231sd"
    | Opcode.VFNMSUB231SH -> "vfnmsub231sh"
    | Opcode.VFNMSUB231SS -> "vfnmsub231ss"
    | Opcode.VFPCLASSPD -> "vfpclasspd"
    | Opcode.VFPCLASSPH -> "vfpclassph"
    | Opcode.VFPCLASSPS -> "vfpclassps"
    | Opcode.VFPCLASSSD -> "vfpclasssd"
    | Opcode.VFPCLASSSH -> "vfpclasssh"
    | Opcode.VFPCLASSSS -> "vfpclassss"
    | Opcode.VGATHERDPD -> "vgatherdpd"
    | Opcode.VGATHERDPS -> "vgatherdps"
    | Opcode.VGATHERPF0DPD -> "vgatherpf0dpd"
    | Opcode.VGATHERPF0DPS -> "vgatherpf0dps"
    | Opcode.VGATHERPF0QPD -> "vgatherpf0qpd"
    | Opcode.VGATHERPF0QPS -> "vgatherpf0qps"
    | Opcode.VGATHERPF1DPD -> "vgatherpf1dpd"
    | Opcode.VGATHERPF1DPS -> "vgatherpf1dps"
    | Opcode.VGATHERPF1QPD -> "vgatherpf1qpd"
    | Opcode.VGATHERPF1QPS -> "vgatherpf1qps"
    | Opcode.VGATHERQPD -> "vgatherqpd"
    | Opcode.VGATHERQPS -> "vgatherqps"
    | Opcode.VGETEXPPD -> "vgetexppd"
    | Opcode.VGETEXPPH -> "vgetexpph"
    | Opcode.VGETEXPPS -> "vgetexpps"
    | Opcode.VGETEXPSD -> "vgetexpsd"
    | Opcode.VGETEXPSH -> "vgetexpsh"
    | Opcode.VGETEXPSS -> "vgetexpss"
    | Opcode.VGETMANTPD -> "vgetmantpd"
    | Opcode.VGETMANTPH -> "vgetmantph"
    | Opcode.VGETMANTPS -> "vgetmantps"
    | Opcode.VGETMANTSD -> "vgetmantsd"
    | Opcode.VGETMANTSH -> "vgetmantsh"
    | Opcode.VGETMANTSS -> "vgetmantss"
    | Opcode.VGF2P8AFFINEINVQB -> "vgf2p8affineinvqb"
    | Opcode.VGF2P8AFFINEQB -> "vgf2p8affineqb"
    | Opcode.VGF2P8MULB -> "vgf2p8mulb"
    | Opcode.VHADDPD -> "vhaddpd"
    | Opcode.VHADDPS -> "vhaddps"
    | Opcode.VHSUBPD -> "vhsubpd"
    | Opcode.VHSUBPS -> "vhsubps"
    | Opcode.VINSERTF128 -> "vinsertf128"
    | Opcode.VINSERTF32X4 -> "vinsertf32x4"
    | Opcode.VINSERTF32X8 -> "vinsertf32x8"
    | Opcode.VINSERTF64X2 -> "vinsertf64x2"
    | Opcode.VINSERTF64X4 -> "vinsertf64x4"
    | Opcode.VINSERTI128 -> "vinserti128"
    | Opcode.VINSERTI32X4 -> "vinserti32x4"
    | Opcode.VINSERTI32X8 -> "vinserti32x8"
    | Opcode.VINSERTI64X2 -> "vinserti64x2"
    | Opcode.VINSERTI64X4 -> "vinserti64x4"
    | Opcode.VINSERTPS -> "vinsertps"
    | Opcode.VLDDQU -> "vlddqu"
    | Opcode.VLDMXCSR -> "vldmxcsr"
    | Opcode.VMASKMOVDQU -> "vmaskmovdqu"
    | Opcode.VMASKMOVPD -> "vmaskmovpd"
    | Opcode.VMASKMOVPS -> "vmaskmovps"
    | Opcode.VMAXPD -> "vmaxpd"
    | Opcode.VMAXPH -> "vmaxph"
    | Opcode.VMAXPS -> "vmaxps"
    | Opcode.VMAXSD -> "vmaxsd"
    | Opcode.VMAXSH -> "vmaxsh"
    | Opcode.VMAXSS -> "vmaxss"
    | Opcode.VMINPD -> "vminpd"
    | Opcode.VMINPH -> "vminph"
    | Opcode.VMINPS -> "vminps"
    | Opcode.VMINSD -> "vminsd"
    | Opcode.VMINSH -> "vminsh"
    | Opcode.VMINSS -> "vminss"
    | Opcode.VMOVAPD -> "vmovapd"
    | Opcode.VMOVAPS -> "vmovaps"
    | Opcode.VMOVD -> "vmovd"
    | Opcode.VMOVDDUP -> "vmovddup"
    | Opcode.VMOVDQA -> "vmovdqa"
    | Opcode.VMOVDQA32 -> "vmovdqa32"
    | Opcode.VMOVDQA64 -> "vmovdqa64"
    | Opcode.VMOVDQU -> "vmovdqu"
    | Opcode.VMOVDQU16 -> "vmovdqu16"
    | Opcode.VMOVDQU32 -> "vmovdqu32"
    | Opcode.VMOVDQU64 -> "vmovdqu64"
    | Opcode.VMOVDQU8 -> "vmovdqu8"
    | Opcode.VMOVHLPS -> "vmovhlps"
    | Opcode.VMOVHPD -> "vmovhpd"
    | Opcode.VMOVHPS -> "vmovhps"
    | Opcode.VMOVLHPS -> "vmovlhps"
    | Opcode.VMOVLPD -> "vmovlpd"
    | Opcode.VMOVLPS -> "vmovlps"
    | Opcode.VMOVMSKPD -> "vmovmskpd"
    | Opcode.VMOVMSKPS -> "vmovmskps"
    | Opcode.VMOVNTDQ -> "vmovntdq"
    | Opcode.VMOVNTDQA -> "vmovntdqa"
    | Opcode.VMOVNTPD -> "vmovntpd"
    | Opcode.VMOVNTPS -> "vmovntps"
    | Opcode.VMOVQ -> "vmovq"
    | Opcode.VMOVSD -> "vmovsd"
    | Opcode.VMOVSH -> "vmovsh"
    | Opcode.VMOVSHDUP -> "vmovshdup"
    | Opcode.VMOVSLDUP -> "vmovsldup"
    | Opcode.VMOVSS -> "vmovss"
    | Opcode.VMOVUPD -> "vmovupd"
    | Opcode.VMOVUPS -> "vmovups"
    | Opcode.VMOVW -> "vmovw"
    | Opcode.VMPSADBW -> "vmpsadbw"
    | Opcode.VMULPD -> "vmulpd"
    | Opcode.VMULPH -> "vmulph"
    | Opcode.VMULPS -> "vmulps"
    | Opcode.VMULSD -> "vmulsd"
    | Opcode.VMULSH -> "vmulsh"
    | Opcode.VMULSS -> "vmulss"
    | Opcode.VORPD -> "vorpd"
    | Opcode.VORPS -> "vorps"
    | Opcode.VP2INTERSECTD -> "vp2intersectd"
    | Opcode.VP2INTERSECTQ -> "vp2intersectq"
    | Opcode.VP4DPWSSD -> "vp4dpwssd"
    | Opcode.VP4DPWSSDS -> "vp4dpwssds"
    | Opcode.VPABSB -> "vpabsb"
    | Opcode.VPABSD -> "vpabsd"
    | Opcode.VPABSQ -> "vpabsq"
    | Opcode.VPABSW -> "vpabsw"
    | Opcode.VPACKSSDW -> "vpackssdw"
    | Opcode.VPACKSSWB -> "vpacksswb"
    | Opcode.VPACKUSDW -> "vpackusdw"
    | Opcode.VPACKUSWB -> "vpackuswb"
    | Opcode.VPADDB -> "vpaddb"
    | Opcode.VPADDD -> "vpaddd"
    | Opcode.VPADDQ -> "vpaddq"
    | Opcode.VPADDSB -> "vpaddsb"
    | Opcode.VPADDSW -> "vpaddsw"
    | Opcode.VPADDUSB -> "vpaddusb"
    | Opcode.VPADDUSW -> "vpaddusw"
    | Opcode.VPADDW -> "vpaddw"
    | Opcode.VPALIGNR -> "vpalignr"
    | Opcode.VPAND -> "vpand"
    | Opcode.VPANDD -> "vpandd"
    | Opcode.VPANDN -> "vpandn"
    | Opcode.VPANDND -> "vpandnd"
    | Opcode.VPANDNQ -> "vpandnq"
    | Opcode.VPANDQ -> "vpandq"
    | Opcode.VPAVGB -> "vpavgb"
    | Opcode.VPAVGW -> "vpavgw"
    | Opcode.VPBLENDD -> "vpblendd"
    | Opcode.VPBLENDMB -> "vpblendmb"
    | Opcode.VPBLENDMD -> "vpblendmd"
    | Opcode.VPBLENDMQ -> "vpblendmq"
    | Opcode.VPBLENDMW -> "vpblendmw"
    | Opcode.VPBLENDVB -> "vpblendvb"
    | Opcode.VPBLENDW -> "vpblendw"
    | Opcode.VPBROADCASTB -> "vpbroadcastb"
    | Opcode.VPBROADCASTD -> "vpbroadcastd"
    | Opcode.VPBROADCASTMB2Q -> "vpbroadcastmb2q"
    | Opcode.VPBROADCASTMW2D -> "vpbroadcastmw2d"
    | Opcode.VPBROADCASTQ -> "vpbroadcastq"
    | Opcode.VPBROADCASTW -> "vpbroadcastw"
    | Opcode.VPCLMULQDQ -> "vpclmulqdq"
    | Opcode.VPCMPB -> "vpcmpb"
    | Opcode.VPCMPD -> "vpcmpd"
    | Opcode.VPCMPEQB -> "vpcmpeqb"
    | Opcode.VPCMPEQD -> "vpcmpeqd"
    | Opcode.VPCMPEQQ -> "vpcmpeqq"
    | Opcode.VPCMPEQW -> "vpcmpeqw"
    | Opcode.VPCMPESTRI -> "vpcmpestri"
    | Opcode.VPCMPESTRM -> "vpcmpestrm"
    | Opcode.VPCMPGTB -> "vpcmpgtb"
    | Opcode.VPCMPGTD -> "vpcmpgtd"
    | Opcode.VPCMPGTQ -> "vpcmpgtq"
    | Opcode.VPCMPGTW -> "vpcmpgtw"
    | Opcode.VPCMPISTRI -> "vpcmpistri"
    | Opcode.VPCMPISTRM -> "vpcmpistrm"
    | Opcode.VPCMPQ -> "vpcmpq"
    | Opcode.VPCMPUB -> "vpcmpub"
    | Opcode.VPCMPUD -> "vpcmpud"
    | Opcode.VPCMPUQ -> "vpcmpuq"
    | Opcode.VPCMPUW -> "vpcmpuw"
    | Opcode.VPCMPW -> "vpcmpw"
    | Opcode.VPCOMPRESSB -> "vpcompressb"
    | Opcode.VPCOMPRESSD -> "vpcompressd"
    | Opcode.VPCOMPRESSQ -> "vpcompressq"
    | Opcode.VPCOMPRESSW -> "vpcompressw"
    | Opcode.VPCONFLICTD -> "vpconflictd"
    | Opcode.VPCONFLICTQ -> "vpconflictq"
    | Opcode.VPDPBSSD -> "vpdpbssd"
    | Opcode.VPDPBSSDS -> "vpdpbssds"
    | Opcode.VPDPBSUD -> "vpdpbsud"
    | Opcode.VPDPBSUDS -> "vpdpbsuds"
    | Opcode.VPDPBUSD -> "vpdpbusd"
    | Opcode.VPDPBUSDS -> "vpdpbusds"
    | Opcode.VPDPBUUD -> "vpdpbuud"
    | Opcode.VPDPBUUDS -> "vpdpbuuds"
    | Opcode.VPDPWSSD -> "vpdpwssd"
    | Opcode.VPDPWSSDS -> "vpdpwssds"
    | Opcode.VPDPWSUD -> "vpdpwsud"
    | Opcode.VPDPWSUDS -> "vpdpwsuds"
    | Opcode.VPDPWUSD -> "vpdpwusd"
    | Opcode.VPDPWUSDS -> "vpdpwusds"
    | Opcode.VPDPWUUD -> "vpdpwuud"
    | Opcode.VPDPWUUDS -> "vpdpwuuds"
    | Opcode.VPERM2F128 -> "vperm2f128"
    | Opcode.VPERM2I128 -> "vperm2i128"
    | Opcode.VPERMB -> "vpermb"
    | Opcode.VPERMD -> "vpermd"
    | Opcode.VPERMI2B -> "vpermi2b"
    | Opcode.VPERMI2D -> "vpermi2d"
    | Opcode.VPERMI2PD -> "vpermi2pd"
    | Opcode.VPERMI2PS -> "vpermi2ps"
    | Opcode.VPERMI2Q -> "vpermi2q"
    | Opcode.VPERMI2W -> "vpermi2w"
    | Opcode.VPERMILPD -> "vpermilpd"
    | Opcode.VPERMILPS -> "vpermilps"
    | Opcode.VPERMPD -> "vpermpd"
    | Opcode.VPERMPS -> "vpermps"
    | Opcode.VPERMQ -> "vpermq"
    | Opcode.VPERMT2B -> "vpermt2b"
    | Opcode.VPERMT2D -> "vpermt2d"
    | Opcode.VPERMT2PD -> "vpermt2pd"
    | Opcode.VPERMT2PS -> "vpermt2ps"
    | Opcode.VPERMT2Q -> "vpermt2q"
    | Opcode.VPERMT2W -> "vpermt2w"
    | Opcode.VPERMW -> "vpermw"
    | Opcode.VPEXPANDB -> "vpexpandb"
    | Opcode.VPEXPANDD -> "vpexpandd"
    | Opcode.VPEXPANDQ -> "vpexpandq"
    | Opcode.VPEXPANDW -> "vpexpandw"
    | Opcode.VPEXTRB -> "vpextrb"
    | Opcode.VPEXTRD -> "vpextrd"
    | Opcode.VPEXTRQ -> "vpextrq"
    | Opcode.VPEXTRW -> "vpextrw"
    | Opcode.VPGATHERDD -> "vpgatherdd"
    | Opcode.VPGATHERDQ -> "vpgatherdq"
    | Opcode.VPGATHERQD -> "vpgatherqd"
    | Opcode.VPGATHERQQ -> "vpgatherqq"
    | Opcode.VPHADDD -> "vphaddd"
    | Opcode.VPHADDSW -> "vphaddsw"
    | Opcode.VPHADDW -> "vphaddw"
    | Opcode.VPHMINPOSUW -> "vphminposuw"
    | Opcode.VPHSUBD -> "vphsubd"
    | Opcode.VPHSUBSW -> "vphsubsw"
    | Opcode.VPHSUBW -> "vphsubw"
    | Opcode.VPINSRB -> "vpinsrb"
    | Opcode.VPINSRD -> "vpinsrd"
    | Opcode.VPINSRQ -> "vpinsrq"
    | Opcode.VPINSRW -> "vpinsrw"
    | Opcode.VPLZCNTD -> "vplzcntd"
    | Opcode.VPLZCNTQ -> "vplzcntq"
    | Opcode.VPMADD52HUQ -> "vpmadd52huq"
    | Opcode.VPMADD52LUQ -> "vpmadd52luq"
    | Opcode.VPMADDUBSW -> "vpmaddubsw"
    | Opcode.VPMADDWD -> "vpmaddwd"
    | Opcode.VPMASKMOVD -> "vpmaskmovd"
    | Opcode.VPMASKMOVQ -> "vpmaskmovq"
    | Opcode.VPMAXSB -> "vpmaxsb"
    | Opcode.VPMAXSD -> "vpmaxsd"
    | Opcode.VPMAXSQ -> "vpmaxsq"
    | Opcode.VPMAXSW -> "vpmaxsw"
    | Opcode.VPMAXUB -> "vpmaxub"
    | Opcode.VPMAXUD -> "vpmaxud"
    | Opcode.VPMAXUQ -> "vpmaxuq"
    | Opcode.VPMAXUW -> "vpmaxuw"
    | Opcode.VPMINSB -> "vpminsb"
    | Opcode.VPMINSD -> "vpminsd"
    | Opcode.VPMINSQ -> "vpminsq"
    | Opcode.VPMINSW -> "vpminsw"
    | Opcode.VPMINUB -> "vpminub"
    | Opcode.VPMINUD -> "vpminud"
    | Opcode.VPMINUQ -> "vpminuq"
    | Opcode.VPMINUW -> "vpminuw"
    | Opcode.VPMOVB2M -> "vpmovb2m"
    | Opcode.VPMOVD2M -> "vpmovd2m"
    | Opcode.VPMOVDB -> "vpmovdb"
    | Opcode.VPMOVDW -> "vpmovdw"
    | Opcode.VPMOVM2B -> "vpmovm2b"
    | Opcode.VPMOVM2D -> "vpmovm2d"
    | Opcode.VPMOVM2Q -> "vpmovm2q"
    | Opcode.VPMOVM2W -> "vpmovm2w"
    | Opcode.VPMOVMSKB -> "vpmovmskb"
    | Opcode.VPMOVQ2M -> "vpmovq2m"
    | Opcode.VPMOVQB -> "vpmovqb"
    | Opcode.VPMOVQD -> "vpmovqd"
    | Opcode.VPMOVQW -> "vpmovqw"
    | Opcode.VPMOVSDB -> "vpmovsdb"
    | Opcode.VPMOVSDW -> "vpmovsdw"
    | Opcode.VPMOVSQB -> "vpmovsqb"
    | Opcode.VPMOVSQD -> "vpmovsqd"
    | Opcode.VPMOVSQW -> "vpmovsqw"
    | Opcode.VPMOVSWB -> "vpmovswb"
    | Opcode.VPMOVSXBD -> "vpmovsxbd"
    | Opcode.VPMOVSXBQ -> "vpmovsxbq"
    | Opcode.VPMOVSXBW -> "vpmovsxbw"
    | Opcode.VPMOVSXDQ -> "vpmovsxdq"
    | Opcode.VPMOVSXWD -> "vpmovsxwd"
    | Opcode.VPMOVSXWQ -> "vpmovsxwq"
    | Opcode.VPMOVUSDB -> "vpmovusdb"
    | Opcode.VPMOVUSDW -> "vpmovusdw"
    | Opcode.VPMOVUSQB -> "vpmovusqb"
    | Opcode.VPMOVUSQD -> "vpmovusqd"
    | Opcode.VPMOVUSQW -> "vpmovusqw"
    | Opcode.VPMOVUSWB -> "vpmovuswb"
    | Opcode.VPMOVW2M -> "vpmovw2m"
    | Opcode.VPMOVWB -> "vpmovwb"
    | Opcode.VPMOVZXBD -> "vpmovzxbd"
    | Opcode.VPMOVZXBQ -> "vpmovzxbq"
    | Opcode.VPMOVZXBW -> "vpmovzxbw"
    | Opcode.VPMOVZXDQ -> "vpmovzxdq"
    | Opcode.VPMOVZXWD -> "vpmovzxwd"
    | Opcode.VPMOVZXWQ -> "vpmovzxwq"
    | Opcode.VPMULDQ -> "vpmuldq"
    | Opcode.VPMULHRSW -> "vpmulhrsw"
    | Opcode.VPMULHUW -> "vpmulhuw"
    | Opcode.VPMULHW -> "vpmulhw"
    | Opcode.VPMULLD -> "vpmulld"
    | Opcode.VPMULLQ -> "vpmullq"
    | Opcode.VPMULLW -> "vpmullw"
    | Opcode.VPMULTISHIFTQB -> "vpmultishiftqb"
    | Opcode.VPMULUDQ -> "vpmuludq"
    | Opcode.VPOPCNTB -> "vpopcntb"
    | Opcode.VPOPCNTD -> "vpopcntd"
    | Opcode.VPOPCNTQ -> "vpopcntq"
    | Opcode.VPOPCNTW -> "vpopcntw"
    | Opcode.VPOR -> "vpor"
    | Opcode.VPORD -> "vpord"
    | Opcode.VPORQ -> "vporq"
    | Opcode.VPROLD -> "vprold"
    | Opcode.VPROLQ -> "vprolq"
    | Opcode.VPROLVD -> "vprolvd"
    | Opcode.VPROLVQ -> "vprolvq"
    | Opcode.VPRORD -> "vprord"
    | Opcode.VPRORQ -> "vprorq"
    | Opcode.VPRORVD -> "vprorvd"
    | Opcode.VPRORVQ -> "vprorvq"
    | Opcode.VPSADBW -> "vpsadbw"
    | Opcode.VPSCATTERDD -> "vpscatterdd"
    | Opcode.VPSCATTERDQ -> "vpscatterdq"
    | Opcode.VPSCATTERQD -> "vpscatterqd"
    | Opcode.VPSCATTERQQ -> "vpscatterqq"
    | Opcode.VPSHLDD -> "vpshldd"
    | Opcode.VPSHLDQ -> "vpshldq"
    | Opcode.VPSHLDVD -> "vpshldvd"
    | Opcode.VPSHLDVQ -> "vpshldvq"
    | Opcode.VPSHLDVW -> "vpshldvw"
    | Opcode.VPSHLDW -> "vpshldw"
    | Opcode.VPSHRDD -> "vpshrdd"
    | Opcode.VPSHRDQ -> "vpshrdq"
    | Opcode.VPSHRDVD -> "vpshrdvd"
    | Opcode.VPSHRDVQ -> "vpshrdvq"
    | Opcode.VPSHRDVW -> "vpshrdvw"
    | Opcode.VPSHRDW -> "vpshrdw"
    | Opcode.VPSHUFB -> "vpshufb"
    | Opcode.VPSHUFBITQMB -> "vpshufbitqmb"
    | Opcode.VPSHUFD -> "vpshufd"
    | Opcode.VPSHUFHW -> "vpshufhw"
    | Opcode.VPSHUFLW -> "vpshuflw"
    | Opcode.VPSIGNB -> "vpsignb"
    | Opcode.VPSIGND -> "vpsignd"
    | Opcode.VPSIGNW -> "vpsignw"
    | Opcode.VPSLLD -> "vpslld"
    | Opcode.VPSLLDQ -> "vpslldq"
    | Opcode.VPSLLQ -> "vpsllq"
    | Opcode.VPSLLVD -> "vpsllvd"
    | Opcode.VPSLLVQ -> "vpsllvq"
    | Opcode.VPSLLVW -> "vpsllvw"
    | Opcode.VPSLLW -> "vpsllw"
    | Opcode.VPSRAD -> "vpsrad"
    | Opcode.VPSRAQ -> "vpsraq"
    | Opcode.VPSRAVD -> "vpsravd"
    | Opcode.VPSRAVQ -> "vpsravq"
    | Opcode.VPSRAVW -> "vpsravw"
    | Opcode.VPSRAW -> "vpsraw"
    | Opcode.VPSRLD -> "vpsrld"
    | Opcode.VPSRLDQ -> "vpsrldq"
    | Opcode.VPSRLQ -> "vpsrlq"
    | Opcode.VPSRLVD -> "vpsrlvd"
    | Opcode.VPSRLVQ -> "vpsrlvq"
    | Opcode.VPSRLVW -> "vpsrlvw"
    | Opcode.VPSRLW -> "vpsrlw"
    | Opcode.VPSUBB -> "vpsubb"
    | Opcode.VPSUBD -> "vpsubd"
    | Opcode.VPSUBQ -> "vpsubq"
    | Opcode.VPSUBSB -> "vpsubsb"
    | Opcode.VPSUBSW -> "vpsubsw"
    | Opcode.VPSUBUSB -> "vpsubusb"
    | Opcode.VPSUBUSW -> "vpsubusw"
    | Opcode.VPSUBW -> "vpsubw"
    | Opcode.VPTERNLOGD -> "vpternlogd"
    | Opcode.VPTERNLOGQ -> "vpternlogq"
    | Opcode.VPTEST -> "vptest"
    | Opcode.VPTESTMB -> "vptestmb"
    | Opcode.VPTESTMD -> "vptestmd"
    | Opcode.VPTESTMQ -> "vptestmq"
    | Opcode.VPTESTMW -> "vptestmw"
    | Opcode.VPTESTNMB -> "vptestnmb"
    | Opcode.VPTESTNMD -> "vptestnmd"
    | Opcode.VPTESTNMQ -> "vptestnmq"
    | Opcode.VPTESTNMW -> "vptestnmw"
    | Opcode.VPUNPCKHBW -> "vpunpckhbw"
    | Opcode.VPUNPCKHDQ -> "vpunpckhdq"
    | Opcode.VPUNPCKHQDQ -> "vpunpckhqdq"
    | Opcode.VPUNPCKHWD -> "vpunpckhwd"
    | Opcode.VPUNPCKLBW -> "vpunpcklbw"
    | Opcode.VPUNPCKLDQ -> "vpunpckldq"
    | Opcode.VPUNPCKLQDQ -> "vpunpcklqdq"
    | Opcode.VPUNPCKLWD -> "vpunpcklwd"
    | Opcode.VPXOR -> "vpxor"
    | Opcode.VPXORD -> "vpxord"
    | Opcode.VPXORQ -> "vpxorq"
    | Opcode.VRANGEPD -> "vrangepd"
    | Opcode.VRANGEPS -> "vrangeps"
    | Opcode.VRANGESD -> "vrangesd"
    | Opcode.VRANGESS -> "vrangess"
    | Opcode.VRCP14PD -> "vrcp14pd"
    | Opcode.VRCP14PS -> "vrcp14ps"
    | Opcode.VRCP14SD -> "vrcp14sd"
    | Opcode.VRCP14SS -> "vrcp14ss"
    | Opcode.VRCP28PD -> "vrcp28pd"
    | Opcode.VRCP28PS -> "vrcp28ps"
    | Opcode.VRCP28SD -> "vrcp28sd"
    | Opcode.VRCP28SS -> "vrcp28ss"
    | Opcode.VRCPPH -> "vrcpph"
    | Opcode.VRCPPS -> "vrcpps"
    | Opcode.VRCPSH -> "vrcpsh"
    | Opcode.VRCPSS -> "vrcpss"
    | Opcode.VREDUCEPD -> "vreducepd"
    | Opcode.VREDUCEPH -> "vreduceph"
    | Opcode.VREDUCEPS -> "vreduceps"
    | Opcode.VREDUCESD -> "vreducesd"
    | Opcode.VREDUCESH -> "vreducesh"
    | Opcode.VREDUCESS -> "vreducess"
    | Opcode.VRNDSCALEPD -> "vrndscalepd"
    | Opcode.VRNDSCALEPH -> "vrndscaleph"
    | Opcode.VRNDSCALEPS -> "vrndscaleps"
    | Opcode.VRNDSCALESD -> "vrndscalesd"
    | Opcode.VRNDSCALESH -> "vrndscalesh"
    | Opcode.VRNDSCALESS -> "vrndscaless"
    | Opcode.VROUNDPD -> "vroundpd"
    | Opcode.VROUNDPS -> "vroundps"
    | Opcode.VROUNDSD -> "vroundsd"
    | Opcode.VROUNDSS -> "vroundss"
    | Opcode.VRSQRT14PD -> "vrsqrt14pd"
    | Opcode.VRSQRT14PS -> "vrsqrt14ps"
    | Opcode.VRSQRT14SD -> "vrsqrt14sd"
    | Opcode.VRSQRT14SS -> "vrsqrt14ss"
    | Opcode.VRSQRT28PD -> "vrsqrt28pd"
    | Opcode.VRSQRT28PS -> "vrsqrt28ps"
    | Opcode.VRSQRT28SD -> "vrsqrt28sd"
    | Opcode.VRSQRT28SS -> "vrsqrt28ss"
    | Opcode.VRSQRTPH -> "vrsqrtph"
    | Opcode.VRSQRTPS -> "vrsqrtps"
    | Opcode.VRSQRTSH -> "vrsqrtsh"
    | Opcode.VRSQRTSS -> "vrsqrtss"
    | Opcode.VSCALEFPD -> "vscalefpd"
    | Opcode.VSCALEFPH -> "vscalefph"
    | Opcode.VSCALEFPS -> "vscalefps"
    | Opcode.VSCALEFSD -> "vscalefsd"
    | Opcode.VSCALEFSH -> "vscalefsh"
    | Opcode.VSCALEFSS -> "vscalefss"
    | Opcode.VSCATTERDPD -> "vscatterdpd"
    | Opcode.VSCATTERDPS -> "vscatterdps"
    | Opcode.VSCATTERPF0DPD -> "vscatterpf0dpd"
    | Opcode.VSCATTERPF0DPS -> "vscatterpf0dps"
    | Opcode.VSCATTERPF0QPD -> "vscatterpf0qpd"
    | Opcode.VSCATTERPF0QPS -> "vscatterpf0qps"
    | Opcode.VSCATTERPF1DPD -> "vscatterpf1dpd"
    | Opcode.VSCATTERPF1DPS -> "vscatterpf1dps"
    | Opcode.VSCATTERPF1QPD -> "vscatterpf1qpd"
    | Opcode.VSCATTERPF1QPS -> "vscatterpf1qps"
    | Opcode.VSCATTERQPD -> "vscatterqpd"
    | Opcode.VSCATTERQPS -> "vscatterqps"
    | Opcode.VSHA512MSG1 -> "vsha512msg1"
    | Opcode.VSHA512MSG2 -> "vsha512msg2"
    | Opcode.VSHA512RNDS2 -> "vsha512rnds2"
    | Opcode.VSHUFF32X4 -> "vshuff32x4"
    | Opcode.VSHUFF64X2 -> "vshuff64x2"
    | Opcode.VSHUFI32X4 -> "vshufi32x4"
    | Opcode.VSHUFI64X2 -> "vshufi64x2"
    | Opcode.VSHUFPD -> "vshufpd"
    | Opcode.VSHUFPS -> "vshufps"
    | Opcode.VSM3MSG1 -> "vsm3msg1"
    | Opcode.VSM3MSG2 -> "vsm3msg2"
    | Opcode.VSM3RNDS2 -> "vsm3rnds2"
    | Opcode.VSM4KEY4 -> "vsm4key4"
    | Opcode.VSM4RNDS4 -> "vsm4rnds4"
    | Opcode.VSQRTPD -> "vsqrtpd"
    | Opcode.VSQRTPH -> "vsqrtph"
    | Opcode.VSQRTPS -> "vsqrtps"
    | Opcode.VSQRTSD -> "vsqrtsd"
    | Opcode.VSQRTSH -> "vsqrtsh"
    | Opcode.VSQRTSS -> "vsqrtss"
    | Opcode.VSTMXCSR -> "vstmxcsr"
    | Opcode.VSUBPD -> "vsubpd"
    | Opcode.VSUBPH -> "vsubph"
    | Opcode.VSUBPS -> "vsubps"
    | Opcode.VSUBSD -> "vsubsd"
    | Opcode.VSUBSH -> "vsubsh"
    | Opcode.VSUBSS -> "vsubss"
    | Opcode.VTESTPD -> "vtestpd"
    | Opcode.VTESTPS -> "vtestps"
    | Opcode.VUCOMISD -> "vucomisd"
    | Opcode.VUCOMISH -> "vucomish"
    | Opcode.VUCOMISS -> "vucomiss"
    | Opcode.VUNPCKHPD -> "vunpckhpd"
    | Opcode.VUNPCKHPS -> "vunpckhps"
    | Opcode.VUNPCKLPD -> "vunpcklpd"
    | Opcode.VUNPCKLPS -> "vunpcklps"
    | Opcode.VXORPD -> "vxorpd"
    | Opcode.VXORPS -> "vxorps"
    | Opcode.VZEROALL -> "vzeroall"
    | Opcode.VZEROUPPER -> "vzeroupper"
    | Opcode.WAIT -> "wait"
    | Opcode.WBINVD -> "wbinvd"
    | Opcode.WBNOINVD -> "wbnoinvd"
    | Opcode.WRFSBASE -> "wrfsbase"
    | Opcode.WRGSBASE -> "wrgsbase"
    | Opcode.WRMSR -> "wrmsr"
    | Opcode.WRMSRLIST -> "wrmsrlist"
    | Opcode.WRMSRNS -> "wrmsrns"
    | Opcode.WRPKRU -> "wrpkru"
    | Opcode.WRSSD -> "wrssd"
    | Opcode.WRSSQ -> "wrssq"
    | Opcode.WRUSSD -> "wrussd"
    | Opcode.WRUSSQ -> "wrussq"
    | Opcode.XABORT -> "xabort"
    | Opcode.XACQUIRE -> "xacquire"
    | Opcode.XADD -> "xadd"
    | Opcode.XBEGIN -> "xbegin"
    | Opcode.XCHG -> "xchg"
    | Opcode.XEND -> "xend"
    | Opcode.XGETBV -> "xgetbv"
    | Opcode.XLAT -> "xlat"
    | Opcode.XLATB -> "xlatb"
    | Opcode.XOR -> "xor"
    | Opcode.XORPD -> "xorpd"
    | Opcode.XORPS -> "xorps"
    | Opcode.XRELEASE -> "xrelease"
    | Opcode.XRESLDTRK -> "xresldtrk"
    | Opcode.XRSTOR -> "xrstor"
    | Opcode.XRSTOR64 -> "xrstor64"
    | Opcode.XRSTORS -> "xrstors"
    | Opcode.XRSTORS64 -> "xrstors64"
    | Opcode.XSAVE -> "xsave"
    | Opcode.XSAVE64 -> "xsave64"
    | Opcode.XSAVEC -> "xsavec"
    | Opcode.XSAVEC64 -> "xsavec64"
    | Opcode.XSAVEOPT -> "xsaveopt"
    | Opcode.XSAVEOPT64 -> "xsaveopt64"
    | Opcode.XSAVES -> "xsaves"
    | Opcode.XSAVES64 -> "xsaves64"
    | Opcode.XSETBV -> "xsetbv"
    | Opcode.XSUSLDTRK -> "xsusldtrk"
    | Opcode.XTEST -> "xtest"
    | Opcode.FFREEP -> "ffreep"
    | Opcode.VMREAD -> "vmread"
    | Opcode.EXTRQ -> "extrq"
    | Opcode.INSERTQ -> "insertq"
    | Opcode.VFMADDPS -> "vfmaddps"
    | Opcode.VFMADDPD -> "vfmaddpd"
    | Opcode.VFMADDSS -> "vfmaddss"
    | Opcode.VFMADDSD -> "vfmaddsd"
    | Opcode.VMCALL -> "vmcall"
    | Opcode.VMLAUNCH -> "vmlaunch"
    | Opcode.VMRESUME -> "vmresume"
    | Opcode.VMXOFF -> "vmxoff"
    | Opcode.VMFUNC -> "vmfunc"
    | Opcode.VMPTRLD -> "vmptrld"
    | Opcode.VMPTRST -> "vmptrst"
    | Opcode.VMCLEAR -> "vmclear"
    | Opcode.VMXON -> "vmxon"
    | Opcode.JMPFar -> "jmp"
    | Opcode.JMPNear -> "jmp"
    | Opcode.CALLFar -> "call"
    | Opcode.CALLNear -> "call"
    | Opcode.RETFar -> "ret"
    | Opcode.RETFarImm -> "ret"
    | Opcode.RETNear -> "ret"
    | Opcode.RETNearImm -> "ret"
    | Opcode.InvalOP -> "(InvalOp)"
    | s -> printfn "%A" s; failwith "InvalidOpcodeException"
