(*
  B2R2 - the Next-Generation Reversing Platform

  Copyright (c) SoftSec Lab. @ KAIST, since 2016

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*)

namespace B2R2.BinIR

open B2R2

/// Represents a side effect that can be generated by an instruction.
type SideEffect =
  /// Software breakpoint.
  | Breakpoint
  /// Memory fence operations, e.g., LFENCE/MFENCE/SFENCE on x86.
  | Fence
  /// Delay the execution for a while, e.g. PAUSE on x86.
  | Delay
  /// Terminate the execution, e.g., HLT on x86.
  | Terminate
  /// System call.
  | SysCall
  /// Trap into a handler identified by a vector number. Covers explicit
  /// software trap instructions (e.g. INT on x86, SVC on ARM, TRAPA on SH4)
  /// as well as asynchronous hardware interrupts.
  | Interrupt of int
  /// A synchronous CPU exception raised during execution.
  | Exception of ExceptionKind
  /// Marks the start of a sequence of IR statements that must be evaluated
  /// atomically, e.g., an x86 LOCK-prefixed instruction.
  | AtomicBegin
  /// Marks the end of an atomic sequence of IR statements. See `AtomicBegin`.
  | AtomicEnd
  /// CPU clock access, e.g., RDTSC on x86. The payload names the destination
  /// the lifter leaves to the emulator: None when the architecture writes fixed
  /// registers (x86 EDX:EAX); Some(reg, isUpper) when the result goes to reg,
  /// isUpper selecting the counter's upper or lower 32 bits (PowerPC
  /// mftb/mftbu, AArch64 CNTVCT read into an operand register).
  | ClockCounterRead of (RegisterID * bool) option
  /// Access CPU details, e.g., CPUID on x86.
  | ProcessorInfoRead
  /// Explicitly undefined, illegal, or reserved instruction, e.g., UD2 on x86.
  | UndefinedInstruction
  /// An instruction that is valid but not yet modeled by B2R2's lifter, e.g.,
  /// an unsupported floating-point, privileged, or extension instruction.
  | UnsupportedInstruction
#if EMULATION
  /// EFLAGS lazy evaluation
  | FlagsUpdate
#endif

/// <summary>
/// Provides functions to access <see cref='T:B2R2.BinIR.SideEffect'/>.
/// </summary>
[<RequireQualifiedAccess>]
module SideEffect =

  /// <summary>
  /// Retrieves the LowUIR string representation of the side effect.
  /// </summary>
  [<CompiledName "ToString">]
  let toString sideEffect =
    match sideEffect with
    | Breakpoint -> "Breakpoint"
    | Fence -> "Fence"
    | Delay -> "Delay"
    | Terminate -> "Terminate"
    | SysCall -> "SysCall"
    | Interrupt(n) -> "Int" + n.ToString()
    | Exception k -> "Exception(" + ExceptionKind.toString k + ")"
    | AtomicBegin -> "AtomicBegin"
    | AtomicEnd -> "AtomicEnd"
    | ClockCounterRead None -> "ClockCounterRead"
    | ClockCounterRead(Some(r, isUpper)) ->
      "ClockCounterRead(" + string (int r) + (if isUpper then ":hi" else ":lo")
      + ")"
    | ProcessorInfoRead -> "ProcessorInfoRead"
    | UndefinedInstruction -> "UndefinedInstruction"
    | UnsupportedInstruction -> "UnsupportedInstruction"
#if EMULATION
    | FlagsUpdate -> "FlagsUpdate"
#endif
