(*
  B2R2 - the Next-Generation Reversing Platform

  Copyright (c) SoftSec Lab. @ KAIST, since 2016

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*)

namespace B2R2

/// Represents macOS (Darwin/XNU) BSD system calls. The enum values are
/// arbitrary indices; use MacosSyscall.toNumber to obtain the actual syscall
/// number for a given ISA.
type MacosSyscall =
  | AbortWithPayload = 0
  | Accept = 1
  | AcceptNocancel = 2
  | Access = 3
  | AccessExtended = 4
  | Acct = 5
  | Adjtime = 6
  | AioCancel = 7
  | AioError = 8
  | AioFsync = 9
  | AioRead = 10
  | AioReturn = 11
  | AioSuspend = 12
  | AioSuspendNocancel = 13
  | AioWrite = 14
  | Audit = 15
  | Auditctl = 16
  | Auditon = 17
  | AuditSessionJoin = 18
  | AuditSessionPort = 19
  | AuditSessionSelf = 20
  | Bind = 21
  | BsdthreadCreate = 22
  | BsdthreadCtl = 23
  | BsdthreadRegister = 24
  | BsdthreadTerminate = 25
  | ChangeFdguardNp = 26
  | ChannelGetInfo = 27
  | ChannelGetOpt = 28
  | ChannelOpen = 29
  | ChannelSetOpt = 30
  | ChannelSync = 31
  | Chdir = 32
  | Chflags = 33
  | Chmod = 34
  | ChmodExtended = 35
  | Chown = 36
  | Chroot = 37
  | Clonefileat = 38
  | Close = 39
  | CloseNocancel = 40
  | Coalition = 41
  | CoalitionInfo = 42
  | CoalitionLedger = 43
  | CoalitionPolicyGet = 44
  | CoalitionPolicySet = 45
  | Connect = 46
  | ConnectNocancel = 47
  | Connectx = 48
  | Copyfile = 49
  | CrossarchTrap = 50
  | Csops = 51
  | CsopsAudittoken = 52
  | Csrctl = 53
  | DebugSyscallReject = 54
  | DebugSyscallRejectConfig = 55
  | Delete = 56
  | DisableThreadsignal = 57
  | Disconnectx = 58
  | Dup = 59
  | Dup2 = 60
  | Exchangedata = 61
  | Execve = 62
  | Exit = 63
  | Faccessat = 64
  | Fchdir = 65
  | Fchflags = 66
  | Fchmod = 67
  | Fchmodat = 68
  | FchmodExtended = 69
  | Fchown = 70
  | Fchownat = 71
  | Fclonefileat = 72
  | Fcntl = 73
  | FcntlNocancel = 74
  | Fdatasync = 75
  | Ffsctl = 76
  | Fgetattrlist = 77
  | Fgetxattr = 78
  | Fhopen = 79
  | FileportMakefd = 80
  | FileportMakeport = 81
  | Flistxattr = 82
  | Flock = 83
  | Fmount = 84
  | Fork = 85
  | Fpathconf = 86
  | Freadlink = 87
  | Fremovexattr = 88
  | Fsctl = 89
  | Fsetattrlist = 90
  | Fsetxattr = 91
  | Fsgetpath = 92
  | FsgetpathExt = 93
  | FsSnapshot = 94
  | Fstat = 95
  | Fstat64 = 96
  | Fstat64Extended = 97
  | Fstatat = 98
  | Fstatat64 = 99
  | FstatExtended = 100
  | Fstatfs = 101
  | Fstatfs64 = 102
  | Fsync = 103
  | FsyncNocancel = 104
  | Ftruncate = 105
  | Funmount = 106
  | Futimes = 107
  | Getattrlist = 108
  | Getattrlistat = 109
  | Getattrlistbulk = 110
  | GetauditAddr = 111
  | Getauid = 112
  | Getdirentries = 113
  | Getdirentries64 = 114
  | Getdirentriesattr = 115
  | Getdtablesize = 116
  | Getegid = 117
  | Getentropy = 118
  | Geteuid = 119
  | Getfh = 120
  | Getfsstat = 121
  | Getfsstat64 = 122
  | Getgid = 123
  | Getgroups = 124
  | Gethostuuid = 125
  | Getitimer = 126
  | Getlogin = 127
  | Getpeername = 128
  | Getpgid = 129
  | Getpgrp = 130
  | Getpid = 131
  | Getppid = 132
  | Getpriority = 133
  | Getrlimit = 134
  | Getrusage = 135
  | Getsgroups = 136
  | Getsid = 137
  | Getsockname = 138
  | Getsockopt = 139
  | Gettid = 140
  | Gettimeofday = 141
  | Getuid = 142
  | Getwgroups = 143
  | Getxattr = 144
  | GrabPgoData = 145
  | Graftdmg = 146
  | GuardedCloseNp = 147
  | GuardedKqueueNp = 148
  | GuardedOpenDprotectedNp = 149
  | GuardedOpenNp = 150
  | GuardedPwriteNp = 151
  | GuardedWriteNp = 152
  | GuardedWritevNp = 153
  | Identitysvc = 154
  | Initgroups = 155
  | Ioctl = 156
  | Iopolicysys = 157
  | Issetugid = 158
  | KasInfo = 159
  | KdebugTrace = 160
  | KdebugTrace64 = 161
  | KdebugTraceString = 162
  | KdebugTypefilter = 163
  | Kevent = 164
  | Kevent64 = 165
  | KeventId = 166
  | KeventQos = 167
  | Kill = 168
  | Kqueue = 169
  | KqueueWorkloopCtl = 170
  | Lchown = 171
  | Ledger = 172
  | Link = 173
  | Linkat = 174
  | LioListio = 175
  | Listen = 176
  | Listxattr = 177
  | LogData = 178
  | Lseek = 179
  | Lstat = 180
  | Lstat64 = 181
  | Lstat64Extended = 182
  | LstatExtended = 183
  | MacExecve = 184
  | MacGetFd = 185
  | MacGetFile = 186
  | MacGetfsstat = 187
  | MacGetLink = 188
  | MacGetMount = 189
  | MacGetPid = 190
  | MacGetProc = 191
  | MachBridgeRemoteTime = 192
  | MachEventlinkSignal = 193
  | MachEventlinkSignalWaitUntil = 194
  | MachEventlinkWaitUntil = 195
  | MacMount = 196
  | MacSetFd = 197
  | MacSetFile = 198
  | MacSetLink = 199
  | MacSetProc = 200
  | MacSyscall = 201
  | Madvise = 202
  | MapWithLinkingNp = 203
  | MemorystatusAvailableMemory = 204
  | MemorystatusControl = 205
  | MemorystatusGetLevel = 206
  | Microstackshot = 207
  | Mincore = 208
  | Minherit = 209
  | Mkdir = 210
  | Mkdirat = 211
  | MkdirExtended = 212
  | Mkfifo = 213
  | Mkfifoat = 214
  | MkfifoExtended = 215
  | Mknod = 216
  | Mknodat = 217
  | Mlock = 218
  | Mlockall = 219
  | Mmap = 220
  | Mount = 221
  | Mprotect = 222
  | MremapEncrypted = 223
  | Msgctl = 224
  | Msgget = 225
  | Msgrcv = 226
  | MsgrcvNocancel = 227
  | Msgsnd = 228
  | MsgsndNocancel = 229
  | Msgsys = 230
  | Msync = 231
  | MsyncNocancel = 232
  | Munlock = 233
  | Munlockall = 234
  | Munmap = 235
  | NecpClientAction = 236
  | NecpMatchPolicy = 237
  | NecpOpen = 238
  | NecpSessionAction = 239
  | NecpSessionOpen = 240
  | NetagentTrigger = 241
  | NetQosGuideline = 242
  | NexusCreate = 243
  | NexusDeregister = 244
  | NexusDestroy = 245
  | NexusGetOpt = 246
  | NexusOpen = 247
  | NexusRegister = 248
  | NexusSetOpt = 249
  | Nfssvc = 250
  | NtpAdjtime = 251
  | NtpGettime = 252
  | ObjcBpAssistCfgNp = 253
  | Open = 254
  | Openat = 255
  | OpenatDprotectedNp = 256
  | OpenatNocancel = 257
  | OpenbyidNp = 258
  | OpenDprotectedNp = 259
  | OpenExtended = 260
  | OpenNocancel = 261
  | OsFaultWithPayload = 262
  | OslogCoproc = 263
  | OslogCoprocReg = 264
  | PanicWithData = 265
  | Pathconf = 266
  | Peeloff = 267
  | Persona = 268
  | PidHibernate = 269
  | PidResume = 270
  | PidShutdownSockets = 271
  | PidSuspend = 272
  | Pipe = 273
  | PivotRoot = 274
  | Poll = 275
  | PollNocancel = 276
  | PosixSpawn = 277
  | Pread = 278
  | PreadNocancel = 279
  | Preadv = 280
  | PreadvNocancel = 281
  | ProcessPolicy = 282
  | ProcInfo = 283
  | ProcInfoExtendedId = 284
  | ProcRlimitControl = 285
  | ProcTraceLog = 286
  | ProcUuidPolicy = 287
  | Pselect = 288
  | PselectNocancel = 289
  | PsynchCvbroad = 290
  | PsynchCvclrprepost = 291
  | PsynchCvsignal = 292
  | PsynchCvwait = 293
  | PsynchMutexdrop = 294
  | PsynchMutexwait = 295
  | PsynchRwDowngrade = 296
  | PsynchRwLongrdlock = 297
  | PsynchRwRdlock = 298
  | PsynchRwUnlock = 299
  | PsynchRwUnlock2 = 300
  | PsynchRwUpgrade = 301
  | PsynchRwWrlock = 302
  | PsynchRwYieldwrlock = 303
  | PthreadCanceled = 304
  | PthreadChdir = 305
  | PthreadFchdir = 306
  | PthreadKill = 307
  | PthreadMarkcancel = 308
  | PthreadSigmask = 309
  | Ptrace = 310
  | Pwrite = 311
  | PwriteNocancel = 312
  | Pwritev = 313
  | PwritevNocancel = 314
  | Quotactl = 315
  | Read = 316
  | Readlink = 317
  | Readlinkat = 318
  | ReadNocancel = 319
  | Readv = 320
  | ReadvNocancel = 321
  | Reboot = 322
  | RecordSystemEvent = 323
  | Recvfrom = 324
  | RecvfromNocancel = 325
  | Recvmsg = 326
  | RecvmsgNocancel = 327
  | RecvmsgX = 328
  | Removexattr = 329
  | Rename = 330
  | Renameat = 331
  | RenameatxNp = 332
  | Revoke = 333
  | Rmdir = 334
  | Searchfs = 335
  | Select = 336
  | SelectNocancel = 337
  | SemClose = 338
  | Semctl = 339
  | Semget = 340
  | Semop = 341
  | SemOpen = 342
  | SemPost = 343
  | Semsys = 344
  | SemTrywait = 345
  | SemUnlink = 346
  | SemWait = 347
  | SemWaitNocancel = 348
  | SemwaitSignal = 349
  | SemwaitSignalNocancel = 350
  | Sendfile = 351
  | Sendmsg = 352
  | SendmsgNocancel = 353
  | SendmsgX = 354
  | Sendto = 355
  | SendtoNocancel = 356
  | Setattrlist = 357
  | Setattrlistat = 358
  | SetauditAddr = 359
  | Setauid = 360
  | Setegid = 361
  | Seteuid = 362
  | Setgid = 363
  | Setgroups = 364
  | Setitimer = 365
  | Setlogin = 366
  | Setpgid = 367
  | Setpriority = 368
  | Setprivexec = 369
  | Setregid = 370
  | Setreuid = 371
  | Setrlimit = 372
  | Setsgroups = 373
  | Setsid = 374
  | Setsockopt = 375
  | Settid = 376
  | SettidWithPid = 377
  | Settimeofday = 378
  | Setuid = 379
  | Setwgroups = 380
  | Setxattr = 381
  | SfiCtl = 382
  | SfiPidctl = 383
  | SharedRegionCheckNp = 384
  | SharedRegionMapAndSlide2Np = 385
  | Shmat = 386
  | Shmctl = 387
  | Shmdt = 388
  | Shmget = 389
  | ShmOpen = 390
  | Shmsys = 391
  | ShmUnlink = 392
  | Shutdown = 393
  | Sigaction = 394
  | Sigaltstack = 395
  | Sigpending = 396
  | Sigprocmask = 397
  | Sigreturn = 398
  | Sigsuspend = 399
  | SigsuspendNocancel = 400
  | Sigwait = 401
  | SigwaitNocancel = 402
  | Socket = 403
  | SocketDelegate = 404
  | Socketpair = 405
  | StackSnapshotWithConfig = 406
  | Stat = 407
  | Stat64 = 408
  | Stat64Extended = 409
  | StatExtended = 410
  | Statfs = 411
  | Statfs64 = 412
  | Swapon = 413
  | Symlink = 414
  | Symlinkat = 415
  | Sync = 416
  | Sysctl = 417
  | Sysctlbyname = 418
  | SystemOverride = 419
  | TaskInspectForPid = 420
  | TaskReadForPid = 421
  | Telemetry = 422
  | TerminateWithPayload = 423
  | ThreadSelfcounts = 424
  | ThreadSelfid = 425
  | ThreadSelfusage = 426
  | TrackerAction = 427
  | Truncate = 428
  | UlockWait = 429
  | UlockWait2 = 430
  | UlockWake = 431
  | Umask = 432
  | UmaskExtended = 433
  | Undelete = 434
  | Ungraftdmg = 435
  | Unlink = 436
  | Unlinkat = 437
  | Unmount = 438
  | Usrctl = 439
  | Utimes = 440
  | Vfork = 441
  | VfsPurge = 442
  | VmPressureMonitor = 443
  | Wait4 = 444
  | Wait4Nocancel = 445
  | Waitid = 446
  | WaitidNocancel = 447
  | WorkIntervalCtl = 448
  | WorkqKernreturn = 449
  | WorkqOpen = 450
  | Write = 451
  | WriteNocancel = 452
  | Writev = 453
  | WritevNocancel = 454

/// Provides functions to convert macOS BSD syscall numbers to their
/// corresponding syscall types and vice versa. BSD syscall numbers are the
/// same on x86_64 and arm64; only the encoding in the number register differs.
[<RequireQualifiedAccess>]
module MacosSyscall =
  let private getBSDNumber = function
    | MacosSyscall.Exit -> 1
    | MacosSyscall.Fork -> 2
    | MacosSyscall.Read -> 3
    | MacosSyscall.Write -> 4
    | MacosSyscall.Open -> 5
    | MacosSyscall.Close -> 6
    | MacosSyscall.Wait4 -> 7
    | MacosSyscall.Link -> 9
    | MacosSyscall.Unlink -> 10
    | MacosSyscall.Chdir -> 12
    | MacosSyscall.Fchdir -> 13
    | MacosSyscall.Mknod -> 14
    | MacosSyscall.Chmod -> 15
    | MacosSyscall.Chown -> 16
    | MacosSyscall.Getfsstat -> 18
    | MacosSyscall.Getpid -> 20
    | MacosSyscall.Setuid -> 23
    | MacosSyscall.Getuid -> 24
    | MacosSyscall.Geteuid -> 25
    | MacosSyscall.Ptrace -> 26
    | MacosSyscall.Recvmsg -> 27
    | MacosSyscall.Sendmsg -> 28
    | MacosSyscall.Recvfrom -> 29
    | MacosSyscall.Accept -> 30
    | MacosSyscall.Getpeername -> 31
    | MacosSyscall.Getsockname -> 32
    | MacosSyscall.Access -> 33
    | MacosSyscall.Chflags -> 34
    | MacosSyscall.Fchflags -> 35
    | MacosSyscall.Sync -> 36
    | MacosSyscall.Kill -> 37
    | MacosSyscall.CrossarchTrap -> 38
    | MacosSyscall.Getppid -> 39
    | MacosSyscall.Dup -> 41
    | MacosSyscall.Pipe -> 42
    | MacosSyscall.Getegid -> 43
    | MacosSyscall.Sigaction -> 46
    | MacosSyscall.Getgid -> 47
    | MacosSyscall.Sigprocmask -> 48
    | MacosSyscall.Getlogin -> 49
    | MacosSyscall.Setlogin -> 50
    | MacosSyscall.Acct -> 51
    | MacosSyscall.Sigpending -> 52
    | MacosSyscall.Sigaltstack -> 53
    | MacosSyscall.Ioctl -> 54
    | MacosSyscall.Reboot -> 55
    | MacosSyscall.Revoke -> 56
    | MacosSyscall.Symlink -> 57
    | MacosSyscall.Readlink -> 58
    | MacosSyscall.Execve -> 59
    | MacosSyscall.Umask -> 60
    | MacosSyscall.Chroot -> 61
    | MacosSyscall.Msync -> 65
    | MacosSyscall.Vfork -> 66
    | MacosSyscall.OslogCoprocReg -> 67
    | MacosSyscall.OslogCoproc -> 68
    | MacosSyscall.Munmap -> 73
    | MacosSyscall.Mprotect -> 74
    | MacosSyscall.Madvise -> 75
    | MacosSyscall.Mincore -> 78
    | MacosSyscall.Getgroups -> 79
    | MacosSyscall.Setgroups -> 80
    | MacosSyscall.Getpgrp -> 81
    | MacosSyscall.Setpgid -> 82
    | MacosSyscall.Setitimer -> 83
    | MacosSyscall.Swapon -> 85
    | MacosSyscall.Getitimer -> 86
    | MacosSyscall.Getdtablesize -> 89
    | MacosSyscall.Dup2 -> 90
    | MacosSyscall.Fcntl -> 92
    | MacosSyscall.Select -> 93
    | MacosSyscall.Fsync -> 95
    | MacosSyscall.Setpriority -> 96
    | MacosSyscall.Socket -> 97
    | MacosSyscall.Connect -> 98
    | MacosSyscall.Getpriority -> 100
    | MacosSyscall.Bind -> 104
    | MacosSyscall.Setsockopt -> 105
    | MacosSyscall.Listen -> 106
    | MacosSyscall.Sigsuspend -> 111
    | MacosSyscall.Gettimeofday -> 116
    | MacosSyscall.Getrusage -> 117
    | MacosSyscall.Getsockopt -> 118
    | MacosSyscall.Readv -> 120
    | MacosSyscall.Writev -> 121
    | MacosSyscall.Settimeofday -> 122
    | MacosSyscall.Fchown -> 123
    | MacosSyscall.Fchmod -> 124
    | MacosSyscall.Setreuid -> 126
    | MacosSyscall.Setregid -> 127
    | MacosSyscall.Rename -> 128
    | MacosSyscall.Flock -> 131
    | MacosSyscall.Mkfifo -> 132
    | MacosSyscall.Sendto -> 133
    | MacosSyscall.Shutdown -> 134
    | MacosSyscall.Socketpair -> 135
    | MacosSyscall.Mkdir -> 136
    | MacosSyscall.Rmdir -> 137
    | MacosSyscall.Utimes -> 138
    | MacosSyscall.Futimes -> 139
    | MacosSyscall.Adjtime -> 140
    | MacosSyscall.Gethostuuid -> 142
    | MacosSyscall.Setsid -> 147
    | MacosSyscall.Getpgid -> 151
    | MacosSyscall.Setprivexec -> 152
    | MacosSyscall.Pread -> 153
    | MacosSyscall.Pwrite -> 154
    | MacosSyscall.Nfssvc -> 155
    | MacosSyscall.Statfs -> 157
    | MacosSyscall.Fstatfs -> 158
    | MacosSyscall.Unmount -> 159
    | MacosSyscall.Getfh -> 161
    | MacosSyscall.Funmount -> 164
    | MacosSyscall.Quotactl -> 165
    | MacosSyscall.Mount -> 167
    | MacosSyscall.Csops -> 169
    | MacosSyscall.CsopsAudittoken -> 170
    | MacosSyscall.Waitid -> 173
    | MacosSyscall.KdebugTypefilter -> 177
    | MacosSyscall.KdebugTraceString -> 178
    | MacosSyscall.KdebugTrace64 -> 179
    | MacosSyscall.KdebugTrace -> 180
    | MacosSyscall.Setgid -> 181
    | MacosSyscall.Setegid -> 182
    | MacosSyscall.Seteuid -> 183
    | MacosSyscall.Sigreturn -> 184
    | MacosSyscall.PanicWithData -> 185
    | MacosSyscall.ThreadSelfcounts -> 186
    | MacosSyscall.Fdatasync -> 187
    | MacosSyscall.Stat -> 188
    | MacosSyscall.Fstat -> 189
    | MacosSyscall.Lstat -> 190
    | MacosSyscall.Pathconf -> 191
    | MacosSyscall.Fpathconf -> 192
    | MacosSyscall.Getrlimit -> 194
    | MacosSyscall.Setrlimit -> 195
    | MacosSyscall.Getdirentries -> 196
    | MacosSyscall.Mmap -> 197
    | MacosSyscall.Lseek -> 199
    | MacosSyscall.Truncate -> 200
    | MacosSyscall.Ftruncate -> 201
    | MacosSyscall.Sysctl -> 202
    | MacosSyscall.Mlock -> 203
    | MacosSyscall.Munlock -> 204
    | MacosSyscall.Undelete -> 205
    | MacosSyscall.OpenDprotectedNp -> 216
    | MacosSyscall.FsgetpathExt -> 217
    | MacosSyscall.OpenatDprotectedNp -> 218
    | MacosSyscall.Getattrlist -> 220
    | MacosSyscall.Setattrlist -> 221
    | MacosSyscall.Getdirentriesattr -> 222
    | MacosSyscall.Exchangedata -> 223
    | MacosSyscall.Searchfs -> 225
    | MacosSyscall.Delete -> 226
    | MacosSyscall.Copyfile -> 227
    | MacosSyscall.Fgetattrlist -> 228
    | MacosSyscall.Fsetattrlist -> 229
    | MacosSyscall.Poll -> 230
    | MacosSyscall.Getxattr -> 234
    | MacosSyscall.Fgetxattr -> 235
    | MacosSyscall.Setxattr -> 236
    | MacosSyscall.Fsetxattr -> 237
    | MacosSyscall.Removexattr -> 238
    | MacosSyscall.Fremovexattr -> 239
    | MacosSyscall.Listxattr -> 240
    | MacosSyscall.Flistxattr -> 241
    | MacosSyscall.Fsctl -> 242
    | MacosSyscall.Initgroups -> 243
    | MacosSyscall.PosixSpawn -> 244
    | MacosSyscall.Ffsctl -> 245
    | MacosSyscall.Fhopen -> 248
    | MacosSyscall.Minherit -> 250
    | MacosSyscall.Semsys -> 251
    | MacosSyscall.Msgsys -> 252
    | MacosSyscall.Shmsys -> 253
    | MacosSyscall.Semctl -> 254
    | MacosSyscall.Semget -> 255
    | MacosSyscall.Semop -> 256
    | MacosSyscall.Msgctl -> 258
    | MacosSyscall.Msgget -> 259
    | MacosSyscall.Msgsnd -> 260
    | MacosSyscall.Msgrcv -> 261
    | MacosSyscall.Shmat -> 262
    | MacosSyscall.Shmctl -> 263
    | MacosSyscall.Shmdt -> 264
    | MacosSyscall.Shmget -> 265
    | MacosSyscall.ShmOpen -> 266
    | MacosSyscall.ShmUnlink -> 267
    | MacosSyscall.SemOpen -> 268
    | MacosSyscall.SemClose -> 269
    | MacosSyscall.SemUnlink -> 270
    | MacosSyscall.SemWait -> 271
    | MacosSyscall.SemTrywait -> 272
    | MacosSyscall.SemPost -> 273
    | MacosSyscall.Sysctlbyname -> 274
    | MacosSyscall.OpenExtended -> 277
    | MacosSyscall.UmaskExtended -> 278
    | MacosSyscall.StatExtended -> 279
    | MacosSyscall.LstatExtended -> 280
    | MacosSyscall.FstatExtended -> 281
    | MacosSyscall.ChmodExtended -> 282
    | MacosSyscall.FchmodExtended -> 283
    | MacosSyscall.AccessExtended -> 284
    | MacosSyscall.Settid -> 285
    | MacosSyscall.Gettid -> 286
    | MacosSyscall.Setsgroups -> 287
    | MacosSyscall.Getsgroups -> 288
    | MacosSyscall.Setwgroups -> 289
    | MacosSyscall.Getwgroups -> 290
    | MacosSyscall.MkfifoExtended -> 291
    | MacosSyscall.MkdirExtended -> 292
    | MacosSyscall.Identitysvc -> 293
    | MacosSyscall.SharedRegionCheckNp -> 294
    | MacosSyscall.VmPressureMonitor -> 296
    | MacosSyscall.PsynchRwLongrdlock -> 297
    | MacosSyscall.PsynchRwYieldwrlock -> 298
    | MacosSyscall.PsynchRwDowngrade -> 299
    | MacosSyscall.PsynchRwUpgrade -> 300
    | MacosSyscall.PsynchMutexwait -> 301
    | MacosSyscall.PsynchMutexdrop -> 302
    | MacosSyscall.PsynchCvbroad -> 303
    | MacosSyscall.PsynchCvsignal -> 304
    | MacosSyscall.PsynchCvwait -> 305
    | MacosSyscall.PsynchRwRdlock -> 306
    | MacosSyscall.PsynchRwWrlock -> 307
    | MacosSyscall.PsynchRwUnlock -> 308
    | MacosSyscall.PsynchRwUnlock2 -> 309
    | MacosSyscall.Getsid -> 310
    | MacosSyscall.SettidWithPid -> 311
    | MacosSyscall.PsynchCvclrprepost -> 312
    | MacosSyscall.AioFsync -> 313
    | MacosSyscall.AioReturn -> 314
    | MacosSyscall.AioSuspend -> 315
    | MacosSyscall.AioCancel -> 316
    | MacosSyscall.AioError -> 317
    | MacosSyscall.AioRead -> 318
    | MacosSyscall.AioWrite -> 319
    | MacosSyscall.LioListio -> 320
    | MacosSyscall.Iopolicysys -> 322
    | MacosSyscall.ProcessPolicy -> 323
    | MacosSyscall.Mlockall -> 324
    | MacosSyscall.Munlockall -> 325
    | MacosSyscall.Issetugid -> 327
    | MacosSyscall.PthreadKill -> 328
    | MacosSyscall.PthreadSigmask -> 329
    | MacosSyscall.Sigwait -> 330
    | MacosSyscall.DisableThreadsignal -> 331
    | MacosSyscall.PthreadMarkcancel -> 332
    | MacosSyscall.PthreadCanceled -> 333
    | MacosSyscall.SemwaitSignal -> 334
    | MacosSyscall.ProcInfo -> 336
    | MacosSyscall.Sendfile -> 337
    | MacosSyscall.Stat64 -> 338
    | MacosSyscall.Fstat64 -> 339
    | MacosSyscall.Lstat64 -> 340
    | MacosSyscall.Stat64Extended -> 341
    | MacosSyscall.Lstat64Extended -> 342
    | MacosSyscall.Fstat64Extended -> 343
    | MacosSyscall.Getdirentries64 -> 344
    | MacosSyscall.Statfs64 -> 345
    | MacosSyscall.Fstatfs64 -> 346
    | MacosSyscall.Getfsstat64 -> 347
    | MacosSyscall.PthreadChdir -> 348
    | MacosSyscall.PthreadFchdir -> 349
    | MacosSyscall.Audit -> 350
    | MacosSyscall.Auditon -> 351
    | MacosSyscall.Getauid -> 353
    | MacosSyscall.Setauid -> 354
    | MacosSyscall.GetauditAddr -> 357
    | MacosSyscall.SetauditAddr -> 358
    | MacosSyscall.Auditctl -> 359
    | MacosSyscall.BsdthreadCreate -> 360
    | MacosSyscall.BsdthreadTerminate -> 361
    | MacosSyscall.Kqueue -> 362
    | MacosSyscall.Kevent -> 363
    | MacosSyscall.Lchown -> 364
    | MacosSyscall.BsdthreadRegister -> 366
    | MacosSyscall.WorkqOpen -> 367
    | MacosSyscall.WorkqKernreturn -> 368
    | MacosSyscall.Kevent64 -> 369
    | MacosSyscall.ThreadSelfid -> 372
    | MacosSyscall.Ledger -> 373
    | MacosSyscall.KeventQos -> 374
    | MacosSyscall.KeventId -> 375
    | MacosSyscall.MacExecve -> 380
    | MacosSyscall.MacSyscall -> 381
    | MacosSyscall.MacGetFile -> 382
    | MacosSyscall.MacSetFile -> 383
    | MacosSyscall.MacGetLink -> 384
    | MacosSyscall.MacSetLink -> 385
    | MacosSyscall.MacGetProc -> 386
    | MacosSyscall.MacSetProc -> 387
    | MacosSyscall.MacGetFd -> 388
    | MacosSyscall.MacSetFd -> 389
    | MacosSyscall.MacGetPid -> 390
    | MacosSyscall.Pselect -> 394
    | MacosSyscall.PselectNocancel -> 395
    | MacosSyscall.ReadNocancel -> 396
    | MacosSyscall.WriteNocancel -> 397
    | MacosSyscall.OpenNocancel -> 398
    | MacosSyscall.CloseNocancel -> 399
    | MacosSyscall.Wait4Nocancel -> 400
    | MacosSyscall.RecvmsgNocancel -> 401
    | MacosSyscall.SendmsgNocancel -> 402
    | MacosSyscall.RecvfromNocancel -> 403
    | MacosSyscall.AcceptNocancel -> 404
    | MacosSyscall.MsyncNocancel -> 405
    | MacosSyscall.FcntlNocancel -> 406
    | MacosSyscall.SelectNocancel -> 407
    | MacosSyscall.FsyncNocancel -> 408
    | MacosSyscall.ConnectNocancel -> 409
    | MacosSyscall.SigsuspendNocancel -> 410
    | MacosSyscall.ReadvNocancel -> 411
    | MacosSyscall.WritevNocancel -> 412
    | MacosSyscall.SendtoNocancel -> 413
    | MacosSyscall.PreadNocancel -> 414
    | MacosSyscall.PwriteNocancel -> 415
    | MacosSyscall.WaitidNocancel -> 416
    | MacosSyscall.PollNocancel -> 417
    | MacosSyscall.MsgsndNocancel -> 418
    | MacosSyscall.MsgrcvNocancel -> 419
    | MacosSyscall.SemWaitNocancel -> 420
    | MacosSyscall.AioSuspendNocancel -> 421
    | MacosSyscall.SigwaitNocancel -> 422
    | MacosSyscall.SemwaitSignalNocancel -> 423
    | MacosSyscall.MacMount -> 424
    | MacosSyscall.MacGetMount -> 425
    | MacosSyscall.MacGetfsstat -> 426
    | MacosSyscall.Fsgetpath -> 427
    | MacosSyscall.AuditSessionSelf -> 428
    | MacosSyscall.AuditSessionJoin -> 429
    | MacosSyscall.FileportMakeport -> 430
    | MacosSyscall.FileportMakefd -> 431
    | MacosSyscall.AuditSessionPort -> 432
    | MacosSyscall.PidSuspend -> 433
    | MacosSyscall.PidResume -> 434
    | MacosSyscall.PidHibernate -> 435
    | MacosSyscall.PidShutdownSockets -> 436
    | MacosSyscall.KasInfo -> 439
    | MacosSyscall.MemorystatusControl -> 440
    | MacosSyscall.GuardedOpenNp -> 441
    | MacosSyscall.GuardedCloseNp -> 442
    | MacosSyscall.GuardedKqueueNp -> 443
    | MacosSyscall.ChangeFdguardNp -> 444
    | MacosSyscall.Usrctl -> 445
    | MacosSyscall.ProcRlimitControl -> 446
    | MacosSyscall.Connectx -> 447
    | MacosSyscall.Disconnectx -> 448
    | MacosSyscall.Peeloff -> 449
    | MacosSyscall.SocketDelegate -> 450
    | MacosSyscall.Telemetry -> 451
    | MacosSyscall.ProcUuidPolicy -> 452
    | MacosSyscall.MemorystatusGetLevel -> 453
    | MacosSyscall.SystemOverride -> 454
    | MacosSyscall.VfsPurge -> 455
    | MacosSyscall.SfiCtl -> 456
    | MacosSyscall.SfiPidctl -> 457
    | MacosSyscall.Coalition -> 458
    | MacosSyscall.CoalitionInfo -> 459
    | MacosSyscall.NecpMatchPolicy -> 460
    | MacosSyscall.Getattrlistbulk -> 461
    | MacosSyscall.Clonefileat -> 462
    | MacosSyscall.Openat -> 463
    | MacosSyscall.OpenatNocancel -> 464
    | MacosSyscall.Renameat -> 465
    | MacosSyscall.Faccessat -> 466
    | MacosSyscall.Fchmodat -> 467
    | MacosSyscall.Fchownat -> 468
    | MacosSyscall.Fstatat -> 469
    | MacosSyscall.Fstatat64 -> 470
    | MacosSyscall.Linkat -> 471
    | MacosSyscall.Unlinkat -> 472
    | MacosSyscall.Readlinkat -> 473
    | MacosSyscall.Symlinkat -> 474
    | MacosSyscall.Mkdirat -> 475
    | MacosSyscall.Getattrlistat -> 476
    | MacosSyscall.ProcTraceLog -> 477
    | MacosSyscall.BsdthreadCtl -> 478
    | MacosSyscall.OpenbyidNp -> 479
    | MacosSyscall.RecvmsgX -> 480
    | MacosSyscall.SendmsgX -> 481
    | MacosSyscall.ThreadSelfusage -> 482
    | MacosSyscall.Csrctl -> 483
    | MacosSyscall.GuardedOpenDprotectedNp -> 484
    | MacosSyscall.GuardedWriteNp -> 485
    | MacosSyscall.GuardedPwriteNp -> 486
    | MacosSyscall.GuardedWritevNp -> 487
    | MacosSyscall.RenameatxNp -> 488
    | MacosSyscall.MremapEncrypted -> 489
    | MacosSyscall.NetagentTrigger -> 490
    | MacosSyscall.StackSnapshotWithConfig -> 491
    | MacosSyscall.Microstackshot -> 492
    | MacosSyscall.GrabPgoData -> 493
    | MacosSyscall.Persona -> 494
    | MacosSyscall.MachEventlinkSignal -> 496
    | MacosSyscall.MachEventlinkWaitUntil -> 497
    | MacosSyscall.MachEventlinkSignalWaitUntil -> 498
    | MacosSyscall.WorkIntervalCtl -> 499
    | MacosSyscall.Getentropy -> 500
    | MacosSyscall.NecpOpen -> 501
    | MacosSyscall.NecpClientAction -> 502
    | MacosSyscall.NexusOpen -> 503
    | MacosSyscall.NexusRegister -> 504
    | MacosSyscall.NexusDeregister -> 505
    | MacosSyscall.NexusCreate -> 506
    | MacosSyscall.NexusDestroy -> 507
    | MacosSyscall.NexusGetOpt -> 508
    | MacosSyscall.NexusSetOpt -> 509
    | MacosSyscall.ChannelOpen -> 510
    | MacosSyscall.ChannelGetInfo -> 511
    | MacosSyscall.ChannelSync -> 512
    | MacosSyscall.ChannelGetOpt -> 513
    | MacosSyscall.ChannelSetOpt -> 514
    | MacosSyscall.UlockWait -> 515
    | MacosSyscall.UlockWake -> 516
    | MacosSyscall.Fclonefileat -> 517
    | MacosSyscall.FsSnapshot -> 518
    | MacosSyscall.TerminateWithPayload -> 520
    | MacosSyscall.AbortWithPayload -> 521
    | MacosSyscall.NecpSessionOpen -> 522
    | MacosSyscall.NecpSessionAction -> 523
    | MacosSyscall.Setattrlistat -> 524
    | MacosSyscall.NetQosGuideline -> 525
    | MacosSyscall.Fmount -> 526
    | MacosSyscall.NtpAdjtime -> 527
    | MacosSyscall.NtpGettime -> 528
    | MacosSyscall.OsFaultWithPayload -> 529
    | MacosSyscall.KqueueWorkloopCtl -> 530
    | MacosSyscall.MachBridgeRemoteTime -> 531
    | MacosSyscall.CoalitionLedger -> 532
    | MacosSyscall.LogData -> 533
    | MacosSyscall.MemorystatusAvailableMemory -> 534
    | MacosSyscall.ObjcBpAssistCfgNp -> 535
    | MacosSyscall.SharedRegionMapAndSlide2Np -> 536
    | MacosSyscall.PivotRoot -> 537
    | MacosSyscall.TaskInspectForPid -> 538
    | MacosSyscall.TaskReadForPid -> 539
    | MacosSyscall.Preadv -> 540
    | MacosSyscall.Pwritev -> 541
    | MacosSyscall.PreadvNocancel -> 542
    | MacosSyscall.PwritevNocancel -> 543
    | MacosSyscall.UlockWait2 -> 544
    | MacosSyscall.ProcInfoExtendedId -> 545
    | MacosSyscall.TrackerAction -> 546
    | MacosSyscall.DebugSyscallReject -> 547
    | MacosSyscall.DebugSyscallRejectConfig -> 548
    | MacosSyscall.Graftdmg -> 549
    | MacosSyscall.MapWithLinkingNp -> 550
    | MacosSyscall.Freadlink -> 551
    | MacosSyscall.RecordSystemEvent -> 552
    | MacosSyscall.Mkfifoat -> 553
    | MacosSyscall.Mknodat -> 554
    | MacosSyscall.Ungraftdmg -> 555
    | MacosSyscall.CoalitionPolicySet -> 556
    | MacosSyscall.CoalitionPolicyGet -> 557
    | _ -> raise UnhandledSyscallException

  (* On x86_64 the BSD syscall class (SYSCALL_CLASS_UNIX = 2) is encoded in the
     high bits of the number register, so the value in RAX is 0x2000000 ||| n.
     On arm64 the raw number is passed in x16 with no class bits. *)
  [<CompiledName "ToNumber">]
  let toNumber isa syscall =
    match isa with
    | X64 -> 0x2000000 ||| getBSDNumber syscall
    | AArch64 -> getBSDNumber syscall
    | _ -> raise UnhandledSyscallException

  let private getBSDSyscall = function
    | 1 -> MacosSyscall.Exit
    | 2 -> MacosSyscall.Fork
    | 3 -> MacosSyscall.Read
    | 4 -> MacosSyscall.Write
    | 5 -> MacosSyscall.Open
    | 6 -> MacosSyscall.Close
    | 7 -> MacosSyscall.Wait4
    | 9 -> MacosSyscall.Link
    | 10 -> MacosSyscall.Unlink
    | 12 -> MacosSyscall.Chdir
    | 13 -> MacosSyscall.Fchdir
    | 14 -> MacosSyscall.Mknod
    | 15 -> MacosSyscall.Chmod
    | 16 -> MacosSyscall.Chown
    | 18 -> MacosSyscall.Getfsstat
    | 20 -> MacosSyscall.Getpid
    | 23 -> MacosSyscall.Setuid
    | 24 -> MacosSyscall.Getuid
    | 25 -> MacosSyscall.Geteuid
    | 26 -> MacosSyscall.Ptrace
    | 27 -> MacosSyscall.Recvmsg
    | 28 -> MacosSyscall.Sendmsg
    | 29 -> MacosSyscall.Recvfrom
    | 30 -> MacosSyscall.Accept
    | 31 -> MacosSyscall.Getpeername
    | 32 -> MacosSyscall.Getsockname
    | 33 -> MacosSyscall.Access
    | 34 -> MacosSyscall.Chflags
    | 35 -> MacosSyscall.Fchflags
    | 36 -> MacosSyscall.Sync
    | 37 -> MacosSyscall.Kill
    | 38 -> MacosSyscall.CrossarchTrap
    | 39 -> MacosSyscall.Getppid
    | 41 -> MacosSyscall.Dup
    | 42 -> MacosSyscall.Pipe
    | 43 -> MacosSyscall.Getegid
    | 46 -> MacosSyscall.Sigaction
    | 47 -> MacosSyscall.Getgid
    | 48 -> MacosSyscall.Sigprocmask
    | 49 -> MacosSyscall.Getlogin
    | 50 -> MacosSyscall.Setlogin
    | 51 -> MacosSyscall.Acct
    | 52 -> MacosSyscall.Sigpending
    | 53 -> MacosSyscall.Sigaltstack
    | 54 -> MacosSyscall.Ioctl
    | 55 -> MacosSyscall.Reboot
    | 56 -> MacosSyscall.Revoke
    | 57 -> MacosSyscall.Symlink
    | 58 -> MacosSyscall.Readlink
    | 59 -> MacosSyscall.Execve
    | 60 -> MacosSyscall.Umask
    | 61 -> MacosSyscall.Chroot
    | 65 -> MacosSyscall.Msync
    | 66 -> MacosSyscall.Vfork
    | 67 -> MacosSyscall.OslogCoprocReg
    | 68 -> MacosSyscall.OslogCoproc
    | 73 -> MacosSyscall.Munmap
    | 74 -> MacosSyscall.Mprotect
    | 75 -> MacosSyscall.Madvise
    | 78 -> MacosSyscall.Mincore
    | 79 -> MacosSyscall.Getgroups
    | 80 -> MacosSyscall.Setgroups
    | 81 -> MacosSyscall.Getpgrp
    | 82 -> MacosSyscall.Setpgid
    | 83 -> MacosSyscall.Setitimer
    | 85 -> MacosSyscall.Swapon
    | 86 -> MacosSyscall.Getitimer
    | 89 -> MacosSyscall.Getdtablesize
    | 90 -> MacosSyscall.Dup2
    | 92 -> MacosSyscall.Fcntl
    | 93 -> MacosSyscall.Select
    | 95 -> MacosSyscall.Fsync
    | 96 -> MacosSyscall.Setpriority
    | 97 -> MacosSyscall.Socket
    | 98 -> MacosSyscall.Connect
    | 100 -> MacosSyscall.Getpriority
    | 104 -> MacosSyscall.Bind
    | 105 -> MacosSyscall.Setsockopt
    | 106 -> MacosSyscall.Listen
    | 111 -> MacosSyscall.Sigsuspend
    | 116 -> MacosSyscall.Gettimeofday
    | 117 -> MacosSyscall.Getrusage
    | 118 -> MacosSyscall.Getsockopt
    | 120 -> MacosSyscall.Readv
    | 121 -> MacosSyscall.Writev
    | 122 -> MacosSyscall.Settimeofday
    | 123 -> MacosSyscall.Fchown
    | 124 -> MacosSyscall.Fchmod
    | 126 -> MacosSyscall.Setreuid
    | 127 -> MacosSyscall.Setregid
    | 128 -> MacosSyscall.Rename
    | 131 -> MacosSyscall.Flock
    | 132 -> MacosSyscall.Mkfifo
    | 133 -> MacosSyscall.Sendto
    | 134 -> MacosSyscall.Shutdown
    | 135 -> MacosSyscall.Socketpair
    | 136 -> MacosSyscall.Mkdir
    | 137 -> MacosSyscall.Rmdir
    | 138 -> MacosSyscall.Utimes
    | 139 -> MacosSyscall.Futimes
    | 140 -> MacosSyscall.Adjtime
    | 142 -> MacosSyscall.Gethostuuid
    | 147 -> MacosSyscall.Setsid
    | 151 -> MacosSyscall.Getpgid
    | 152 -> MacosSyscall.Setprivexec
    | 153 -> MacosSyscall.Pread
    | 154 -> MacosSyscall.Pwrite
    | 155 -> MacosSyscall.Nfssvc
    | 157 -> MacosSyscall.Statfs
    | 158 -> MacosSyscall.Fstatfs
    | 159 -> MacosSyscall.Unmount
    | 161 -> MacosSyscall.Getfh
    | 164 -> MacosSyscall.Funmount
    | 165 -> MacosSyscall.Quotactl
    | 167 -> MacosSyscall.Mount
    | 169 -> MacosSyscall.Csops
    | 170 -> MacosSyscall.CsopsAudittoken
    | 173 -> MacosSyscall.Waitid
    | 177 -> MacosSyscall.KdebugTypefilter
    | 178 -> MacosSyscall.KdebugTraceString
    | 179 -> MacosSyscall.KdebugTrace64
    | 180 -> MacosSyscall.KdebugTrace
    | 181 -> MacosSyscall.Setgid
    | 182 -> MacosSyscall.Setegid
    | 183 -> MacosSyscall.Seteuid
    | 184 -> MacosSyscall.Sigreturn
    | 185 -> MacosSyscall.PanicWithData
    | 186 -> MacosSyscall.ThreadSelfcounts
    | 187 -> MacosSyscall.Fdatasync
    | 188 -> MacosSyscall.Stat
    | 189 -> MacosSyscall.Fstat
    | 190 -> MacosSyscall.Lstat
    | 191 -> MacosSyscall.Pathconf
    | 192 -> MacosSyscall.Fpathconf
    | 194 -> MacosSyscall.Getrlimit
    | 195 -> MacosSyscall.Setrlimit
    | 196 -> MacosSyscall.Getdirentries
    | 197 -> MacosSyscall.Mmap
    | 199 -> MacosSyscall.Lseek
    | 200 -> MacosSyscall.Truncate
    | 201 -> MacosSyscall.Ftruncate
    | 202 -> MacosSyscall.Sysctl
    | 203 -> MacosSyscall.Mlock
    | 204 -> MacosSyscall.Munlock
    | 205 -> MacosSyscall.Undelete
    | 216 -> MacosSyscall.OpenDprotectedNp
    | 217 -> MacosSyscall.FsgetpathExt
    | 218 -> MacosSyscall.OpenatDprotectedNp
    | 220 -> MacosSyscall.Getattrlist
    | 221 -> MacosSyscall.Setattrlist
    | 222 -> MacosSyscall.Getdirentriesattr
    | 223 -> MacosSyscall.Exchangedata
    | 225 -> MacosSyscall.Searchfs
    | 226 -> MacosSyscall.Delete
    | 227 -> MacosSyscall.Copyfile
    | 228 -> MacosSyscall.Fgetattrlist
    | 229 -> MacosSyscall.Fsetattrlist
    | 230 -> MacosSyscall.Poll
    | 234 -> MacosSyscall.Getxattr
    | 235 -> MacosSyscall.Fgetxattr
    | 236 -> MacosSyscall.Setxattr
    | 237 -> MacosSyscall.Fsetxattr
    | 238 -> MacosSyscall.Removexattr
    | 239 -> MacosSyscall.Fremovexattr
    | 240 -> MacosSyscall.Listxattr
    | 241 -> MacosSyscall.Flistxattr
    | 242 -> MacosSyscall.Fsctl
    | 243 -> MacosSyscall.Initgroups
    | 244 -> MacosSyscall.PosixSpawn
    | 245 -> MacosSyscall.Ffsctl
    | 248 -> MacosSyscall.Fhopen
    | 250 -> MacosSyscall.Minherit
    | 251 -> MacosSyscall.Semsys
    | 252 -> MacosSyscall.Msgsys
    | 253 -> MacosSyscall.Shmsys
    | 254 -> MacosSyscall.Semctl
    | 255 -> MacosSyscall.Semget
    | 256 -> MacosSyscall.Semop
    | 258 -> MacosSyscall.Msgctl
    | 259 -> MacosSyscall.Msgget
    | 260 -> MacosSyscall.Msgsnd
    | 261 -> MacosSyscall.Msgrcv
    | 262 -> MacosSyscall.Shmat
    | 263 -> MacosSyscall.Shmctl
    | 264 -> MacosSyscall.Shmdt
    | 265 -> MacosSyscall.Shmget
    | 266 -> MacosSyscall.ShmOpen
    | 267 -> MacosSyscall.ShmUnlink
    | 268 -> MacosSyscall.SemOpen
    | 269 -> MacosSyscall.SemClose
    | 270 -> MacosSyscall.SemUnlink
    | 271 -> MacosSyscall.SemWait
    | 272 -> MacosSyscall.SemTrywait
    | 273 -> MacosSyscall.SemPost
    | 274 -> MacosSyscall.Sysctlbyname
    | 277 -> MacosSyscall.OpenExtended
    | 278 -> MacosSyscall.UmaskExtended
    | 279 -> MacosSyscall.StatExtended
    | 280 -> MacosSyscall.LstatExtended
    | 281 -> MacosSyscall.FstatExtended
    | 282 -> MacosSyscall.ChmodExtended
    | 283 -> MacosSyscall.FchmodExtended
    | 284 -> MacosSyscall.AccessExtended
    | 285 -> MacosSyscall.Settid
    | 286 -> MacosSyscall.Gettid
    | 287 -> MacosSyscall.Setsgroups
    | 288 -> MacosSyscall.Getsgroups
    | 289 -> MacosSyscall.Setwgroups
    | 290 -> MacosSyscall.Getwgroups
    | 291 -> MacosSyscall.MkfifoExtended
    | 292 -> MacosSyscall.MkdirExtended
    | 293 -> MacosSyscall.Identitysvc
    | 294 -> MacosSyscall.SharedRegionCheckNp
    | 296 -> MacosSyscall.VmPressureMonitor
    | 297 -> MacosSyscall.PsynchRwLongrdlock
    | 298 -> MacosSyscall.PsynchRwYieldwrlock
    | 299 -> MacosSyscall.PsynchRwDowngrade
    | 300 -> MacosSyscall.PsynchRwUpgrade
    | 301 -> MacosSyscall.PsynchMutexwait
    | 302 -> MacosSyscall.PsynchMutexdrop
    | 303 -> MacosSyscall.PsynchCvbroad
    | 304 -> MacosSyscall.PsynchCvsignal
    | 305 -> MacosSyscall.PsynchCvwait
    | 306 -> MacosSyscall.PsynchRwRdlock
    | 307 -> MacosSyscall.PsynchRwWrlock
    | 308 -> MacosSyscall.PsynchRwUnlock
    | 309 -> MacosSyscall.PsynchRwUnlock2
    | 310 -> MacosSyscall.Getsid
    | 311 -> MacosSyscall.SettidWithPid
    | 312 -> MacosSyscall.PsynchCvclrprepost
    | 313 -> MacosSyscall.AioFsync
    | 314 -> MacosSyscall.AioReturn
    | 315 -> MacosSyscall.AioSuspend
    | 316 -> MacosSyscall.AioCancel
    | 317 -> MacosSyscall.AioError
    | 318 -> MacosSyscall.AioRead
    | 319 -> MacosSyscall.AioWrite
    | 320 -> MacosSyscall.LioListio
    | 322 -> MacosSyscall.Iopolicysys
    | 323 -> MacosSyscall.ProcessPolicy
    | 324 -> MacosSyscall.Mlockall
    | 325 -> MacosSyscall.Munlockall
    | 327 -> MacosSyscall.Issetugid
    | 328 -> MacosSyscall.PthreadKill
    | 329 -> MacosSyscall.PthreadSigmask
    | 330 -> MacosSyscall.Sigwait
    | 331 -> MacosSyscall.DisableThreadsignal
    | 332 -> MacosSyscall.PthreadMarkcancel
    | 333 -> MacosSyscall.PthreadCanceled
    | 334 -> MacosSyscall.SemwaitSignal
    | 336 -> MacosSyscall.ProcInfo
    | 337 -> MacosSyscall.Sendfile
    | 338 -> MacosSyscall.Stat64
    | 339 -> MacosSyscall.Fstat64
    | 340 -> MacosSyscall.Lstat64
    | 341 -> MacosSyscall.Stat64Extended
    | 342 -> MacosSyscall.Lstat64Extended
    | 343 -> MacosSyscall.Fstat64Extended
    | 344 -> MacosSyscall.Getdirentries64
    | 345 -> MacosSyscall.Statfs64
    | 346 -> MacosSyscall.Fstatfs64
    | 347 -> MacosSyscall.Getfsstat64
    | 348 -> MacosSyscall.PthreadChdir
    | 349 -> MacosSyscall.PthreadFchdir
    | 350 -> MacosSyscall.Audit
    | 351 -> MacosSyscall.Auditon
    | 353 -> MacosSyscall.Getauid
    | 354 -> MacosSyscall.Setauid
    | 357 -> MacosSyscall.GetauditAddr
    | 358 -> MacosSyscall.SetauditAddr
    | 359 -> MacosSyscall.Auditctl
    | 360 -> MacosSyscall.BsdthreadCreate
    | 361 -> MacosSyscall.BsdthreadTerminate
    | 362 -> MacosSyscall.Kqueue
    | 363 -> MacosSyscall.Kevent
    | 364 -> MacosSyscall.Lchown
    | 366 -> MacosSyscall.BsdthreadRegister
    | 367 -> MacosSyscall.WorkqOpen
    | 368 -> MacosSyscall.WorkqKernreturn
    | 369 -> MacosSyscall.Kevent64
    | 372 -> MacosSyscall.ThreadSelfid
    | 373 -> MacosSyscall.Ledger
    | 374 -> MacosSyscall.KeventQos
    | 375 -> MacosSyscall.KeventId
    | 380 -> MacosSyscall.MacExecve
    | 381 -> MacosSyscall.MacSyscall
    | 382 -> MacosSyscall.MacGetFile
    | 383 -> MacosSyscall.MacSetFile
    | 384 -> MacosSyscall.MacGetLink
    | 385 -> MacosSyscall.MacSetLink
    | 386 -> MacosSyscall.MacGetProc
    | 387 -> MacosSyscall.MacSetProc
    | 388 -> MacosSyscall.MacGetFd
    | 389 -> MacosSyscall.MacSetFd
    | 390 -> MacosSyscall.MacGetPid
    | 394 -> MacosSyscall.Pselect
    | 395 -> MacosSyscall.PselectNocancel
    | 396 -> MacosSyscall.ReadNocancel
    | 397 -> MacosSyscall.WriteNocancel
    | 398 -> MacosSyscall.OpenNocancel
    | 399 -> MacosSyscall.CloseNocancel
    | 400 -> MacosSyscall.Wait4Nocancel
    | 401 -> MacosSyscall.RecvmsgNocancel
    | 402 -> MacosSyscall.SendmsgNocancel
    | 403 -> MacosSyscall.RecvfromNocancel
    | 404 -> MacosSyscall.AcceptNocancel
    | 405 -> MacosSyscall.MsyncNocancel
    | 406 -> MacosSyscall.FcntlNocancel
    | 407 -> MacosSyscall.SelectNocancel
    | 408 -> MacosSyscall.FsyncNocancel
    | 409 -> MacosSyscall.ConnectNocancel
    | 410 -> MacosSyscall.SigsuspendNocancel
    | 411 -> MacosSyscall.ReadvNocancel
    | 412 -> MacosSyscall.WritevNocancel
    | 413 -> MacosSyscall.SendtoNocancel
    | 414 -> MacosSyscall.PreadNocancel
    | 415 -> MacosSyscall.PwriteNocancel
    | 416 -> MacosSyscall.WaitidNocancel
    | 417 -> MacosSyscall.PollNocancel
    | 418 -> MacosSyscall.MsgsndNocancel
    | 419 -> MacosSyscall.MsgrcvNocancel
    | 420 -> MacosSyscall.SemWaitNocancel
    | 421 -> MacosSyscall.AioSuspendNocancel
    | 422 -> MacosSyscall.SigwaitNocancel
    | 423 -> MacosSyscall.SemwaitSignalNocancel
    | 424 -> MacosSyscall.MacMount
    | 425 -> MacosSyscall.MacGetMount
    | 426 -> MacosSyscall.MacGetfsstat
    | 427 -> MacosSyscall.Fsgetpath
    | 428 -> MacosSyscall.AuditSessionSelf
    | 429 -> MacosSyscall.AuditSessionJoin
    | 430 -> MacosSyscall.FileportMakeport
    | 431 -> MacosSyscall.FileportMakefd
    | 432 -> MacosSyscall.AuditSessionPort
    | 433 -> MacosSyscall.PidSuspend
    | 434 -> MacosSyscall.PidResume
    | 435 -> MacosSyscall.PidHibernate
    | 436 -> MacosSyscall.PidShutdownSockets
    | 439 -> MacosSyscall.KasInfo
    | 440 -> MacosSyscall.MemorystatusControl
    | 441 -> MacosSyscall.GuardedOpenNp
    | 442 -> MacosSyscall.GuardedCloseNp
    | 443 -> MacosSyscall.GuardedKqueueNp
    | 444 -> MacosSyscall.ChangeFdguardNp
    | 445 -> MacosSyscall.Usrctl
    | 446 -> MacosSyscall.ProcRlimitControl
    | 447 -> MacosSyscall.Connectx
    | 448 -> MacosSyscall.Disconnectx
    | 449 -> MacosSyscall.Peeloff
    | 450 -> MacosSyscall.SocketDelegate
    | 451 -> MacosSyscall.Telemetry
    | 452 -> MacosSyscall.ProcUuidPolicy
    | 453 -> MacosSyscall.MemorystatusGetLevel
    | 454 -> MacosSyscall.SystemOverride
    | 455 -> MacosSyscall.VfsPurge
    | 456 -> MacosSyscall.SfiCtl
    | 457 -> MacosSyscall.SfiPidctl
    | 458 -> MacosSyscall.Coalition
    | 459 -> MacosSyscall.CoalitionInfo
    | 460 -> MacosSyscall.NecpMatchPolicy
    | 461 -> MacosSyscall.Getattrlistbulk
    | 462 -> MacosSyscall.Clonefileat
    | 463 -> MacosSyscall.Openat
    | 464 -> MacosSyscall.OpenatNocancel
    | 465 -> MacosSyscall.Renameat
    | 466 -> MacosSyscall.Faccessat
    | 467 -> MacosSyscall.Fchmodat
    | 468 -> MacosSyscall.Fchownat
    | 469 -> MacosSyscall.Fstatat
    | 470 -> MacosSyscall.Fstatat64
    | 471 -> MacosSyscall.Linkat
    | 472 -> MacosSyscall.Unlinkat
    | 473 -> MacosSyscall.Readlinkat
    | 474 -> MacosSyscall.Symlinkat
    | 475 -> MacosSyscall.Mkdirat
    | 476 -> MacosSyscall.Getattrlistat
    | 477 -> MacosSyscall.ProcTraceLog
    | 478 -> MacosSyscall.BsdthreadCtl
    | 479 -> MacosSyscall.OpenbyidNp
    | 480 -> MacosSyscall.RecvmsgX
    | 481 -> MacosSyscall.SendmsgX
    | 482 -> MacosSyscall.ThreadSelfusage
    | 483 -> MacosSyscall.Csrctl
    | 484 -> MacosSyscall.GuardedOpenDprotectedNp
    | 485 -> MacosSyscall.GuardedWriteNp
    | 486 -> MacosSyscall.GuardedPwriteNp
    | 487 -> MacosSyscall.GuardedWritevNp
    | 488 -> MacosSyscall.RenameatxNp
    | 489 -> MacosSyscall.MremapEncrypted
    | 490 -> MacosSyscall.NetagentTrigger
    | 491 -> MacosSyscall.StackSnapshotWithConfig
    | 492 -> MacosSyscall.Microstackshot
    | 493 -> MacosSyscall.GrabPgoData
    | 494 -> MacosSyscall.Persona
    | 496 -> MacosSyscall.MachEventlinkSignal
    | 497 -> MacosSyscall.MachEventlinkWaitUntil
    | 498 -> MacosSyscall.MachEventlinkSignalWaitUntil
    | 499 -> MacosSyscall.WorkIntervalCtl
    | 500 -> MacosSyscall.Getentropy
    | 501 -> MacosSyscall.NecpOpen
    | 502 -> MacosSyscall.NecpClientAction
    | 503 -> MacosSyscall.NexusOpen
    | 504 -> MacosSyscall.NexusRegister
    | 505 -> MacosSyscall.NexusDeregister
    | 506 -> MacosSyscall.NexusCreate
    | 507 -> MacosSyscall.NexusDestroy
    | 508 -> MacosSyscall.NexusGetOpt
    | 509 -> MacosSyscall.NexusSetOpt
    | 510 -> MacosSyscall.ChannelOpen
    | 511 -> MacosSyscall.ChannelGetInfo
    | 512 -> MacosSyscall.ChannelSync
    | 513 -> MacosSyscall.ChannelGetOpt
    | 514 -> MacosSyscall.ChannelSetOpt
    | 515 -> MacosSyscall.UlockWait
    | 516 -> MacosSyscall.UlockWake
    | 517 -> MacosSyscall.Fclonefileat
    | 518 -> MacosSyscall.FsSnapshot
    | 520 -> MacosSyscall.TerminateWithPayload
    | 521 -> MacosSyscall.AbortWithPayload
    | 522 -> MacosSyscall.NecpSessionOpen
    | 523 -> MacosSyscall.NecpSessionAction
    | 524 -> MacosSyscall.Setattrlistat
    | 525 -> MacosSyscall.NetQosGuideline
    | 526 -> MacosSyscall.Fmount
    | 527 -> MacosSyscall.NtpAdjtime
    | 528 -> MacosSyscall.NtpGettime
    | 529 -> MacosSyscall.OsFaultWithPayload
    | 530 -> MacosSyscall.KqueueWorkloopCtl
    | 531 -> MacosSyscall.MachBridgeRemoteTime
    | 532 -> MacosSyscall.CoalitionLedger
    | 533 -> MacosSyscall.LogData
    | 534 -> MacosSyscall.MemorystatusAvailableMemory
    | 535 -> MacosSyscall.ObjcBpAssistCfgNp
    | 536 -> MacosSyscall.SharedRegionMapAndSlide2Np
    | 537 -> MacosSyscall.PivotRoot
    | 538 -> MacosSyscall.TaskInspectForPid
    | 539 -> MacosSyscall.TaskReadForPid
    | 540 -> MacosSyscall.Preadv
    | 541 -> MacosSyscall.Pwritev
    | 542 -> MacosSyscall.PreadvNocancel
    | 543 -> MacosSyscall.PwritevNocancel
    | 544 -> MacosSyscall.UlockWait2
    | 545 -> MacosSyscall.ProcInfoExtendedId
    | 546 -> MacosSyscall.TrackerAction
    | 547 -> MacosSyscall.DebugSyscallReject
    | 548 -> MacosSyscall.DebugSyscallRejectConfig
    | 549 -> MacosSyscall.Graftdmg
    | 550 -> MacosSyscall.MapWithLinkingNp
    | 551 -> MacosSyscall.Freadlink
    | 552 -> MacosSyscall.RecordSystemEvent
    | 553 -> MacosSyscall.Mkfifoat
    | 554 -> MacosSyscall.Mknodat
    | 555 -> MacosSyscall.Ungraftdmg
    | 556 -> MacosSyscall.CoalitionPolicySet
    | 557 -> MacosSyscall.CoalitionPolicyGet
    | _ -> raise UnhandledSyscallException

  [<CompiledName "OfNumber">]
  let ofNumber arch num =
    match arch with
    | X64 -> getBSDSyscall (num &&& 0xffffff)
    | AArch64 -> getBSDSyscall num
    | _ -> raise UnhandledSyscallException

  /// Converts a MacosSyscall to a string.
  [<CompiledName "ToString">]
  let toString = function
    | MacosSyscall.ChannelGetInfo -> "__channel_get_info"
    | MacosSyscall.ChannelGetOpt -> "__channel_get_opt"
    | MacosSyscall.ChannelOpen -> "__channel_open"
    | MacosSyscall.ChannelSetOpt -> "__channel_set_opt"
    | MacosSyscall.ChannelSync -> "__channel_sync"
    | MacosSyscall.DisableThreadsignal -> "__disable_threadsignal"
    | MacosSyscall.MacExecve -> "__mac_execve"
    | MacosSyscall.MacGetFd -> "__mac_get_fd"
    | MacosSyscall.MacGetFile -> "__mac_get_file"
    | MacosSyscall.MacGetLink -> "__mac_get_link"
    | MacosSyscall.MacGetMount -> "__mac_get_mount"
    | MacosSyscall.MacGetPid -> "__mac_get_pid"
    | MacosSyscall.MacGetProc -> "__mac_get_proc"
    | MacosSyscall.MacGetfsstat -> "__mac_getfsstat"
    | MacosSyscall.MacMount -> "__mac_mount"
    | MacosSyscall.MacSetFd -> "__mac_set_fd"
    | MacosSyscall.MacSetFile -> "__mac_set_file"
    | MacosSyscall.MacSetLink -> "__mac_set_link"
    | MacosSyscall.MacSetProc -> "__mac_set_proc"
    | MacosSyscall.MacSyscall -> "__mac_syscall"
    | MacosSyscall.MachBridgeRemoteTime -> "__mach_bridge_remote_time"
    | MacosSyscall.NexusCreate -> "__nexus_create"
    | MacosSyscall.NexusDeregister -> "__nexus_deregister"
    | MacosSyscall.NexusDestroy -> "__nexus_destroy"
    | MacosSyscall.NexusGetOpt -> "__nexus_get_opt"
    | MacosSyscall.NexusOpen -> "__nexus_open"
    | MacosSyscall.NexusRegister -> "__nexus_register"
    | MacosSyscall.NexusSetOpt -> "__nexus_set_opt"
    | MacosSyscall.PthreadCanceled -> "__pthread_canceled"
    | MacosSyscall.PthreadChdir -> "__pthread_chdir"
    | MacosSyscall.PthreadFchdir -> "__pthread_fchdir"
    | MacosSyscall.PthreadKill -> "__pthread_kill"
    | MacosSyscall.PthreadMarkcancel -> "__pthread_markcancel"
    | MacosSyscall.PthreadSigmask -> "__pthread_sigmask"
    | MacosSyscall.SemwaitSignal -> "__semwait_signal"
    | MacosSyscall.SemwaitSignalNocancel -> "__semwait_signal_nocancel"
    | MacosSyscall.Sigwait -> "__sigwait"
    | MacosSyscall.SigwaitNocancel -> "__sigwait_nocancel"
    | MacosSyscall.AbortWithPayload -> "abort_with_payload"
    | MacosSyscall.Accept -> "accept"
    | MacosSyscall.AcceptNocancel -> "accept_nocancel"
    | MacosSyscall.Access -> "access"
    | MacosSyscall.AccessExtended -> "access_extended"
    | MacosSyscall.Acct -> "acct"
    | MacosSyscall.Adjtime -> "adjtime"
    | MacosSyscall.AioCancel -> "aio_cancel"
    | MacosSyscall.AioError -> "aio_error"
    | MacosSyscall.AioFsync -> "aio_fsync"
    | MacosSyscall.AioRead -> "aio_read"
    | MacosSyscall.AioReturn -> "aio_return"
    | MacosSyscall.AioSuspend -> "aio_suspend"
    | MacosSyscall.AioSuspendNocancel -> "aio_suspend_nocancel"
    | MacosSyscall.AioWrite -> "aio_write"
    | MacosSyscall.Audit -> "audit"
    | MacosSyscall.AuditSessionJoin -> "audit_session_join"
    | MacosSyscall.AuditSessionPort -> "audit_session_port"
    | MacosSyscall.AuditSessionSelf -> "audit_session_self"
    | MacosSyscall.Auditctl -> "auditctl"
    | MacosSyscall.Auditon -> "auditon"
    | MacosSyscall.Bind -> "bind"
    | MacosSyscall.BsdthreadCreate -> "bsdthread_create"
    | MacosSyscall.BsdthreadCtl -> "bsdthread_ctl"
    | MacosSyscall.BsdthreadRegister -> "bsdthread_register"
    | MacosSyscall.BsdthreadTerminate -> "bsdthread_terminate"
    | MacosSyscall.ChangeFdguardNp -> "change_fdguard_np"
    | MacosSyscall.Chdir -> "chdir"
    | MacosSyscall.Chflags -> "chflags"
    | MacosSyscall.Chmod -> "chmod"
    | MacosSyscall.ChmodExtended -> "chmod_extended"
    | MacosSyscall.Chown -> "chown"
    | MacosSyscall.Chroot -> "chroot"
    | MacosSyscall.Clonefileat -> "clonefileat"
    | MacosSyscall.Close -> "close"
    | MacosSyscall.CloseNocancel -> "close_nocancel"
    | MacosSyscall.Coalition -> "coalition"
    | MacosSyscall.CoalitionInfo -> "coalition_info"
    | MacosSyscall.CoalitionLedger -> "coalition_ledger"
    | MacosSyscall.CoalitionPolicyGet -> "coalition_policy_get"
    | MacosSyscall.CoalitionPolicySet -> "coalition_policy_set"
    | MacosSyscall.Connect -> "connect"
    | MacosSyscall.ConnectNocancel -> "connect_nocancel"
    | MacosSyscall.Connectx -> "connectx"
    | MacosSyscall.Copyfile -> "copyfile"
    | MacosSyscall.CrossarchTrap -> "crossarch_trap"
    | MacosSyscall.Csops -> "csops"
    | MacosSyscall.CsopsAudittoken -> "csops_audittoken"
    | MacosSyscall.Csrctl -> "csrctl"
    | MacosSyscall.DebugSyscallReject -> "debug_syscall_reject"
    | MacosSyscall.DebugSyscallRejectConfig -> "debug_syscall_reject_config"
    | MacosSyscall.Delete -> "delete"
    | MacosSyscall.Disconnectx -> "disconnectx"
    | MacosSyscall.Dup -> "dup"
    | MacosSyscall.Dup2 -> "dup2"
    | MacosSyscall.Exchangedata -> "exchangedata"
    | MacosSyscall.Execve -> "execve"
    | MacosSyscall.Exit -> "exit"
    | MacosSyscall.Faccessat -> "faccessat"
    | MacosSyscall.Fchdir -> "fchdir"
    | MacosSyscall.Fchflags -> "fchflags"
    | MacosSyscall.Fchmod -> "fchmod"
    | MacosSyscall.FchmodExtended -> "fchmod_extended"
    | MacosSyscall.Fchmodat -> "fchmodat"
    | MacosSyscall.Fchown -> "fchown"
    | MacosSyscall.Fchownat -> "fchownat"
    | MacosSyscall.Fclonefileat -> "fclonefileat"
    | MacosSyscall.Fcntl -> "fcntl"
    | MacosSyscall.FcntlNocancel -> "fcntl_nocancel"
    | MacosSyscall.Fdatasync -> "fdatasync"
    | MacosSyscall.Ffsctl -> "ffsctl"
    | MacosSyscall.Fgetattrlist -> "fgetattrlist"
    | MacosSyscall.Fgetxattr -> "fgetxattr"
    | MacosSyscall.Fhopen -> "fhopen"
    | MacosSyscall.FileportMakefd -> "fileport_makefd"
    | MacosSyscall.FileportMakeport -> "fileport_makeport"
    | MacosSyscall.Flistxattr -> "flistxattr"
    | MacosSyscall.Flock -> "flock"
    | MacosSyscall.Fmount -> "fmount"
    | MacosSyscall.Fork -> "fork"
    | MacosSyscall.Fpathconf -> "fpathconf"
    | MacosSyscall.Freadlink -> "freadlink"
    | MacosSyscall.Fremovexattr -> "fremovexattr"
    | MacosSyscall.FsSnapshot -> "fs_snapshot"
    | MacosSyscall.Fsctl -> "fsctl"
    | MacosSyscall.Fsetattrlist -> "fsetattrlist"
    | MacosSyscall.Fsetxattr -> "fsetxattr"
    | MacosSyscall.Fsgetpath -> "fsgetpath"
    | MacosSyscall.FsgetpathExt -> "fsgetpath_ext"
    | MacosSyscall.Fstat -> "fstat"
    | MacosSyscall.Fstat64 -> "fstat64"
    | MacosSyscall.Fstat64Extended -> "fstat64_extended"
    | MacosSyscall.FstatExtended -> "fstat_extended"
    | MacosSyscall.Fstatat -> "fstatat"
    | MacosSyscall.Fstatat64 -> "fstatat64"
    | MacosSyscall.Fstatfs -> "fstatfs"
    | MacosSyscall.Fstatfs64 -> "fstatfs64"
    | MacosSyscall.Fsync -> "fsync"
    | MacosSyscall.FsyncNocancel -> "fsync_nocancel"
    | MacosSyscall.Ftruncate -> "ftruncate"
    | MacosSyscall.Funmount -> "funmount"
    | MacosSyscall.Futimes -> "futimes"
    | MacosSyscall.Getattrlist -> "getattrlist"
    | MacosSyscall.Getattrlistat -> "getattrlistat"
    | MacosSyscall.Getattrlistbulk -> "getattrlistbulk"
    | MacosSyscall.GetauditAddr -> "getaudit_addr"
    | MacosSyscall.Getauid -> "getauid"
    | MacosSyscall.Getdirentries -> "getdirentries"
    | MacosSyscall.Getdirentries64 -> "getdirentries64"
    | MacosSyscall.Getdirentriesattr -> "getdirentriesattr"
    | MacosSyscall.Getdtablesize -> "getdtablesize"
    | MacosSyscall.Getegid -> "getegid"
    | MacosSyscall.Getentropy -> "getentropy"
    | MacosSyscall.Geteuid -> "geteuid"
    | MacosSyscall.Getfh -> "getfh"
    | MacosSyscall.Getfsstat -> "getfsstat"
    | MacosSyscall.Getfsstat64 -> "getfsstat64"
    | MacosSyscall.Getgid -> "getgid"
    | MacosSyscall.Getgroups -> "getgroups"
    | MacosSyscall.Gethostuuid -> "gethostuuid"
    | MacosSyscall.Getitimer -> "getitimer"
    | MacosSyscall.Getlogin -> "getlogin"
    | MacosSyscall.Getpeername -> "getpeername"
    | MacosSyscall.Getpgid -> "getpgid"
    | MacosSyscall.Getpgrp -> "getpgrp"
    | MacosSyscall.Getpid -> "getpid"
    | MacosSyscall.Getppid -> "getppid"
    | MacosSyscall.Getpriority -> "getpriority"
    | MacosSyscall.Getrlimit -> "getrlimit"
    | MacosSyscall.Getrusage -> "getrusage"
    | MacosSyscall.Getsgroups -> "getsgroups"
    | MacosSyscall.Getsid -> "getsid"
    | MacosSyscall.Getsockname -> "getsockname"
    | MacosSyscall.Getsockopt -> "getsockopt"
    | MacosSyscall.Gettid -> "gettid"
    | MacosSyscall.Gettimeofday -> "gettimeofday"
    | MacosSyscall.Getuid -> "getuid"
    | MacosSyscall.Getwgroups -> "getwgroups"
    | MacosSyscall.Getxattr -> "getxattr"
    | MacosSyscall.GrabPgoData -> "grab_pgo_data"
    | MacosSyscall.Graftdmg -> "graftdmg"
    | MacosSyscall.GuardedCloseNp -> "guarded_close_np"
    | MacosSyscall.GuardedKqueueNp -> "guarded_kqueue_np"
    | MacosSyscall.GuardedOpenDprotectedNp -> "guarded_open_dprotected_np"
    | MacosSyscall.GuardedOpenNp -> "guarded_open_np"
    | MacosSyscall.GuardedPwriteNp -> "guarded_pwrite_np"
    | MacosSyscall.GuardedWriteNp -> "guarded_write_np"
    | MacosSyscall.GuardedWritevNp -> "guarded_writev_np"
    | MacosSyscall.Identitysvc -> "identitysvc"
    | MacosSyscall.Initgroups -> "initgroups"
    | MacosSyscall.Ioctl -> "ioctl"
    | MacosSyscall.Iopolicysys -> "iopolicysys"
    | MacosSyscall.Issetugid -> "issetugid"
    | MacosSyscall.KasInfo -> "kas_info"
    | MacosSyscall.KdebugTrace -> "kdebug_trace"
    | MacosSyscall.KdebugTrace64 -> "kdebug_trace64"
    | MacosSyscall.KdebugTraceString -> "kdebug_trace_string"
    | MacosSyscall.KdebugTypefilter -> "kdebug_typefilter"
    | MacosSyscall.Kevent -> "kevent"
    | MacosSyscall.Kevent64 -> "kevent64"
    | MacosSyscall.KeventId -> "kevent_id"
    | MacosSyscall.KeventQos -> "kevent_qos"
    | MacosSyscall.Kill -> "kill"
    | MacosSyscall.Kqueue -> "kqueue"
    | MacosSyscall.KqueueWorkloopCtl -> "kqueue_workloop_ctl"
    | MacosSyscall.Lchown -> "lchown"
    | MacosSyscall.Ledger -> "ledger"
    | MacosSyscall.Link -> "link"
    | MacosSyscall.Linkat -> "linkat"
    | MacosSyscall.LioListio -> "lio_listio"
    | MacosSyscall.Listen -> "listen"
    | MacosSyscall.Listxattr -> "listxattr"
    | MacosSyscall.LogData -> "log_data"
    | MacosSyscall.Lseek -> "lseek"
    | MacosSyscall.Lstat -> "lstat"
    | MacosSyscall.Lstat64 -> "lstat64"
    | MacosSyscall.Lstat64Extended -> "lstat64_extended"
    | MacosSyscall.LstatExtended -> "lstat_extended"
    | MacosSyscall.MachEventlinkSignal -> "mach_eventlink_signal"
    | MacosSyscall.MachEventlinkSignalWaitUntil ->
      "mach_eventlink_signal_wait_until"
    | MacosSyscall.MachEventlinkWaitUntil -> "mach_eventlink_wait_until"
    | MacosSyscall.Madvise -> "madvise"
    | MacosSyscall.MapWithLinkingNp -> "map_with_linking_np"
    | MacosSyscall.MemorystatusAvailableMemory ->
      "memorystatus_available_memory"
    | MacosSyscall.MemorystatusControl -> "memorystatus_control"
    | MacosSyscall.MemorystatusGetLevel -> "memorystatus_get_level"
    | MacosSyscall.Microstackshot -> "microstackshot"
    | MacosSyscall.Mincore -> "mincore"
    | MacosSyscall.Minherit -> "minherit"
    | MacosSyscall.Mkdir -> "mkdir"
    | MacosSyscall.MkdirExtended -> "mkdir_extended"
    | MacosSyscall.Mkdirat -> "mkdirat"
    | MacosSyscall.Mkfifo -> "mkfifo"
    | MacosSyscall.MkfifoExtended -> "mkfifo_extended"
    | MacosSyscall.Mkfifoat -> "mkfifoat"
    | MacosSyscall.Mknod -> "mknod"
    | MacosSyscall.Mknodat -> "mknodat"
    | MacosSyscall.Mlock -> "mlock"
    | MacosSyscall.Mlockall -> "mlockall"
    | MacosSyscall.Mmap -> "mmap"
    | MacosSyscall.Mount -> "mount"
    | MacosSyscall.Mprotect -> "mprotect"
    | MacosSyscall.MremapEncrypted -> "mremap_encrypted"
    | MacosSyscall.Msgctl -> "msgctl"
    | MacosSyscall.Msgget -> "msgget"
    | MacosSyscall.Msgrcv -> "msgrcv"
    | MacosSyscall.MsgrcvNocancel -> "msgrcv_nocancel"
    | MacosSyscall.Msgsnd -> "msgsnd"
    | MacosSyscall.MsgsndNocancel -> "msgsnd_nocancel"
    | MacosSyscall.Msgsys -> "msgsys"
    | MacosSyscall.Msync -> "msync"
    | MacosSyscall.MsyncNocancel -> "msync_nocancel"
    | MacosSyscall.Munlock -> "munlock"
    | MacosSyscall.Munlockall -> "munlockall"
    | MacosSyscall.Munmap -> "munmap"
    | MacosSyscall.NecpClientAction -> "necp_client_action"
    | MacosSyscall.NecpMatchPolicy -> "necp_match_policy"
    | MacosSyscall.NecpOpen -> "necp_open"
    | MacosSyscall.NecpSessionAction -> "necp_session_action"
    | MacosSyscall.NecpSessionOpen -> "necp_session_open"
    | MacosSyscall.NetQosGuideline -> "net_qos_guideline"
    | MacosSyscall.NetagentTrigger -> "netagent_trigger"
    | MacosSyscall.Nfssvc -> "nfssvc"
    | MacosSyscall.NtpAdjtime -> "ntp_adjtime"
    | MacosSyscall.NtpGettime -> "ntp_gettime"
    | MacosSyscall.ObjcBpAssistCfgNp -> "objc_bp_assist_cfg_np"
    | MacosSyscall.Open -> "open"
    | MacosSyscall.OpenDprotectedNp -> "open_dprotected_np"
    | MacosSyscall.OpenExtended -> "open_extended"
    | MacosSyscall.OpenNocancel -> "open_nocancel"
    | MacosSyscall.Openat -> "openat"
    | MacosSyscall.OpenatDprotectedNp -> "openat_dprotected_np"
    | MacosSyscall.OpenatNocancel -> "openat_nocancel"
    | MacosSyscall.OpenbyidNp -> "openbyid_np"
    | MacosSyscall.OsFaultWithPayload -> "os_fault_with_payload"
    | MacosSyscall.OslogCoproc -> "oslog_coproc"
    | MacosSyscall.OslogCoprocReg -> "oslog_coproc_reg"
    | MacosSyscall.PanicWithData -> "panic_with_data"
    | MacosSyscall.Pathconf -> "pathconf"
    | MacosSyscall.Peeloff -> "peeloff"
    | MacosSyscall.Persona -> "persona"
    | MacosSyscall.PidHibernate -> "pid_hibernate"
    | MacosSyscall.PidResume -> "pid_resume"
    | MacosSyscall.PidShutdownSockets -> "pid_shutdown_sockets"
    | MacosSyscall.PidSuspend -> "pid_suspend"
    | MacosSyscall.Pipe -> "pipe"
    | MacosSyscall.PivotRoot -> "pivot_root"
    | MacosSyscall.Poll -> "poll"
    | MacosSyscall.PollNocancel -> "poll_nocancel"
    | MacosSyscall.PosixSpawn -> "posix_spawn"
    | MacosSyscall.Pread -> "pread"
    | MacosSyscall.PreadNocancel -> "pread_nocancel"
    | MacosSyscall.Preadv -> "preadv"
    | MacosSyscall.PreadvNocancel -> "preadv_nocancel"
    | MacosSyscall.ProcInfo -> "proc_info"
    | MacosSyscall.ProcInfoExtendedId -> "proc_info_extended_id"
    | MacosSyscall.ProcRlimitControl -> "proc_rlimit_control"
    | MacosSyscall.ProcTraceLog -> "proc_trace_log"
    | MacosSyscall.ProcUuidPolicy -> "proc_uuid_policy"
    | MacosSyscall.ProcessPolicy -> "process_policy"
    | MacosSyscall.Pselect -> "pselect"
    | MacosSyscall.PselectNocancel -> "pselect_nocancel"
    | MacosSyscall.PsynchCvbroad -> "psynch_cvbroad"
    | MacosSyscall.PsynchCvclrprepost -> "psynch_cvclrprepost"
    | MacosSyscall.PsynchCvsignal -> "psynch_cvsignal"
    | MacosSyscall.PsynchCvwait -> "psynch_cvwait"
    | MacosSyscall.PsynchMutexdrop -> "psynch_mutexdrop"
    | MacosSyscall.PsynchMutexwait -> "psynch_mutexwait"
    | MacosSyscall.PsynchRwDowngrade -> "psynch_rw_downgrade"
    | MacosSyscall.PsynchRwLongrdlock -> "psynch_rw_longrdlock"
    | MacosSyscall.PsynchRwRdlock -> "psynch_rw_rdlock"
    | MacosSyscall.PsynchRwUnlock -> "psynch_rw_unlock"
    | MacosSyscall.PsynchRwUnlock2 -> "psynch_rw_unlock2"
    | MacosSyscall.PsynchRwUpgrade -> "psynch_rw_upgrade"
    | MacosSyscall.PsynchRwWrlock -> "psynch_rw_wrlock"
    | MacosSyscall.PsynchRwYieldwrlock -> "psynch_rw_yieldwrlock"
    | MacosSyscall.Ptrace -> "ptrace"
    | MacosSyscall.Pwrite -> "pwrite"
    | MacosSyscall.PwriteNocancel -> "pwrite_nocancel"
    | MacosSyscall.Pwritev -> "pwritev"
    | MacosSyscall.PwritevNocancel -> "pwritev_nocancel"
    | MacosSyscall.Quotactl -> "quotactl"
    | MacosSyscall.Read -> "read"
    | MacosSyscall.ReadNocancel -> "read_nocancel"
    | MacosSyscall.Readlink -> "readlink"
    | MacosSyscall.Readlinkat -> "readlinkat"
    | MacosSyscall.Readv -> "readv"
    | MacosSyscall.ReadvNocancel -> "readv_nocancel"
    | MacosSyscall.Reboot -> "reboot"
    | MacosSyscall.RecordSystemEvent -> "record_system_event"
    | MacosSyscall.Recvfrom -> "recvfrom"
    | MacosSyscall.RecvfromNocancel -> "recvfrom_nocancel"
    | MacosSyscall.Recvmsg -> "recvmsg"
    | MacosSyscall.RecvmsgNocancel -> "recvmsg_nocancel"
    | MacosSyscall.RecvmsgX -> "recvmsg_x"
    | MacosSyscall.Removexattr -> "removexattr"
    | MacosSyscall.Rename -> "rename"
    | MacosSyscall.Renameat -> "renameat"
    | MacosSyscall.RenameatxNp -> "renameatx_np"
    | MacosSyscall.Revoke -> "revoke"
    | MacosSyscall.Rmdir -> "rmdir"
    | MacosSyscall.Searchfs -> "searchfs"
    | MacosSyscall.Select -> "select"
    | MacosSyscall.SelectNocancel -> "select_nocancel"
    | MacosSyscall.SemClose -> "sem_close"
    | MacosSyscall.SemOpen -> "sem_open"
    | MacosSyscall.SemPost -> "sem_post"
    | MacosSyscall.SemTrywait -> "sem_trywait"
    | MacosSyscall.SemUnlink -> "sem_unlink"
    | MacosSyscall.SemWait -> "sem_wait"
    | MacosSyscall.SemWaitNocancel -> "sem_wait_nocancel"
    | MacosSyscall.Semctl -> "semctl"
    | MacosSyscall.Semget -> "semget"
    | MacosSyscall.Semop -> "semop"
    | MacosSyscall.Semsys -> "semsys"
    | MacosSyscall.Sendfile -> "sendfile"
    | MacosSyscall.Sendmsg -> "sendmsg"
    | MacosSyscall.SendmsgNocancel -> "sendmsg_nocancel"
    | MacosSyscall.SendmsgX -> "sendmsg_x"
    | MacosSyscall.Sendto -> "sendto"
    | MacosSyscall.SendtoNocancel -> "sendto_nocancel"
    | MacosSyscall.Setattrlist -> "setattrlist"
    | MacosSyscall.Setattrlistat -> "setattrlistat"
    | MacosSyscall.SetauditAddr -> "setaudit_addr"
    | MacosSyscall.Setauid -> "setauid"
    | MacosSyscall.Setegid -> "setegid"
    | MacosSyscall.Seteuid -> "seteuid"
    | MacosSyscall.Setgid -> "setgid"
    | MacosSyscall.Setgroups -> "setgroups"
    | MacosSyscall.Setitimer -> "setitimer"
    | MacosSyscall.Setlogin -> "setlogin"
    | MacosSyscall.Setpgid -> "setpgid"
    | MacosSyscall.Setpriority -> "setpriority"
    | MacosSyscall.Setprivexec -> "setprivexec"
    | MacosSyscall.Setregid -> "setregid"
    | MacosSyscall.Setreuid -> "setreuid"
    | MacosSyscall.Setrlimit -> "setrlimit"
    | MacosSyscall.Setsgroups -> "setsgroups"
    | MacosSyscall.Setsid -> "setsid"
    | MacosSyscall.Setsockopt -> "setsockopt"
    | MacosSyscall.Settid -> "settid"
    | MacosSyscall.SettidWithPid -> "settid_with_pid"
    | MacosSyscall.Settimeofday -> "settimeofday"
    | MacosSyscall.Setuid -> "setuid"
    | MacosSyscall.Setwgroups -> "setwgroups"
    | MacosSyscall.Setxattr -> "setxattr"
    | MacosSyscall.SfiCtl -> "sfi_ctl"
    | MacosSyscall.SfiPidctl -> "sfi_pidctl"
    | MacosSyscall.SharedRegionCheckNp -> "shared_region_check_np"
    | MacosSyscall.SharedRegionMapAndSlide2Np ->
      "shared_region_map_and_slide_2_np"
    | MacosSyscall.ShmOpen -> "shm_open"
    | MacosSyscall.ShmUnlink -> "shm_unlink"
    | MacosSyscall.Shmat -> "shmat"
    | MacosSyscall.Shmctl -> "shmctl"
    | MacosSyscall.Shmdt -> "shmdt"
    | MacosSyscall.Shmget -> "shmget"
    | MacosSyscall.Shmsys -> "shmsys"
    | MacosSyscall.Shutdown -> "shutdown"
    | MacosSyscall.Sigaction -> "sigaction"
    | MacosSyscall.Sigaltstack -> "sigaltstack"
    | MacosSyscall.Sigpending -> "sigpending"
    | MacosSyscall.Sigprocmask -> "sigprocmask"
    | MacosSyscall.Sigreturn -> "sigreturn"
    | MacosSyscall.Sigsuspend -> "sigsuspend"
    | MacosSyscall.SigsuspendNocancel -> "sigsuspend_nocancel"
    | MacosSyscall.Socket -> "socket"
    | MacosSyscall.SocketDelegate -> "socket_delegate"
    | MacosSyscall.Socketpair -> "socketpair"
    | MacosSyscall.StackSnapshotWithConfig -> "stack_snapshot_with_config"
    | MacosSyscall.Stat -> "stat"
    | MacosSyscall.Stat64 -> "stat64"
    | MacosSyscall.Stat64Extended -> "stat64_extended"
    | MacosSyscall.StatExtended -> "stat_extended"
    | MacosSyscall.Statfs -> "statfs"
    | MacosSyscall.Statfs64 -> "statfs64"
    | MacosSyscall.Swapon -> "swapon"
    | MacosSyscall.Symlink -> "symlink"
    | MacosSyscall.Symlinkat -> "symlinkat"
    | MacosSyscall.Sync -> "sync"
    | MacosSyscall.Sysctl -> "sysctl"
    | MacosSyscall.Sysctlbyname -> "sysctlbyname"
    | MacosSyscall.SystemOverride -> "system_override"
    | MacosSyscall.TaskInspectForPid -> "task_inspect_for_pid"
    | MacosSyscall.TaskReadForPid -> "task_read_for_pid"
    | MacosSyscall.Telemetry -> "telemetry"
    | MacosSyscall.TerminateWithPayload -> "terminate_with_payload"
    | MacosSyscall.ThreadSelfcounts -> "thread_selfcounts"
    | MacosSyscall.ThreadSelfid -> "thread_selfid"
    | MacosSyscall.ThreadSelfusage -> "thread_selfusage"
    | MacosSyscall.TrackerAction -> "tracker_action"
    | MacosSyscall.Truncate -> "truncate"
    | MacosSyscall.UlockWait -> "ulock_wait"
    | MacosSyscall.UlockWait2 -> "ulock_wait2"
    | MacosSyscall.UlockWake -> "ulock_wake"
    | MacosSyscall.Umask -> "umask"
    | MacosSyscall.UmaskExtended -> "umask_extended"
    | MacosSyscall.Undelete -> "undelete"
    | MacosSyscall.Ungraftdmg -> "ungraftdmg"
    | MacosSyscall.Unlink -> "unlink"
    | MacosSyscall.Unlinkat -> "unlinkat"
    | MacosSyscall.Unmount -> "unmount"
    | MacosSyscall.Usrctl -> "usrctl"
    | MacosSyscall.Utimes -> "utimes"
    | MacosSyscall.Vfork -> "vfork"
    | MacosSyscall.VfsPurge -> "vfs_purge"
    | MacosSyscall.VmPressureMonitor -> "vm_pressure_monitor"
    | MacosSyscall.Wait4 -> "wait4"
    | MacosSyscall.Wait4Nocancel -> "wait4_nocancel"
    | MacosSyscall.Waitid -> "waitid"
    | MacosSyscall.WaitidNocancel -> "waitid_nocancel"
    | MacosSyscall.WorkIntervalCtl -> "work_interval_ctl"
    | MacosSyscall.WorkqKernreturn -> "workq_kernreturn"
    | MacosSyscall.WorkqOpen -> "workq_open"
    | MacosSyscall.Write -> "write"
    | MacosSyscall.WriteNocancel -> "write_nocancel"
    | MacosSyscall.Writev -> "writev"
    | MacosSyscall.WritevNocancel -> "writev_nocancel"
    | _ -> raise UnhandledSyscallException

  /// Converts a string to a MacosSyscall.
  [<CompiledName "OfString">]
  let ofString = function
    | "__channel_get_info" -> MacosSyscall.ChannelGetInfo
    | "__channel_get_opt" -> MacosSyscall.ChannelGetOpt
    | "__channel_open" -> MacosSyscall.ChannelOpen
    | "__channel_set_opt" -> MacosSyscall.ChannelSetOpt
    | "__channel_sync" -> MacosSyscall.ChannelSync
    | "__disable_threadsignal" -> MacosSyscall.DisableThreadsignal
    | "__mac_execve" -> MacosSyscall.MacExecve
    | "__mac_get_fd" -> MacosSyscall.MacGetFd
    | "__mac_get_file" -> MacosSyscall.MacGetFile
    | "__mac_get_link" -> MacosSyscall.MacGetLink
    | "__mac_get_mount" -> MacosSyscall.MacGetMount
    | "__mac_get_pid" -> MacosSyscall.MacGetPid
    | "__mac_get_proc" -> MacosSyscall.MacGetProc
    | "__mac_getfsstat" -> MacosSyscall.MacGetfsstat
    | "__mac_mount" -> MacosSyscall.MacMount
    | "__mac_set_fd" -> MacosSyscall.MacSetFd
    | "__mac_set_file" -> MacosSyscall.MacSetFile
    | "__mac_set_link" -> MacosSyscall.MacSetLink
    | "__mac_set_proc" -> MacosSyscall.MacSetProc
    | "__mac_syscall" -> MacosSyscall.MacSyscall
    | "__mach_bridge_remote_time" -> MacosSyscall.MachBridgeRemoteTime
    | "__nexus_create" -> MacosSyscall.NexusCreate
    | "__nexus_deregister" -> MacosSyscall.NexusDeregister
    | "__nexus_destroy" -> MacosSyscall.NexusDestroy
    | "__nexus_get_opt" -> MacosSyscall.NexusGetOpt
    | "__nexus_open" -> MacosSyscall.NexusOpen
    | "__nexus_register" -> MacosSyscall.NexusRegister
    | "__nexus_set_opt" -> MacosSyscall.NexusSetOpt
    | "__pthread_canceled" -> MacosSyscall.PthreadCanceled
    | "__pthread_chdir" -> MacosSyscall.PthreadChdir
    | "__pthread_fchdir" -> MacosSyscall.PthreadFchdir
    | "__pthread_kill" -> MacosSyscall.PthreadKill
    | "__pthread_markcancel" -> MacosSyscall.PthreadMarkcancel
    | "__pthread_sigmask" -> MacosSyscall.PthreadSigmask
    | "__semwait_signal" -> MacosSyscall.SemwaitSignal
    | "__semwait_signal_nocancel" -> MacosSyscall.SemwaitSignalNocancel
    | "__sigwait" -> MacosSyscall.Sigwait
    | "__sigwait_nocancel" -> MacosSyscall.SigwaitNocancel
    | "abort_with_payload" -> MacosSyscall.AbortWithPayload
    | "accept" -> MacosSyscall.Accept
    | "accept_nocancel" -> MacosSyscall.AcceptNocancel
    | "access" -> MacosSyscall.Access
    | "access_extended" -> MacosSyscall.AccessExtended
    | "acct" -> MacosSyscall.Acct
    | "adjtime" -> MacosSyscall.Adjtime
    | "aio_cancel" -> MacosSyscall.AioCancel
    | "aio_error" -> MacosSyscall.AioError
    | "aio_fsync" -> MacosSyscall.AioFsync
    | "aio_read" -> MacosSyscall.AioRead
    | "aio_return" -> MacosSyscall.AioReturn
    | "aio_suspend" -> MacosSyscall.AioSuspend
    | "aio_suspend_nocancel" -> MacosSyscall.AioSuspendNocancel
    | "aio_write" -> MacosSyscall.AioWrite
    | "audit" -> MacosSyscall.Audit
    | "audit_session_join" -> MacosSyscall.AuditSessionJoin
    | "audit_session_port" -> MacosSyscall.AuditSessionPort
    | "audit_session_self" -> MacosSyscall.AuditSessionSelf
    | "auditctl" -> MacosSyscall.Auditctl
    | "auditon" -> MacosSyscall.Auditon
    | "bind" -> MacosSyscall.Bind
    | "bsdthread_create" -> MacosSyscall.BsdthreadCreate
    | "bsdthread_ctl" -> MacosSyscall.BsdthreadCtl
    | "bsdthread_register" -> MacosSyscall.BsdthreadRegister
    | "bsdthread_terminate" -> MacosSyscall.BsdthreadTerminate
    | "change_fdguard_np" -> MacosSyscall.ChangeFdguardNp
    | "chdir" -> MacosSyscall.Chdir
    | "chflags" -> MacosSyscall.Chflags
    | "chmod" -> MacosSyscall.Chmod
    | "chmod_extended" -> MacosSyscall.ChmodExtended
    | "chown" -> MacosSyscall.Chown
    | "chroot" -> MacosSyscall.Chroot
    | "clonefileat" -> MacosSyscall.Clonefileat
    | "close" -> MacosSyscall.Close
    | "close_nocancel" -> MacosSyscall.CloseNocancel
    | "coalition" -> MacosSyscall.Coalition
    | "coalition_info" -> MacosSyscall.CoalitionInfo
    | "coalition_ledger" -> MacosSyscall.CoalitionLedger
    | "coalition_policy_get" -> MacosSyscall.CoalitionPolicyGet
    | "coalition_policy_set" -> MacosSyscall.CoalitionPolicySet
    | "connect" -> MacosSyscall.Connect
    | "connect_nocancel" -> MacosSyscall.ConnectNocancel
    | "connectx" -> MacosSyscall.Connectx
    | "copyfile" -> MacosSyscall.Copyfile
    | "crossarch_trap" -> MacosSyscall.CrossarchTrap
    | "csops" -> MacosSyscall.Csops
    | "csops_audittoken" -> MacosSyscall.CsopsAudittoken
    | "csrctl" -> MacosSyscall.Csrctl
    | "debug_syscall_reject" -> MacosSyscall.DebugSyscallReject
    | "debug_syscall_reject_config" -> MacosSyscall.DebugSyscallRejectConfig
    | "delete" -> MacosSyscall.Delete
    | "disconnectx" -> MacosSyscall.Disconnectx
    | "dup" -> MacosSyscall.Dup
    | "dup2" -> MacosSyscall.Dup2
    | "exchangedata" -> MacosSyscall.Exchangedata
    | "execve" -> MacosSyscall.Execve
    | "exit" -> MacosSyscall.Exit
    | "faccessat" -> MacosSyscall.Faccessat
    | "fchdir" -> MacosSyscall.Fchdir
    | "fchflags" -> MacosSyscall.Fchflags
    | "fchmod" -> MacosSyscall.Fchmod
    | "fchmod_extended" -> MacosSyscall.FchmodExtended
    | "fchmodat" -> MacosSyscall.Fchmodat
    | "fchown" -> MacosSyscall.Fchown
    | "fchownat" -> MacosSyscall.Fchownat
    | "fclonefileat" -> MacosSyscall.Fclonefileat
    | "fcntl" -> MacosSyscall.Fcntl
    | "fcntl_nocancel" -> MacosSyscall.FcntlNocancel
    | "fdatasync" -> MacosSyscall.Fdatasync
    | "ffsctl" -> MacosSyscall.Ffsctl
    | "fgetattrlist" -> MacosSyscall.Fgetattrlist
    | "fgetxattr" -> MacosSyscall.Fgetxattr
    | "fhopen" -> MacosSyscall.Fhopen
    | "fileport_makefd" -> MacosSyscall.FileportMakefd
    | "fileport_makeport" -> MacosSyscall.FileportMakeport
    | "flistxattr" -> MacosSyscall.Flistxattr
    | "flock" -> MacosSyscall.Flock
    | "fmount" -> MacosSyscall.Fmount
    | "fork" -> MacosSyscall.Fork
    | "fpathconf" -> MacosSyscall.Fpathconf
    | "freadlink" -> MacosSyscall.Freadlink
    | "fremovexattr" -> MacosSyscall.Fremovexattr
    | "fs_snapshot" -> MacosSyscall.FsSnapshot
    | "fsctl" -> MacosSyscall.Fsctl
    | "fsetattrlist" -> MacosSyscall.Fsetattrlist
    | "fsetxattr" -> MacosSyscall.Fsetxattr
    | "fsgetpath" -> MacosSyscall.Fsgetpath
    | "fsgetpath_ext" -> MacosSyscall.FsgetpathExt
    | "fstat" -> MacosSyscall.Fstat
    | "fstat64" -> MacosSyscall.Fstat64
    | "fstat64_extended" -> MacosSyscall.Fstat64Extended
    | "fstat_extended" -> MacosSyscall.FstatExtended
    | "fstatat" -> MacosSyscall.Fstatat
    | "fstatat64" -> MacosSyscall.Fstatat64
    | "fstatfs" -> MacosSyscall.Fstatfs
    | "fstatfs64" -> MacosSyscall.Fstatfs64
    | "fsync" -> MacosSyscall.Fsync
    | "fsync_nocancel" -> MacosSyscall.FsyncNocancel
    | "ftruncate" -> MacosSyscall.Ftruncate
    | "funmount" -> MacosSyscall.Funmount
    | "futimes" -> MacosSyscall.Futimes
    | "getattrlist" -> MacosSyscall.Getattrlist
    | "getattrlistat" -> MacosSyscall.Getattrlistat
    | "getattrlistbulk" -> MacosSyscall.Getattrlistbulk
    | "getaudit_addr" -> MacosSyscall.GetauditAddr
    | "getauid" -> MacosSyscall.Getauid
    | "getdirentries" -> MacosSyscall.Getdirentries
    | "getdirentries64" -> MacosSyscall.Getdirentries64
    | "getdirentriesattr" -> MacosSyscall.Getdirentriesattr
    | "getdtablesize" -> MacosSyscall.Getdtablesize
    | "getegid" -> MacosSyscall.Getegid
    | "getentropy" -> MacosSyscall.Getentropy
    | "geteuid" -> MacosSyscall.Geteuid
    | "getfh" -> MacosSyscall.Getfh
    | "getfsstat" -> MacosSyscall.Getfsstat
    | "getfsstat64" -> MacosSyscall.Getfsstat64
    | "getgid" -> MacosSyscall.Getgid
    | "getgroups" -> MacosSyscall.Getgroups
    | "gethostuuid" -> MacosSyscall.Gethostuuid
    | "getitimer" -> MacosSyscall.Getitimer
    | "getlogin" -> MacosSyscall.Getlogin
    | "getpeername" -> MacosSyscall.Getpeername
    | "getpgid" -> MacosSyscall.Getpgid
    | "getpgrp" -> MacosSyscall.Getpgrp
    | "getpid" -> MacosSyscall.Getpid
    | "getppid" -> MacosSyscall.Getppid
    | "getpriority" -> MacosSyscall.Getpriority
    | "getrlimit" -> MacosSyscall.Getrlimit
    | "getrusage" -> MacosSyscall.Getrusage
    | "getsgroups" -> MacosSyscall.Getsgroups
    | "getsid" -> MacosSyscall.Getsid
    | "getsockname" -> MacosSyscall.Getsockname
    | "getsockopt" -> MacosSyscall.Getsockopt
    | "gettid" -> MacosSyscall.Gettid
    | "gettimeofday" -> MacosSyscall.Gettimeofday
    | "getuid" -> MacosSyscall.Getuid
    | "getwgroups" -> MacosSyscall.Getwgroups
    | "getxattr" -> MacosSyscall.Getxattr
    | "grab_pgo_data" -> MacosSyscall.GrabPgoData
    | "graftdmg" -> MacosSyscall.Graftdmg
    | "guarded_close_np" -> MacosSyscall.GuardedCloseNp
    | "guarded_kqueue_np" -> MacosSyscall.GuardedKqueueNp
    | "guarded_open_dprotected_np" -> MacosSyscall.GuardedOpenDprotectedNp
    | "guarded_open_np" -> MacosSyscall.GuardedOpenNp
    | "guarded_pwrite_np" -> MacosSyscall.GuardedPwriteNp
    | "guarded_write_np" -> MacosSyscall.GuardedWriteNp
    | "guarded_writev_np" -> MacosSyscall.GuardedWritevNp
    | "identitysvc" -> MacosSyscall.Identitysvc
    | "initgroups" -> MacosSyscall.Initgroups
    | "ioctl" -> MacosSyscall.Ioctl
    | "iopolicysys" -> MacosSyscall.Iopolicysys
    | "issetugid" -> MacosSyscall.Issetugid
    | "kas_info" -> MacosSyscall.KasInfo
    | "kdebug_trace" -> MacosSyscall.KdebugTrace
    | "kdebug_trace64" -> MacosSyscall.KdebugTrace64
    | "kdebug_trace_string" -> MacosSyscall.KdebugTraceString
    | "kdebug_typefilter" -> MacosSyscall.KdebugTypefilter
    | "kevent" -> MacosSyscall.Kevent
    | "kevent64" -> MacosSyscall.Kevent64
    | "kevent_id" -> MacosSyscall.KeventId
    | "kevent_qos" -> MacosSyscall.KeventQos
    | "kill" -> MacosSyscall.Kill
    | "kqueue" -> MacosSyscall.Kqueue
    | "kqueue_workloop_ctl" -> MacosSyscall.KqueueWorkloopCtl
    | "lchown" -> MacosSyscall.Lchown
    | "ledger" -> MacosSyscall.Ledger
    | "link" -> MacosSyscall.Link
    | "linkat" -> MacosSyscall.Linkat
    | "lio_listio" -> MacosSyscall.LioListio
    | "listen" -> MacosSyscall.Listen
    | "listxattr" -> MacosSyscall.Listxattr
    | "log_data" -> MacosSyscall.LogData
    | "lseek" -> MacosSyscall.Lseek
    | "lstat" -> MacosSyscall.Lstat
    | "lstat64" -> MacosSyscall.Lstat64
    | "lstat64_extended" -> MacosSyscall.Lstat64Extended
    | "lstat_extended" -> MacosSyscall.LstatExtended
    | "mach_eventlink_signal" -> MacosSyscall.MachEventlinkSignal
    | "mach_eventlink_signal_wait_until" ->
      MacosSyscall.MachEventlinkSignalWaitUntil
    | "mach_eventlink_wait_until" -> MacosSyscall.MachEventlinkWaitUntil
    | "madvise" -> MacosSyscall.Madvise
    | "map_with_linking_np" -> MacosSyscall.MapWithLinkingNp
    | "memorystatus_available_memory" ->
      MacosSyscall.MemorystatusAvailableMemory
    | "memorystatus_control" -> MacosSyscall.MemorystatusControl
    | "memorystatus_get_level" -> MacosSyscall.MemorystatusGetLevel
    | "microstackshot" -> MacosSyscall.Microstackshot
    | "mincore" -> MacosSyscall.Mincore
    | "minherit" -> MacosSyscall.Minherit
    | "mkdir" -> MacosSyscall.Mkdir
    | "mkdir_extended" -> MacosSyscall.MkdirExtended
    | "mkdirat" -> MacosSyscall.Mkdirat
    | "mkfifo" -> MacosSyscall.Mkfifo
    | "mkfifo_extended" -> MacosSyscall.MkfifoExtended
    | "mkfifoat" -> MacosSyscall.Mkfifoat
    | "mknod" -> MacosSyscall.Mknod
    | "mknodat" -> MacosSyscall.Mknodat
    | "mlock" -> MacosSyscall.Mlock
    | "mlockall" -> MacosSyscall.Mlockall
    | "mmap" -> MacosSyscall.Mmap
    | "mount" -> MacosSyscall.Mount
    | "mprotect" -> MacosSyscall.Mprotect
    | "mremap_encrypted" -> MacosSyscall.MremapEncrypted
    | "msgctl" -> MacosSyscall.Msgctl
    | "msgget" -> MacosSyscall.Msgget
    | "msgrcv" -> MacosSyscall.Msgrcv
    | "msgrcv_nocancel" -> MacosSyscall.MsgrcvNocancel
    | "msgsnd" -> MacosSyscall.Msgsnd
    | "msgsnd_nocancel" -> MacosSyscall.MsgsndNocancel
    | "msgsys" -> MacosSyscall.Msgsys
    | "msync" -> MacosSyscall.Msync
    | "msync_nocancel" -> MacosSyscall.MsyncNocancel
    | "munlock" -> MacosSyscall.Munlock
    | "munlockall" -> MacosSyscall.Munlockall
    | "munmap" -> MacosSyscall.Munmap
    | "necp_client_action" -> MacosSyscall.NecpClientAction
    | "necp_match_policy" -> MacosSyscall.NecpMatchPolicy
    | "necp_open" -> MacosSyscall.NecpOpen
    | "necp_session_action" -> MacosSyscall.NecpSessionAction
    | "necp_session_open" -> MacosSyscall.NecpSessionOpen
    | "net_qos_guideline" -> MacosSyscall.NetQosGuideline
    | "netagent_trigger" -> MacosSyscall.NetagentTrigger
    | "nfssvc" -> MacosSyscall.Nfssvc
    | "ntp_adjtime" -> MacosSyscall.NtpAdjtime
    | "ntp_gettime" -> MacosSyscall.NtpGettime
    | "objc_bp_assist_cfg_np" -> MacosSyscall.ObjcBpAssistCfgNp
    | "open" -> MacosSyscall.Open
    | "open_dprotected_np" -> MacosSyscall.OpenDprotectedNp
    | "open_extended" -> MacosSyscall.OpenExtended
    | "open_nocancel" -> MacosSyscall.OpenNocancel
    | "openat" -> MacosSyscall.Openat
    | "openat_dprotected_np" -> MacosSyscall.OpenatDprotectedNp
    | "openat_nocancel" -> MacosSyscall.OpenatNocancel
    | "openbyid_np" -> MacosSyscall.OpenbyidNp
    | "os_fault_with_payload" -> MacosSyscall.OsFaultWithPayload
    | "oslog_coproc" -> MacosSyscall.OslogCoproc
    | "oslog_coproc_reg" -> MacosSyscall.OslogCoprocReg
    | "panic_with_data" -> MacosSyscall.PanicWithData
    | "pathconf" -> MacosSyscall.Pathconf
    | "peeloff" -> MacosSyscall.Peeloff
    | "persona" -> MacosSyscall.Persona
    | "pid_hibernate" -> MacosSyscall.PidHibernate
    | "pid_resume" -> MacosSyscall.PidResume
    | "pid_shutdown_sockets" -> MacosSyscall.PidShutdownSockets
    | "pid_suspend" -> MacosSyscall.PidSuspend
    | "pipe" -> MacosSyscall.Pipe
    | "pivot_root" -> MacosSyscall.PivotRoot
    | "poll" -> MacosSyscall.Poll
    | "poll_nocancel" -> MacosSyscall.PollNocancel
    | "posix_spawn" -> MacosSyscall.PosixSpawn
    | "pread" -> MacosSyscall.Pread
    | "pread_nocancel" -> MacosSyscall.PreadNocancel
    | "preadv" -> MacosSyscall.Preadv
    | "preadv_nocancel" -> MacosSyscall.PreadvNocancel
    | "proc_info" -> MacosSyscall.ProcInfo
    | "proc_info_extended_id" -> MacosSyscall.ProcInfoExtendedId
    | "proc_rlimit_control" -> MacosSyscall.ProcRlimitControl
    | "proc_trace_log" -> MacosSyscall.ProcTraceLog
    | "proc_uuid_policy" -> MacosSyscall.ProcUuidPolicy
    | "process_policy" -> MacosSyscall.ProcessPolicy
    | "pselect" -> MacosSyscall.Pselect
    | "pselect_nocancel" -> MacosSyscall.PselectNocancel
    | "psynch_cvbroad" -> MacosSyscall.PsynchCvbroad
    | "psynch_cvclrprepost" -> MacosSyscall.PsynchCvclrprepost
    | "psynch_cvsignal" -> MacosSyscall.PsynchCvsignal
    | "psynch_cvwait" -> MacosSyscall.PsynchCvwait
    | "psynch_mutexdrop" -> MacosSyscall.PsynchMutexdrop
    | "psynch_mutexwait" -> MacosSyscall.PsynchMutexwait
    | "psynch_rw_downgrade" -> MacosSyscall.PsynchRwDowngrade
    | "psynch_rw_longrdlock" -> MacosSyscall.PsynchRwLongrdlock
    | "psynch_rw_rdlock" -> MacosSyscall.PsynchRwRdlock
    | "psynch_rw_unlock" -> MacosSyscall.PsynchRwUnlock
    | "psynch_rw_unlock2" -> MacosSyscall.PsynchRwUnlock2
    | "psynch_rw_upgrade" -> MacosSyscall.PsynchRwUpgrade
    | "psynch_rw_wrlock" -> MacosSyscall.PsynchRwWrlock
    | "psynch_rw_yieldwrlock" -> MacosSyscall.PsynchRwYieldwrlock
    | "ptrace" -> MacosSyscall.Ptrace
    | "pwrite" -> MacosSyscall.Pwrite
    | "pwrite_nocancel" -> MacosSyscall.PwriteNocancel
    | "pwritev" -> MacosSyscall.Pwritev
    | "pwritev_nocancel" -> MacosSyscall.PwritevNocancel
    | "quotactl" -> MacosSyscall.Quotactl
    | "read" -> MacosSyscall.Read
    | "read_nocancel" -> MacosSyscall.ReadNocancel
    | "readlink" -> MacosSyscall.Readlink
    | "readlinkat" -> MacosSyscall.Readlinkat
    | "readv" -> MacosSyscall.Readv
    | "readv_nocancel" -> MacosSyscall.ReadvNocancel
    | "reboot" -> MacosSyscall.Reboot
    | "record_system_event" -> MacosSyscall.RecordSystemEvent
    | "recvfrom" -> MacosSyscall.Recvfrom
    | "recvfrom_nocancel" -> MacosSyscall.RecvfromNocancel
    | "recvmsg" -> MacosSyscall.Recvmsg
    | "recvmsg_nocancel" -> MacosSyscall.RecvmsgNocancel
    | "recvmsg_x" -> MacosSyscall.RecvmsgX
    | "removexattr" -> MacosSyscall.Removexattr
    | "rename" -> MacosSyscall.Rename
    | "renameat" -> MacosSyscall.Renameat
    | "renameatx_np" -> MacosSyscall.RenameatxNp
    | "revoke" -> MacosSyscall.Revoke
    | "rmdir" -> MacosSyscall.Rmdir
    | "searchfs" -> MacosSyscall.Searchfs
    | "select" -> MacosSyscall.Select
    | "select_nocancel" -> MacosSyscall.SelectNocancel
    | "sem_close" -> MacosSyscall.SemClose
    | "sem_open" -> MacosSyscall.SemOpen
    | "sem_post" -> MacosSyscall.SemPost
    | "sem_trywait" -> MacosSyscall.SemTrywait
    | "sem_unlink" -> MacosSyscall.SemUnlink
    | "sem_wait" -> MacosSyscall.SemWait
    | "sem_wait_nocancel" -> MacosSyscall.SemWaitNocancel
    | "semctl" -> MacosSyscall.Semctl
    | "semget" -> MacosSyscall.Semget
    | "semop" -> MacosSyscall.Semop
    | "semsys" -> MacosSyscall.Semsys
    | "sendfile" -> MacosSyscall.Sendfile
    | "sendmsg" -> MacosSyscall.Sendmsg
    | "sendmsg_nocancel" -> MacosSyscall.SendmsgNocancel
    | "sendmsg_x" -> MacosSyscall.SendmsgX
    | "sendto" -> MacosSyscall.Sendto
    | "sendto_nocancel" -> MacosSyscall.SendtoNocancel
    | "setattrlist" -> MacosSyscall.Setattrlist
    | "setattrlistat" -> MacosSyscall.Setattrlistat
    | "setaudit_addr" -> MacosSyscall.SetauditAddr
    | "setauid" -> MacosSyscall.Setauid
    | "setegid" -> MacosSyscall.Setegid
    | "seteuid" -> MacosSyscall.Seteuid
    | "setgid" -> MacosSyscall.Setgid
    | "setgroups" -> MacosSyscall.Setgroups
    | "setitimer" -> MacosSyscall.Setitimer
    | "setlogin" -> MacosSyscall.Setlogin
    | "setpgid" -> MacosSyscall.Setpgid
    | "setpriority" -> MacosSyscall.Setpriority
    | "setprivexec" -> MacosSyscall.Setprivexec
    | "setregid" -> MacosSyscall.Setregid
    | "setreuid" -> MacosSyscall.Setreuid
    | "setrlimit" -> MacosSyscall.Setrlimit
    | "setsgroups" -> MacosSyscall.Setsgroups
    | "setsid" -> MacosSyscall.Setsid
    | "setsockopt" -> MacosSyscall.Setsockopt
    | "settid" -> MacosSyscall.Settid
    | "settid_with_pid" -> MacosSyscall.SettidWithPid
    | "settimeofday" -> MacosSyscall.Settimeofday
    | "setuid" -> MacosSyscall.Setuid
    | "setwgroups" -> MacosSyscall.Setwgroups
    | "setxattr" -> MacosSyscall.Setxattr
    | "sfi_ctl" -> MacosSyscall.SfiCtl
    | "sfi_pidctl" -> MacosSyscall.SfiPidctl
    | "shared_region_check_np" -> MacosSyscall.SharedRegionCheckNp
    | "shared_region_map_and_slide_2_np" ->
      MacosSyscall.SharedRegionMapAndSlide2Np
    | "shm_open" -> MacosSyscall.ShmOpen
    | "shm_unlink" -> MacosSyscall.ShmUnlink
    | "shmat" -> MacosSyscall.Shmat
    | "shmctl" -> MacosSyscall.Shmctl
    | "shmdt" -> MacosSyscall.Shmdt
    | "shmget" -> MacosSyscall.Shmget
    | "shmsys" -> MacosSyscall.Shmsys
    | "shutdown" -> MacosSyscall.Shutdown
    | "sigaction" -> MacosSyscall.Sigaction
    | "sigaltstack" -> MacosSyscall.Sigaltstack
    | "sigpending" -> MacosSyscall.Sigpending
    | "sigprocmask" -> MacosSyscall.Sigprocmask
    | "sigreturn" -> MacosSyscall.Sigreturn
    | "sigsuspend" -> MacosSyscall.Sigsuspend
    | "sigsuspend_nocancel" -> MacosSyscall.SigsuspendNocancel
    | "socket" -> MacosSyscall.Socket
    | "socket_delegate" -> MacosSyscall.SocketDelegate
    | "socketpair" -> MacosSyscall.Socketpair
    | "stack_snapshot_with_config" -> MacosSyscall.StackSnapshotWithConfig
    | "stat" -> MacosSyscall.Stat
    | "stat64" -> MacosSyscall.Stat64
    | "stat64_extended" -> MacosSyscall.Stat64Extended
    | "stat_extended" -> MacosSyscall.StatExtended
    | "statfs" -> MacosSyscall.Statfs
    | "statfs64" -> MacosSyscall.Statfs64
    | "swapon" -> MacosSyscall.Swapon
    | "symlink" -> MacosSyscall.Symlink
    | "symlinkat" -> MacosSyscall.Symlinkat
    | "sync" -> MacosSyscall.Sync
    | "sysctl" -> MacosSyscall.Sysctl
    | "sysctlbyname" -> MacosSyscall.Sysctlbyname
    | "system_override" -> MacosSyscall.SystemOverride
    | "task_inspect_for_pid" -> MacosSyscall.TaskInspectForPid
    | "task_read_for_pid" -> MacosSyscall.TaskReadForPid
    | "telemetry" -> MacosSyscall.Telemetry
    | "terminate_with_payload" -> MacosSyscall.TerminateWithPayload
    | "thread_selfcounts" -> MacosSyscall.ThreadSelfcounts
    | "thread_selfid" -> MacosSyscall.ThreadSelfid
    | "thread_selfusage" -> MacosSyscall.ThreadSelfusage
    | "tracker_action" -> MacosSyscall.TrackerAction
    | "truncate" -> MacosSyscall.Truncate
    | "ulock_wait" -> MacosSyscall.UlockWait
    | "ulock_wait2" -> MacosSyscall.UlockWait2
    | "ulock_wake" -> MacosSyscall.UlockWake
    | "umask" -> MacosSyscall.Umask
    | "umask_extended" -> MacosSyscall.UmaskExtended
    | "undelete" -> MacosSyscall.Undelete
    | "ungraftdmg" -> MacosSyscall.Ungraftdmg
    | "unlink" -> MacosSyscall.Unlink
    | "unlinkat" -> MacosSyscall.Unlinkat
    | "unmount" -> MacosSyscall.Unmount
    | "usrctl" -> MacosSyscall.Usrctl
    | "utimes" -> MacosSyscall.Utimes
    | "vfork" -> MacosSyscall.Vfork
    | "vfs_purge" -> MacosSyscall.VfsPurge
    | "vm_pressure_monitor" -> MacosSyscall.VmPressureMonitor
    | "wait4" -> MacosSyscall.Wait4
    | "wait4_nocancel" -> MacosSyscall.Wait4Nocancel
    | "waitid" -> MacosSyscall.Waitid
    | "waitid_nocancel" -> MacosSyscall.WaitidNocancel
    | "work_interval_ctl" -> MacosSyscall.WorkIntervalCtl
    | "workq_kernreturn" -> MacosSyscall.WorkqKernreturn
    | "workq_open" -> MacosSyscall.WorkqOpen
    | "write" -> MacosSyscall.Write
    | "write_nocancel" -> MacosSyscall.WriteNocancel
    | "writev" -> MacosSyscall.Writev
    | "writev_nocancel" -> MacosSyscall.WritevNocancel
    | _ -> raise UnhandledSyscallException
