(*
  B2R2 - the Next-Generation Reversing Platform

  Copyright (c) SoftSec Lab. @ KAIST, since 2016

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*)

namespace B2R2

/// Raised when unhandled syscall is encountered.
exception UnhandledSyscallException

/// Linux syscall type.
type LinuxSyscall =
  | Accept = 1
  | Accept4 = 2
  | Access = 3
  | Acct = 4
  | AddKey = 5
  | AdjTimex = 6
  | Alarm = 7
  | AllocHugePages = 8
  | ArcGetTLS = 9
  | ArcSetTLS = 10
  | ArcUsrCmpxchg = 11
  | ArchPrctl = 12
  | AtomicBarrier = 13
  | AtomicCmpxchg32 = 14
  | Bdflush = 15
  | BfinSpinlock = 16
  | Bind = 17
  | Bpf = 18
  | Brk = 19
  | Breakpoint = 20
  | CacheFlush = 21
  | CapGet = 22
  | CapSet = 23
  | Chdir = 24
  | Chmod = 25
  | Chown = 26
  | Chown32 = 27
  | Chroot = 28
  | ClockAdjtime = 29
  | ClockGetres = 30
  | ClockGettime = 31
  | ClockNanosleep = 32
  | ClockSettime = 33
  | Clone2 = 34
  | Clone = 35
  | Clone3 = 36
  | Close = 37
  | CmpxchgBadaddr = 38
  | Connect = 39
  | CopyFileRange = 40
  | Creat = 41
  | CreateModule = 42
  | DeleteModule = 43
  | DmaMemcpy = 44
  | Dup = 45
  | Dup2 = 46
  | Dup3 = 47
  | EpollCreate = 48
  | EpollCreate1 = 49
  | EpollCtl = 50
  | EpollPwait = 51
  | EpollWait = 52
  | Eventfd = 53
  | Eventfd2 = 54
  | Execv = 55
  | Execve = 56
  | Execveat = 57
  | Exit = 58
  | ExitGroup = 59
  | Faccessat = 60
  | Fadvise64 = 61
  | Fallocate = 62
  | FanotifyInit = 63
  | FanotifyMark = 64
  | Fchdir = 65
  | Fchmod = 66
  | Fchmodat = 67
  | Fchown = 68
  | Fchown32 = 69
  | Fchownat = 70
  | Fcntl = 71
  | Fcntl64 = 72
  | Fdatasync = 73
  | Fgetxattr = 74
  | FinitModule = 75
  | Flistxattr = 76
  | Flock = 77
  | Fork = 78
  | FreeHugepages = 79
  | Fremovexattr = 80
  | Fsconfig = 81
  | Fsetxattr = 82
  | Fsmount = 83
  | Fsopen = 84
  | Fspick = 85
  | Fstat = 86
  | Fstat64 = 87
  | Fstatat64 = 88
  | Fstatfs = 89
  | Fstatfs64 = 90
  | Fsync = 91
  | Ftruncate = 92
  | Ftruncate64 = 93
  | Futex = 94
  | Futimesat = 95
  | GetKernelSyms = 96
  | GetMempolicy = 97
  | GetRobustList = 98
  | GetThreadArea = 99
  | GetTLS = 100
  | Getcpu = 101
  | Getcwd = 102
  | Getdents = 103
  | Getdents64 = 104
  | Getdomainname = 105
  | Getdtablesize = 106
  | Getegid = 107
  | Getegid32 = 108
  | Geteuid = 109
  | Geteuid32 = 110
  | Getgid = 111
  | Getgid32 = 112
  | Getgroups = 113
  | Getgroups32 = 114
  | Gethostname = 115
  | Getitimer = 116
  | Getpeername = 117
  | Getpagesize = 118
  | Getpgid = 119
  | Getpgrp = 120
  | Getpid = 121
  | Getppid = 122
  | Getpriority = 123
  | Getrandom = 124
  | Getresgid = 125
  | Getresgid32 = 126
  | Getresuid = 127
  | Getresuid32 = 128
  | Getrlimit = 129
  | Getrusage = 130
  | Getsid = 131
  | Getsockname = 132
  | Getsockopt = 133
  | Gettid = 134
  | Gettimeofday = 135
  | Getuid = 136
  | Getuid32 = 137
  | Getunwind = 138
  | Getxattr = 139
  | Getxgid = 140
  | Getxpid = 141
  | Getxuid = 142
  | InitModule = 143
  | InotifyAddWatch = 144
  | InotifyInit = 145
  | InotifyInit1 = 146
  | InotifyRmWatch = 147
  | IoCancel = 148
  | IoDestroy = 149
  | IoGetevents = 150
  | IoPgetevents = 151
  | IoSetup = 152
  | IoSubmit = 153
  | IoUringEnter = 154
  | IoUringRegister = 155
  | IoUringSetup = 156
  | Ioctl = 157
  | Ioperm = 158
  | Iopl = 159
  | IoprioGet = 160
  | IoprioSet = 161
  | Ipc = 162
  | Kcmp = 163
  | KernFeatures = 164
  | KexecFileLoad = 165
  | KexecLoad = 166
  | Keyctl = 167
  | Kill = 168
  | Lchown = 169
  | Lchown32 = 170
  | Lgetxattr = 171
  | Link = 172
  | Linkat = 173
  | Listen = 174
  | Listxattr = 175
  | Llistxattr = 176
  | LookupDcookie = 177
  | Lremovexattr = 178
  | Lseek = 179
  | LLseek = 180
  | Lsetxattr = 181
  | Lstat = 182
  | Lstat64 = 183
  | Madvise = 184
  | Mbind = 185
  | MemoryOrdering = 186
  | MetagGetTLS = 187
  | MetagSetFpuFlags = 188
  | MetagSetTLS = 189
  | MetagSetglobalbit = 190
  | Membarrier = 191
  | MemfdCreate = 192
  | MigratePages = 193
  | Mincore = 194
  | Mkdir = 195
  | Mkdirat = 196
  | Mknod = 197
  | Mknodat = 198
  | Mlock = 199
  | Mlock2 = 200
  | Mlockall = 201
  | Mmap = 202
  | Mmap2 = 203
  | ModifyLdt = 204
  | Mount = 205
  | MoveMount = 206
  | MovePages = 207
  | Mprotect = 208
  | MqGetsetattr = 209
  | MqNotify = 210
  | MqOpen = 211
  | MqTimedreceive = 212
  | MqTimedsend = 213
  | MqUnlink = 214
  | Mremap = 215
  | Msgctl = 216
  | Msgget = 217
  | Msgrcv = 218
  | Msgsnd = 219
  | Msync = 220
  | Munlock = 221
  | Munlockall = 222
  | Munmap = 223
  | NameToHandleAt = 224
  | Nanosleep = 225
  | Newfstatat = 226
  | NewSelect = 227
  | Nfsservctl = 228
  | Nice = 229
  | OldAdjtimex = 230
  | OldGetrlimit = 231
  | Oldfstat = 232
  | Oldlstat = 233
  | Oldolduname = 234
  | Oldstat = 235
  | Oldumount = 236
  | Olduname = 237
  | Open = 238
  | OpenByHandleAt = 239
  | OpenTree = 240
  | Openat = 241
  | Openat2 = 242
  | Or1kAtomic = 243
  | Pause = 244
  | PciconfigIobase = 245
  | PciconfigRead = 246
  | PciconfigWrite = 247
  | PerfEventOpen = 248
  | Personality = 249
  | Perfctr = 250
  | Perfmonctl = 251
  | PidfdGetfd = 252
  | PidfdSendSignal = 253
  | PidfdOpen = 254
  | Pipe = 255
  | Pipe2 = 256
  | PivotRoot = 257
  | PkeyAlloc = 258
  | PkeyFree = 259
  | PkeyMprotect = 260
  | Poll = 261
  | Ppoll = 262
  | Prctl = 263
  | Pread = 264
  | Pread64 = 265
  | Preadv = 266
  | Preadv2 = 267
  | Prlimit64 = 268
  | ProcessVmReadv = 269
  | ProcessVmWritev = 270
  | Pselect6 = 271
  | Ptrace = 272
  | Pwrite = 273
  | Pwrite64 = 274
  | Pwritev = 275
  | Pwritev2 = 276
  | QueryModule = 277
  | Quotactl = 278
  | Read = 279
  | Readahead = 280
  | Readdir = 281
  | Readlink = 282
  | Readlinkat = 283
  | Readv = 284
  | Reboot = 285
  | Recv = 286
  | Recvfrom = 287
  | Recvmsg = 288
  | Recvmmsg = 289
  | RemapFilePages = 290
  | Removexattr = 291
  | Rename = 292
  | Renameat = 293
  | Renameat2 = 294
  | RequestKey = 295
  | RestartSyscall = 296
  | RiscvFlushIcache = 297
  | Rmdir = 298
  | Rseq = 299
  | RtSigaction = 300
  | RtSigpending = 301
  | RtSigprocmask = 302
  | RtSigqueueinfo = 303
  | RtSigreturn = 304
  | RtSigsuspend = 305
  | RtSigtimedwait = 306
  | RtTgsigqueueinfo = 307
  | Rtas = 308
  | S390RuntimeInstr = 309
  | S390PciMmioRead = 310
  | S390PciMmioWrite = 311
  | S390Sthyi = 312
  | S390GuardedStorage = 313
  | SchedGetAffinity = 314
  | SchedGetPriorityMax = 315
  | SchedGetPriorityMin = 316
  | SchedGetaffinity = 317
  | SchedGetattr = 318
  | SchedGetparam = 319
  | SchedGetscheduler = 320
  | SchedRrGetInterval = 321
  | SchedSetAffinity = 322
  | SchedSetaffinity = 323
  | SchedSetattr = 324
  | SchedSetparam = 325
  | SchedSetscheduler = 326
  | SchedYield = 327
  | Seccomp = 328
  | Select = 329
  | Semctl = 330
  | Semget = 331
  | Semop = 332
  | Semtimedop = 333
  | Send = 334
  | Sendfile = 335
  | Sendfile64 = 336
  | Sendmmsg = 337
  | Sendmsg = 338
  | Sendto = 339
  | SetMempolicy = 340
  | SetRobustList = 341
  | SetThreadArea = 342
  | SetTidAddress = 343
  | SetTLS = 344
  | Setdomainname = 345
  | Setfsgid = 346
  | Setfsgid32 = 347
  | Setfsuid = 348
  | Setfsuid32 = 349
  | Setgid = 350
  | Setgid32 = 351
  | Setgroups = 352
  | Setgroups32 = 353
  | Sethae = 354
  | Sethostname = 355
  | Setitimer = 356
  | Setns = 357
  | Setpgid = 358
  | Setpgrp = 359
  | Setpriority = 360
  | Setregid = 361
  | Setregid32 = 362
  | Setresgid = 363
  | Setresgid32 = 364
  | Setresuid = 365
  | Setresuid32 = 366
  | Setreuid = 367
  | Setreuid32 = 368
  | Setrlimit = 369
  | Setsid = 370
  | Setsockopt = 371
  | Settimeofday = 372
  | Setuid = 373
  | Setuid32 = 374
  | Setup = 375
  | Setxattr = 376
  | Sgetmask = 377
  | Shmat = 378
  | Shmctl = 379
  | Shmdt = 380
  | Shmget = 381
  | Shutdown = 382
  | Sigaction = 383
  | Sigaltstack = 384
  | Signal = 385
  | Signalfd = 386
  | Signalfd4 = 387
  | Sigpending = 388
  | Sigprocmask = 389
  | Sigreturn = 390
  | Sigsuspend = 391
  | Socket = 392
  | Socketcall = 393
  | Socketpair = 394
  | Spill = 395
  | Splice = 396
  | SpuCreate = 397
  | SpuRun = 398
  | SramAlloc = 399
  | SramFree = 400
  | Ssetmask = 401
  | Stat = 402
  | Stat64 = 403
  | Statfs = 404
  | Statfs64 = 405
  | Statx = 406
  | Stime = 407
  | SubpageProt = 408
  | SwitchEndian = 409
  | Swapcontext = 410
  | Swapoff = 411
  | Swapon = 412
  | Symlink = 413
  | Symlinkat = 414
  | Sync = 415
  | SyncFileRange = 416
  | SyncFileRange2 = 417
  | Syncfs = 418
  | SysDebugSetcontext = 419
  | Syscall = 420
  | Sysctl = 421
  | Sysfs = 422
  | Sysinfo = 423
  | Syslog = 424
  | Sysmips = 425
  | Tee = 426
  | Tgkill = 427
  | Time = 428
  | TimerCreate = 429
  | TimerDelete = 430
  | TimerGetoverrun = 431
  | TimerGettime = 432
  | TimerSettime = 433
  | TimerfdCreate = 434
  | TimerfdGettime = 435
  | TimerfdSettime = 436
  | Times = 437
  | Tkill = 438
  | Truncate = 439
  | Truncate64 = 440
  | Ugetrlimit = 441
  | Umask = 442
  | Umount = 443
  | Umount2 = 444
  | Uname = 445
  | Unlink = 446
  | Unlinkat = 447
  | Unshare = 448
  | Uselib = 449
  | Ustat = 450
  | Userfaultfd = 451
  | Usr26 = 452
  | Usr32 = 453
  | Utime = 454
  | Utimensat = 455
  | Utimes = 456
  | UtrapInstall = 457
  | Vfork = 458
  | Vhangup = 459
  | Vm86old = 460
  | Vm86 = 461
  | Vmsplice = 462
  | Wait4 = 463
  | Waitid = 464
  | Waitpid = 465
  | Write = 466
  | Writev = 467
  | Xtensa = 468

module LinuxSyscall =
  let private getX86Number = function
    | LinuxSyscall.RestartSyscall -> 0
    | LinuxSyscall.Exit -> 1
    | LinuxSyscall.Fork -> 2
    | LinuxSyscall.Read -> 3
    | LinuxSyscall.Write -> 4
    | LinuxSyscall.Open -> 5
    | LinuxSyscall.Close -> 6
    | LinuxSyscall.Waitpid -> 7
    | LinuxSyscall.Creat -> 8
    | LinuxSyscall.Link -> 9
    | LinuxSyscall.Unlink -> 10
    | LinuxSyscall.Execve -> 11
    | LinuxSyscall.Chdir -> 12
    | LinuxSyscall.Time -> 13
    | LinuxSyscall.Mknod -> 14
    | LinuxSyscall.Chmod -> 15
    | LinuxSyscall.Lchown -> 16
    | LinuxSyscall.Oldstat -> 18
    | LinuxSyscall.Lseek -> 19
    | LinuxSyscall.Getpid -> 20
    | LinuxSyscall.Mount -> 21
    | LinuxSyscall.Umount -> 22
    | LinuxSyscall.Setuid -> 23
    | LinuxSyscall.Getuid -> 24
    | LinuxSyscall.Stime -> 25
    | LinuxSyscall.Ptrace -> 26
    | LinuxSyscall.Alarm -> 27
    | LinuxSyscall.Oldfstat -> 28
    | LinuxSyscall.Pause -> 29
    | LinuxSyscall.Utime -> 30
    | LinuxSyscall.Access -> 33
    | LinuxSyscall.Nice -> 34
    | LinuxSyscall.Sync -> 36
    | LinuxSyscall.Kill -> 37
    | LinuxSyscall.Rename -> 38
    | LinuxSyscall.Mkdir -> 39
    | LinuxSyscall.Rmdir -> 40
    | LinuxSyscall.Dup -> 41
    | LinuxSyscall.Pipe -> 42
    | LinuxSyscall.Times -> 43
    | LinuxSyscall.Brk -> 45
    | LinuxSyscall.Setgid -> 46
    | LinuxSyscall.Getgid -> 47
    | LinuxSyscall.Signal -> 48
    | LinuxSyscall.Geteuid -> 49
    | LinuxSyscall.Getegid -> 50
    | LinuxSyscall.Acct -> 51
    | LinuxSyscall.Umount2 -> 52
    | LinuxSyscall.Ioctl -> 54
    | LinuxSyscall.Fcntl -> 55
    | LinuxSyscall.Setpgid -> 57
    | LinuxSyscall.Oldolduname -> 59
    | LinuxSyscall.Umask -> 60
    | LinuxSyscall.Chroot -> 61
    | LinuxSyscall.Ustat -> 62
    | LinuxSyscall.Dup2 -> 63
    | LinuxSyscall.Getppid -> 64
    | LinuxSyscall.Getpgrp -> 65
    | LinuxSyscall.Setsid -> 66
    | LinuxSyscall.Sigaction -> 67
    | LinuxSyscall.Sgetmask -> 68
    | LinuxSyscall.Ssetmask -> 69
    | LinuxSyscall.Setreuid -> 70
    | LinuxSyscall.Setregid -> 71
    | LinuxSyscall.Sigsuspend -> 72
    | LinuxSyscall.Sigpending -> 73
    | LinuxSyscall.Sethostname -> 74
    | LinuxSyscall.Setrlimit -> 75
    | LinuxSyscall.Getrlimit -> 76
    | LinuxSyscall.Getrusage -> 77
    | LinuxSyscall.Gettimeofday -> 78
    | LinuxSyscall.Settimeofday -> 79
    | LinuxSyscall.Getgroups -> 80
    | LinuxSyscall.Setgroups -> 81
    | LinuxSyscall.Select -> 82
    | LinuxSyscall.Symlink -> 83
    | LinuxSyscall.Oldlstat -> 84
    | LinuxSyscall.Readlink -> 85
    | LinuxSyscall.Uselib -> 86
    | LinuxSyscall.Swapon -> 87
    | LinuxSyscall.Reboot -> 88
    | LinuxSyscall.Readdir -> 89
    | LinuxSyscall.Mmap -> 90
    | LinuxSyscall.Munmap -> 91
    | LinuxSyscall.Truncate -> 92
    | LinuxSyscall.Ftruncate -> 93
    | LinuxSyscall.Fchmod -> 94
    | LinuxSyscall.Fchown -> 95
    | LinuxSyscall.Getpriority -> 96
    | LinuxSyscall.Setpriority -> 97
    | LinuxSyscall.Statfs -> 99
    | LinuxSyscall.Fstatfs -> 100
    | LinuxSyscall.Ioperm -> 101
    | LinuxSyscall.Socketcall -> 102
    | LinuxSyscall.Syslog -> 103
    | LinuxSyscall.Setitimer -> 104
    | LinuxSyscall.Getitimer -> 105
    | LinuxSyscall.Stat -> 106
    | LinuxSyscall.Lstat -> 107
    | LinuxSyscall.Fstat -> 108
    | LinuxSyscall.Olduname -> 109
    | LinuxSyscall.Iopl -> 110
    | LinuxSyscall.Vhangup -> 111
    | LinuxSyscall.Vm86old -> 113
    | LinuxSyscall.Wait4 -> 114
    | LinuxSyscall.Swapoff -> 115
    | LinuxSyscall.Sysinfo -> 116
    | LinuxSyscall.Ipc -> 117
    | LinuxSyscall.Fsync -> 118
    | LinuxSyscall.Sigreturn -> 119
    | LinuxSyscall.Clone -> 120
    | LinuxSyscall.Setdomainname -> 121
    | LinuxSyscall.Uname -> 122
    | LinuxSyscall.ModifyLdt -> 123
    | LinuxSyscall.AdjTimex -> 124
    | LinuxSyscall.Mprotect -> 125
    | LinuxSyscall.Sigprocmask -> 126
    | LinuxSyscall.CreateModule -> 127
    | LinuxSyscall.InitModule -> 128
    | LinuxSyscall.DeleteModule -> 129
    | LinuxSyscall.GetKernelSyms -> 130
    | LinuxSyscall.Quotactl -> 131
    | LinuxSyscall.Getpgid -> 132
    | LinuxSyscall.Fchdir -> 133
    | LinuxSyscall.Bdflush -> 134
    | LinuxSyscall.Sysfs -> 135
    | LinuxSyscall.Personality -> 136
    | LinuxSyscall.Setfsuid -> 138
    | LinuxSyscall.Setfsgid -> 139
    | LinuxSyscall.LLseek -> 140
    | LinuxSyscall.Getdents -> 141
    | LinuxSyscall.NewSelect -> 142
    | LinuxSyscall.Flock -> 143
    | LinuxSyscall.Msync -> 144
    | LinuxSyscall.Readv -> 145
    | LinuxSyscall.Writev -> 146
    | LinuxSyscall.Getsid -> 147
    | LinuxSyscall.Fdatasync -> 148
    | LinuxSyscall.Sysctl -> 149
    | LinuxSyscall.Mlock -> 150
    | LinuxSyscall.Munlock -> 151
    | LinuxSyscall.Mlockall -> 152
    | LinuxSyscall.Munlockall -> 153
    | LinuxSyscall.SchedSetparam -> 154
    | LinuxSyscall.SchedGetparam -> 155
    | LinuxSyscall.SchedSetscheduler -> 156
    | LinuxSyscall.SchedGetscheduler -> 157
    | LinuxSyscall.SchedYield -> 158
    | LinuxSyscall.SchedGetPriorityMax -> 159
    | LinuxSyscall.SchedGetPriorityMin -> 160
    | LinuxSyscall.SchedRrGetInterval -> 161
    | LinuxSyscall.Nanosleep -> 162
    | LinuxSyscall.Mremap -> 163
    | LinuxSyscall.Setresuid -> 164
    | LinuxSyscall.Getresuid -> 165
    | LinuxSyscall.Vm86 -> 166
    | LinuxSyscall.QueryModule -> 167
    | LinuxSyscall.Poll -> 168
    | LinuxSyscall.Nfsservctl -> 169
    | LinuxSyscall.Setresgid -> 170
    | LinuxSyscall.Getresgid -> 171
    | LinuxSyscall.Prctl -> 172
    | LinuxSyscall.RtSigreturn -> 173
    | LinuxSyscall.RtSigaction -> 174
    | LinuxSyscall.RtSigprocmask -> 175
    | LinuxSyscall.RtSigpending -> 176
    | LinuxSyscall.RtSigtimedwait -> 177
    | LinuxSyscall.RtSigqueueinfo -> 178
    | LinuxSyscall.RtSigsuspend -> 179
    | LinuxSyscall.Pread64 -> 180
    | LinuxSyscall.Pwrite64 -> 181
    | LinuxSyscall.Chown -> 182
    | LinuxSyscall.Getcwd -> 183
    | LinuxSyscall.CapGet -> 184
    | LinuxSyscall.CapSet -> 185
    | LinuxSyscall.Sigaltstack -> 186
    | LinuxSyscall.Sendfile -> 187
    | LinuxSyscall.Vfork -> 190
    | LinuxSyscall.Ugetrlimit -> 191
    | LinuxSyscall.Mmap2 -> 192
    | LinuxSyscall.Truncate64 -> 193
    | LinuxSyscall.Ftruncate64 -> 194
    | LinuxSyscall.Stat64 -> 195
    | LinuxSyscall.Lstat64 -> 196
    | LinuxSyscall.Fstat64 -> 197
    | LinuxSyscall.Lchown32 -> 198
    | LinuxSyscall.Getuid32 -> 199
    | LinuxSyscall.Getgid32 -> 200
    | LinuxSyscall.Geteuid32 -> 201
    | LinuxSyscall.Getegid32 -> 202
    | LinuxSyscall.Setreuid32 -> 203
    | LinuxSyscall.Setregid32 -> 204
    | LinuxSyscall.Getgroups32 -> 205
    | LinuxSyscall.Setgroups32 -> 206
    | LinuxSyscall.Fchown32 -> 207
    | LinuxSyscall.Setresuid32 -> 208
    | LinuxSyscall.Getresuid32 -> 209
    | LinuxSyscall.Setresgid32 -> 210
    | LinuxSyscall.Getresgid32 -> 211
    | LinuxSyscall.Chown32 -> 212
    | LinuxSyscall.Setuid32 -> 213
    | LinuxSyscall.Setgid32 -> 214
    | LinuxSyscall.Setfsuid32 -> 215
    | LinuxSyscall.Setfsgid32 -> 216
    | LinuxSyscall.PivotRoot -> 217
    | LinuxSyscall.Mincore -> 218
    | LinuxSyscall.Madvise -> 219
    | LinuxSyscall.Getdents64 -> 220
    | LinuxSyscall.Fcntl64 -> 221
    | LinuxSyscall.Gettid -> 224
    | LinuxSyscall.Readahead -> 225
    | LinuxSyscall.Setxattr -> 226
    | LinuxSyscall.Lsetxattr -> 227
    | LinuxSyscall.Fsetxattr -> 228
    | LinuxSyscall.Getxattr -> 229
    | LinuxSyscall.Lgetxattr -> 230
    | LinuxSyscall.Fgetxattr -> 231
    | LinuxSyscall.Listxattr -> 232
    | LinuxSyscall.Llistxattr -> 233
    | LinuxSyscall.Flistxattr -> 234
    | LinuxSyscall.Removexattr -> 235
    | LinuxSyscall.Lremovexattr -> 236
    | LinuxSyscall.Fremovexattr -> 237
    | LinuxSyscall.Tkill -> 238
    | LinuxSyscall.Sendfile64 -> 239
    | LinuxSyscall.Futex -> 240
    | LinuxSyscall.SchedSetaffinity -> 241
    | LinuxSyscall.SchedGetaffinity -> 242
    | LinuxSyscall.SetThreadArea -> 243
    | LinuxSyscall.GetThreadArea -> 244
    | LinuxSyscall.IoSetup -> 245
    | LinuxSyscall.IoDestroy -> 246
    | LinuxSyscall.IoGetevents -> 247
    | LinuxSyscall.IoSubmit -> 248
    | LinuxSyscall.IoCancel -> 249
    | LinuxSyscall.Fadvise64 -> 250
    | LinuxSyscall.ExitGroup -> 252
    | LinuxSyscall.LookupDcookie -> 253
    | LinuxSyscall.EpollCreate -> 254
    | LinuxSyscall.EpollCtl -> 255
    | LinuxSyscall.EpollWait -> 256
    | LinuxSyscall.RemapFilePages -> 257
    | LinuxSyscall.SetTidAddress -> 258
    | LinuxSyscall.TimerCreate -> 259
    | LinuxSyscall.TimerSettime -> 260
    | LinuxSyscall.TimerGettime -> 261
    | LinuxSyscall.TimerGetoverrun -> 262
    | LinuxSyscall.TimerDelete -> 263
    | LinuxSyscall.ClockSettime -> 264
    | LinuxSyscall.ClockGettime -> 265
    | LinuxSyscall.ClockGetres -> 266
    | LinuxSyscall.ClockNanosleep -> 267
    | LinuxSyscall.Statfs64 -> 268
    | LinuxSyscall.Fstatfs64 -> 269
    | LinuxSyscall.Tgkill -> 270
    | LinuxSyscall.Utimes -> 271
    | LinuxSyscall.Mbind -> 274
    | LinuxSyscall.GetMempolicy -> 275
    | LinuxSyscall.SetMempolicy -> 276
    | LinuxSyscall.MqOpen -> 277
    | LinuxSyscall.MqUnlink -> 278
    | LinuxSyscall.MqTimedsend -> 279
    | LinuxSyscall.MqTimedreceive -> 280
    | LinuxSyscall.MqNotify -> 281
    | LinuxSyscall.MqGetsetattr -> 282
    | LinuxSyscall.KexecLoad -> 283
    | LinuxSyscall.Waitid -> 284
    | LinuxSyscall.AddKey -> 286
    | LinuxSyscall.RequestKey -> 287
    | LinuxSyscall.Keyctl -> 288
    | LinuxSyscall.IoprioSet -> 289
    | LinuxSyscall.IoprioGet -> 290
    | LinuxSyscall.InotifyInit -> 291
    | LinuxSyscall.InotifyAddWatch -> 292
    | LinuxSyscall.InotifyRmWatch -> 293
    | LinuxSyscall.MigratePages -> 294
    | LinuxSyscall.Openat -> 295
    | LinuxSyscall.Mkdirat -> 296
    | LinuxSyscall.Mknodat -> 297
    | LinuxSyscall.Fchownat -> 298
    | LinuxSyscall.Futimesat -> 299
    | LinuxSyscall.Fstatat64 -> 300
    | LinuxSyscall.Unlinkat -> 301
    | LinuxSyscall.Renameat -> 302
    | LinuxSyscall.Linkat -> 303
    | LinuxSyscall.Symlinkat -> 304
    | LinuxSyscall.Readlinkat -> 305
    | LinuxSyscall.Fchmodat -> 306
    | LinuxSyscall.Faccessat -> 307
    | LinuxSyscall.Pselect6 -> 308
    | LinuxSyscall.Ppoll -> 309
    | LinuxSyscall.Unshare -> 310
    | LinuxSyscall.SetRobustList -> 311
    | LinuxSyscall.GetRobustList -> 312
    | LinuxSyscall.Splice -> 313
    | LinuxSyscall.SyncFileRange -> 314
    | LinuxSyscall.Tee -> 315
    | LinuxSyscall.Vmsplice -> 316
    | LinuxSyscall.MovePages -> 317
    | LinuxSyscall.Getcpu -> 318
    | LinuxSyscall.EpollPwait -> 319
    | LinuxSyscall.Utimensat -> 320
    | LinuxSyscall.Signalfd -> 321
    | LinuxSyscall.TimerfdCreate -> 322
    | LinuxSyscall.Eventfd -> 323
    | LinuxSyscall.Fallocate -> 324
    | LinuxSyscall.TimerfdSettime -> 325
    | LinuxSyscall.TimerfdGettime -> 326
    | LinuxSyscall.Signalfd4 -> 327
    | LinuxSyscall.Eventfd2 -> 328
    | LinuxSyscall.EpollCreate1 -> 329
    | LinuxSyscall.Dup3 -> 330
    | LinuxSyscall.Pipe2 -> 331
    | LinuxSyscall.InotifyInit1 -> 332
    | LinuxSyscall.Preadv -> 333
    | LinuxSyscall.Pwritev -> 334
    | LinuxSyscall.RtTgsigqueueinfo -> 335
    | LinuxSyscall.PerfEventOpen -> 336
    | LinuxSyscall.Recvmmsg -> 337
    | LinuxSyscall.FanotifyInit -> 338
    | LinuxSyscall.FanotifyMark -> 339
    | LinuxSyscall.Prlimit64 -> 340
    | LinuxSyscall.NameToHandleAt -> 341
    | LinuxSyscall.OpenByHandleAt -> 342
    | LinuxSyscall.ClockAdjtime -> 343
    | LinuxSyscall.Syncfs -> 344
    | LinuxSyscall.Sendmmsg -> 345
    | LinuxSyscall.Setns -> 346
    | LinuxSyscall.ProcessVmReadv -> 347
    | LinuxSyscall.ProcessVmWritev -> 348
    | LinuxSyscall.Kcmp -> 349
    | LinuxSyscall.FinitModule -> 350
    | LinuxSyscall.SchedSetattr -> 351
    | LinuxSyscall.SchedGetattr -> 352
    | LinuxSyscall.Renameat2 -> 353
    | LinuxSyscall.Seccomp -> 354
    | LinuxSyscall.Getrandom -> 355
    | LinuxSyscall.MemfdCreate -> 356
    | LinuxSyscall.Bpf -> 357
    | LinuxSyscall.Execveat -> 358
    | LinuxSyscall.Socket -> 359
    | LinuxSyscall.Socketpair -> 360
    | LinuxSyscall.Bind -> 361
    | LinuxSyscall.Connect -> 362
    | LinuxSyscall.Listen -> 363
    | LinuxSyscall.Accept4 -> 364
    | LinuxSyscall.Getsockopt -> 365
    | LinuxSyscall.Setsockopt -> 366
    | LinuxSyscall.Getsockname -> 367
    | LinuxSyscall.Getpeername -> 368
    | LinuxSyscall.Sendto -> 369
    | LinuxSyscall.Sendmsg -> 370
    | LinuxSyscall.Recvfrom -> 371
    | LinuxSyscall.Recvmsg -> 372
    | LinuxSyscall.Shutdown -> 373
    | LinuxSyscall.Userfaultfd -> 374
    | LinuxSyscall.Membarrier -> 375
    | LinuxSyscall.Mlock2 -> 376
    | LinuxSyscall.CopyFileRange -> 377
    | LinuxSyscall.Preadv2 -> 378
    | LinuxSyscall.Pwritev2 -> 379
    | LinuxSyscall.PkeyMprotect -> 380
    | LinuxSyscall.PkeyAlloc -> 381
    | LinuxSyscall.PkeyFree -> 382
    | LinuxSyscall.Statx -> 383
    | LinuxSyscall.ArchPrctl -> 384
    | _ -> raise UnhandledSyscallException

  let private getX64Number = function
    | LinuxSyscall.Read -> 0
    | LinuxSyscall.Write -> 1
    | LinuxSyscall.Open -> 2
    | LinuxSyscall.Close -> 3
    | LinuxSyscall.Stat -> 4
    | LinuxSyscall.Fstat -> 5
    | LinuxSyscall.Lstat -> 6
    | LinuxSyscall.Poll -> 7
    | LinuxSyscall.Lseek -> 8
    | LinuxSyscall.Mmap -> 9
    | LinuxSyscall.Mprotect -> 10
    | LinuxSyscall.Munmap -> 11
    | LinuxSyscall.Brk -> 12
    | LinuxSyscall.RtSigaction -> 13
    | LinuxSyscall.RtSigprocmask -> 14
    | LinuxSyscall.RtSigreturn -> 15
    | LinuxSyscall.Ioctl -> 16
    | LinuxSyscall.Pread64 -> 17
    | LinuxSyscall.Pwrite64 -> 18
    | LinuxSyscall.Readv -> 19
    | LinuxSyscall.Writev -> 20
    | LinuxSyscall.Access -> 21
    | LinuxSyscall.Pipe -> 22
    | LinuxSyscall.Select -> 23
    | LinuxSyscall.SchedYield -> 24
    | LinuxSyscall.Mremap -> 25
    | LinuxSyscall.Msync -> 26
    | LinuxSyscall.Mincore -> 27
    | LinuxSyscall.Madvise -> 28
    | LinuxSyscall.Shmget -> 29
    | LinuxSyscall.Shmat -> 30
    | LinuxSyscall.Shmctl -> 31
    | LinuxSyscall.Dup -> 32
    | LinuxSyscall.Dup2 -> 33
    | LinuxSyscall.Pause -> 34
    | LinuxSyscall.Nanosleep -> 35
    | LinuxSyscall.Getitimer -> 36
    | LinuxSyscall.Alarm -> 37
    | LinuxSyscall.Setitimer -> 38
    | LinuxSyscall.Getpid -> 39
    | LinuxSyscall.Sendfile -> 40
    | LinuxSyscall.Socket -> 41
    | LinuxSyscall.Connect -> 42
    | LinuxSyscall.Accept -> 43
    | LinuxSyscall.Sendto -> 44
    | LinuxSyscall.Recvfrom -> 45
    | LinuxSyscall.Sendmsg -> 46
    | LinuxSyscall.Recvmsg -> 47
    | LinuxSyscall.Shutdown -> 48
    | LinuxSyscall.Bind -> 49
    | LinuxSyscall.Listen -> 50
    | LinuxSyscall.Getsockname -> 51
    | LinuxSyscall.Getpeername -> 52
    | LinuxSyscall.Socketpair -> 53
    | LinuxSyscall.Setsockopt -> 54
    | LinuxSyscall.Getsockopt -> 55
    | LinuxSyscall.Clone -> 56
    | LinuxSyscall.Fork -> 57
    | LinuxSyscall.Vfork -> 58
    | LinuxSyscall.Execve -> 59
    | LinuxSyscall.Exit -> 60
    | LinuxSyscall.Wait4 -> 61
    | LinuxSyscall.Kill -> 62
    | LinuxSyscall.Uname -> 63
    | LinuxSyscall.Semget -> 64
    | LinuxSyscall.Semop -> 65
    | LinuxSyscall.Semctl -> 66
    | LinuxSyscall.Shmdt -> 67
    | LinuxSyscall.Msgget -> 68
    | LinuxSyscall.Msgsnd -> 69
    | LinuxSyscall.Msgrcv -> 70
    | LinuxSyscall.Msgctl -> 71
    | LinuxSyscall.Fcntl -> 72
    | LinuxSyscall.Flock -> 73
    | LinuxSyscall.Fsync -> 74
    | LinuxSyscall.Fdatasync -> 75
    | LinuxSyscall.Truncate -> 76
    | LinuxSyscall.Ftruncate -> 77
    | LinuxSyscall.Getdents -> 78
    | LinuxSyscall.Getcwd -> 79
    | LinuxSyscall.Chdir -> 80
    | LinuxSyscall.Fchdir -> 81
    | LinuxSyscall.Rename -> 82
    | LinuxSyscall.Mkdir -> 83
    | LinuxSyscall.Rmdir -> 84
    | LinuxSyscall.Creat -> 85
    | LinuxSyscall.Link -> 86
    | LinuxSyscall.Unlink -> 87
    | LinuxSyscall.Symlink -> 88
    | LinuxSyscall.Readlink -> 89
    | LinuxSyscall.Chmod -> 90
    | LinuxSyscall.Fchmod -> 91
    | LinuxSyscall.Chown -> 92
    | LinuxSyscall.Fchown -> 93
    | LinuxSyscall.Lchown -> 94
    | LinuxSyscall.Umask -> 95
    | LinuxSyscall.Gettimeofday -> 96
    | LinuxSyscall.Getrlimit -> 97
    | LinuxSyscall.Getrusage -> 98
    | LinuxSyscall.Sysinfo -> 99
    | LinuxSyscall.Times -> 100
    | LinuxSyscall.Ptrace -> 101
    | LinuxSyscall.Getuid -> 102
    | LinuxSyscall.Syslog -> 103
    | LinuxSyscall.Getgid -> 104
    | LinuxSyscall.Setuid -> 105
    | LinuxSyscall.Setgid -> 106
    | LinuxSyscall.Geteuid -> 107
    | LinuxSyscall.Getegid -> 108
    | LinuxSyscall.Setpgid -> 109
    | LinuxSyscall.Getppid -> 110
    | LinuxSyscall.Getpgrp -> 111
    | LinuxSyscall.Setsid -> 112
    | LinuxSyscall.Setreuid -> 113
    | LinuxSyscall.Setregid -> 114
    | LinuxSyscall.Getgroups -> 115
    | LinuxSyscall.Setgroups -> 116
    | LinuxSyscall.Setresuid -> 117
    | LinuxSyscall.Getresuid -> 118
    | LinuxSyscall.Setresgid -> 119
    | LinuxSyscall.Getresgid -> 120
    | LinuxSyscall.Getpgid -> 121
    | LinuxSyscall.Setfsuid -> 122
    | LinuxSyscall.Setfsgid -> 123
    | LinuxSyscall.Getsid -> 124
    | LinuxSyscall.CapGet -> 125
    | LinuxSyscall.CapSet -> 126
    | LinuxSyscall.RtSigpending -> 127
    | LinuxSyscall.RtSigtimedwait -> 128
    | LinuxSyscall.RtSigqueueinfo -> 129
    | LinuxSyscall.RtSigsuspend -> 130
    | LinuxSyscall.Sigaltstack -> 131
    | LinuxSyscall.Utime -> 132
    | LinuxSyscall.Mknod -> 133
    | LinuxSyscall.Uselib -> 134
    | LinuxSyscall.Personality -> 135
    | LinuxSyscall.Ustat -> 136
    | LinuxSyscall.Statfs -> 137
    | LinuxSyscall.Fstatfs -> 138
    | LinuxSyscall.Sysfs -> 139
    | LinuxSyscall.Getpriority -> 140
    | LinuxSyscall.Setpriority -> 141
    | LinuxSyscall.SchedSetparam -> 142
    | LinuxSyscall.SchedGetparam -> 143
    | LinuxSyscall.SchedSetscheduler -> 144
    | LinuxSyscall.SchedGetscheduler -> 145
    | LinuxSyscall.SchedGetPriorityMax -> 146
    | LinuxSyscall.SchedGetPriorityMin -> 147
    | LinuxSyscall.SchedRrGetInterval -> 148
    | LinuxSyscall.Mlock -> 149
    | LinuxSyscall.Munlock -> 150
    | LinuxSyscall.Mlockall -> 151
    | LinuxSyscall.Munlockall -> 152
    | LinuxSyscall.Vhangup -> 153
    | LinuxSyscall.ModifyLdt -> 154
    | LinuxSyscall.PivotRoot -> 155
    | LinuxSyscall.Sysctl -> 156
    | LinuxSyscall.Prctl -> 157
    | LinuxSyscall.ArchPrctl -> 158
    | LinuxSyscall.AdjTimex -> 159
    | LinuxSyscall.Setrlimit -> 160
    | LinuxSyscall.Chroot -> 161
    | LinuxSyscall.Sync -> 162
    | LinuxSyscall.Acct -> 163
    | LinuxSyscall.Settimeofday -> 164
    | LinuxSyscall.Mount -> 165
    | LinuxSyscall.Umount2 -> 166
    | LinuxSyscall.Swapon -> 167
    | LinuxSyscall.Swapoff -> 168
    | LinuxSyscall.Reboot -> 169
    | LinuxSyscall.Sethostname -> 170
    | LinuxSyscall.Setdomainname -> 171
    | LinuxSyscall.Iopl -> 172
    | LinuxSyscall.Ioperm -> 173
    | LinuxSyscall.CreateModule -> 174
    | LinuxSyscall.InitModule -> 175
    | LinuxSyscall.DeleteModule -> 176
    | LinuxSyscall.GetKernelSyms -> 177
    | LinuxSyscall.QueryModule -> 178
    | LinuxSyscall.Quotactl -> 179
    | LinuxSyscall.Nfsservctl -> 180
    | LinuxSyscall.Gettid -> 186
    | LinuxSyscall.Readahead -> 187
    | LinuxSyscall.Setxattr -> 188
    | LinuxSyscall.Lsetxattr -> 189
    | LinuxSyscall.Fsetxattr -> 190
    | LinuxSyscall.Getxattr -> 191
    | LinuxSyscall.Lgetxattr -> 192
    | LinuxSyscall.Fgetxattr -> 193
    | LinuxSyscall.Listxattr -> 194
    | LinuxSyscall.Llistxattr -> 195
    | LinuxSyscall.Flistxattr -> 196
    | LinuxSyscall.Removexattr -> 197
    | LinuxSyscall.Lremovexattr -> 198
    | LinuxSyscall.Fremovexattr -> 199
    | LinuxSyscall.Tkill -> 200
    | LinuxSyscall.Time -> 201
    | LinuxSyscall.Futex -> 202
    | LinuxSyscall.SchedSetaffinity -> 203
    | LinuxSyscall.SchedGetaffinity -> 204
    | LinuxSyscall.SetThreadArea -> 205
    | LinuxSyscall.IoSetup -> 206
    | LinuxSyscall.IoDestroy -> 207
    | LinuxSyscall.IoGetevents -> 208
    | LinuxSyscall.IoSubmit -> 209
    | LinuxSyscall.IoCancel -> 210
    | LinuxSyscall.GetThreadArea -> 211
    | LinuxSyscall.LookupDcookie -> 212
    | LinuxSyscall.EpollCreate -> 213
    | LinuxSyscall.RemapFilePages -> 216
    | LinuxSyscall.Getdents64 -> 217
    | LinuxSyscall.SetTidAddress -> 218
    | LinuxSyscall.RestartSyscall -> 219
    | LinuxSyscall.Semtimedop -> 220
    | LinuxSyscall.Fadvise64 -> 221
    | LinuxSyscall.TimerCreate -> 222
    | LinuxSyscall.TimerSettime -> 223
    | LinuxSyscall.TimerGettime -> 224
    | LinuxSyscall.TimerGetoverrun -> 225
    | LinuxSyscall.TimerDelete -> 226
    | LinuxSyscall.ClockSettime -> 227
    | LinuxSyscall.ClockGettime -> 228
    | LinuxSyscall.ClockGetres -> 229
    | LinuxSyscall.ClockNanosleep -> 230
    | LinuxSyscall.ExitGroup -> 231
    | LinuxSyscall.EpollWait -> 232
    | LinuxSyscall.EpollCtl -> 233
    | LinuxSyscall.Tgkill -> 234
    | LinuxSyscall.Utimes -> 235
    | LinuxSyscall.Mbind -> 237
    | LinuxSyscall.SetMempolicy -> 238
    | LinuxSyscall.GetMempolicy -> 239
    | LinuxSyscall.MqOpen -> 240
    | LinuxSyscall.MqUnlink -> 241
    | LinuxSyscall.MqTimedsend -> 242
    | LinuxSyscall.MqTimedreceive -> 243
    | LinuxSyscall.MqNotify -> 244
    | LinuxSyscall.MqGetsetattr -> 245
    | LinuxSyscall.KexecLoad -> 246
    | LinuxSyscall.Waitid -> 247
    | LinuxSyscall.AddKey -> 248
    | LinuxSyscall.RequestKey -> 249
    | LinuxSyscall.Keyctl -> 250
    | LinuxSyscall.IoprioSet -> 251
    | LinuxSyscall.IoprioGet -> 252
    | LinuxSyscall.InotifyInit -> 253
    | LinuxSyscall.InotifyAddWatch -> 254
    | LinuxSyscall.InotifyRmWatch -> 255
    | LinuxSyscall.MigratePages -> 256
    | LinuxSyscall.Openat -> 257
    | LinuxSyscall.Mkdirat -> 258
    | LinuxSyscall.Mknodat -> 259
    | LinuxSyscall.Fchownat -> 260
    | LinuxSyscall.Futimesat -> 261
    | LinuxSyscall.Newfstatat -> 262
    | LinuxSyscall.Unlinkat -> 263
    | LinuxSyscall.Renameat -> 264
    | LinuxSyscall.Linkat -> 265
    | LinuxSyscall.Symlinkat -> 266
    | LinuxSyscall.Readlinkat -> 267
    | LinuxSyscall.Fchmodat -> 268
    | LinuxSyscall.Faccessat -> 269
    | LinuxSyscall.Pselect6 -> 270
    | LinuxSyscall.Ppoll -> 271
    | LinuxSyscall.Unshare -> 272
    | LinuxSyscall.SetRobustList -> 273
    | LinuxSyscall.GetRobustList -> 274
    | LinuxSyscall.Splice -> 275
    | LinuxSyscall.Tee -> 276
    | LinuxSyscall.SyncFileRange -> 277
    | LinuxSyscall.Vmsplice -> 278
    | LinuxSyscall.MovePages -> 279
    | LinuxSyscall.Utimensat -> 280
    | LinuxSyscall.EpollPwait -> 281
    | LinuxSyscall.Signalfd -> 282
    | LinuxSyscall.TimerfdCreate -> 283
    | LinuxSyscall.Eventfd -> 284
    | LinuxSyscall.Fallocate -> 285
    | LinuxSyscall.TimerfdSettime -> 286
    | LinuxSyscall.TimerfdGettime -> 287
    | LinuxSyscall.Accept4 -> 288
    | LinuxSyscall.Signalfd4 -> 289
    | LinuxSyscall.Eventfd2 -> 290
    | LinuxSyscall.EpollCreate1 -> 291
    | LinuxSyscall.Dup3 -> 292
    | LinuxSyscall.Pipe2 -> 293
    | LinuxSyscall.InotifyInit1 -> 294
    | LinuxSyscall.Preadv -> 295
    | LinuxSyscall.Pwritev -> 296
    | LinuxSyscall.RtTgsigqueueinfo -> 297
    | LinuxSyscall.PerfEventOpen -> 298
    | LinuxSyscall.Recvmmsg -> 299
    | LinuxSyscall.FanotifyInit -> 300
    | LinuxSyscall.FanotifyMark -> 301
    | LinuxSyscall.Prlimit64 -> 302
    | LinuxSyscall.NameToHandleAt -> 303
    | LinuxSyscall.OpenByHandleAt -> 304
    | LinuxSyscall.ClockAdjtime -> 305
    | LinuxSyscall.Syncfs -> 306
    | LinuxSyscall.Sendmmsg -> 307
    | LinuxSyscall.Setns -> 308
    | LinuxSyscall.Getcpu -> 309
    | LinuxSyscall.ProcessVmReadv -> 310
    | LinuxSyscall.ProcessVmWritev -> 311
    | LinuxSyscall.Kcmp -> 312
    | LinuxSyscall.FinitModule -> 313
    | LinuxSyscall.SchedSetattr -> 314
    | LinuxSyscall.SchedGetattr -> 315
    | LinuxSyscall.Renameat2 -> 316
    | LinuxSyscall.Seccomp -> 317
    | LinuxSyscall.Getrandom -> 318
    | LinuxSyscall.MemfdCreate -> 319
    | LinuxSyscall.KexecFileLoad -> 320
    | LinuxSyscall.Bpf -> 321
    | LinuxSyscall.Execveat -> 322
    | LinuxSyscall.Userfaultfd -> 323
    | LinuxSyscall.Membarrier -> 324
    | LinuxSyscall.Mlock2 -> 325
    | LinuxSyscall.CopyFileRange -> 326
    | LinuxSyscall.Preadv2 -> 327
    | LinuxSyscall.Pwritev2 -> 328
    | LinuxSyscall.PkeyMprotect -> 329
    | LinuxSyscall.PkeyAlloc -> 330
    | LinuxSyscall.PkeyFree -> 331
    | LinuxSyscall.Statx -> 332
    | _ -> raise UnhandledSyscallException

  let toNumber arch syscall =
    match arch with
    | Arch.IntelX86 -> getX86Number syscall
    | Arch.IntelX64 -> getX64Number syscall
    | _ -> raise UnhandledSyscallException

  let private getX86Syscall = function
    | 0 -> LinuxSyscall.RestartSyscall
    | 1 -> LinuxSyscall.Exit
    | 2 -> LinuxSyscall.Fork
    | 3 -> LinuxSyscall.Read
    | 4 -> LinuxSyscall.Write
    | 5 -> LinuxSyscall.Open
    | 6 -> LinuxSyscall.Close
    | 7 -> LinuxSyscall.Waitpid
    | 8 -> LinuxSyscall.Creat
    | 9 -> LinuxSyscall.Link
    | 10 -> LinuxSyscall.Unlink
    | 11 -> LinuxSyscall.Execve
    | 12 -> LinuxSyscall.Chdir
    | 13 -> LinuxSyscall.Time
    | 14 -> LinuxSyscall.Mknod
    | 15 -> LinuxSyscall.Chmod
    | 16 -> LinuxSyscall.Lchown
    | 18 -> LinuxSyscall.Oldstat
    | 19 -> LinuxSyscall.Lseek
    | 20 -> LinuxSyscall.Getpid
    | 21 -> LinuxSyscall.Mount
    | 22 -> LinuxSyscall.Umount
    | 23 -> LinuxSyscall.Setuid
    | 24 -> LinuxSyscall.Getuid
    | 25 -> LinuxSyscall.Stime
    | 26 -> LinuxSyscall.Ptrace
    | 27 -> LinuxSyscall.Alarm
    | 28 -> LinuxSyscall.Oldfstat
    | 29 -> LinuxSyscall.Pause
    | 30 -> LinuxSyscall.Utime
    | 33 -> LinuxSyscall.Access
    | 34 -> LinuxSyscall.Nice
    | 36 -> LinuxSyscall.Sync
    | 37 -> LinuxSyscall.Kill
    | 38 -> LinuxSyscall.Rename
    | 39 -> LinuxSyscall.Mkdir
    | 40 -> LinuxSyscall.Rmdir
    | 41 -> LinuxSyscall.Dup
    | 42 -> LinuxSyscall.Pipe
    | 43 -> LinuxSyscall.Times
    | 45 -> LinuxSyscall.Brk
    | 46 -> LinuxSyscall.Setgid
    | 47 -> LinuxSyscall.Getgid
    | 48 -> LinuxSyscall.Signal
    | 49 -> LinuxSyscall.Geteuid
    | 50 -> LinuxSyscall.Getegid
    | 51 -> LinuxSyscall.Acct
    | 52 -> LinuxSyscall.Umount2
    | 54 -> LinuxSyscall.Ioctl
    | 55 -> LinuxSyscall.Fcntl
    | 57 -> LinuxSyscall.Setpgid
    | 59 -> LinuxSyscall.Oldolduname
    | 60 -> LinuxSyscall.Umask
    | 61 -> LinuxSyscall.Chroot
    | 62 -> LinuxSyscall.Ustat
    | 63 -> LinuxSyscall.Dup2
    | 64 -> LinuxSyscall.Getppid
    | 65 -> LinuxSyscall.Getpgrp
    | 66 -> LinuxSyscall.Setsid
    | 67 -> LinuxSyscall.Sigaction
    | 68 -> LinuxSyscall.Sgetmask
    | 69 -> LinuxSyscall.Ssetmask
    | 70 -> LinuxSyscall.Setreuid
    | 71 -> LinuxSyscall.Setregid
    | 72 -> LinuxSyscall.Sigsuspend
    | 73 -> LinuxSyscall.Sigpending
    | 74 -> LinuxSyscall.Sethostname
    | 75 -> LinuxSyscall.Setrlimit
    | 76 -> LinuxSyscall.Getrlimit
    | 77 -> LinuxSyscall.Getrusage
    | 78 -> LinuxSyscall.Gettimeofday
    | 79 -> LinuxSyscall.Settimeofday
    | 80 -> LinuxSyscall.Getgroups
    | 81 -> LinuxSyscall.Setgroups
    | 82 -> LinuxSyscall.Select
    | 83 -> LinuxSyscall.Symlink
    | 84 -> LinuxSyscall.Oldlstat
    | 85 -> LinuxSyscall.Readlink
    | 86 -> LinuxSyscall.Uselib
    | 87 -> LinuxSyscall.Swapon
    | 88 -> LinuxSyscall.Reboot
    | 89 -> LinuxSyscall.Readdir
    | 90 -> LinuxSyscall.Mmap
    | 91 -> LinuxSyscall.Munmap
    | 92 -> LinuxSyscall.Truncate
    | 93 -> LinuxSyscall.Ftruncate
    | 94 -> LinuxSyscall.Fchmod
    | 95 -> LinuxSyscall.Fchown
    | 96 -> LinuxSyscall.Getpriority
    | 97 -> LinuxSyscall.Setpriority
    | 99 -> LinuxSyscall.Statfs
    | 100 -> LinuxSyscall.Fstatfs
    | 101 -> LinuxSyscall.Ioperm
    | 102 -> LinuxSyscall.Socketcall
    | 103 -> LinuxSyscall.Syslog
    | 104 -> LinuxSyscall.Setitimer
    | 105 -> LinuxSyscall.Getitimer
    | 106 -> LinuxSyscall.Stat
    | 107 -> LinuxSyscall.Lstat
    | 108 -> LinuxSyscall.Fstat
    | 109 -> LinuxSyscall.Olduname
    | 110 -> LinuxSyscall.Iopl
    | 111 -> LinuxSyscall.Vhangup
    | 113 -> LinuxSyscall.Vm86old
    | 114 -> LinuxSyscall.Wait4
    | 115 -> LinuxSyscall.Swapoff
    | 116 -> LinuxSyscall.Sysinfo
    | 117 -> LinuxSyscall.Ipc
    | 118 -> LinuxSyscall.Fsync
    | 119 -> LinuxSyscall.Sigreturn
    | 120 -> LinuxSyscall.Clone
    | 121 -> LinuxSyscall.Setdomainname
    | 122 -> LinuxSyscall.Uname
    | 123 -> LinuxSyscall.ModifyLdt
    | 124 -> LinuxSyscall.AdjTimex
    | 125 -> LinuxSyscall.Mprotect
    | 126 -> LinuxSyscall.Sigprocmask
    | 127 -> LinuxSyscall.CreateModule
    | 128 -> LinuxSyscall.InitModule
    | 129 -> LinuxSyscall.DeleteModule
    | 130 -> LinuxSyscall.GetKernelSyms
    | 131 -> LinuxSyscall.Quotactl
    | 132 -> LinuxSyscall.Getpgid
    | 133 -> LinuxSyscall.Fchdir
    | 134 -> LinuxSyscall.Bdflush
    | 135 -> LinuxSyscall.Sysfs
    | 136 -> LinuxSyscall.Personality
    | 138 -> LinuxSyscall.Setfsuid
    | 139 -> LinuxSyscall.Setfsgid
    | 140 -> LinuxSyscall.LLseek
    | 141 -> LinuxSyscall.Getdents
    | 142 -> LinuxSyscall.NewSelect
    | 143 -> LinuxSyscall.Flock
    | 144 -> LinuxSyscall.Msync
    | 145 -> LinuxSyscall.Readv
    | 146 -> LinuxSyscall.Writev
    | 147 -> LinuxSyscall.Getsid
    | 148 -> LinuxSyscall.Fdatasync
    | 149 -> LinuxSyscall.Sysctl
    | 150 -> LinuxSyscall.Mlock
    | 151 -> LinuxSyscall.Munlock
    | 152 -> LinuxSyscall.Mlockall
    | 153 -> LinuxSyscall.Munlockall
    | 154 -> LinuxSyscall.SchedSetparam
    | 155 -> LinuxSyscall.SchedGetparam
    | 156 -> LinuxSyscall.SchedSetscheduler
    | 157 -> LinuxSyscall.SchedGetscheduler
    | 158 -> LinuxSyscall.SchedYield
    | 159 -> LinuxSyscall.SchedGetPriorityMax
    | 160 -> LinuxSyscall.SchedGetPriorityMin
    | 161 -> LinuxSyscall.SchedRrGetInterval
    | 162 -> LinuxSyscall.Nanosleep
    | 163 -> LinuxSyscall.Mremap
    | 164 -> LinuxSyscall.Setresuid
    | 165 -> LinuxSyscall.Getresuid
    | 166 -> LinuxSyscall.Vm86
    | 167 -> LinuxSyscall.QueryModule
    | 168 -> LinuxSyscall.Poll
    | 169 -> LinuxSyscall.Nfsservctl
    | 170 -> LinuxSyscall.Setresgid
    | 171 -> LinuxSyscall.Getresgid
    | 172 -> LinuxSyscall.Prctl
    | 173 -> LinuxSyscall.RtSigreturn
    | 174 -> LinuxSyscall.RtSigaction
    | 175 -> LinuxSyscall.RtSigprocmask
    | 176 -> LinuxSyscall.RtSigpending
    | 177 -> LinuxSyscall.RtSigtimedwait
    | 178 -> LinuxSyscall.RtSigqueueinfo
    | 179 -> LinuxSyscall.RtSigsuspend
    | 180 -> LinuxSyscall.Pread64
    | 181 -> LinuxSyscall.Pwrite64
    | 182 -> LinuxSyscall.Chown
    | 183 -> LinuxSyscall.Getcwd
    | 184 -> LinuxSyscall.CapGet
    | 185 -> LinuxSyscall.CapSet
    | 186 -> LinuxSyscall.Sigaltstack
    | 187 -> LinuxSyscall.Sendfile
    | 190 -> LinuxSyscall.Vfork
    | 191 -> LinuxSyscall.Ugetrlimit
    | 192 -> LinuxSyscall.Mmap2
    | 193 -> LinuxSyscall.Truncate64
    | 194 -> LinuxSyscall.Ftruncate64
    | 195 -> LinuxSyscall.Stat64
    | 196 -> LinuxSyscall.Lstat64
    | 197 -> LinuxSyscall.Fstat64
    | 198 -> LinuxSyscall.Lchown32
    | 199 -> LinuxSyscall.Getuid32
    | 200 -> LinuxSyscall.Getgid32
    | 201 -> LinuxSyscall.Geteuid32
    | 202 -> LinuxSyscall.Getegid32
    | 203 -> LinuxSyscall.Setreuid32
    | 204 -> LinuxSyscall.Setregid32
    | 205 -> LinuxSyscall.Getgroups32
    | 206 -> LinuxSyscall.Setgroups32
    | 207 -> LinuxSyscall.Fchown32
    | 208 -> LinuxSyscall.Setresuid32
    | 209 -> LinuxSyscall.Getresuid32
    | 210 -> LinuxSyscall.Setresgid32
    | 211 -> LinuxSyscall.Getresgid32
    | 212 -> LinuxSyscall.Chown32
    | 213 -> LinuxSyscall.Setuid32
    | 214 -> LinuxSyscall.Setgid32
    | 215 -> LinuxSyscall.Setfsuid32
    | 216 -> LinuxSyscall.Setfsgid32
    | 217 -> LinuxSyscall.PivotRoot
    | 218 -> LinuxSyscall.Mincore
    | 219 -> LinuxSyscall.Madvise
    | 220 -> LinuxSyscall.Getdents64
    | 221 -> LinuxSyscall.Fcntl64
    | 224 -> LinuxSyscall.Gettid
    | 225 -> LinuxSyscall.Readahead
    | 226 -> LinuxSyscall.Setxattr
    | 227 -> LinuxSyscall.Lsetxattr
    | 228 -> LinuxSyscall.Fsetxattr
    | 229 -> LinuxSyscall.Getxattr
    | 230 -> LinuxSyscall.Lgetxattr
    | 231 -> LinuxSyscall.Fgetxattr
    | 232 -> LinuxSyscall.Listxattr
    | 233 -> LinuxSyscall.Llistxattr
    | 234 -> LinuxSyscall.Flistxattr
    | 235 -> LinuxSyscall.Removexattr
    | 236 -> LinuxSyscall.Lremovexattr
    | 237 -> LinuxSyscall.Fremovexattr
    | 238 -> LinuxSyscall.Tkill
    | 239 -> LinuxSyscall.Sendfile64
    | 240 -> LinuxSyscall.Futex
    | 241 -> LinuxSyscall.SchedSetaffinity
    | 242 -> LinuxSyscall.SchedGetaffinity
    | 243 -> LinuxSyscall.SetThreadArea
    | 244 -> LinuxSyscall.GetThreadArea
    | 245 -> LinuxSyscall.IoSetup
    | 246 -> LinuxSyscall.IoDestroy
    | 247 -> LinuxSyscall.IoGetevents
    | 248 -> LinuxSyscall.IoSubmit
    | 249 -> LinuxSyscall.IoCancel
    | 250 -> LinuxSyscall.Fadvise64
    | 252 -> LinuxSyscall.ExitGroup
    | 253 -> LinuxSyscall.LookupDcookie
    | 254 -> LinuxSyscall.EpollCreate
    | 255 -> LinuxSyscall.EpollCtl
    | 256 -> LinuxSyscall.EpollWait
    | 257 -> LinuxSyscall.RemapFilePages
    | 258 -> LinuxSyscall.SetTidAddress
    | 259 -> LinuxSyscall.TimerCreate
    | 260 -> LinuxSyscall.TimerSettime
    | 261 -> LinuxSyscall.TimerGettime
    | 262 -> LinuxSyscall.TimerGetoverrun
    | 263 -> LinuxSyscall.TimerDelete
    | 264 -> LinuxSyscall.ClockSettime
    | 265 -> LinuxSyscall.ClockGettime
    | 266 -> LinuxSyscall.ClockGetres
    | 267 -> LinuxSyscall.ClockNanosleep
    | 268 -> LinuxSyscall.Statfs64
    | 269 -> LinuxSyscall.Fstatfs64
    | 270 -> LinuxSyscall.Tgkill
    | 271 -> LinuxSyscall.Utimes
    | 274 -> LinuxSyscall.Mbind
    | 275 -> LinuxSyscall.GetMempolicy
    | 276 -> LinuxSyscall.SetMempolicy
    | 277 -> LinuxSyscall.MqOpen
    | 278 -> LinuxSyscall.MqUnlink
    | 279 -> LinuxSyscall.MqTimedsend
    | 280 -> LinuxSyscall.MqTimedreceive
    | 281 -> LinuxSyscall.MqNotify
    | 282 -> LinuxSyscall.MqGetsetattr
    | 283 -> LinuxSyscall.KexecLoad
    | 284 -> LinuxSyscall.Waitid
    | 286 -> LinuxSyscall.AddKey
    | 287 -> LinuxSyscall.RequestKey
    | 288 -> LinuxSyscall.Keyctl
    | 289 -> LinuxSyscall.IoprioSet
    | 290 -> LinuxSyscall.IoprioGet
    | 291 -> LinuxSyscall.InotifyInit
    | 292 -> LinuxSyscall.InotifyAddWatch
    | 293 -> LinuxSyscall.InotifyRmWatch
    | 294 -> LinuxSyscall.MigratePages
    | 295 -> LinuxSyscall.Openat
    | 296 -> LinuxSyscall.Mkdirat
    | 297 -> LinuxSyscall.Mknodat
    | 298 -> LinuxSyscall.Fchownat
    | 299 -> LinuxSyscall.Futimesat
    | 300 -> LinuxSyscall.Fstatat64
    | 301 -> LinuxSyscall.Unlinkat
    | 302 -> LinuxSyscall.Renameat
    | 303 -> LinuxSyscall.Linkat
    | 304 -> LinuxSyscall.Symlinkat
    | 305 -> LinuxSyscall.Readlinkat
    | 306 -> LinuxSyscall.Fchmodat
    | 307 -> LinuxSyscall.Faccessat
    | 308 -> LinuxSyscall.Pselect6
    | 309 -> LinuxSyscall.Ppoll
    | 310 -> LinuxSyscall.Unshare
    | 311 -> LinuxSyscall.SetRobustList
    | 312 -> LinuxSyscall.GetRobustList
    | 313 -> LinuxSyscall.Splice
    | 314 -> LinuxSyscall.SyncFileRange
    | 315 -> LinuxSyscall.Tee
    | 316 -> LinuxSyscall.Vmsplice
    | 317 -> LinuxSyscall.MovePages
    | 318 -> LinuxSyscall.Getcpu
    | 319 -> LinuxSyscall.EpollPwait
    | 320 -> LinuxSyscall.Utimensat
    | 321 -> LinuxSyscall.Signalfd
    | 322 -> LinuxSyscall.TimerfdCreate
    | 323 -> LinuxSyscall.Eventfd
    | 324 -> LinuxSyscall.Fallocate
    | 325 -> LinuxSyscall.TimerfdSettime
    | 326 -> LinuxSyscall.TimerfdGettime
    | 327 -> LinuxSyscall.Signalfd4
    | 328 -> LinuxSyscall.Eventfd2
    | 329 -> LinuxSyscall.EpollCreate1
    | 330 -> LinuxSyscall.Dup3
    | 331 -> LinuxSyscall.Pipe2
    | 332 -> LinuxSyscall.InotifyInit1
    | 333 -> LinuxSyscall.Preadv
    | 334 -> LinuxSyscall.Pwritev
    | 335 -> LinuxSyscall.RtTgsigqueueinfo
    | 336 -> LinuxSyscall.PerfEventOpen
    | 337 -> LinuxSyscall.Recvmmsg
    | 338 -> LinuxSyscall.FanotifyInit
    | 339 -> LinuxSyscall.FanotifyMark
    | 340 -> LinuxSyscall.Prlimit64
    | 341 -> LinuxSyscall.NameToHandleAt
    | 342 -> LinuxSyscall.OpenByHandleAt
    | 343 -> LinuxSyscall.ClockAdjtime
    | 344 -> LinuxSyscall.Syncfs
    | 345 -> LinuxSyscall.Sendmmsg
    | 346 -> LinuxSyscall.Setns
    | 347 -> LinuxSyscall.ProcessVmReadv
    | 348 -> LinuxSyscall.ProcessVmWritev
    | 349 -> LinuxSyscall.Kcmp
    | 350 -> LinuxSyscall.FinitModule
    | 351 -> LinuxSyscall.SchedSetattr
    | 352 -> LinuxSyscall.SchedGetattr
    | 353 -> LinuxSyscall.Renameat2
    | 354 -> LinuxSyscall.Seccomp
    | 355 -> LinuxSyscall.Getrandom
    | 356 -> LinuxSyscall.MemfdCreate
    | 357 -> LinuxSyscall.Bpf
    | 358 -> LinuxSyscall.Execveat
    | 359 -> LinuxSyscall.Socket
    | 360 -> LinuxSyscall.Socketpair
    | 361 -> LinuxSyscall.Bind
    | 362 -> LinuxSyscall.Connect
    | 363 -> LinuxSyscall.Listen
    | 364 -> LinuxSyscall.Accept4
    | 365 -> LinuxSyscall.Getsockopt
    | 366 -> LinuxSyscall.Setsockopt
    | 367 -> LinuxSyscall.Getsockname
    | 368 -> LinuxSyscall.Getpeername
    | 369 -> LinuxSyscall.Sendto
    | 370 -> LinuxSyscall.Sendmsg
    | 371 -> LinuxSyscall.Recvfrom
    | 372 -> LinuxSyscall.Recvmsg
    | 373 -> LinuxSyscall.Shutdown
    | 374 -> LinuxSyscall.Userfaultfd
    | 375 -> LinuxSyscall.Membarrier
    | 376 -> LinuxSyscall.Mlock2
    | 377 -> LinuxSyscall.CopyFileRange
    | 378 -> LinuxSyscall.Preadv2
    | 379 -> LinuxSyscall.Pwritev2
    | 380 -> LinuxSyscall.PkeyMprotect
    | 381 -> LinuxSyscall.PkeyAlloc
    | 382 -> LinuxSyscall.PkeyFree
    | 383 -> LinuxSyscall.Statx
    | 384 -> LinuxSyscall.ArchPrctl
    | _ -> raise UnhandledSyscallException

  let private getX64Syscall = function
    | 0 -> LinuxSyscall.Read
    | 1 -> LinuxSyscall.Write
    | 2 -> LinuxSyscall.Open
    | 3 -> LinuxSyscall.Close
    | 4 -> LinuxSyscall.Stat
    | 5 -> LinuxSyscall.Fstat
    | 6 -> LinuxSyscall.Lstat
    | 7 -> LinuxSyscall.Poll
    | 8 -> LinuxSyscall.Lseek
    | 9 -> LinuxSyscall.Mmap
    | 10 -> LinuxSyscall.Mprotect
    | 11 -> LinuxSyscall.Munmap
    | 12 -> LinuxSyscall.Brk
    | 13 -> LinuxSyscall.RtSigaction
    | 14 -> LinuxSyscall.RtSigprocmask
    | 15 -> LinuxSyscall.RtSigreturn
    | 16 -> LinuxSyscall.Ioctl
    | 17 -> LinuxSyscall.Pread64
    | 18 -> LinuxSyscall.Pwrite64
    | 19 -> LinuxSyscall.Readv
    | 20 -> LinuxSyscall.Writev
    | 21 -> LinuxSyscall.Access
    | 22 -> LinuxSyscall.Pipe
    | 23 -> LinuxSyscall.Select
    | 24 -> LinuxSyscall.SchedYield
    | 25 -> LinuxSyscall.Mremap
    | 26 -> LinuxSyscall.Msync
    | 27 -> LinuxSyscall.Mincore
    | 28 -> LinuxSyscall.Madvise
    | 29 -> LinuxSyscall.Shmget
    | 30 -> LinuxSyscall.Shmat
    | 31 -> LinuxSyscall.Shmctl
    | 32 -> LinuxSyscall.Dup
    | 33 -> LinuxSyscall.Dup2
    | 34 -> LinuxSyscall.Pause
    | 35 -> LinuxSyscall.Nanosleep
    | 36 -> LinuxSyscall.Getitimer
    | 37 -> LinuxSyscall.Alarm
    | 38 -> LinuxSyscall.Setitimer
    | 39 -> LinuxSyscall.Getpid
    | 40 -> LinuxSyscall.Sendfile
    | 41 -> LinuxSyscall.Socket
    | 42 -> LinuxSyscall.Connect
    | 43 -> LinuxSyscall.Accept
    | 44 -> LinuxSyscall.Sendto
    | 45 -> LinuxSyscall.Recvfrom
    | 46 -> LinuxSyscall.Sendmsg
    | 47 -> LinuxSyscall.Recvmsg
    | 48 -> LinuxSyscall.Shutdown
    | 49 -> LinuxSyscall.Bind
    | 50 -> LinuxSyscall.Listen
    | 51 -> LinuxSyscall.Getsockname
    | 52 -> LinuxSyscall.Getpeername
    | 53 -> LinuxSyscall.Socketpair
    | 54 -> LinuxSyscall.Setsockopt
    | 55 -> LinuxSyscall.Getsockopt
    | 56 -> LinuxSyscall.Clone
    | 57 -> LinuxSyscall.Fork
    | 58 -> LinuxSyscall.Vfork
    | 59 -> LinuxSyscall.Execve
    | 60 -> LinuxSyscall.Exit
    | 61 -> LinuxSyscall.Wait4
    | 62 -> LinuxSyscall.Kill
    | 63 -> LinuxSyscall.Uname
    | 64 -> LinuxSyscall.Semget
    | 65 -> LinuxSyscall.Semop
    | 66 -> LinuxSyscall.Semctl
    | 67 -> LinuxSyscall.Shmdt
    | 68 -> LinuxSyscall.Msgget
    | 69 -> LinuxSyscall.Msgsnd
    | 70 -> LinuxSyscall.Msgrcv
    | 71 -> LinuxSyscall.Msgctl
    | 72 -> LinuxSyscall.Fcntl
    | 73 -> LinuxSyscall.Flock
    | 74 -> LinuxSyscall.Fsync
    | 75 -> LinuxSyscall.Fdatasync
    | 76 -> LinuxSyscall.Truncate
    | 77 -> LinuxSyscall.Ftruncate
    | 78 -> LinuxSyscall.Getdents
    | 79 -> LinuxSyscall.Getcwd
    | 80 -> LinuxSyscall.Chdir
    | 81 -> LinuxSyscall.Fchdir
    | 82 -> LinuxSyscall.Rename
    | 83 -> LinuxSyscall.Mkdir
    | 84 -> LinuxSyscall.Rmdir
    | 85 -> LinuxSyscall.Creat
    | 86 -> LinuxSyscall.Link
    | 87 -> LinuxSyscall.Unlink
    | 88 -> LinuxSyscall.Symlink
    | 89 -> LinuxSyscall.Readlink
    | 90 -> LinuxSyscall.Chmod
    | 91 -> LinuxSyscall.Fchmod
    | 92 -> LinuxSyscall.Chown
    | 93 -> LinuxSyscall.Fchown
    | 94 -> LinuxSyscall.Lchown
    | 95 -> LinuxSyscall.Umask
    | 96 -> LinuxSyscall.Gettimeofday
    | 97 -> LinuxSyscall.Getrlimit
    | 98 -> LinuxSyscall.Getrusage
    | 99 -> LinuxSyscall.Sysinfo
    | 100 -> LinuxSyscall.Times
    | 101 -> LinuxSyscall.Ptrace
    | 102 -> LinuxSyscall.Getuid
    | 103 -> LinuxSyscall.Syslog
    | 104 -> LinuxSyscall.Getgid
    | 105 -> LinuxSyscall.Setuid
    | 106 -> LinuxSyscall.Setgid
    | 107 -> LinuxSyscall.Geteuid
    | 108 -> LinuxSyscall.Getegid
    | 109 -> LinuxSyscall.Setpgid
    | 110 -> LinuxSyscall.Getppid
    | 111 -> LinuxSyscall.Getpgrp
    | 112 -> LinuxSyscall.Setsid
    | 113 -> LinuxSyscall.Setreuid
    | 114 -> LinuxSyscall.Setregid
    | 115 -> LinuxSyscall.Getgroups
    | 116 -> LinuxSyscall.Setgroups
    | 117 -> LinuxSyscall.Setresuid
    | 118 -> LinuxSyscall.Getresuid
    | 119 -> LinuxSyscall.Setresgid
    | 120 -> LinuxSyscall.Getresgid
    | 121 -> LinuxSyscall.Getpgid
    | 122 -> LinuxSyscall.Setfsuid
    | 123 -> LinuxSyscall.Setfsgid
    | 124 -> LinuxSyscall.Getsid
    | 125 -> LinuxSyscall.CapGet
    | 126 -> LinuxSyscall.CapSet
    | 127 -> LinuxSyscall.RtSigpending
    | 128 -> LinuxSyscall.RtSigtimedwait
    | 129 -> LinuxSyscall.RtSigqueueinfo
    | 130 -> LinuxSyscall.RtSigsuspend
    | 131 -> LinuxSyscall.Sigaltstack
    | 132 -> LinuxSyscall.Utime
    | 133 -> LinuxSyscall.Mknod
    | 134 -> LinuxSyscall.Uselib
    | 135 -> LinuxSyscall.Personality
    | 136 -> LinuxSyscall.Ustat
    | 137 -> LinuxSyscall.Statfs
    | 138 -> LinuxSyscall.Fstatfs
    | 139 -> LinuxSyscall.Sysfs
    | 140 -> LinuxSyscall.Getpriority
    | 141 -> LinuxSyscall.Setpriority
    | 142 -> LinuxSyscall.SchedSetparam
    | 143 -> LinuxSyscall.SchedGetparam
    | 144 -> LinuxSyscall.SchedSetscheduler
    | 145 -> LinuxSyscall.SchedGetscheduler
    | 146 -> LinuxSyscall.SchedGetPriorityMax
    | 147 -> LinuxSyscall.SchedGetPriorityMin
    | 148 -> LinuxSyscall.SchedRrGetInterval
    | 149 -> LinuxSyscall.Mlock
    | 150 -> LinuxSyscall.Munlock
    | 151 -> LinuxSyscall.Mlockall
    | 152 -> LinuxSyscall.Munlockall
    | 153 -> LinuxSyscall.Vhangup
    | 154 -> LinuxSyscall.ModifyLdt
    | 155 -> LinuxSyscall.PivotRoot
    | 156 -> LinuxSyscall.Sysctl
    | 157 -> LinuxSyscall.Prctl
    | 158 -> LinuxSyscall.ArchPrctl
    | 159 -> LinuxSyscall.AdjTimex
    | 160 -> LinuxSyscall.Setrlimit
    | 161 -> LinuxSyscall.Chroot
    | 162 -> LinuxSyscall.Sync
    | 163 -> LinuxSyscall.Acct
    | 164 -> LinuxSyscall.Settimeofday
    | 165 -> LinuxSyscall.Mount
    | 166 -> LinuxSyscall.Umount2
    | 167 -> LinuxSyscall.Swapon
    | 168 -> LinuxSyscall.Swapoff
    | 169 -> LinuxSyscall.Reboot
    | 170 -> LinuxSyscall.Sethostname
    | 171 -> LinuxSyscall.Setdomainname
    | 172 -> LinuxSyscall.Iopl
    | 173 -> LinuxSyscall.Ioperm
    | 174 -> LinuxSyscall.CreateModule
    | 175 -> LinuxSyscall.InitModule
    | 176 -> LinuxSyscall.DeleteModule
    | 177 -> LinuxSyscall.GetKernelSyms
    | 178 -> LinuxSyscall.QueryModule
    | 179 -> LinuxSyscall.Quotactl
    | 180 -> LinuxSyscall.Nfsservctl
    | 186 -> LinuxSyscall.Gettid
    | 187 -> LinuxSyscall.Readahead
    | 188 -> LinuxSyscall.Setxattr
    | 189 -> LinuxSyscall.Lsetxattr
    | 190 -> LinuxSyscall.Fsetxattr
    | 191 -> LinuxSyscall.Getxattr
    | 192 -> LinuxSyscall.Lgetxattr
    | 193 -> LinuxSyscall.Fgetxattr
    | 194 -> LinuxSyscall.Listxattr
    | 195 -> LinuxSyscall.Llistxattr
    | 196 -> LinuxSyscall.Flistxattr
    | 197 -> LinuxSyscall.Removexattr
    | 198 -> LinuxSyscall.Lremovexattr
    | 199 -> LinuxSyscall.Fremovexattr
    | 200 -> LinuxSyscall.Tkill
    | 201 -> LinuxSyscall.Time
    | 202 -> LinuxSyscall.Futex
    | 203 -> LinuxSyscall.SchedSetaffinity
    | 204 -> LinuxSyscall.SchedGetaffinity
    | 205 -> LinuxSyscall.SetThreadArea
    | 206 -> LinuxSyscall.IoSetup
    | 207 -> LinuxSyscall.IoDestroy
    | 208 -> LinuxSyscall.IoGetevents
    | 209 -> LinuxSyscall.IoSubmit
    | 210 -> LinuxSyscall.IoCancel
    | 211 -> LinuxSyscall.GetThreadArea
    | 212 -> LinuxSyscall.LookupDcookie
    | 213 -> LinuxSyscall.EpollCreate
    | 216 -> LinuxSyscall.RemapFilePages
    | 217 -> LinuxSyscall.Getdents64
    | 218 -> LinuxSyscall.SetTidAddress
    | 219 -> LinuxSyscall.RestartSyscall
    | 220 -> LinuxSyscall.Semtimedop
    | 221 -> LinuxSyscall.Fadvise64
    | 222 -> LinuxSyscall.TimerCreate
    | 223 -> LinuxSyscall.TimerSettime
    | 224 -> LinuxSyscall.TimerGettime
    | 225 -> LinuxSyscall.TimerGetoverrun
    | 226 -> LinuxSyscall.TimerDelete
    | 227 -> LinuxSyscall.ClockSettime
    | 228 -> LinuxSyscall.ClockGettime
    | 229 -> LinuxSyscall.ClockGetres
    | 230 -> LinuxSyscall.ClockNanosleep
    | 231 -> LinuxSyscall.ExitGroup
    | 232 -> LinuxSyscall.EpollWait
    | 233 -> LinuxSyscall.EpollCtl
    | 234 -> LinuxSyscall.Tgkill
    | 235 -> LinuxSyscall.Utimes
    | 237 -> LinuxSyscall.Mbind
    | 238 -> LinuxSyscall.SetMempolicy
    | 239 -> LinuxSyscall.GetMempolicy
    | 240 -> LinuxSyscall.MqOpen
    | 241 -> LinuxSyscall.MqUnlink
    | 242 -> LinuxSyscall.MqTimedsend
    | 243 -> LinuxSyscall.MqTimedreceive
    | 244 -> LinuxSyscall.MqNotify
    | 245 -> LinuxSyscall.MqGetsetattr
    | 246 -> LinuxSyscall.KexecLoad
    | 247 -> LinuxSyscall.Waitid
    | 248 -> LinuxSyscall.AddKey
    | 249 -> LinuxSyscall.RequestKey
    | 250 -> LinuxSyscall.Keyctl
    | 251 -> LinuxSyscall.IoprioSet
    | 252 -> LinuxSyscall.IoprioGet
    | 253 -> LinuxSyscall.InotifyInit
    | 254 -> LinuxSyscall.InotifyAddWatch
    | 255 -> LinuxSyscall.InotifyRmWatch
    | 256 -> LinuxSyscall.MigratePages
    | 257 -> LinuxSyscall.Openat
    | 258 -> LinuxSyscall.Mkdirat
    | 259 -> LinuxSyscall.Mknodat
    | 260 -> LinuxSyscall.Fchownat
    | 261 -> LinuxSyscall.Futimesat
    | 262 -> LinuxSyscall.Newfstatat
    | 263 -> LinuxSyscall.Unlinkat
    | 264 -> LinuxSyscall.Renameat
    | 265 -> LinuxSyscall.Linkat
    | 266 -> LinuxSyscall.Symlinkat
    | 267 -> LinuxSyscall.Readlinkat
    | 268 -> LinuxSyscall.Fchmodat
    | 269 -> LinuxSyscall.Faccessat
    | 270 -> LinuxSyscall.Pselect6
    | 271 -> LinuxSyscall.Ppoll
    | 272 -> LinuxSyscall.Unshare
    | 273 -> LinuxSyscall.SetRobustList
    | 274 -> LinuxSyscall.GetRobustList
    | 275 -> LinuxSyscall.Splice
    | 276 -> LinuxSyscall.Tee
    | 277 -> LinuxSyscall.SyncFileRange
    | 278 -> LinuxSyscall.Vmsplice
    | 279 -> LinuxSyscall.MovePages
    | 280 -> LinuxSyscall.Utimensat
    | 281 -> LinuxSyscall.EpollPwait
    | 282 -> LinuxSyscall.Signalfd
    | 283 -> LinuxSyscall.TimerfdCreate
    | 284 -> LinuxSyscall.Eventfd
    | 285 -> LinuxSyscall.Fallocate
    | 286 -> LinuxSyscall.TimerfdSettime
    | 287 -> LinuxSyscall.TimerfdGettime
    | 288 -> LinuxSyscall.Accept4
    | 289 -> LinuxSyscall.Signalfd4
    | 290 -> LinuxSyscall.Eventfd2
    | 291 -> LinuxSyscall.EpollCreate1
    | 292 -> LinuxSyscall.Dup3
    | 293 -> LinuxSyscall.Pipe2
    | 294 -> LinuxSyscall.InotifyInit1
    | 295 -> LinuxSyscall.Preadv
    | 296 -> LinuxSyscall.Pwritev
    | 297 -> LinuxSyscall.RtTgsigqueueinfo
    | 298 -> LinuxSyscall.PerfEventOpen
    | 299 -> LinuxSyscall.Recvmmsg
    | 300 -> LinuxSyscall.FanotifyInit
    | 301 -> LinuxSyscall.FanotifyMark
    | 302 -> LinuxSyscall.Prlimit64
    | 303 -> LinuxSyscall.NameToHandleAt
    | 304 -> LinuxSyscall.OpenByHandleAt
    | 305 -> LinuxSyscall.ClockAdjtime
    | 306 -> LinuxSyscall.Syncfs
    | 307 -> LinuxSyscall.Sendmmsg
    | 308 -> LinuxSyscall.Setns
    | 309 -> LinuxSyscall.Getcpu
    | 310 -> LinuxSyscall.ProcessVmReadv
    | 311 -> LinuxSyscall.ProcessVmWritev
    | 312 -> LinuxSyscall.Kcmp
    | 313 -> LinuxSyscall.FinitModule
    | 314 -> LinuxSyscall.SchedSetattr
    | 315 -> LinuxSyscall.SchedGetattr
    | 316 -> LinuxSyscall.Renameat2
    | 317 -> LinuxSyscall.Seccomp
    | 318 -> LinuxSyscall.Getrandom
    | 319 -> LinuxSyscall.MemfdCreate
    | 320 -> LinuxSyscall.KexecFileLoad
    | 321 -> LinuxSyscall.Bpf
    | 322 -> LinuxSyscall.Execveat
    | 323 -> LinuxSyscall.Userfaultfd
    | 324 -> LinuxSyscall.Membarrier
    | 325 -> LinuxSyscall.Mlock2
    | 326 -> LinuxSyscall.CopyFileRange
    | 327 -> LinuxSyscall.Preadv2
    | 328 -> LinuxSyscall.Pwritev2
    | 329 -> LinuxSyscall.PkeyMprotect
    | 330 -> LinuxSyscall.PkeyAlloc
    | 331 -> LinuxSyscall.PkeyFree
    | 332 -> LinuxSyscall.Statx
    | _ -> raise UnhandledSyscallException

  let ofNumber arch num =
    match arch with
    | Arch.IntelX86 -> getX86Syscall num
    | Arch.IntelX64 -> getX64Syscall num
    | _ -> raise UnhandledSyscallException

  let toStr = function
    | LinuxSyscall.Accept -> "accept"
    | LinuxSyscall.Accept4 -> "accept4"
    | LinuxSyscall.Access -> "access"
    | LinuxSyscall.Acct -> "acct"
    | LinuxSyscall.AddKey -> "add_key"
    | LinuxSyscall.AdjTimex -> "adjtimex"
    | LinuxSyscall.Alarm -> "alarm"
    | LinuxSyscall.AllocHugePages -> "alloc_hugepages"
    | LinuxSyscall.ArcGetTLS -> "arc_gettls"
    | LinuxSyscall.ArcSetTLS -> "arc_settls"
    | LinuxSyscall.ArcUsrCmpxchg -> "arc_usr_cmpxchg"
    | LinuxSyscall.ArchPrctl -> "arch_prctl"
    | LinuxSyscall.AtomicBarrier -> "atomic_barrier"
    | LinuxSyscall.AtomicCmpxchg32 -> "atomic_cmpxchg_32"
    | LinuxSyscall.Bdflush -> "bdflush"
    | LinuxSyscall.BfinSpinlock -> "bfin_spinlock"
    | LinuxSyscall.Bind -> "bind"
    | LinuxSyscall.Bpf -> "bpf"
    | LinuxSyscall.Brk -> "brk"
    | LinuxSyscall.Breakpoint -> "breakpoint"
    | LinuxSyscall.CacheFlush -> "cacheflush"
    | LinuxSyscall.CapGet -> "capget"
    | LinuxSyscall.CapSet -> "capset"
    | LinuxSyscall.Chdir -> "chdir"
    | LinuxSyscall.Chmod -> "chmod"
    | LinuxSyscall.Chown -> "chown"
    | LinuxSyscall.Chown32 -> "chown32"
    | LinuxSyscall.Chroot -> "chroot"
    | LinuxSyscall.ClockAdjtime -> "clock_adjtime"
    | LinuxSyscall.ClockGetres -> "clock_getres"
    | LinuxSyscall.ClockGettime -> "clock_gettime"
    | LinuxSyscall.ClockNanosleep -> "clock_nanosleep"
    | LinuxSyscall.ClockSettime -> "clock_settime"
    | LinuxSyscall.Clone2 -> "clone2"
    | LinuxSyscall.Clone -> "clone"
    | LinuxSyscall.Clone3 -> "clone3"
    | LinuxSyscall.Close -> "close"
    | LinuxSyscall.CmpxchgBadaddr -> "cmpxchg_badaddr"
    | LinuxSyscall.Connect -> "connect"
    | LinuxSyscall.CopyFileRange -> "copy_file_range"
    | LinuxSyscall.Creat -> "creat"
    | LinuxSyscall.CreateModule -> "create_module"
    | LinuxSyscall.DeleteModule -> "delete_module"
    | LinuxSyscall.DmaMemcpy -> "dma_memcpy"
    | LinuxSyscall.Dup -> "dup"
    | LinuxSyscall.Dup2 -> "dup2"
    | LinuxSyscall.Dup3 -> "dup3"
    | LinuxSyscall.EpollCreate -> "epoll_create"
    | LinuxSyscall.EpollCreate1 -> "epoll_create1"
    | LinuxSyscall.EpollCtl -> "epoll_ctl"
    | LinuxSyscall.EpollPwait -> "epoll_pwait"
    | LinuxSyscall.EpollWait -> "epoll_wait"
    | LinuxSyscall.Eventfd -> "eventfd"
    | LinuxSyscall.Eventfd2 -> "eventfd2"
    | LinuxSyscall.Execv -> "execv"
    | LinuxSyscall.Execve -> "execve"
    | LinuxSyscall.Execveat -> "execveat"
    | LinuxSyscall.Exit -> "exit"
    | LinuxSyscall.ExitGroup -> "exit_group"
    | LinuxSyscall.Faccessat -> "faccessat"
    | LinuxSyscall.Fadvise64 -> "fadvise64"
    | LinuxSyscall.Fallocate -> "fallocate"
    | LinuxSyscall.FanotifyInit -> "fanotify_init"
    | LinuxSyscall.FanotifyMark -> "fanotify_mark"
    | LinuxSyscall.Fchdir -> "fchdir"
    | LinuxSyscall.Fchmod -> "fchmod"
    | LinuxSyscall.Fchmodat -> "fchmodat"
    | LinuxSyscall.Fchown -> "fchown"
    | LinuxSyscall.Fchown32 -> "fchown32"
    | LinuxSyscall.Fchownat -> "fchownat"
    | LinuxSyscall.Fcntl -> "fcntl"
    | LinuxSyscall.Fcntl64 -> "fcntl64"
    | LinuxSyscall.Fdatasync -> "fdatasync"
    | LinuxSyscall.Fgetxattr -> "fgetxattr"
    | LinuxSyscall.FinitModule -> "finit_module"
    | LinuxSyscall.Flistxattr -> "flistxattr"
    | LinuxSyscall.Flock -> "flock"
    | LinuxSyscall.Fork -> "fork"
    | LinuxSyscall.FreeHugepages -> "free_hugepages"
    | LinuxSyscall.Fremovexattr -> "fremovexattr"
    | LinuxSyscall.Fsconfig -> "fsconfig"
    | LinuxSyscall.Fsetxattr -> "fsetxattr"
    | LinuxSyscall.Fsmount -> "fsmount"
    | LinuxSyscall.Fsopen -> "fsopen"
    | LinuxSyscall.Fspick -> "fspick"
    | LinuxSyscall.Fstat -> "fstat"
    | LinuxSyscall.Fstat64 -> "fstat64"
    | LinuxSyscall.Fstatat64 -> "fstatat64"
    | LinuxSyscall.Fstatfs -> "fstatfs"
    | LinuxSyscall.Fstatfs64 -> "fstatfs64"
    | LinuxSyscall.Fsync -> "fsync"
    | LinuxSyscall.Ftruncate -> "ftruncate"
    | LinuxSyscall.Ftruncate64 -> "ftruncate64"
    | LinuxSyscall.Futex -> "futex"
    | LinuxSyscall.Futimesat -> "futimesat"
    | LinuxSyscall.GetKernelSyms -> "get_kernel_syms"
    | LinuxSyscall.GetMempolicy -> "get_mempolicy"
    | LinuxSyscall.GetRobustList -> "get_robust_list"
    | LinuxSyscall.GetThreadArea -> "get_thread_area"
    | LinuxSyscall.GetTLS -> "get_tls"
    | LinuxSyscall.Getcpu -> "getcpu"
    | LinuxSyscall.Getcwd -> "getcwd"
    | LinuxSyscall.Getdents -> "getdents"
    | LinuxSyscall.Getdents64 -> "getdents64"
    | LinuxSyscall.Getdomainname -> "getdomainname"
    | LinuxSyscall.Getdtablesize -> "getdtablesize"
    | LinuxSyscall.Getegid -> "getegid"
    | LinuxSyscall.Getegid32 -> "getegid32"
    | LinuxSyscall.Geteuid -> "geteuid"
    | LinuxSyscall.Geteuid32 -> "geteuid32"
    | LinuxSyscall.Getgid -> "getgid"
    | LinuxSyscall.Getgid32 -> "getgid32"
    | LinuxSyscall.Getgroups -> "getgroups"
    | LinuxSyscall.Getgroups32 -> "getgroups32"
    | LinuxSyscall.Gethostname -> "gethostname"
    | LinuxSyscall.Getitimer -> "getitimer"
    | LinuxSyscall.Getpeername -> "getpeername"
    | LinuxSyscall.Getpagesize -> "getpagesize"
    | LinuxSyscall.Getpgid -> "getpgid"
    | LinuxSyscall.Getpgrp -> "getpgrp"
    | LinuxSyscall.Getpid -> "getpid"
    | LinuxSyscall.Getppid -> "getppid"
    | LinuxSyscall.Getpriority -> "getpriority"
    | LinuxSyscall.Getrandom -> "getrandom"
    | LinuxSyscall.Getresgid -> "getresgid"
    | LinuxSyscall.Getresgid32 -> "getresgid32"
    | LinuxSyscall.Getresuid -> "getresuid"
    | LinuxSyscall.Getresuid32 -> "getresuid32"
    | LinuxSyscall.Getrlimit -> "getrlimit"
    | LinuxSyscall.Getrusage -> "getrusage"
    | LinuxSyscall.Getsid -> "getsid"
    | LinuxSyscall.Getsockname -> "getsockname"
    | LinuxSyscall.Getsockopt -> "getsockopt"
    | LinuxSyscall.Gettid -> "gettid"
    | LinuxSyscall.Gettimeofday -> "gettimeofday"
    | LinuxSyscall.Getuid -> "getuid"
    | LinuxSyscall.Getuid32 -> "getuid32"
    | LinuxSyscall.Getunwind -> "getunwind"
    | LinuxSyscall.Getxattr -> "getxattr"
    | LinuxSyscall.Getxgid -> "getxgid"
    | LinuxSyscall.Getxpid -> "getxpid"
    | LinuxSyscall.Getxuid -> "getxuid"
    | LinuxSyscall.InitModule -> "init_module"
    | LinuxSyscall.InotifyAddWatch -> "inotify_add_watch"
    | LinuxSyscall.InotifyInit -> "inotify_init"
    | LinuxSyscall.InotifyInit1 -> "inotify_init1"
    | LinuxSyscall.InotifyRmWatch -> "inotify_rm_watch"
    | LinuxSyscall.IoCancel -> "io_cancel"
    | LinuxSyscall.IoDestroy -> "io_destroy"
    | LinuxSyscall.IoGetevents -> "io_getevents"
    | LinuxSyscall.IoPgetevents -> "io_pgetevents"
    | LinuxSyscall.IoSetup -> "io_setup"
    | LinuxSyscall.IoSubmit -> "io_submit"
    | LinuxSyscall.IoUringEnter -> "io_uring_enter"
    | LinuxSyscall.IoUringRegister -> "io_uring_register"
    | LinuxSyscall.IoUringSetup -> "io_uring_setup"
    | LinuxSyscall.Ioctl -> "ioctl"
    | LinuxSyscall.Ioperm -> "ioperm"
    | LinuxSyscall.Iopl -> "iopl"
    | LinuxSyscall.IoprioGet -> "ioprio_get"
    | LinuxSyscall.IoprioSet -> "ioprio_set"
    | LinuxSyscall.Ipc -> "ipc"
    | LinuxSyscall.Kcmp -> "kcmp"
    | LinuxSyscall.KernFeatures -> "kern_features"
    | LinuxSyscall.KexecFileLoad -> "kexec_file_load"
    | LinuxSyscall.KexecLoad -> "kexec_load"
    | LinuxSyscall.Keyctl -> "keyctl"
    | LinuxSyscall.Kill -> "kill"
    | LinuxSyscall.Lchown -> "lchown"
    | LinuxSyscall.Lchown32 -> "lchown32"
    | LinuxSyscall.Lgetxattr -> "lgetxattr"
    | LinuxSyscall.Link -> "link"
    | LinuxSyscall.Linkat -> "linkat"
    | LinuxSyscall.Listen -> "listen"
    | LinuxSyscall.Listxattr -> "listxattr"
    | LinuxSyscall.Llistxattr -> "llistxattr"
    | LinuxSyscall.LookupDcookie -> "lookup_dcookie"
    | LinuxSyscall.Lremovexattr -> "lremovexattr"
    | LinuxSyscall.Lseek -> "lseek"
    | LinuxSyscall.LLseek -> "_llseek"
    | LinuxSyscall.Lsetxattr -> "lsetxattr"
    | LinuxSyscall.Lstat -> "lstat"
    | LinuxSyscall.Lstat64 -> "lstat64"
    | LinuxSyscall.Madvise -> "madvise"
    | LinuxSyscall.Mbind -> "mbind"
    | LinuxSyscall.MemoryOrdering -> "memory_ordering"
    | LinuxSyscall.MetagGetTLS -> "metag_get_tls"
    | LinuxSyscall.MetagSetFpuFlags -> "metag_set_fpu_flags"
    | LinuxSyscall.MetagSetTLS -> "metag_set_tls"
    | LinuxSyscall.MetagSetglobalbit -> "metag_setglobalbit"
    | LinuxSyscall.Membarrier -> "membarrier"
    | LinuxSyscall.MemfdCreate -> "memfd_create"
    | LinuxSyscall.MigratePages -> "migrate_pages"
    | LinuxSyscall.Mincore -> "mincore"
    | LinuxSyscall.Mkdir -> "mkdir"
    | LinuxSyscall.Mkdirat -> "mkdirat"
    | LinuxSyscall.Mknod -> "mknod"
    | LinuxSyscall.Mknodat -> "mknodat"
    | LinuxSyscall.Mlock -> "mlock"
    | LinuxSyscall.Mlock2 -> "mlock2"
    | LinuxSyscall.Mlockall -> "mlockall"
    | LinuxSyscall.Mmap -> "mmap"
    | LinuxSyscall.Mmap2 -> "mmap2"
    | LinuxSyscall.ModifyLdt -> "modify_ldt"
    | LinuxSyscall.Mount -> "mount"
    | LinuxSyscall.MoveMount -> "move_mount"
    | LinuxSyscall.MovePages -> "move_pages"
    | LinuxSyscall.Mprotect -> "mprotect"
    | LinuxSyscall.MqGetsetattr -> "mq_getsetattr"
    | LinuxSyscall.MqNotify -> "mq_notify"
    | LinuxSyscall.MqOpen -> "mq_open"
    | LinuxSyscall.MqTimedreceive -> "mq_timedreceive"
    | LinuxSyscall.MqTimedsend -> "mq_timedsend"
    | LinuxSyscall.MqUnlink -> "mq_unlink"
    | LinuxSyscall.Mremap -> "mremap"
    | LinuxSyscall.Msgctl -> "msgctl"
    | LinuxSyscall.Msgget -> "msgget"
    | LinuxSyscall.Msgrcv -> "msgrcv"
    | LinuxSyscall.Msgsnd -> "msgsnd"
    | LinuxSyscall.Msync -> "msync"
    | LinuxSyscall.Munlock -> "munlock"
    | LinuxSyscall.Munlockall -> "munlockall"
    | LinuxSyscall.Munmap -> "munmap"
    | LinuxSyscall.NameToHandleAt -> "name_to_handle_at"
    | LinuxSyscall.Nanosleep -> "nanosleep"
    | LinuxSyscall.Newfstatat -> "newfstatat"
    | LinuxSyscall.NewSelect -> "_newselect"
    | LinuxSyscall.Nfsservctl -> "nfsservctl"
    | LinuxSyscall.Nice -> "nice"
    | LinuxSyscall.OldAdjtimex -> "old_adjtimex"
    | LinuxSyscall.OldGetrlimit -> "old_getrlimit"
    | LinuxSyscall.Oldfstat -> "oldfstat"
    | LinuxSyscall.Oldlstat -> "oldlstat"
    | LinuxSyscall.Oldolduname -> "oldolduname"
    | LinuxSyscall.Oldstat -> "oldstat"
    | LinuxSyscall.Oldumount -> "oldumount"
    | LinuxSyscall.Olduname -> "olduname"
    | LinuxSyscall.Open -> "open"
    | LinuxSyscall.OpenByHandleAt -> "open_by_handle_at"
    | LinuxSyscall.OpenTree -> "open_tree"
    | LinuxSyscall.Openat -> "openat"
    | LinuxSyscall.Openat2 -> "openat2"
    | LinuxSyscall.Or1kAtomic -> "or1k_atomic"
    | LinuxSyscall.Pause -> "pause"
    | LinuxSyscall.PciconfigIobase -> "pciconfig_iobase"
    | LinuxSyscall.PciconfigRead -> "pciconfig_read"
    | LinuxSyscall.PciconfigWrite -> "pciconfig_write"
    | LinuxSyscall.PerfEventOpen -> "perf_event_open"
    | LinuxSyscall.Personality -> "personality"
    | LinuxSyscall.Perfctr -> "perfctr"
    | LinuxSyscall.Perfmonctl -> "perfmonctl"
    | LinuxSyscall.PidfdGetfd -> "pidfd_getfd"
    | LinuxSyscall.PidfdSendSignal -> "pidfd_send_signal"
    | LinuxSyscall.PidfdOpen -> "pidfd_open"
    | LinuxSyscall.Pipe -> "pipe"
    | LinuxSyscall.Pipe2 -> "pipe2"
    | LinuxSyscall.PivotRoot -> "pivot_root"
    | LinuxSyscall.PkeyAlloc -> "pkey_alloc"
    | LinuxSyscall.PkeyFree -> "pkey_free"
    | LinuxSyscall.PkeyMprotect -> "pkey_mprotect"
    | LinuxSyscall.Poll -> "poll"
    | LinuxSyscall.Ppoll -> "ppoll"
    | LinuxSyscall.Prctl -> "prctl"
    | LinuxSyscall.Pread -> "pread"
    | LinuxSyscall.Pread64 -> "pread64"
    | LinuxSyscall.Preadv -> "preadv"
    | LinuxSyscall.Preadv2 -> "preadv2"
    | LinuxSyscall.Prlimit64 -> "prlimit64"
    | LinuxSyscall.ProcessVmReadv -> "process_vm_readv"
    | LinuxSyscall.ProcessVmWritev -> "process_vm_writev"
    | LinuxSyscall.Pselect6 -> "pselect6"
    | LinuxSyscall.Ptrace -> "ptrace"
    | LinuxSyscall.Pwrite -> "pwrite"
    | LinuxSyscall.Pwrite64 -> "pwrite64"
    | LinuxSyscall.Pwritev -> "pwritev"
    | LinuxSyscall.Pwritev2 -> "pwritev2"
    | LinuxSyscall.QueryModule -> "query_module"
    | LinuxSyscall.Quotactl -> "quotactl"
    | LinuxSyscall.Read -> "read"
    | LinuxSyscall.Readahead -> "readahead"
    | LinuxSyscall.Readdir -> "readdir"
    | LinuxSyscall.Readlink -> "readlink"
    | LinuxSyscall.Readlinkat -> "readlinkat"
    | LinuxSyscall.Readv -> "readv"
    | LinuxSyscall.Reboot -> "reboot"
    | LinuxSyscall.Recv -> "recv"
    | LinuxSyscall.Recvfrom -> "recvfrom"
    | LinuxSyscall.Recvmsg -> "recvmsg"
    | LinuxSyscall.Recvmmsg -> "recvmmsg"
    | LinuxSyscall.RemapFilePages -> "remap_file_pages"
    | LinuxSyscall.Removexattr -> "removexattr"
    | LinuxSyscall.Rename -> "rename"
    | LinuxSyscall.Renameat -> "renameat"
    | LinuxSyscall.Renameat2 -> "renameat2"
    | LinuxSyscall.RequestKey -> "request_key"
    | LinuxSyscall.RestartSyscall -> "restart_syscall"
    | LinuxSyscall.RiscvFlushIcache -> "riscv_flush_icache"
    | LinuxSyscall.Rmdir -> "rmdir"
    | LinuxSyscall.Rseq -> "rseq"
    | LinuxSyscall.RtSigaction -> "rt_sigaction"
    | LinuxSyscall.RtSigpending -> "rt_sigpending"
    | LinuxSyscall.RtSigprocmask -> "rt_sigprocmask"
    | LinuxSyscall.RtSigqueueinfo -> "rt_sigqueueinfo"
    | LinuxSyscall.RtSigreturn -> "rt_sigreturn"
    | LinuxSyscall.RtSigsuspend -> "rt_sigsuspend"
    | LinuxSyscall.RtSigtimedwait -> "rt_sigtimedwait"
    | LinuxSyscall.RtTgsigqueueinfo -> "rt_tgsigqueueinfo"
    | LinuxSyscall.Rtas -> "rtas"
    | LinuxSyscall.S390RuntimeInstr -> "s390_runtime_instr"
    | LinuxSyscall.S390PciMmioRead -> "s390_pci_mmio_read"
    | LinuxSyscall.S390PciMmioWrite -> "s390_pci_mmio_write"
    | LinuxSyscall.S390Sthyi -> "s390_sthyi"
    | LinuxSyscall.S390GuardedStorage -> "s390_guarded_storage"
    | LinuxSyscall.SchedGetAffinity -> "sched_get_affinity"
    | LinuxSyscall.SchedGetPriorityMax -> "sched_get_priority_max"
    | LinuxSyscall.SchedGetPriorityMin -> "sched_get_priority_min"
    | LinuxSyscall.SchedGetaffinity -> "sched_getaffinity"
    | LinuxSyscall.SchedGetattr -> "sched_getattr"
    | LinuxSyscall.SchedGetparam -> "sched_getparam"
    | LinuxSyscall.SchedGetscheduler -> "sched_getscheduler"
    | LinuxSyscall.SchedRrGetInterval -> "sched_rr_get_interval"
    | LinuxSyscall.SchedSetAffinity -> "sched_set_affinity"
    | LinuxSyscall.SchedSetaffinity -> "sched_setaffinity"
    | LinuxSyscall.SchedSetattr -> "sched_setattr"
    | LinuxSyscall.SchedSetparam -> "sched_setparam"
    | LinuxSyscall.SchedSetscheduler -> "sched_setscheduler"
    | LinuxSyscall.SchedYield -> "sched_yield"
    | LinuxSyscall.Seccomp -> "seccomp"
    | LinuxSyscall.Select -> "select"
    | LinuxSyscall.Semctl -> "semctl"
    | LinuxSyscall.Semget -> "semget"
    | LinuxSyscall.Semop -> "semop"
    | LinuxSyscall.Semtimedop -> "semtimedop"
    | LinuxSyscall.Send -> "send"
    | LinuxSyscall.Sendfile -> "sendfile"
    | LinuxSyscall.Sendfile64 -> "sendfile64"
    | LinuxSyscall.Sendmmsg -> "sendmmsg"
    | LinuxSyscall.Sendmsg -> "sendmsg"
    | LinuxSyscall.Sendto -> "sendto"
    | LinuxSyscall.SetMempolicy -> "set_mempolicy"
    | LinuxSyscall.SetRobustList -> "set_robust_list"
    | LinuxSyscall.SetThreadArea -> "set_thread_area"
    | LinuxSyscall.SetTidAddress -> "set_tid_address"
    | LinuxSyscall.SetTLS -> "set_tls"
    | LinuxSyscall.Setdomainname -> "setdomainname"
    | LinuxSyscall.Setfsgid -> "setfsgid"
    | LinuxSyscall.Setfsgid32 -> "setfsgid32"
    | LinuxSyscall.Setfsuid -> "setfsuid"
    | LinuxSyscall.Setfsuid32 -> "setfsuid32"
    | LinuxSyscall.Setgid -> "setgid"
    | LinuxSyscall.Setgid32 -> "setgid32"
    | LinuxSyscall.Setgroups -> "setgroups"
    | LinuxSyscall.Setgroups32 -> "setgroups32"
    | LinuxSyscall.Sethae -> "sethae"
    | LinuxSyscall.Sethostname -> "sethostname"
    | LinuxSyscall.Setitimer -> "setitimer"
    | LinuxSyscall.Setns -> "setns"
    | LinuxSyscall.Setpgid -> "setpgid"
    | LinuxSyscall.Setpgrp -> "setpgrp"
    | LinuxSyscall.Setpriority -> "setpriority"
    | LinuxSyscall.Setregid -> "setregid"
    | LinuxSyscall.Setregid32 -> "setregid32"
    | LinuxSyscall.Setresgid -> "setresgid"
    | LinuxSyscall.Setresgid32 -> "setresgid32"
    | LinuxSyscall.Setresuid -> "setresuid"
    | LinuxSyscall.Setresuid32 -> "setresuid32"
    | LinuxSyscall.Setreuid -> "setreuid"
    | LinuxSyscall.Setreuid32 -> "setreuid32"
    | LinuxSyscall.Setrlimit -> "setrlimit"
    | LinuxSyscall.Setsid -> "setsid"
    | LinuxSyscall.Setsockopt -> "setsockopt"
    | LinuxSyscall.Settimeofday -> "settimeofday"
    | LinuxSyscall.Setuid -> "setuid"
    | LinuxSyscall.Setuid32 -> "setuid32"
    | LinuxSyscall.Setup -> "setup"
    | LinuxSyscall.Setxattr -> "setxattr"
    | LinuxSyscall.Sgetmask -> "sgetmask"
    | LinuxSyscall.Shmat -> "shmat"
    | LinuxSyscall.Shmctl -> "shmctl"
    | LinuxSyscall.Shmdt -> "shmdt"
    | LinuxSyscall.Shmget -> "shmget"
    | LinuxSyscall.Shutdown -> "shutdown"
    | LinuxSyscall.Sigaction -> "sigaction"
    | LinuxSyscall.Sigaltstack -> "sigaltstack"
    | LinuxSyscall.Signal -> "signal"
    | LinuxSyscall.Signalfd -> "signalfd"
    | LinuxSyscall.Signalfd4 -> "signalfd4"
    | LinuxSyscall.Sigpending -> "sigpending"
    | LinuxSyscall.Sigprocmask -> "sigprocmask"
    | LinuxSyscall.Sigreturn -> "sigreturn"
    | LinuxSyscall.Sigsuspend -> "sigsuspend"
    | LinuxSyscall.Socket -> "socket"
    | LinuxSyscall.Socketcall -> "socketcall"
    | LinuxSyscall.Socketpair -> "socketpair"
    | LinuxSyscall.Spill -> "spill"
    | LinuxSyscall.Splice -> "splice"
    | LinuxSyscall.SpuCreate -> "spu_create"
    | LinuxSyscall.SpuRun -> "spu_run"
    | LinuxSyscall.SramAlloc -> "sram_alloc"
    | LinuxSyscall.SramFree -> "sram_free"
    | LinuxSyscall.Ssetmask -> "ssetmask"
    | LinuxSyscall.Stat -> "stat"
    | LinuxSyscall.Stat64 -> "stat64"
    | LinuxSyscall.Statfs -> "statfs"
    | LinuxSyscall.Statfs64 -> "statfs64"
    | LinuxSyscall.Statx -> "statx"
    | LinuxSyscall.Stime -> "stime"
    | LinuxSyscall.SubpageProt -> "subpage_prot"
    | LinuxSyscall.SwitchEndian -> "swapcontext"
    | LinuxSyscall.Swapcontext -> "switch_endian"
    | LinuxSyscall.Swapoff -> "swapoff"
    | LinuxSyscall.Swapon -> "swapon"
    | LinuxSyscall.Symlink -> "symlink"
    | LinuxSyscall.Symlinkat -> "symlinkat"
    | LinuxSyscall.Sync -> "sync"
    | LinuxSyscall.SyncFileRange -> "sync_file_range"
    | LinuxSyscall.SyncFileRange2 -> "sync_file_range2"
    | LinuxSyscall.Syncfs -> "syncfs"
    | LinuxSyscall.SysDebugSetcontext -> "sys_debug_setcontext"
    | LinuxSyscall.Syscall -> "syscall"
    | LinuxSyscall.Sysctl -> "_sysctl"
    | LinuxSyscall.Sysfs -> "sysfs"
    | LinuxSyscall.Sysinfo -> "sysinfo"
    | LinuxSyscall.Syslog -> "syslog"
    | LinuxSyscall.Sysmips -> "sysmips"
    | LinuxSyscall.Tee -> "tee"
    | LinuxSyscall.Tgkill -> "tgkill"
    | LinuxSyscall.Time -> "time"
    | LinuxSyscall.TimerCreate -> "timer_create"
    | LinuxSyscall.TimerDelete -> "timer_delete"
    | LinuxSyscall.TimerGetoverrun -> "timer_getoverrun"
    | LinuxSyscall.TimerGettime -> "timer_gettime"
    | LinuxSyscall.TimerSettime -> "timer_settime"
    | LinuxSyscall.TimerfdCreate -> "timerfd_create"
    | LinuxSyscall.TimerfdGettime -> "timerfd_gettime"
    | LinuxSyscall.TimerfdSettime -> "timerfd_settime"
    | LinuxSyscall.Times -> "times"
    | LinuxSyscall.Tkill -> "tkill"
    | LinuxSyscall.Truncate -> "truncate"
    | LinuxSyscall.Truncate64 -> "truncate64"
    | LinuxSyscall.Ugetrlimit -> "ugetrlimit"
    | LinuxSyscall.Umask -> "umask"
    | LinuxSyscall.Umount -> "umount"
    | LinuxSyscall.Umount2 -> "umount2"
    | LinuxSyscall.Uname -> "uname"
    | LinuxSyscall.Unlink -> "unlink"
    | LinuxSyscall.Unlinkat -> "unlinkat"
    | LinuxSyscall.Unshare -> "unshare"
    | LinuxSyscall.Uselib -> "uselib"
    | LinuxSyscall.Ustat -> "ustat"
    | LinuxSyscall.Userfaultfd -> "userfaultfd"
    | LinuxSyscall.Usr26 -> "usr26"
    | LinuxSyscall.Usr32 -> "usr32"
    | LinuxSyscall.Utime -> "utime"
    | LinuxSyscall.Utimensat -> "utimensat"
    | LinuxSyscall.Utimes -> "utimes"
    | LinuxSyscall.UtrapInstall -> "utrap_install"
    | LinuxSyscall.Vfork -> "vfork"
    | LinuxSyscall.Vhangup -> "vhangup"
    | LinuxSyscall.Vm86old -> "vm86old"
    | LinuxSyscall.Vm86 -> "vm86"
    | LinuxSyscall.Vmsplice -> "vmsplice"
    | LinuxSyscall.Wait4 -> "wait4"
    | LinuxSyscall.Waitid -> "waitid"
    | LinuxSyscall.Waitpid -> "waitpid"
    | LinuxSyscall.Write -> "write"
    | LinuxSyscall.Writev -> "writev"
    | LinuxSyscall.Xtensa -> "xtensa"
    | _ -> raise UnhandledSyscallException
