<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>B2R2 middle-end executor.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="IStateAccessor.fs" />
    <Compile Include="StopPoint.fs" />
    <Compile Include="CallContext.fs" />
    <Compile Include="CallPolicy.fs" />
    <Compile Include="Labels.fs" />
    <Compile Include="IExecutor.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BinIR\B2R2.BinIR.fsproj" />
    <ProjectReference Include="..\..\FrontEnd\API\B2R2.FrontEnd.API.fsproj" />
  </ItemGroup>
</Project>
