name: lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
    - name: Lint files
      run: |
        dotnet tool restore
        dotnet fslint src --strict

  notify-failure:

    needs: linting
    if: failure()

    uses: ./.github/workflows/notify-failure.yml
    secrets: inherit
