name: push-notification
on: push
jobs:
    notify-push:
        runs-on: ubuntu-latest
        if: github.event.head_commit != null
        steps:
        - name: Push Info
          run: |
            echo "Workflow initiated by event with name: ${{ github.event_name }}"
            echo "Pushing commit: ${{ github.event.head_commit.id }}"
            echo "Pushed by: ${{ github.actor }}"

        - uses: actions/checkout@v5

        - name: Setup .NET
          uses: actions/setup-dotnet@v5

        - name: Push Notification to Google Chat
          working-directory: .github
          env:
              WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
              COMMIT: ${{ github.event.head_commit.message }}
              ACTOR: ${{ github.actor }}
              BRANCH: ${{ github.ref_name }}
              COMMIT_ID: ${{ github.event.head_commit.id }}
              COMPARE_URL: ${{ github.event.compare }}
              COMMIT_URL: ${{ github.event.head_commit.url }}
          run: |
            printf '%s' "$COMMIT" > msg.txt
            dotnet fsi notify.fsx push "$ACTOR" \
                                       "$BRANCH" \
                                       "$COMMIT_ID" \
                                       "$COMMIT_URL" \
                                       "$COMPARE_URL"
